toptal/picasso

- README.md
[FX-NNNN]
<details>
<br />
</details>
> fix: private readme link

- package.json
- puppeteer/utils.js
- yarn.lock
[FX-1848]
To test that alpha packages are working again, davinci needs to be upgraded
<details>
<br />
</details>
[FX-1848]: …
> chore: upgrade davinci

- packages/picasso/src/Modal/styles.ts
[TEA-2610]
When the content of the modal is heigher than the window, the modal should get a scrollbar to make
the content accessible. It was overflowing the screen instead.
- Go to https://picasso.toptal.net/?path=/story/overlays-modal--modal#max-height
- Set emulated screen size to small mobile
- Open the max height example modal
| ![Screenshot 2021-05-13 at 16 41 49](https://user-images.githubusercontent.com/2437969/118141995-40840a80-b40a-11eb-99f2-b89118b2f877.png) | ![Screenshot 2021-05-13 at 16 47 14](https://user-images.githubusercontent.com/2437969/118142793-0109ee00-b40b-11eb-91c1-b98effda3c8f.png) |
In Talent …
> fix(modal): the content is not scrollable on mobile

- .github/workflows/request-review-on-pr.yml
Fix PR Review workflow job
<details>
<br />
</details>
> chore: fix review pr workflow

- .github/workflows/report_gha_stats_to_anvil.yml
[CI-490]
This is a workflow which is triggered by other workflow's completion event. It sends request to Anvil to fetch stats.
[CI-490]: https://toptal-core.atlassian.net/browse/CI-490
> feat(ci): create workflow for gha stats

- packages/picasso-forms/src/index.ts
[SPC-1066]
Add `Config`, `setIn` export from final-form
Add `arrayMutators` export from final-form-arrays
<details>
<br />
</details>
[SPC-1066]: …
> feat: add final-form exports

- packages/picasso-forms/src/NumberInput/NumberInput.tsx
- packages/picasso-forms/src/utils/validators.ts
[FX-1994]
Validation is required, because user can input custom value even if max and min are specified.
Form.NumberInput should check if value is in `Int` range between  [−2,147,483,648 to 2,147,483,647].
Readable user error message have to be shown.
Try to input or paste some huge number value
https://picasso.toptal.net/?path=/story/picasso-forms-form--form
in comparison to
https://picasso.toptal.net/FX-1994-add-int-validation-form-input/?path=/story/picasso-forms-form--form
| ![image](https://user-images.githubusercontent.com/67374194/124726991-f7869900-df16-11eb-88f1-da03e20b74e5.png) | …
> feat(NumberInput): add Int validation for Form.NumberInput

- packages/picasso-forms/package.json
- packages/picasso-forms/src/index.ts
- yarn.lock
[SPB-2053]
Expose `react-final-form-listeners` [package](https://github.com/final-form/react-final-form-listeners)
<details>
<br />
</details>
[SPB-2053]: https://toptal-core.atlassian.net/browse/SPB-2053
> feat(forms): expose react final forms listeners

- cypress/component/Dropdown.spec.tsx
- packages/picasso/src/Dropdown/Dropdown.tsx
- packages/picasso/src/Dropdown/story/LongMenuList.example.tsx
- packages/picasso/src/Dropdown/story/index.jsx
- packages/picasso/src/Dropdown/styles.ts
- yarn.lock
[SPT-1828](https://toptal-core.atlassian.net/browse/SPT-1828)
Add `contentOverflow` option to manage overflow settings for a dropdown content
`/?path=/story/components-dropdown--dropdown#long-menu-list`
| contentOverflow: SCROLL (default)|contentOverflow: VISIBLE |
|--|--|
| <img width="615" alt="Screenshot 2021-08-05 at 15 28 49" src="https://user-images.githubusercontent.com/496713/128349980-835f13ed-9a5a-4cbf-b742-41e7b35a0e3a.png"> | <img width="673" alt="Screenshot 2021-08-05 at 15 28 41" src="https://user-images.githubusercontent.com/496713/128349983-3bad935e-7f10-490e-abd3-4bf2b0a6f4ff.png"> |
| contentOverflow: SCROLL (default)| contentOverflow: VISIBLE |
|--|--|
| <img width="491" alt="Screenshot 2021-08-05 at 15 33 38" src="https://user-images.githubusercontent.com/496713/1283506 …
> feat(Dropdown): add contentOverflow option

- .github/workflows/pr.yaml
[no-jira]
Run tests on feature branches
Affected PR https://github.com/toptal/picasso/pull/2141
- can be tested only after merging this commit to `master` and merging `master` to `feature/picasso-compliance` branch
<details>
<br />
</details>
> chore: run tests on PRs to feature/* branches

- packages/picasso/src/ModalContent/use-scrollable-shades.ts
[SPT-1889](https://toptal-core.atlassian.net/browse/SPT-1889)
1. Go to [/?path=/story/overlays-modal--modal](https://picasso.toptal.net/SPT-1889-fix-modal-scrollable-shades-inheritance-on-resize/?path=/story/overlays-modal--modal) and open one of the modals
2. Resize the window height to make the content scrollable
3. Scroll so the shade effect will be in place
4. Resize back to non-scrollable content, the shade effect should dissapear
5. Compare to [current](https://picasso.toptal.net/?path=/story/overlays-modal--modal)
https://user-images.githubusercontent.com/79158829/132189780-86ad126e-d00d-4311-94ed-a7e8a9c5c093.mov
https://user-images.githubusercontent.com/79158829/132189784-2d12f0f7-34c0-4df9-ab53-a6dcf384614e.mov
<details>
<br />
List of available …
> fix: [SPT-1889] updated modal scrollable shades to fix resize inheritance

- package.json
- yarn.lock
No ticket.
In order to fix CVE-2021-23337 and CVE-2020-28500.
As regular dependency updates.
- [n/a] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
- [n/a] Ensure that deployed demo has expected results and good examples
<details>
<br /> …
> chore(deps-dev): [Security] Resolve lodash to 4.17.21

- .changeset/spotty-bats-repair.md
- packages/picasso/src/SidebarItem/styles.ts
[FX-2249](https://toptal-core.atlassian.net/browse/FX-2249)
Added `fontSize: 1rem` into the SideBarItem root style for the correct calculation of the height.
- `N/A` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/api-principles.md)
<details>
<br /> …
> feat(sidebatitem): [FX-2249] add font-size style

- .changeset/config.json
[FX-NNNN]
<details>
<br />
</details>
> chore: set access so public

- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-lab/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
[FX-NNNN]
changesets need to have setup publish directory, so we release only builded components
<details>
<br />
</details>
> chore: set publish directory

- .github/PULL_REQUEST_TEMPLATE.md
[FX-2256](https://toptal-core.atlassian.net/browse/FX-2256)
Added `PR Review Guidelines` section to the PR template.
1. Read `PR Review Guidelines` section.
<details>
<br />
</details>
> chore: add pr review guidelines to the pr template

- .github/workflows/release.yml
Update jenkins url to deployment, because other tokens are set for it.
<details>
<br />
</details>
<details>
<br /> …
> chore: update jenkins_url

- .github/workflows/release.yml
Docker image needs to be built before we try to deploy storybook
<details>
<br />
</details>
<details>
<br /> …
> chore(release): trigger build image pipeline

- .github/workflows/release.yml
`job_params` needs to be in JSON format
<details>
<br />
</details>
<details>
<br />
2. …
> fix: job_params needs to be in JSON format

- .changeset/tame-squids-buy.md
- packages/picasso/src/Pagination/Pagination.tsx
[FX-2269](https://toptal-core.atlassian.net/browse/FX-2269)
Fixed warning, related to the duplicate keys in the Pagination
Run Pagination tests. 
Expected
warnings shouldn't exist
<details>
<br />
</details>
<details>
<br />
1. Add …
> fix(pagintaion): [FX-2269] fix pagination key names

- .github/workflows/release.yml
Set correct `jenkins_user` for triggering pipeline from [jenkins-build](https://jenkins-build.toptal.net/)
<details>
<br />
</details>
<details>
<br /> …
> chore: set correct 'jenkins_user'

- .changeset/selfish-buttons-cover.md
- packages/picasso/src/Notification/Notification.tsx
[FX-2287](https://toptal-core.atlassian.net/browse/FX-2287)
Added data-testid into the Notification.
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to …
> feat(notification): [FX-2287] add data-testid into the notification

- .changeset/odd-guests-explain.md
- packages/picasso/src/Notification/Notification.tsx
[FX-2287](https://toptal-core.atlassian.net/browse/FX-2287)
Updated Notification testids props as optional
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle …
> fix(Notification): [FX-2287] set Notification testids props as optional

- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-lab/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
[FX-2291]
When `lerna` tries to publish the alpha package we don't have actual `package.json` inside `dist-package`. Thic copy functionality was removed previously, because it was not needed in `changeset publish`, I have tested locally, that this works for `changesets` correctly.
<details>
<br />
</details>
<details>
<br />
1. Add …
> chore: copy package.json to dist-package after version bumb

- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-lab/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
[FX-2291]
We dont have `dist-package/dist-package`, so we cant copy into it.
<details>
<br />
</details>
<details>
<br /> …
> chore: remove the dist-package/dist-package

- .github/PULL_REQUEST_TEMPLATE.md
[FX-2288]
Updated PR template with link to contribution guidelines
Plus fixed link to Component API principles
Create a PR from alpha package
<details>
<br />
</details>
<details>
<br />
1. …
> chore: added contribution process guidelines in PR template as a comment

- .github/workflows/release.yml
In current master we have problem with triggering jenkins job on `jenkins-build.toptal.net`, because of auth problems. With Nebojsa from infra team, we realized that we forgot to pass TOKEN from secrets to env variables 🤦 
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable …
> chore: trigger jenkins build job from GHA

- .changeset/wise-berries-exercise.md
- packages/picasso/src/TagSelectorInput/TagSelectorInput.tsx
- packages/picasso/src/TagSelectorInput/__snapshots__/test.tsx.snap
- packages/picasso/src/TagSelectorInput/test.tsx
[FX-2304](https://toptal-core.atlassian.net/browse/FX-2304)
Fixed the problem with testIds in the TagSelectorInput.
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from …
> fix(TagSelectorInput): [FX-2304] fix testIds prop

- .changeset/spicy-hats-try.md
- packages/picasso/src/Autocomplete/Autocomplete.tsx
- packages/picasso/src/Autocomplete/test.tsx
[FX-2312](https://toptal-core.atlassian.net/browse/FX-2312)
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from …
> fix(Autocomplete): [FX-2312] add separate testid for autofill input

- packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
- packages/picasso/src/Select/hooks/use-highlighted-index/use-highlighted-index.ts
[FX-2322](https://toptal-core.atlassian.net/browse/FX-2322)
Fixed the bug when a disabled & selected option is highlighted initially. Added a test to prevent this bug in the future.
1. Go to Select story in the temploy.
2. Make the first option selected & disabled (with the built-in editor).
3. Open the Select.
4. Be sure that the first option is selected, disabled & not highlighted.
5. Be sure that the second option is highlighted.
<table>
<td>
</td>
<td>
➡️
</td>
<td>
</td>
</table>
<details>
<br /> …
> fix(Select): fix disabled and selected option is highlighted initially

- .changeset/violet-llamas-peel.md
- packages/picasso-lab/package.json
- packages/picasso/package.json
- packages/picasso/src/Select/hooks/use-highlighted-index/test.ts
- packages/shared/package.json
[FX-2322](https://toptal-core.atlassian.net/browse/FX-2322)
<details>
<br />
</details>
<details> …
> chore: refactor useHighlightedIndex test

- packages/picasso/src/List/List.tsx
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You …
> chore: fix types

- packages/picasso-forms/src/Dropzone/Dropzone.tsx
- packages/picasso-forms/src/Dropzone/index.ts
- packages/picasso-forms/src/Form/Form.tsx
- packages/picasso-forms/src/Form/story/Default.example.tsx
- packages/picasso-forms/src/Form/story/Dropzone.example.tsx
- packages/picasso-forms/src/Form/story/index.jsx
[SPT-2211](https://toptal-core.atlassian.net/browse/SPT-2211)
Add dropzone component to the Picasso form. The dropzone should be integrated with the Final Form.
- Navigate to https://picasso.toptal.net/SPT-2211-add-dropzone-component-to-picasso-form/?path=/story/picasso-forms-form--form#dropzone-on-a-form
- Check the dropzone component
<details>
<br />
</details>
<details>
<br />
1. You have no …
> feat: add dropzone component to picasso form

- .changeset/smooth-melons-collect.md
- packages/picasso/src/Accordion/Accordion.tsx
- packages/picasso/src/Modal/Modal.tsx
- packages/shared/src/types.ts
[FX-2345]
This adds correct `transitionProps` prop support for Modal and Accordion components.
<details>
<br />
</details>
<details>
<br />
2. …
> feat(Modal): [FX-2345] Extend Modal component with `transitionProps` prop support

- packages/picasso-codemod/README.md
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You …
> chore: added container-borders codemod to README

- .github/workflows/notify-jira-about-contribution.yml
[FX-2367]
Triggers JIRA automation on opened PR by external to FX contributor
- Well, ask someone not in the FX team to create a PR
<details>
<br />
</details>
<details>
<br />
1. Something …
> chore: notify jira about contribution

- .changeset/thirty-bottles-complain.md
- packages/picasso-codemod/src/v17.0.0/typography-sizes/__testfixtures__/basic.input.tsx
- packages/picasso-codemod/src/v17.0.0/typography-sizes/__testfixtures__/basic.output.tsx
- packages/picasso-codemod/src/v17.0.0/typography-sizes/typography-sizes.ts
[FX-NNNN]
patched a bug that calculated wrong size in nested Typography components
<details>
<br />
</details>
<details> …
> fix: patch codemod typography-sizes for picasso v17

- .changeset/heavy-peaches-pay.md
- packages/picasso-forms/src/index.ts
[SPT-582]
Add additional reexports from final-form packages
- CI should pass
- [n/a] Ensure that deployed demo has expected results and good examples
- [n/a] Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- [n/a] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
<details>
<br />
- …
> chore(picasso-forms): add additional reexports from final-form packages

- packages/picasso-lab/src/TextEditor/TextEditor.tsx
- packages/picasso-lab/src/TextEditor/story/Default.example.tsx
- packages/picasso-lab/src/TextEditor/story/DefaultValue.example.tsx
- packages/picasso-lab/src/TextEditor/story/Disabled.example.tsx
- packages/picasso-lab/src/TextEditor/story/Limit.example.tsx
- packages/picasso-lab/src/TextEditor/story/Readonly.example.tsx
- packages/picasso-lab/src/TextEditor/styles.ts
[FX-2390](https://toptal-core.atlassian.net/browse/FX-2390)
[Abstract](https://share.goabstract.com/2de8e3f4-5704-4139-8a68-9e9519ed09f8?mode=build&sha=4f1f6493dfac89015cc6c71ea348807e931fe3bc)
- Make text editor vertically resizable
- Visit [Picasso Text Editor component](https://picasso.toptal.net/fx-2390-make-text-editor-vertically-resizable/?path=/story/picasso-lab-texteditor--texteditor) and resize any of the text editor examples.
<details>
<br />
- `@toptal-bot run all` - …
> chore: [FX-2390] Make text editor vertically resizable

- .storybook/main.js
Enable Fast Refresh
- Run `yarn start`
- Change the code in the story
- Page should not get refreshed
<details>
<br />
</details>
<details>
<br />
2. …
> chore: enable fast refresh

- .prettierignore
- .storybook/main.js
- .storybook/tsconfig.json
- packages/picasso-codemod/src/v17.0.0/container-borders/__testfixtures__/actual.tsx
- packages/picasso-codemod/src/v17.0.0/container-borders/__testfixtures__/expected.tsx
- packages/picasso-forms/src/Form/test.tsx
- packages/picasso-provider/src/Picasso/story/index.jsx
Fix multiple issues in our `master` branch:
1. Fixtures typecheck failure
2. Warning about PostCSS loader deprecated by Storybook
3. Picasso root component example had huge horizontal scrollbar
<details>
<br />
</details>
<details>
<br /> …
> chore: fix typecheck for fixtures

- .changeset/thick-tigers-search.md
- packages/picasso-lab/src/Timeline/Timeline.tsx
[FX-2403]
Extended Timeline's children type definition to allow for conditional rendering of its children, e.g. 
```
<Timeline>
<Timeline.Row ...>...<Timeline.Row>
{isSomething && <Timeline.Row ...>...</Timeline.Row>}
<Timeline>
```
- Ensure regular Timeline renders as expected
- Ensure falsey values do not slip into DOM
<details>
<br />
</details>
<details>
<br /> …
> fix(Timeline): extend Timeline children type to support conditional rendering

- CONTRIBUTING.md
- docs/contribution/changeset-guidelines.md
Add changesets guidelines to our contribution guidelines
<details>
<br />
</details>
<details>
<br />
3. Code …
> chore: add changeset guidelines

- .changeset/beige-clocks-exist.md
[FX-2041]
Add a missing changeset to release `@toptal/picasso-codemod` package
<details>
<br />
</details>
<details>
<br /> …
> chore: add picasso codemods changeset

- packages/picasso-codemod/bin/build.sh
[FX-2041]
Fix picasso codemod build process
<details>
<br />
</details>
<details>
<br /> …
> chore: [FX-2041] Fix picasso codemod build process

- packages/picasso-lab/package.json
- packages/picasso-lab/src/TextEditor/hooks/useAutofocus/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useAutofocus/test.ts
- packages/picasso-lab/src/TextEditor/hooks/useAutofocus/useAutofocus.tsx
- packages/picasso-lab/src/TextEditor/hooks/useDisabledEditor/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useDisabledEditor/test.ts
- packages/picasso-lab/src/TextEditor/hooks/useDisabledEditor/useDisabledEditor.tsx
- packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/test.tsx
- packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/useQuillInstance.tsx
- packages/picasso-lab/src/TextEditor/hooks/useTextEditor.tsx
[FX-2394]
- change the name of the hook to follow name conventions
- add test
- remove unnecessary first render checking
- the hook is not used anywhere, I will provide PR for all hooks first 
<details>
<br />
</details>
<details>
<br /> …
> refactor(TextEditor): cleanup useAutofocus hook and add test

- packages/picasso-codemod/src/v16.0.0/revert-colors/revert-colors.ts
- packages/picasso-codemod/src/v17.0.0/container-borders/container-borders.ts
- packages/picasso-codemod/src/v5.0.0/accordion-borders/accordion-borders.ts
- packages/picasso-codemod/src/v5.0.0/prompt-modal-variants/prompt-modal-variants.ts
Looks like after upgrading some library (most likely `babel`) [here](https://github.com/toptal/picasso/commit/09b4209a42d3d0a05c1d6b3c7f4f52e8ef873cc5#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de) some TS errors appeared in codemods:
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. …
> chore: fix typings after upgrading some packages

- packages/picasso-lab/src/TextEditor/constants.tsx
- packages/picasso-lab/src/TextEditor/hooks/useEditorChange/getUpdateToolbarState.tsx
- packages/picasso-lab/src/TextEditor/hooks/useEditorChange/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useEditorChange/test.ts
- packages/picasso-lab/src/TextEditor/hooks/useEditorChange/useEditorChange.tsx
- packages/picasso-lab/src/TextEditor/hooks/useTextEditor.tsx
- packages/picasso-lab/src/TextEditor/hooks/useTextEditor/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useTextEditor/test.tsx
- packages/picasso-lab/src/TextEditor/hooks/useTextEditor/useTextEditor.tsx
- packages/picasso-lab/src/TextEditor/hooks/useToolbar/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useToolbar/test.ts
- packages/picasso-lab/src/TextEditor/hooks/useToolbar/useToolbar.tsx
- packages/picasso-lab/src/TextEditor/hooks/useToolbarHandlers/index.ts
- packages/picasso-lab/src/TextEditor/hooks/useToolbarHandlers/test.ts
- packages/picasso-lab/src/TextEditor/hooks/useToolbarHandlers/useToolbarHandlers.tsx
- packages/picasso-lab/src/TextEditor/types.ts
[FX-2394]
prepare hook to connect quill editor with custom toolbar
<details>
<br />
</details>
<details>
<br /> …
> refactor(TextEditor): FX-2394 useToolbar

- .changeset/neat-wolves-applaud.md
- packages/picasso-lab/src/TextEditor/TextEditorButton.tsx
- packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
- packages/picasso-lab/src/TextEditor/types.ts
[FX-2414](https://toptal-core.atlassian.net/browse/FX-2414)
[Abstract](https://app.abstract.com/projects/1b06c884-06af-482a-bf12-a82f521a19a1/branches/master/commits/4f1f6493dfac89015cc6c71ea348807e931fe3bc/files/13531207-e094-44ec-ae1f-f27628c1aea5/layers/5AFC1310-BBF4-4601-BA95-9FB38248733B?mode=design)
- Button in toolbar should look like in design.
- Visit [TextEditor Picasso component](https://picasso.toptal.net/fx-2414-toolbar-button-styles/?path=/story/picasso-lab-texteditor--texteditor) and click on toolbar action buttons.
> Note:  Bold and Italic buttons states are not working yet and hook responsible for it needs to be fixed 
https://github.com/toptal/picasso/tree/FX-2293-text-editor and Tomas is already investigating it. …
> [FX-2414] Toolbar button styles

- packages/picasso-lab/src/TextEditor/hooks/useQuillInstance/test.tsx
[FX-2424]
test that Quill constructor is used with proper `id`
<details>
<br />
</details>
<details>
<br />
3. …
> test(TextEditor): test usage of Quill constructor

- .github/workflows/handle-contribution.yml
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You …
> fix: add Alex Radulescu as maintainer

- README.md
- packages/picasso-forms/README.md
[FX-NNNN]
- Remove dangling reference to `picasso-lab` in `README` files
<details>
<br />
</details>
<details>
<br /> …
> chore: remove picasso-lab reference in README files

- packages/picasso/src/QuillEditor/QuillEditor.tsx
- packages/picasso/src/QuillEditor/hooks/useSubscribeToQuillEvents/useSubscribeToQuillEvents.tsx
- packages/picasso/src/QuillEditor/types.ts
- packages/picasso/src/QuillEditor/utils/getTextLengthChangeHandler/getTextLengthChangeHandler.tsx
- packages/picasso/src/QuillEditor/utils/getTextLengthChangeHandler/index.ts
- packages/picasso/src/QuillEditor/utils/getTextLengthChangeHandler/test.ts
- packages/picasso/src/RichTextEditor/RichTextEditor.tsx
- packages/picasso/src/RichTextEditor/story/Limit.example.tsx
- packages/picasso/src/RichTextEditor/story/index.jsx
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You …
> feat: what do you think

- packages/picasso/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
- packages/picasso/src/QuillEditor/utils/getFormatChangeHandler/getFormatChangeHandler.ts
- packages/picasso/src/RichTextEditor/hooks/useOnFocus/useOnFocus.tsx
This PR is fixing 3 small bugs. They are so small, that I have decided to create 1 PR.
1. We need to be able to select both bold and italic with mouse and then the written text should have both formats.
2. When we write some formatted text, for example heading. Then we press CTRL + A; DEL/Backspace. Everything should be removed, even formats. So when we start writing again, it would be plain text
3. `onBlur` was triggering `setDisabled` action, when it was not necessary.
- check temploy and try above described scenarios
[multiple formats bug](https://user-images.githubusercontent.com/6830426/154228596-3f4e34e7-2f0e-4ad7-9b20-88fcf5642b02.mp4)
[remove all](https://user-images.githubusercontent.com/6830426/154228896-47734194-38be-405a-bd7a-748ca4087e2d.mp4) …
> fix(RichTextEditor): multiple bugs

- packages/picasso/src/Slider/story/ControlledWithLabel.example.tsx
- packages/picasso/src/Slider/story/MinMaxValueLabel.example.tsx
- packages/picasso/src/Slider/story/RangeWithValueLabel.example.tsx
- packages/picasso/src/Slider/story/index.jsx
- packages/picasso/src/Slider/styles.ts
[SAT-1176]
Sync picasso slider with BASE
- Run storybook
- Go to storybook slider component, and verify newly added examples
<details>
<br />
</details>
<details>
<br /> …
> chore(slider): sync picasso slider with base

- .changeset/rude-dogs-wonder.md
- jest.config.js
- packages/picasso/package.json
- packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
- yarn.lock
The latest version of `hast-to-hyperscript` is in ESM, it affects all projects that use Picasso and breaks jest tests. In all projects would have to be `jest.config` changed with the current solution. Much easier is to downgrade to the version without ESM
- ci passes
- story of RichText works as before
<details>
<br />
</details>
<details>
<br />
2. You have …
> chore: downgrade hast-to-hyperscript since new version is in ESM

- .changeset/stale-apples-fix.md
- packages/picasso/src/Stepper/styles.ts
[SPT-2453]
This PR changes background-color for `Stepper` component to `inherit` so it can be displayed correctly in containers with non-white background-color
- Compare two screenshots
| ![image](https://user-images.githubusercontent.com/9210534/154954685-f2fe9c1e-a0e1-4c77-b0c0-5463205f47f1.png) | ![image](https://user-images.githubusercontent.com/9210534/154954769-69401291-bf9e-41af-9e7e-0fb49d5f5d0f.png) |
<details>
<br />
- …
> chore(stepper): change background-color to `inherit`

- cypress/component/ApplicationUpdateNotification.spec.tsx
- cypress/component/Link.spec.tsx
- cypress/component/List.spec.tsx
- cypress/component/Menu.spec.tsx
- cypress/component/Tooltip.spec.tsx
[FX-2526]
- added some missing brackets for selectors
<details>
<br />
</details>
<details>
<br />
3. Code is …
> fix(Tooltip): add missing closing brackets to several cypress test files

- packages/picasso/src/RichTextEditor/RichTextEditor.tsx
- packages/picasso/src/RichTextEditor/story/Default.example.tsx
[FX-2509]
To be consistent with rest of codebase, we rename `autofocus` 👉 `autoFocus`
<details>
<br />
</details>
<details>
<br />
2. Acceptance …
> refactor(RichTextEditor): rename autofocus to autoFocus

- .changeset/breezy-drinks-act.md
- packages/picasso/src/StepLabel/styles.ts
[MAT-995]
Remove all labels on Stepper when small screens in order to make it responsive.
1. Open Picasso storybook.
2. Open mobile mode
3. Labels should be hidden on small screens (less than 576px)
|  <img width="432" alt="image" src="https://user-images.githubusercontent.com/91321923/156321843-2e286931-5500-4f03-973f-c25b43ee2a80.png"> | <img width="432" alt="image" src="https://user-images.githubusercontent.com/91321923/156321895-a7ea2de0-ee01-45bd-a307-968651cf428f.png"> |
<details>
<br /> …
> feat(Stepper): make component responsive for small screens

- .changeset/yellow-snakes-yell.md
[FX-2542]
PicassoProvider was not bumped in the last release when purple color was added.
So now when you update to latest picasso and picasso-provider your app will crash due to nonexistent purple color.
I created a small fix for gray.dark color ([source](https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=8%3A7)) as an excuse to bump version of PicassoProvider and fix this.
Update picasso-provider in SP to `@toptal/picasso-provider@0.6.2-alpha-fx-2542-fix-broken-tests-on-master.2754` and open project in development
<details>
<br /> …
> fix(PicassoProvider): bump PicassoProvider to include purple color

- cypress/component/RichTextEditor.spec.tsx
[FX-2541]
Test case to cover [FX-2504]
<details>
<br />
</details>
<details>
<br />
**You …
> test(RichTextEditor): add testcase for disabled editor

- cypress/component/RichTextEditor.spec.tsx
[FX-2541]
Test to cover already solved bug [FX-2508]
<details>
<br />
</details>
<details>
<br />
3. Code is …
> test: click on disabled select will not be opened

- package.json
- yarn.lock
[FX-2533]
update `webpack-dev-server` and remove unused `wait-on` package. Also, we had to reinstall `follow-redirects` to the latest version to remove [vulnerability](https://github.com/toptal/picasso/security/dependabot/56)
- local development should work as before.
<details>
<br />
</details>
<details>
<br /> …
> chore: update webpack-dev-server and remove unused wait-on

- yarn.lock
[FX-2533]
reinstall `dns-packet` to patch the [vulnerability issue](https://github.com/toptal/picasso/security/dependabot/22).  
Bump from 1.3.1 to 1.3.4, should be without any problem.
`dns-packet` is used by `webpack-dev-server`
`yarn start` should run as expected
<details>
<br />
</details>
<details>
<br /> …
> chore: update dns-packet

- package.json
- packages/picasso/package.json
- yarn.lock
[FX-2533]
Remove 5 high vulnerabilities of `tar` package. The old version of tar was only by `npm@5` which we have in resolutions. It was added [3 years ago to fix different vulnerabilities](https://github.com/toptal/picasso/pull/553/files) and it is not needed anymore 
- CI is green
<details>
<br />
</details>
<details>
<br />
1. Add …
> chore: remove npm resolution

- package.json
- yarn.lock
[FX-2533]
Upgrade [glob-parent](https://github.com/gulpjs/glob-parent/releases) to latest version to fix [high vulnerability](https://github.com/toptal/picasso/security/dependabot/24)
Previous versions:
5.1.2 - lerna
3.1.0 - storybook, webpack
In version 5.1.2 the vulnerability was already fixed, but since in version 6, there were no API changes we can upgrade to a higher version.
Since the storybook is already in the latest version we need to add `glob-parent` to resolutions
I have tested:
1. `lerna version --no-push` with local change commited
2. `lerna build:package`
3. `yarn start`
4. `yarn test:cypress`
<details>
<br />
- …
> chore: update glob-parent

- package.json
- yarn.lock
[FX-2533]
Remove [high vulnerability](https://github.com/toptal/picasso/security/dependabot/16) in `merge` package. Fixed in `2.1.1`, current version `1.2.1`
`merge` is used only by `find-node-modules`, which is used by the `commitizen` package. Upgrading `commitizen` from `4.2.2` to `4.2.4` fixed the issue.
- using `git cz` instead of `git commit` works properly.
<details>
<br />
</details>
<details>
<br /> …
> chore: update commitizen

- package.json
- yarn.lock
[FX-2533]
This PR removes `trim` [vulnerability](https://github.com/toptal/picasso/security/dependabot/19).
`trim` is used by `remark-parse`, which is dependency of multiple packages. We need `remark-parse` to have version 9+.
1. **react-markdown**
- upgraded to the latest possible version for us `6.0.3`. Version `7+` is in ESM only. This update was enough to upgrade the dependency of `remark-parse` from 5 to 9 ✅ 
- we use `react-markdown` only for components in the storybook and we use it in a very simple way. None of the breaking changes from version 4 to 6 did touch our code.
2. **prettierx**
- has the dependency of `remark-parse@5`, since we don't use `prettierx` anymore, but we use `prettier` directly, I have removed this dependency ✅ 
3. **@storybook/react**
- we already have the …
> chore: remove trim vulnerability

- packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
- packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/Input/Input.tsx
- packages/picasso-forms/src/InputFieldWrapper/InputFieldWrapper.tsx
- packages/picasso/src/FormField/story/Error.example.tsx
- packages/picasso/src/Input/Input.tsx
- packages/picasso/src/Input/story/Error.example.tsx
- packages/picasso/src/Input/story/Status.example.tsx
- packages/picasso/src/Input/story/index.jsx
- packages/picasso/src/Input/test.tsx
[FX-2502]
- refactor `<Input>` to support `status`
<details>
<br />
</details>
<details>
<br /> …
> feat(ValidateStatus): refactor Input to support status

- cypress/component/NumberInput.spec.tsx
- packages/picasso-forms/src/NumberInput/NumberInput.tsx
- packages/picasso/src/NumberInput/NumberInput.tsx
- packages/picasso/src/NumberInput/story/Error.example.tsx
- packages/picasso/src/NumberInput/story/Status.example.tsx
- packages/picasso/src/NumberInput/story/index.jsx
- packages/picasso/src/NumberInput/test.tsx
[FX-2502]
- refactor `<NumberInput>` to support `status`
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> feat(ValidateStatus): refactor NumberInput to support status

- cypress/component/PasswordInput.spec.tsx
- packages/picasso-forms/src/PasswordInput/FieldRenderer.tsx
- packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
- packages/picasso/src/PasswordInput/PasswordInput.tsx
- packages/picasso/src/PasswordInput/story/Error.example.tsx
- packages/picasso/src/PasswordInput/story/Status.example.tsx
- packages/picasso/src/PasswordInput/story/index.jsx
- packages/picasso/src/PasswordInput/test.tsx
[FX-2502]
- refactor `<PasswordInput>` to support `status`
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> feat(ValidateStatus): refactor PasswordInput to support status

- cypress/component/Autocomplete.spec.tsx
- cypress/component/TagSelector.spec.tsx
- packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
- packages/picasso-forms/src/TagSelector/TagSelector.tsx
- packages/picasso/src/Autocomplete/Autocomplete.tsx
- packages/picasso/src/Autocomplete/story/Error.example.tsx
- packages/picasso/src/Autocomplete/story/Status.example.tsx
- packages/picasso/src/Autocomplete/story/index.jsx
- packages/picasso/src/TagSelector/TagSelector.tsx
- packages/picasso/src/TagSelector/story/Status.example.tsx
- packages/picasso/src/TagSelector/story/index.jsx
- packages/picasso/src/TagSelector/test.tsx
- packages/picasso/src/TagSelectorInput/TagSelectorInput.tsx
[FX-2502]
- refactor `<TagSelector>` to support `status`
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> feat(ValidateStatus): refactor TagSelector to support status

- .changeset/blue-kids-reply.md
- .changeset/config.json
[FX-2323]
Setup changeset config to update peer dependencies only when out of range. And also update ranges in peer dependencies so we are in control to update peer dependencies.
**The problem:**
Every `minor` update to `@toptal/picasso` triggers `major` bump for `@toptal/picasso-forms`, `@toptal/picasso-charts`, and analytics for charts. The reason behind it is, that these packages are having Picasso in peer dependencies, when peer dependency is updated, it is considered as a possible breaking change. To solve this issue we will upgrade peer dependencies only for major bumps.
- check the screenshots
**`minor` bump of Picasso with previous setup**
**`minor` bump of Picasso with new config**
**`major` bump of Picasso with new config**
<details>
<br />
List of …
> chore: test changeset experimental flag

- yarn.lock
[FX-2533]
Bump patch version of `find-process` to remove high vulnerability
This library is used only by `pupeteer` so old visual tests should be green.
<details>
<br />
</details>
<details>
<br /> …
> chore: update find-process to remove vulnerability

- packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
- packages/picasso-forms/src/DatePicker/DatePicker.tsx
- packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
- packages/picasso-forms/src/Input/Input.tsx
- packages/picasso-forms/src/NumberInput/NumberInput.tsx
- packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
- packages/picasso-forms/src/Select/Select.tsx
- packages/picasso-forms/src/TagSelector/TagSelector.tsx
- packages/picasso-forms/src/TimePicker/TimePicker.tsx
Omit label and title case props to not pass them to input
<details>
<br />
</details>
<details>
<br />
3. Code …
> Omit label and title case props

- package.json
- yarn.lock
To solve the conflict between IDE/CLI formatting and pre-commit formatting, the resolution is added.
Here is the discussion: https://toptal-core.slack.com/archives/GG3F4AS4T/p1648111799836769
- formatting the code and triggering pre-commit should produce the same result
<details>
<br />
</details>
<details>
<br /> …
> fix: add prettier resolution

- packages/picasso-forms/src/Form/index.ts
- packages/picasso-forms/src/Rating/Rating.tsx
- packages/picasso-forms/src/Rating/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/Rating/test.tsx
- packages/picasso/src/DatePicker/DatePicker.tsx
Fix visual test for Rating component
<details>
<br />
</details>
<details>
<br />
**You want …
> fix: rating label in Form

- yarn.lock
[FX-2533]
Upgrade node-forge to `1.3.0` to remove [the vulnerability](https://security.snyk.io/vuln/SNYK-JS-NODEFORGE-2430339)
Since this package is only used by `@toptal/davinci-graphql-codegen -> @google-cloud/storage -> ...`, for us green CI should be enough.
<details>
<br />
</details>
<details>
<br /> …
> chore: update node-forge to remove vulnerability

- .changeset/six-crews-cover.md
- .prettierignore
- packages/picasso-codemod/README.md
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/as-variable.input.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/as-variable.output.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/basic.input.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/basic.output.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/import-as.input.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__testfixtures__/import-as.output.tsx
- packages/picasso-codemod/src/v20.0.0/replace-error/__tests__/test.ts
- packages/picasso-codemod/src/v20.0.0/replace-error/index.ts
- packages/picasso-codemod/src/v20.0.0/replace-error/replace-error.ts
[FX-2502]
- prepared a codemod for the input field components which uses `error` as a prop
<details>
<br />
</details>
<details>
<br />
2. Acceptance …
> chore: prepare codemod for error prop

- .changeset/quiet-baboons-melt.md
- cypress/component/Tabs.spec.tsx
- packages/picasso/src/Tab/styles.ts
[FX-2172]
Extend underline in `Tab` with icon.
Visit the Tabs page in storybook
| ![image](https://user-images.githubusercontent.com/22159416/160152597-6b77251a-bf39-4f5f-9974-712bf5e24f20.png) | ![image](https://user-images.githubusercontent.com/22159416/160152677-2f6a9cfe-bd19-4822-9a8a-87f9b435cb26.png) |
<details>
<br />
- `@toptal-bot run package:alpha-release` - …
> feat(Tab): extend underline to icon

- cypress/component/NumberInput.spec.tsx
[FX-2502]
- added error state visual test
<details>
<br />
</details>
<details>
<br />
**You …
> chore: add visual test for NumberInput

- package.json
- yarn.lock
[FX-2533]
Update `minimist` to `^1.2.6` to remove [vulnerability](https://github.com/toptal/picasso/security/dependabot/78).
We need to add to the resolutions because of `commitizen@4.2.4`, they have in dependencies directly `1.2.5`. After commitizen is updated we can safely remove it from resolutions.
- `yarn cz` works properly
- danger ci check works properly
<details>
<br />
</details>
<details>
<br /> …
> chore: update minimist

- yarn.lock
[FX-2533]
Update `tmpl` to version 1.0.5 to remove [vulnerabilty](https://security.snyk.io/vuln/SNYK-JS-TMPL-1583443)
- `tmpl` is internally used by `jest`, so CI needs to be green
<details>
<br />
</details>
<details>
<br />
**You are not …
> chore: update tmpl to remove vulnerability

- package.json
- yarn.lock
[FX-2533]
Affected vulnerabilities:
- [ReDoS @<1.23.0](https://security.snyk.io/vuln/SNYK-JS-PRISMJS-1076581) - caused by `react-storybook-addon-chapters` 
- [ReDoS @<1.24.0](https://security.snyk.io/vuln/SNYK-JS-PRISMJS-1314893) - caused by `react-storybook-addon-chapters` 
- [ReDoS @<1.25.0](https://security.snyk.io/vuln/SNYK-JS-PRISMJS-1585202) - caused by `react-storybook-addon-chapters` 
- [XSS @<1.21.0](https://security.snyk.io/vuln/SNYK-JS-PRISMJS-597628) - caused by `react-storybook-addon-chapters` 
- storybook works as before
<details>
<br />
- `@toptal-bot run deploy:documentation` - Deploy …
> chore: update prismjs to remove vulnerability

- package.json
- yarn.lock
[FX-2533]
I went through old resolutions and checked if they are still needed. Both `js-yaml` and `merge-deep` were added to remove vulnerability in older versions. None of our packages uses older versions, so we are good to go to remove them.
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd …
> chore: remove unnecessary resolutions

- package.json
- yarn.lock
[FX-2533]
Update `semver-regex` to remove [vulnerability](https://security.snyk.io/vuln/SNYK-JS-SEMVERREGEX-1584358).
Since v4 is pure ESM, we upgraded to 3.1.3.
Dependencies were using two versions 2.0.0, and 3.1.2. Since the only breaking change of bump to v3 was only dropping support for Node@8, it should be without any problem for us.
<details>
<br />
</details>
<details>
<br />
1. You have …
> chore: update semver-regex to remove vulnerability

- .changeset/late-vans-type.md
- packages/picasso/src/RichText/hooks/useRichText/test.tsx
- packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
- packages/picasso/src/RichText/story/HTML.example.tsx
- packages/picasso/src/RichText/story/index.jsx
- packages/picasso/src/RichTextEditor/hooks/useOnFocus/useOnFocus.tsx
[FX-NNNN]
Update RichText stories, so it is clear how to use the RichText component. While testing in the storybook, an unhandled error occurred, when ReactNode had no children, so I had to add a small fix.
- check stories of RichText
| ![image](https://user-images.githubusercontent.com/6830426/160821755-ed627a76-d727-4771-ab42-4b75b8bd9ff8.png) | ![image](https://user-images.githubusercontent.com/6830426/160821791-d348ef72-e33c-47dd-bcbb-53391be40f7f.png) |
<details>
<br />
- …
> fix: handle empty children of ReactNode

- cypress/component/RichTextEditor.spec.tsx
[FX-NNNN]
It seems, that making sure, that the editor is focused before typing, fixed the issue.
<details>
<br />
</details>
<details>
<br />
2. …
> chore: try to fix flake test by focusing editor before writing

- package.json
- yarn.lock
[FX-2533]
Update `node-fetch` to remove [vulnerability](https://github.com/toptal/picasso/security/dependabot/66). The vulnerable version was used by `react-storybook-addon-chapters`, after we remove this unmaintained library, we can remove `node-fetch` from resolutions.
- storybook should work as before
<details>
<br />
</details>
<details>
<br />
2. You have …
> chore: update node-fetch to remove vulnerability

- yarn.lock
[FX-2533]
Update `json-schema` to v0.4.0, to fix [vulnerability](https://security.snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922). 
<details>
<br />
</details>
<details>
<br /> …
> chore: update json-schema to remove vulnerability

- .changeset/tasty-tigers-cheer.md
- packages/picasso/src/FileInput/FileInput.tsx
[FX-2567](https://toptal-core.atlassian.net/browse/FX-2567)
In this PR the `onFocus` and `onBlur` events are being added to the [FileInput](https://picasso.toptal.net/?path=/story/forms-fileinput--fileinput) component. The goal is to validate this field when the user tabs over it creating a better UX.
- CI green
- Go to the [Form Default Story](https://picasso.toptal.net/?path=/story/picasso-forms-form--form#default)
- Press tab to navigate over the components
- Note that, when tab is pressed on the **FileInput** component, the requireness message appears
https://user-images.githubusercontent.com/4607181/160970449-b7daa106-dcd4-49dc-a319-c7ab36abc2b2.mp4
<details>
<br />
- `@toptal-bot …
> feat(FileInput): add onFocus and onBlur events to FileInput

- ci/jobs/picasso-master-publish-docs/Jenkinsfile
ci: fix sshagent in docs Jenkinsfile
-
> ci: fix sshagent in docs Jenkinsfile

- .changeset/seven-terms-sniff.md
- cypress/component/BarChart.spec.tsx
- packages/picasso-charts/src/BarChart/BarChart.tsx
- packages/picasso-charts/src/BarChart/story/HideBarLabel.example.tsx
- packages/picasso-charts/src/BarChart/story/index.jsx
- packages/picasso-charts/src/BarChart/test.tsx
[PRI-10](https://toptal-core.atlassian.net/browse/PRI-10)
- Add optional `hideBarLabel ` prop to `BarChart` component which allows hiding label of each bar
- Add story about how to use `hideBarLabel ` prop
- Add jest&cypress tests
- Add changeset for `Picasso-Charts` package
| ![Without prop (false by default)](https://user-images.githubusercontent.com/101523174/161029811-4157e4f6-901e-4406-b3fe-e5a4a182967e.png) | ![With passed prop](https://user-images.githubusercontent.com/101523174/161029718-fce26ad6-4b39-4b71-8ee6-cdace395d58d.png) |
<details>
<br />
- …
> feat(BarChart): add hideBarLabel prop which hides label of each bar

- .storybook/components/Markdown/Markdown.tsx
- .storybook/utils/documentation-generator.ts
- package.json
- packages/picasso-charts/src/BarChart/BarChart.tsx
- packages/picasso-charts/src/BarChart/story/index.jsx
- packages/picasso-charts/src/LineChart/LineChart.tsx
- packages/picasso-charts/src/LineChart/story/index.jsx
- packages/picasso-charts/src/types.ts
- yarn.lock
[FX-2568]
Remove manually entered docs and replace them with automatically generated docs, based on props.
| Before | After |
| ---- | ---- |
| <img width="857" alt="Screenshot 2022-04-05 at 10 54 23" src="https://user-images.githubusercontent.com/2836281/161706085-05bbca60-9b48-42da-a603-e44ad65111a3.png"> | <img width="945" alt="Screenshot 2022-04-05 at 10 54 32" src="https://user-images.githubusercontent.com/2836281/161706175-0cc37d67-d2da-4683-a16a-0b70ca96c9a0.png"> |
| ---- | ---- |
| <img width="411" alt="Screenshot 2022-04-05 at 10 56 11" src="https://user-images.githubusercontent.com/2836281/161706391-ed92b2a8-c519-4cdd-82ef-9d7682cee20f.png"> | <img width="370" alt="Screenshot 2022-04-05 at 10 56 20" src="https://user-images.githubusercontent.com/2836281/161706438-adf2f9ce-1174-4 …
> chore: remove bar charts manual docs

- .changeset/strong-penguins-accept.md
- packages/picasso/package.json
[FX-NNNN]
When updating `picasso-testbed` I have noticed, that we have a storybook addon as a dependency. It is a mistake.
<details>
<br />
</details>
<details>
<br /> …
> chore: move storybook addon to dev dependencies

- .changeset/eleven-frogs-rush.md
- cypress/component/RichTextEditor.spec.tsx
- packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
- packages/picasso/src/RichTextEditor/RichTextEditor.tsx
- packages/picasso/src/RichTextEditor/story/Status.example.tsx
- packages/picasso/src/RichTextEditor/story/index.jsx
- packages/picasso/src/Select/types.ts
- packages/picasso/src/TimePicker/TimePicker.tsx
[FX-2510]
- added `status` prop just like other input props
- you can check the form page to see its working
<details>
<br />
</details>
<details>
<br /> …
> chore(RichTextEditor): add `status` prop

- cypress/component/Avatar.spec.tsx
- packages/picasso/src/StaticTreeView/story/Default.example.tsx
- packages/picasso/src/StaticTreeView/story/Horizontal.example.tsx
- packages/picasso/src/TreeView/story/CustomZoom.example.tsx
- packages/picasso/src/TreeView/story/Default.example.tsx
- packages/picasso/src/TreeView/story/Horizontal.example.tsx
- packages/picasso/src/TreeView/story/Modal.example.tsx
You should understand that Jacqueline Roque was the favorite woman in Pablo Picasso's life... and never use full URLs anymore 😃 
<details>
<br />
</details>
<details>
<br /> …
> chore: relative path for Jacqueline

- .github/workflows/handle-contribution.yml
- .github/workflows/request-review-on-pr.yml
[FX-2570](https://toptal-core.atlassian.net/browse/FX-2570?atlOrigin=eyJpIjoiNjUyNTQyMDk5MjdlNDUzZmEyODQ0ZDg3NDk1ZmVlOWEiLCJwIjoiaiJ9)
Use `notify-jira-about-contribution` GH action which already does what we want:
- handle draft PRs
- ignore dependabot PRs
<details>
<br />
- …
> chore: [FX-2570] Split contribution workflow into reusable parts

- .changeset/yellow-rivers-agree.md
[FX-2164](https://toptal-core.atlassian.net/browse/FX-2164)
Adds the missing picasso-codemods changeset from #2561
<details>
<br />
</details>
<details>
<br />
1. Something is broken after …
> chore: add missing changeset for Badge codemod

- package.json
- yarn.lock
[FX-NNNN]
Update `async` package to remove [vulnerability](https://security.snyk.io/vuln/SNYK-JS-ASYNC-2441827)
Old versions of async were used by:
- `happo-plugin-storybook` - upgradeable (will do in next PR with a major update of happo.io)
- `happo-cypress` - upgradeable (will do in next PR with a major update of happo.io)
- `ejs` - used in old visual tests, already up to date - not fixable at the moment
- `webpack-dev-server` - uses old version even on latest version - not fixable at the moment
Since we have some unfixable dependencies, we need to add `async` to resolutions.
<details>
<br />
- …
> chore: update async to remove vulnerability

- .changeset/two-ducks-fry.md
- package.json
- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/picasso/src/Autocomplete/test.tsx
- packages/picasso/src/Autocomplete/use-autocomplete/test.ts
- packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts
- packages/picasso/src/DatePicker/test.tsx
- packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
- packages/picasso/src/PromptModal/test.tsx
- packages/picasso/src/Tooltip/test.tsx
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
- yarn.lock
[FX-2601]
Picasso is backward compatible, so our users can keep using React 16 if they want. I have changed peerDependencies to `>=16.12.0`.
In React@18 render function from `react-dom` is [deprecated](https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis) and needs to be replaced with a new API so React actually uses new version. In our application, it is used only by `@testing-library`, so I needed to update these packages too. It brought some small changes in tests.
<details>
<br />
- `@toptal-bot …
> chore: update to react18

- .github/workflows/release.yml
> Revert "fix: skip ci commit message for changesets"

- .storybook/main.js
[FX-2601]
Enable [StrictMode](https://reactjs.org/docs/strict-mode.html) for development in storybook.
<details>
<br />
</details>
<details>
<br /> …
> chore: enable strict mode in storybook

- packages/picasso/package.json
- yarn.lock
[FX-NNNN]
Update styled components to latest version
<details>
<br />
</details>
<details>
<br />
3. Code is …
> chore: update styled-components

- .github/workflows/davinci-alpha-package.yml
[FX-NNNN]
Add davinci alpha package workflow.
<details>
<br />
</details>
<details>
<br /> …
> chore: add alpha package workflow

- .github/workflows/davinci-alpha-package.yml
[FX-NNNN]
update NPM_TOKEN
<details>
<br />
</details>
<details>
<br />
1. You …
> chore: update NPM_TOKEN

- .changeset/chilled-adults-poke.md
- packages/picasso/src/ModalContent/hooks/test.tsx
- packages/picasso/src/ModalContent/hooks/use-scrollable-shades.ts
Just a small fix: clear `updateShades` debounce on component unmount
- CI should pass
<details>
<br />
</details>
<details>
<br />
**You …
> chore(modal content): clear `update shades` debounce on component unmount

- packages/picasso-forms/src/Form/story/CustomValidator.example.tsx
- packages/picasso-forms/src/Form/story/Default.example.tsx
- packages/picasso-forms/src/Form/story/ParseInput.example.tsx
- packages/picasso-forms/src/Form/story/TitleCase.example.tsx
- packages/picasso-forms/src/story/FormSpy.example.tsx
[FX-2635]
- just added stringify to our form submit alert messages.
- you can try to submit some values and check the alert
<details>
<br />
</details>
<details>
<br /> …
> chore: prettify alert messages for submit values

- .husky/pre-commit
- package.json
- yarn.lock
Upgrade `husky` and `davinci`.
<details>
<br />
</details>
<details>
<br />
**You want your …
> chore: upgrade husky

- packages/picasso-charts/package.json
- packages/picasso/package.json
- packages/picasso/src/TreeView/TreeViewContainer.tsx
- packages/picasso/src/TreeView/useTree.ts
- packages/picasso/src/TreeView/useZoom.ts
- packages/topkit-analytics-charts/package.json
- yarn.lock
Update all d3 packages to the latest possible version.
- We don't need to keep d3-arrays in resolutions anymore
- We are not able to update to the highest major versions of d3 packages since they are ESM
**affected components:**
- Charts
- StaticTreeView
- TreeView
<details>
<br />
</details>
<details>
<br /> …
> chore(deps): bump d3 packages

- packages/picasso-provider/package.json
- packages/picasso-provider/src/CssBaseline/CssBaseline.tsx
- packages/picasso-provider/src/CssBaseline/styles.ts
- packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
- packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
- packages/picasso-provider/src/Picasso/Picasso.tsx
- packages/picasso-provider/src/Picasso/PicassoProvider.tsx
- packages/picasso-provider/src/Picasso/config/breakpoints.ts
- packages/picasso-provider/src/Picasso/config/palette.ts
- packages/picasso-provider/src/Picasso/config/shadows.ts
- packages/picasso-provider/src/Picasso/config/theme.ts
- packages/picasso-provider/src/Picasso/config/typography.ts
- packages/picasso-provider/src/Picasso/styles.tsx
- packages/picasso-provider/src/Picasso/utils/get-serverside-stylesheets.ts
- yarn.lock
[FX-2653]
I ran preset-safe codemod for our picasso-provider package.
I also fixed some type issues manually for now.
There will be more changes related to Picasso package soon
### How to test
Rather than actual testing, trying to understand what is being changed is enough. This PR will always be red due to Picasso package type errors. I will handle them next
<details>
<br />
</details>
<details>
<br />
**You are OK** with merging this …
> chore: run codemods for picasso-provider package

- packages/picasso/src/Accordion/Accordion.tsx
- packages/picasso/src/Notification/Notification.tsx
- packages/picasso/src/PromptModal/PromptModal.tsx
- packages/picasso/src/utils/Notifications/use-notifications.tsx
[FX-2654]
Updated ref types according to [MUI migration document](fx-2654-update-ref-types) 
- codewise review is enough
<details>
<br />
</details>
<details>
<br /> …
> chore: update ref types

- .storybook/main.js
- .storybook/preview.js
- packages/picasso-provider/package.json
- packages/picasso-provider/src/CssBaseline/styles.ts
- packages/picasso-provider/src/Picasso/PicassoProvider.tsx
- packages/picasso-provider/src/Picasso/config/breakpoints.ts
- packages/picasso-provider/src/Picasso/config/theme.ts
- packages/picasso/package.json
- packages/picasso/src/Modal/Modal.tsx
- yarn.lock
[FX-2655]
- fixed storybook configuration for new emotion usages
- updated some of the MUI utilities and theme structures
- You can check some of the pages in the storybook. Don't forget that there are still some broken styles. It may be related to nested selectors which should be updated due to emotion updates. I will take care of them in the tss-react migration.
<details>
<br />
</details>
<details>
<br /> …
> fix: fix emotion for storybook

- .github/PULL_REQUEST_TEMPLATE.md
[FX-2584]
Update PR template with development acceptance criteria
- check the **Development checks**
<details>
<br />
</details>
<details>
<br /> …
> chore: update pr template with review criteria

- jest-setup-dom.js
- packages/picasso/src/NativeSelect/NativeSelect.tsx
- packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
- packages/picasso/src/index.ts
- puppeteer/index.ts
No ticket.
- doing some Spring clean up on TODOs
- tests pass
- check TODOs manually, make sure they can be removed
~~- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~~
~~- [ ] Annotate all `props` in component with documentation~~
~~- [ ] Create `examples` for component~~
~~- [ ] Ensure that deployed demo has expected results and good examples~~
~~- [ ] Ensure the changed/created …
> chore: clean up old TODOs

- .github/PULL_REQUEST_TEMPLATE.md
[FX-2584]
Add check to not forget to mention codemods in changeset
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contributio …
> chore: add aditional todo to PR template

- .changeset/young-ways-shake.md
- packages/picasso/package.json
- packages/picasso/src/DatePicker/DatePicker.tsx
- packages/picasso/src/DatePicker/constants.ts
- packages/picasso/src/Dropdown/Dropdown.tsx
- packages/picasso/src/MenuItem/MenuItem.tsx
- packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
- packages/picasso/src/PageTopBarMenu/PageTopBarMenu.tsx
- packages/picasso/src/Popper/Popper.tsx
- packages/picasso/src/Popper/index.ts
- packages/picasso/src/Popper/styles.ts
- packages/picasso/src/Popper/test.tsx
- packages/picasso/src/Select/types.ts
- packages/picasso/src/Select/utils/is-related-target-inside-popper/is-related-target-inside-popper.ts
- packages/picasso/src/Sidebar/Sidebar.tsx
- packages/picasso/src/Tooltip/Tooltip.tsx
- packages/picasso/src/Tooltip/useTooltipFollowCursor.ts
- packages/picasso/src/Tooltip/useTooltipHandlers.ts
- packages/picasso/src/TypographyOverflow/TypographyOverflow.tsx
- yarn.lock
[FX-2665]
- migrated Popper.js to version 2. Here is also [migration document from popperjs](https://popper.js.org/docs/v2/migration-guide/)
- you can check out the tooltip page.
- some styles are still broken due to nested stylings (`$`)
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename …
> chore: migrate Popper.js to v2

- .changeset/dry-plums-accept.md
- packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
- packages/picasso/src/Autocomplete/test.tsx
- packages/picasso/src/NonNativeSelect/__snapshots__/test.tsx.snap
- packages/picasso/src/NonNativeSelectLoader/__snapshots__/test.tsx.snap
- packages/picasso/src/NonNativeSelectOptions/__snapshots__/test.tsx.snap
- packages/picasso/src/ScrollMenu/ScrollMenu.tsx
- packages/picasso/src/ScrollMenu/__snapshots__/test.tsx.snap
- packages/picasso/src/ScrollMenu/test.tsx
- packages/picasso/src/YearSelect/__snapshots__/test.tsx.snap
[FX-2668]
Move the prevent mouseDown to the div with the scrollbar to be able to use search input in fixedHeader
- TagSelector and Autocomplete do not close options when using the scrollbar
- search input in the Select component is focusable
<details>
<br />
</details>
<details>
<br />
**You are OK** with merging this …
> fix(ScrollMenu): prevent mousedown on part with scrollbar

- docs/decisions/template.md
- packages/picasso/README.md
[FX-NNNN]
- check [new desicition story](https://picasso.toptal.net/FX-RFC/?path=/story/decisions-changeset-verb-tense--changeset-verb-tense)
-  Covered with tests
-  codemod is created and showcased in the changeset
-  test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details>
<br />
1. You …
> chore: document decision about changeset verb tense

- .github/workflows/davinci-alpha-package.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/pr.yaml
[FX-2732]
Let workflows use v1 of reusable GitHub actions
- deploys should work
<details>
<br />
</details>
<details>
<br /> …
> chore: checkout davinci github actions with version 1

- ci/jobs/picasso-master-publish-docs/Jenkinsfile
Throw an error in CI when rsync finished with an error and we couldn't deploy a new version of Picasso storybook.
**How it works now:**
https://jenkins-deployment.toptal.net/job/picasso-docs/227/console
output:
```
15:19:10  + rsync -avz --delete -e ssh /var/lib/jenkins/workspace/picasso-docs/deploy-docs/ 'docs@docs.staging.toptal.net:~/docs/picasso/master'
15:21:32  ssh: connect to host docs.staging.toptal.net port 22: Connection timed out
15:21:32  rsync: connection unexpectedly closed (0 bytes received so far) [sender]
15:21:32  rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.2]
15:21:32  + rm -rf /var/lib/jenkins/workspace/picasso-docs/deploy-docs
```
but the job status is `SUCCESS`.
**How it should work:** …
> fix: raise error from rsync if error

- .github/workflows/davinci-alpha-package.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/pr.yaml
[FX-2711]
Start using version 2 of davinci github actions. Changes in new version:
- all inputs/outputs using kebab-case
- `build-alpha-package` action changed to `build-publish-alpha-package`
- CI is green
- deploys are working
- alpha package release is working
<details>
<br />
</details>
<details>
<br />
1. Add …
> chore: synced workflow with refactored GHAs

- packages/picasso/src/Button/Button.tsx
- packages/picasso/src/Button/story/index.jsx
Replace manual props docs and use manually generated docs instead.
<details>
<br />
</details>
<details>
<br /> …
> chore: generate props automatically for Button

- docs/contribution/changeset-guidelines.md
- docs/decisions/changeset-verb-tense.md
Document decision about using present simple in changesets
- checkout the document
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual …
> docs: add changeset verb tense decisions

- .changeset/stupid-monkeys-teach.md
- packages/picasso/src/Calendar/Calendar.tsx
- packages/picasso/src/Calendar/__snapshots__/test.tsx.snap
- packages/picasso/src/Calendar/styles.ts
- packages/picasso/src/CalendarContainer/styles.ts
- packages/picasso/src/CalendarMonthHeader/CalendarMonthHeader.tsx
[FX-2608]
[Design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library)
Update design of DatePicker to latest
- Compare [design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library) with the [storybook](https://picasso.toptal.net/FX-2608-date-picker/?path=/story/components-datepicker--datepicker)
| ![image](https://user-images.githubusercontent.com/6830426/167363676-79b3ff5c-b3a7-43e9-882e-b406f740df49.png) | ![image](https://user-images.githubusercontent.com/6830426/167363532-0bf45fd5-190b-4a75-aea7-a013db1336e2.png) |
- Create …
> style(DatePicker): update to latest design

- packages/picasso/package.json
- yarn.lock
🍎 
While working on Picasso update for our repo; during analysis, it is shown as
`"react-helmet": "6.1.0",` in Picasso's package.json
but 
`"@types/react-helmet": "^5.0.15",`
Fixing these inconsistencies.
Review is required, nothing should be affected on output.
No visual changes.
- n/a Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- n/a Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testi …
> chore: sync @types/react-helmet with react-helmet

- docs/decisions/mui-v5-migration.md
Proposal for Material-UI v5 migration plan
1. You understand the plan and you don't have any objection to it.
2. You have optional requests related to planning or the goal.
> chore: add proposal for MUIv5 migration

- .storybook/stories/tutorials/layout/story/Layout.3.example.tsx
- .storybook/stories/tutorials/layout/story/Layout.4.example.tsx
- .storybook/stories/tutorials/layout/story/Layout.final.example.tsx
No ticket.
It was noticed our tutorial was broken.
Codemods were not applied to it, and old Sidebar imports were used, instead of Page.Sidebar.
This PR fixes that.
- The layout tutorial found here https://picasso.toptal.net/?path=/story/tutorials-how-to-layout-a-page--how-to-layout-a-page works just fine and doesn't crash
<details>
<br />
</details>
<details>
<br /> …
> fix: import correct sidebar in layout tutorial

- packages/picasso/src/Input/Input.tsx
- packages/picasso/src/Input/__snapshots__/test.tsx.snap
- packages/picasso/src/Input/styles.ts
- packages/picasso/src/InputIconAdornment/InputIconAdornment.tsx
- packages/picasso/src/InputIconAdornment/index.ts
- packages/picasso/src/InputIconAdornment/styles.ts
- packages/picasso/src/InputLimitAdornment/InputLimitAdornment.tsx
- packages/picasso/src/InputLimitAdornment/index.ts
- packages/picasso/src/InputLimitAdornment/styles.ts
- packages/picasso/src/TimePicker/__snapshots__/test.tsx.snap
Extracted internal adornment components from `Input` to avoid pollution and bring better readability.
We have a contribution to extending the status="success" adornment, so this PR will ease the process for modifications on adornments.
- Input component should work as the same
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: …
> chore: extract internal adornment components from Input

- .madgerc
- package.json
- yarn.lock
[FX-2739]
Add circularity check via [Madge](https://github.com/pahen/madge)
- `yarn install`
- `yarn circularity`
<details>
<br />
</details>
<details>
<br /> …
> chore: [FX-2739] Add madge circularity check

- .prettierignore
- packages/picasso/src/Accordion/Accordion.tsx
- packages/picasso/src/Alert/Alert.tsx
- packages/picasso/src/Button/Button.tsx
- packages/picasso/src/Button/index.ts
- packages/picasso/src/ButtonCompound/index.tsx
- packages/picasso/src/ButtonGroup/test.tsx
- packages/picasso/src/ButtonSplit/ButtonSplit.tsx
- packages/picasso/src/CalendarMonthHeader/CalendarMonthHeader.tsx
- packages/picasso/src/Drawer/Drawer.tsx
- packages/picasso/src/FileListItem/FileListItem.tsx
- packages/picasso/src/Helpbox/Helpbox.tsx
- packages/picasso/src/Modal/Modal.tsx
- packages/picasso/src/Notification/Notification.tsx
- packages/picasso/src/OutlinedInput/OutlinedInput.tsx
- packages/picasso/src/PageSidebar/PageSidebar.tsx
- packages/picasso/src/PasswordInput/PasswordInput.tsx
- packages/picasso/src/RichTextEditorButton/RichTextEditorButton.tsx
- packages/picasso/src/Section/Section.tsx
- packages/picasso/src/ShowMore/ShowMore.tsx
- packages/picasso/src/index.ts
[FX-2739]
Fix circularity issues in `Button` component files
- `yarn circularity`
-  see 47 errors instead of 53
<details>
<br />
</details>
<details>
<br /> …
> fix: [FX-2739] Fix circularity in Button files - part 1

- packages/picasso/CHANGELOG.md
no-jira
fixed indentation for last commit
> fix(changelog): fix changelog file indentation for last merged commit

- .changeset/shiny-lemons-teach.md
[FX-2739]
Fix file circularity issues
https://github.com/toptal/picasso/pull/2772
https://github.com/toptal/picasso/pull/2777
https://github.com/toptal/picasso/pull/2778
https://github.com/toptal/picasso/pull/2787
https://github.com/toptal/picasso/pull/2789
https://github.com/toptal/picasso/pull/2791
and added PR circularity check
https://github.com/toptal/picasso/pull/2792
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> fix: [FX-2739] Fix file circularity issues

- cypress/component/Accordion.spec.tsx
[FX-2705]
Unskip visual tests for accordion. We were also testing the same thing in multiple test cases, so I have cleared that out. Expect some changes in Happo screenshots.
- I have run the CI tests multiple times and any flakiness didn't appear
- …
> chore: unskip accordion tests

- cypress/component/Dropzone.spec.tsx
[FX-2705]
CI tests run multiple times without any flakiness.
<details>
<br />
</details>
<details>
<br />
3. …
> chore: unskip Dropzone tests

- cypress/component/Tooltip.spec.tsx
[FX-2705]
It seems we missed a bug because of the skipped test. I have created [ticket](https://toptal-core.atlassian.net/browse/FX-2791) to fix it separately.
<details>
<br />
</details>
<details>
<br />
**You are not OK** with merging …
> chore: unskip Tooltip tests

- cypress/component/PageSidebar.spec.tsx
[FX-2705]
<details>
<br />
</details>
<details>
<br /> …
> chore: fix flake test in PageSidebar

- .changeset/happy-parents-reply.md
- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
`&&` is not supported in [semantic versions](https://jubianchi.github.io/semver-check/#/%3E%3D16.12.0%20%26%26%20%3C%2019.0.0/19). I have fixed the issue with the proper range format https://jubianchi.github.io/semver-check/#/%3E%3D16.12.0%20%3C%2019.0.0/19
- nothing should change
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- Ensure the changed/created components have not caused …
> fix(dep): update semver range for react

- .github/workflows/visual-testing.yml
When I was implementing integration tests with parallelization, I forgot to call the workflow from visual-testing.yml and just [removed the steps for integration tests](https://github.com/toptal/picasso/pull/2667/files#diff-ccca055b523bbd9bd29f335134232730d3ff76974628b4c4ff7b01cfca66f0d6)
Thanks @ozgurkececioglu for noticing
The workflow is temporarily allowed in this PR, you can check it in PR checks (or [here](https://github.com/toptal/picasso/runs/6606732614?check_suite_focus=true))
<details>
<br />
- `@toptal-bot …
> fix: visual-testing wf after PR merge

- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
This PR is about adding storybook-happo into the visual testing workflow
- nothing to see as a test result
<details>
<br />
</details>
<details>
<br /> …
> chore(happo): add happo tests to visual-testing.yml

- .changeset/large-badgers-remain.md
- .changeset/shiny-beans-exist.md
- .changeset/wicked-cycles-kneel.md
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/picasso/src/utils/Notifications/styles.ts
- packages/shared/package.json
- yarn.lock
[TACO-1516]
On small screens, notifications overflow the screen. That makes it impossible to read a notification message or close it with `x` icon. That happens because we fixed the width of `SnackbarContent` to `27.5em` for info notification type and to `20em` for other notification types. 
The solution is to add `max-width: 100%` to `SnackbarContent` styles. But that property is ignored by the browser because the parent element has `width: auto` which is set by the `notistack` package. That was fixed in [version `1.0.6`](https://github.com/iamhosseindhv/notistack/commit/fe4b7c8edd53189a9f46b3032e276aaef98f76b2). That's why I have to upgrade version of `notistack` from `1.0.5` to `1.0.6`.
- Open https://picasso.toptal.net/?path=/story/components-notification--notification#notifications-st …
> fix(Notification): fix notification overflow on small screens

- cypress.config.ts
- package.json
- yarn.lock
Fix parallelization for cypress tests in CI
- check [integration tests parallel runs](https://github.com/toptal/picasso/runs/6933099492?check_suite_focus=true) and compare test files - each run should have different files
- codemod is created and …
> fix: cypress parallelization in CI

- .github/PULL_REQUEST_TEMPLATE.md
Simplify PR template - remove `Ensure that all PR checks are green` check as it unnecessary
- just checking the code is enough
<details>
<summary>PR …
> chore: remove 'Ensure that all PR checks are green' from PR template

- .github/workflows/handle-contribution.yml
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You are OK** with merging this …
> chore: bump notify jira about contribution version

- .storybook/preview-head.html
- .storybook/preview.js
- package.json
- yarn.lock
Fix markdown CSS styles in Storybook
- Open storybook temploy
- Check markdown styles
| <img width="1489" alt="Screenshot 2022-06-23 at 20 29 27" src="https://user-images.githubusercontent.com/2836281/175359611-334cbd92-5c10-42c2-b35e-4a2b458b8f4b.png"> |  <img width="1511" alt="Screenshot 2022-06-23 at 20 29 00" src="https://user-images.githubusercontent.com/2836281/175359644-d4b936ef-c30c-4fda-b95c-a07788010c36.png">  |
<details>
<br />
- `@toptal-bot run deploy:documentation` …
> chore: fix markdown styles in storybook

- .github/workflows/handle-contribution.yml
Update contribution workflow to latest with fixed and escaped TITLE
- tickets from contributors have correct title 
<details>
<summary>PR …
> fix: update contribution workflow

- packages/picasso/src/Accordion/Accordion.tsx
- packages/picasso/src/Accordion/Details.tsx
- packages/picasso/src/Accordion/Summary.tsx
- packages/picasso/src/Accordion/index.ts
- packages/picasso/src/Accordion/story/index.jsx
- packages/picasso/src/AccordionCompound/index.ts
- yarn.lock
After exporting `Details` and `Summary` from `Accordion.tsx` the doc generation broke down. Thank you @TomasSlama for pointing this out. 
I've extracted these components to 2 separate files and updated the story.
- `yarn`
- `yarn start`
- inspect the Storybook
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from …
> refactor(Accordion): fix documentation

- .changeset/swift-trainers-applaud.md
- packages/picasso/src/QuillEditor/formats/bold.ts
- packages/picasso/src/QuillEditor/formats/header.ts
- packages/picasso/src/QuillEditor/formats/link.ts
- yarn.lock
[COMM-1067]
Format creation for RichTextEditor needed a refactor to make it more efficient
- Access the temploy/preview.
- RichTextEditor should work as expected
- CI should be 💚 
<details>
<br />
</details>
<details>
<br /> …
> fix: refactor creating formats

- .changeset/sour-cougars-rhyme.md
- packages/picasso/src/Section/Section.tsx
- packages/picasso/src/Section/__snapshots__/test.tsx.snap
- packages/picasso/src/Section/story/Collapsible.example.tsx
- packages/picasso/src/Section/styles.ts
[SPT-2767](https://toptal-core.atlassian.net/browse/SPT-2767)
The collapsible animation for the Section with variant `withHeaderBar` is not smooth.
This PR fixes this issue by adding a wrapper for the section content.
- Check the Section storybook - https://picasso.toptal.net/SPT-2767-fix-collapsible-section-animation/?path=/story/components-section--section#collapsible
|![old-sectionKapture 2022-06-27 at 15 25 52](https://user-images.githubusercontent.com/2583281/175941596-6be0b9b4-7862-429b-a09b-a0425ce1bad5.gif)|![new-section-Kapture 2022-06-27 at 15 27 07](https://user-images.githubusercontent.com/2583281/175941561-3 …
> fix: improve collapsible section animation

- package.json
- yarn.lock
[FX-2859](https://toptal-core.atlassian.net/browse/FX-2859)
Updating lerna to v5. I didn't find any relevant performance boosts for our use cases when running `build:package` (the only script still using lerna on Picasso). In fact when using `useNx: true` it was twice as slower, even thought it is expected to be a lot faster.
- You can run `yarn build:package` on the local branch, as it uses lerna
| Version                      | Benchmark |
| --------------------------------------- | --- |
| Lerna v4 | ![image](https://user-images.githubusercontent.com/5845160/176086702-fa208a69-db1c-4019-bd31-748f30e34dcb.png) |
| Lerna v5 | ![image](https://user-images.githubusercontent.com/5845160/176086788-4aaacde1-0a79-4547-ad7e-e1c42b578a5a.png) |
| Lerna v5 with useNx | …
> chore: update lerna to v5

- .github/workflows/release.yml
By using `workflow_dispatch` event, we will be able to trigger release manually in case the workflow isnt triggered automatically when Version PR is merged.
- Unfortunately, until its merged to master, it cannot be tested. But adding one more trigger event won't affect previous behavior
- …
> chore: add ability to trigger release manually

- .changeset/eight-apples-refuse.md
- packages/picasso-provider/package.json
- packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
- packages/picasso-provider/src/Picasso/NotificationsProvider/styles.ts
- packages/picasso/package.json
- packages/picasso/src/utils/Notifications/__snapshots__/test.tsx.snap
- packages/shared/package.json
- yarn.lock
After [conversation with Tiago](https://toptal-core.slack.com/archives/CERF5NHT3/p1656618387544099) we realized `notistack` needs a bump to version `1.0.10`
- CR is enough
<details>
<br />
- …
> chore: bump notistack to 1.0.10

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Add a checkbox about BASE design on PR template
<details>
<br />
</details>
<details>
<br />
**You want your comments …
> docs: add BASE design instructions on PR template

- .github/workflows/handle-contribution.yml
Update contribution workflow to latest …
> feat: update contribution workflow to latest

- docs/contribution/component-api.md
Add principle to component API principles
<details>
<br />
</details>
<details>
<br />
**You want your comments to be addressed** before …
> docs: add component api principles

- package.json
- yarn.lock
[FX-NNNN]
We need this patch that adds `--no-verify-access` to fix Lerna publish for alpha packages
- check that alpha package was generated probably
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contr …
> chore: bump Davinci to 18.4.2

- .changeset/short-elephants-whisper.md
- packages/picasso/src/PageTopBarMenu/PageTopBarMenu.tsx
[TACO-1619]
On `small` and `medium` screens the `meta` of the `TopBarMenu` is shown in a drop-down with white background. The `meta` itself is using white font color making it invisible.
Use the following example https://picasso.toptal.net/TACO-1619-talent-application-responsive-design-issues/?path=/story/layout-page--page#page-topbar-right-content 
| ![image](https://user-images.githubusercontent.com/4757057/180770382-5b9e2d24-96cd-4729-9174-d268376f7cf0.png) | ![image](https://user-images.githubusercontent.com/4757057/180770231-3405e36b-6b21-4ac4-8b9d-01c8e6738e2c.png) |
> All **_development checks_** should be done …
> fix(TopBarMenu): meta is invisible on small and medium screens

- .changeset/brave-eyes-smell.md
- packages/picasso-charts/package.json
- packages/picasso-provider/package.json
- packages/picasso-provider/src/Picasso/config/theme.ts
- packages/picasso/package.json
- packages/picasso/src/Accordion/__snapshots__/test.tsx.snap
- packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
- packages/picasso/src/DatePicker/__snapshots__/test.tsx.snap
- packages/picasso/src/Input/__snapshots__/test.tsx.snap
- packages/picasso/src/Section/__snapshots__/test.tsx.snap
- packages/picasso/src/SidebarItem/__snapshots__/test.tsx.snap
- packages/picasso/src/TimePicker/__snapshots__/test.tsx.snap
- packages/picasso/src/utils/Notifications/__snapshots__/test.tsx.snap
- yarn.lock
[FX-2948](https://toptal-core.atlassian.net/browse/FX-2948)
Update material to the latest 4.x.x version
- Alpha storybook should be working the same as before the update
<details> …
> feat: update material-ui to latest 4.x.x

- .changeset/few-rules-wink.md
- .storybook/stories/tutorials/spacings/story/index.jsx
[FX-NNNN]
- Links to `Paper` and `Container` components in [How to use spacings](https://picasso.toptal.net/?path=/story/tutorials-how-to-use-spacings--how-to-use-spacings) tutorial is broken
- [How to use spacings](https://picasso.toptal.net/?path=/story/tutorials-how-to-use-spacings--how-to-use-spacings) page has correct links to `Paper` and `Container` components.
- …
> fix: broken links in storybook spacing tutorial

- .changeset/young-numbers-attack.md
- packages/picasso/src/Drawer/Drawer.tsx
Following #2315 added `transitionProps` prop to Drawer for better control over open/close transitions
<details>
<br />
</details>
<details>
<br />
**You are …
> feat(Drawer): add transitionProps prop

- docs/decisions/09-avatar-upload.md
[FX-2889]
I created an RFC document according to the requirements of the ticket. Any questions/suggestions will be welcomed.
No need testing
None.
- Ensure that deployed demo has expected results …
> chore: add RFC document for avatar-upload

- .github/PULL_REQUEST_TEMPLATE.md
[FX-NNNN]
- Make sure that additions and changes on design follow [Toptal's …
> chore: add anvil review in pr template

- .changeset/khaki-carpets-beam.md
- cypress/component/Dropdown.spec.tsx
- packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
- packages/picasso/src/Dropdown/Dropdown.tsx
- packages/picasso/src/Dropdown/story/CustomStyle.example.tsx
- packages/picasso/src/Dropdown/story/index.jsx
- packages/picasso/src/Dropdown/styles.ts
[CPT-122](https://toptal-core.atlassian.net/browse/CPT-122)
Adding options to control dropdown content component
- check the 'Custom Height' example on picasso storybook
| <img width="293" alt="image" src="https://user-images.githubusercontent.com/5438099/183448498-8c6468e1-e354-409f-b2d1-f890ec5e561c.png"> | <img width="299" alt="image" src="https://user-images.githubusercontent.com/5438099/183448691-acec79f0-3dc9-4665-adba-1cbde2c21e43.png"> |
- [n/a] codemod is created and showcased in the changeset
- [n/a] test alpha package of Picasso in StaffPortal
> All **_development checks_** should be done …
> feat(dropdown): add contentStyle prop

- package.json
- yarn.lock
[FX-2977]
Bump Lerna to the latest version to fix https://github.com/toptal/picasso/security/dependabot/91
- CI is green
| ![image](https://user-images.githubusercontent.com/6830426/185057130-a66c8d58-0eba-4892-a45c-ee326ae94adb.png) | ![image](https://user-images.githubusercontent.com/6830426/185057195-5a241452-08ff-4ebf-b034-b0725c2a4dd6.png) | …
> chore(deps): bump lerna to use latest parse-url

- package.json
- yarn.lock
Cypress added a new feature `experimentalSingleTabRunMode` in 10.6.0, which actually uses functionality that was used back in version 9. We have this feature turned on by default in the Davinci
- locally run `yarn test:integration` - it should be 40%-50% faster than on current master
- similar results should be in CI
| ![image](https://user-images.githubusercontent.com/6830426/185063642-3d2690c4-4575-4c4d-ab98-56f9d5cab283.png) | ![image](https://user-images.githubusercontent.com/6830426/185064172-5451752b-dc67-455b-8d0f-4dee76c174a2.png) |
| Before.                                 | After. …
> chore(cypress): bump to 10.6.0 to run tests in single tab

- .changeset/metal-needles-talk.md
- packages/shared/package.json
[FX-3023](https://toptal-core.atlassian.net/browse/FX-3023)
We are moving `notistack` from picasso-shared dependencies to it's peerDeps
<details>
<br />
</details>
<details> …
> feat: move notistack on picasso-shared from a dependency to peerDep

- yarn.lock
[FX-2977]
Fix https://github.com/toptal/picasso/security/dependabot/93
CI should be green
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from …
> chore: bump terser to fix vulnerability issue

- .github/PULL_REQUEST_TEMPLATE.md
[FX-3024]
remove deprecated commands from PR template
<details>
<br />
</details>
<details>
<br />
**You are not OK** …
> docs: remove deprecated commands from PR template

- .changeset/blue-eels-compete.md
- cypress/component/AvatarUpload.spec.tsx
- packages/picasso/src/AvatarUpload/AvatarUpload.tsx
- packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
- packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
- packages/picasso/src/AvatarUpload/DropzoneSvg/utils.ts
- packages/picasso/src/AvatarUpload/__snapshots__/test.tsx.snap
- packages/picasso/src/AvatarUpload/index.ts
- packages/picasso/src/AvatarUpload/story/Default.example.tsx
- packages/picasso/src/AvatarUpload/story/WithUpload.example.tsx
- packages/picasso/src/AvatarUpload/story/index.jsx
- packages/picasso/src/AvatarUpload/styles.ts
- packages/picasso/src/AvatarUpload/test.tsx
- packages/picasso/src/AvatarUpload/types.ts
- packages/picasso/src/index.ts
[FX-2889]
- added functionality as simple as possible. other requirements like sizes and visual states will follow this PR.
- go to [component page](https://picasso.toptal.net/fx-2889-implement-basic-avatar-upload/?path=/story/components-avatarupload--avatarupload)
- there are two stories: default and with-upload. You can check them both to check the functionality works
> **GitHub Bot: TODOLess** …
> feat(AvatarUpload): implement AvatarUpload

- .eslintignore
- package.json
- yarn.lock
Start [linting changesets](https://github.com/toptal/davinci/wiki/packages:eslint-plugin:README#toptaldavinciconsistent-changesets)
- checkout branch
- generate empty changeset, add it to staged area and run lint-staged
- `yarn changeset --empty && git add .changeset && yarn lint-staged`
- Ensure the changed/created components …
> chore: lint changesets

- packages/picasso/src/AvatarUpload/story/UsingRef.example.tsx
- packages/picasso/src/AvatarUpload/story/index.jsx
no-jira
- I added an example for using ref while editing to reach the underlying dropzone.
you can check the newly added story: https://picasso.toptal.net/fx-avatarupload-add-edit-example/?path=/story/components-avatarupload--avatarupload#using-ref
no visual change
- Annotate all …
> chore(AvatarUpload): add editing example

- .changeset/four-hairs-yell.md
- .changeset/mean-pears-nail.md
- .changeset/twelve-bears-rescue.md
- README.md
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> Changeset release/test automerge tsl

- .changeset/four-hairs-yell.md
- .changeset/mean-pears-nail.md
- .changeset/twelve-bears-rescue.md
- README.md
[FX-NNNN]
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> Changeset release/test automerge

- package.json
- packages/picasso-charts/package.json
- packages/picasso-codemod/package.json
- packages/picasso-forms/package.json
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/shared/package.json
- packages/topkit-analytics-charts/package.json
- yarn.lock
[FX-NNNN]
Update Lerna to the latest version to remove [cricital vulnerability](https://github.com/toptal/picasso/security/dependabot/96)
We bump one minor version, where support for pnpm workspaces was added ([release notes](https://github.com/lerna/lerna/releases)) and it should not affect us at all
We had to fixate the version of Typescript to not be updated unexpectedly. Typescript is not following common semver and even minor bums can have breaking changes, we will need separate PR to update TS.
- Ensure that deployed demo has expected …
> chore: update lerna to latest version

- .github/workflows/automerge-release.yaml
[FX-3025](https://toptal-core.atlassian.net/browse/FX-3025)
Lift env variables to the workflow level to align with our standards.
- Nothing functional is changed, see if the code looks good
> All **_development checks_** …
> chore: lift envars up in the automerge job

- .changeset/hungry-clouds-stare.md
- packages/picasso/src/PageHead/PageHead.tsx
- packages/picasso/src/PageHead/story/NoBorder.example.tsx
- packages/picasso/src/PageHead/story/index.jsx
- packages/picasso/src/PageHead/styles.ts
[FX-NNNN]
closes #2955 
Users needs to be more flexible and hide bottom border of PageHead when directly followed by bordered section. Details and design approval is in the issue (#2955)
- Check storybook
- Check new screenshot in Happo 🙇 
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from …
> feat(PageHead): add noBorder prop

- .changeset/calm-pots-play.md
- packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
[TACO-1767]
This PR fixes a broken animation due to a type in the css.
To better see the difference update `fill` color in packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts on line 62 to red (or any other color). And maybe even increase transition duration.
- Run storybook locally
- Visit AvatarUpload example and hover on it. We should see transition to our color
<details>
<br />
</details>
<details>
<br />
1. You …
> fix(AvatarUpload): remove redundant time unit for animation function

- .changeset/gentle-meals-sort.md
- packages/picasso/src/utils/Formatters/format-amount.ts
- packages/picasso/src/utils/Formatters/story/amount.example.tsx
- packages/picasso/src/utils/Formatters/test.ts
[PRI-150]
add `maximumFractionDigits` and `minimumFractionDigits` options to `formatAmount` functions
<details>
<br />
</details>
<details>
<br />
2. …
> feat: decimal point options

- ci/jobs/build-image/Jenkinsfile
[CI-1537]
Duplicate image to artifact registry for later replace
[CI-1537]: https://toptal-core.atlassian.net/browse/CI-1537?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: duplicate image to artifact registry for later replace

- .changeset/fuzzy-items-invite.md
- packages/picasso/src/Amount/Amount.tsx
- packages/picasso/src/Amount/story/Decimals.example.tsx
- packages/picasso/src/Amount/story/index.jsx
[PRI-150]
Add `minimumFractionDigits` and `maximumFractionDigits` options to `<Amount />` component
- check new [example](https://picasso.toptal.net/PRI-150-amount-component/?path=/story/components-amount--amount#decimal-digits) in the storybook.
Storybook
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: …
> feat: add options prop

- docs/decisions/10-menu-item.md
[FX-3163]
RFC for refactoring of MenuItem
- discuss the document in review
<details>
<br />
</details>
<details>
<br /> …
> docs: add RFC for MenuItem refactoring

- .changeset/loud-scissors-remember.md
- packages/picasso/src/AccountSelect/__snapshots__/test.tsx.snap
- packages/picasso/src/Avatar/AvatarWrapper/AvatarWrapper.tsx
- packages/picasso/src/Avatar/AvatarWrapper/styles.ts
- packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
- packages/picasso/src/Dropdown/Dropdown.tsx
- packages/picasso/src/Dropdown/styles.ts
- packages/picasso/src/PageTopBarMenu/__snapshots__/test.tsx.snap
- packages/picasso/src/ProgressBar/ProgressBar.tsx
- packages/picasso/src/ProgressBar/__snapshots__/test.tsx.snap
- packages/picasso/src/ProgressBar/styles.ts
- packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
- packages/picasso/src/RichTextEditorToolbar/styles.ts
- packages/picasso/src/UserBadge/__snapshots__/test.tsx.snap
[FX-3191]
This PR is about removing dynamic style functions due to not working after the latest storybook update locally.
- Green CI and happo reports
- Nothing should be different visually
- no visual changes
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …
> fix: get rid of style functions

- ci/jobs/build-image/Jenkinsfile
[CI]
<details>
<br />
</details>
<details>
<br /> …
> fix: fix docker image build job

- .changeset/eleven-drinks-speak.md
- packages/picasso/src/DatePicker/DatePicker.tsx
- packages/picasso/src/DatePicker/story/WithFooterBackgroundColor.example.tsx
- packages/picasso/src/DatePicker/story/index.jsx
- packages/picasso/src/DatePicker/test.tsx
[SDE-607](https://toptal-core.atlassian.net/browse/SDE-607)
Add footer background color on DatePicker
- Access [https://picasso.toptal.net/sde-607-add-footer-background-color-property/](https://picasso.toptal.net/sde-607-add-footer-background-color-property)
- Verify footer background color example at Datepicker section
- Compare requirements in the ticket with implementation
| ![Screenshot_20221026_120057](https://user-images.githubusercontent.com/5639968/198062642-718c8286-2bf7-4c41-988b-29cb86b2e5cd.png) | ![Screenshot_20221026_120106](https://user-images.githubusercontent.com/5639968/198062674-aefe2fd8-1e8e-41aa-9d15 …
> feat(DatePicker): add footer background color

- .changeset/wise-yaks-care.md
- packages/picasso/src/AccountSelect/__snapshots__/test.tsx.snap
- packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap
- packages/picasso/src/Dropdown/__snapshots__/test.tsx.snap
- packages/picasso/src/Menu/__snapshots__/test.tsx.snap
- packages/picasso/src/Menu/story/Default.example.tsx
- packages/picasso/src/MenuItem/MenuItem.tsx
- packages/picasso/src/MenuItem/__snapshots__/test.tsx.snap
- packages/picasso/src/MenuItem/styles.ts
- packages/picasso/src/NonNativeSelect/__snapshots__/test.tsx.snap
- packages/picasso/src/NonNativeSelectLimitFooter/__snapshots__/test.tsx.snap
- packages/picasso/src/NonNativeSelectOption/__snapshots__/test.tsx.snap
- packages/picasso/src/NonNativeSelectOptions/__snapshots__/test.tsx.snap
- packages/picasso/src/ScrollMenu/__snapshots__/test.tsx.snap
- packages/picasso/src/SidebarItem/__snapshots__/test.tsx.snap
- packages/picasso/src/YearSelect/__snapshots__/test.tsx.snap
- yarn.lock
[FX-3129]
Add avatar option to MenuItem and consequently to Dropdown
- Check demo and Happo tests
<details>
<br />
</details>
<details>
<br /> …
> feat: dropdown with avatar

- .changeset/tricky-pears-mix.md
- packages/picasso/src/Dropzone/Dropzone.tsx
- packages/picasso/src/Dropzone/__snapshots__/test.tsx.snap
- packages/picasso/src/Dropzone/test.tsx
[FX-3229](https://toptal-core.atlassian.net/browse/FX-3229)
Updated Dropzone copy: "Click or drag file to upload" => "Click or drag to upload"
- Check the deployed temploy to see if the copy is updated according to the ticket
<details>
<br />
- `@toptal-anvil ping reviewers` - …
> fix: update copy text for Dropzone

- docs/decisions/12-vertical-tabs.md
[FX-3220]
Prepare RFC to decide which development approach to choose
<details>
<br />
</details>
<details>
<br />
**You …
> chore: showcase vertical tabs with userBadge

- yarn.lock
[FX-3262]
Bump `loader-utils`
- `2.0.3` 👉 `2.0.4`
- to remove vulnerabilities [[1](https://github.com/toptal/picasso/security/dependabot/110), [2](https://github.com/toptal/picasso/security/dependabot/108)] 
- `3.2.0` 👉 `3.2.1`
- to remove vulnerabilities [[3](https://github.com/toptal/picasso/security/dependabot/104), [4](https://github.com/toptal/picasso/security/dependabot/103)]
- CI should be green, temploy should work. `loader-utils` is used only by webpack loaders
<details>
<br />
</details> …
> chore(deps): bump loader-utils to fix vulnerabilities

- cypress/component/TopBarMenu.spec.tsx
- packages/picasso/src/PageCompound/index.ts
- packages/picasso/src/PageTopBar/PageTopBar.tsx
- packages/picasso/src/PageTopBar/story/CenterContent.example.tsx
- packages/picasso/src/PageTopBar/story/Variants.example.tsx
- packages/picasso/src/PageTopBar/story/index.jsx
- packages/picasso/src/PageTopBar/styles.ts
- packages/picasso/src/PageTopBarCompound/index.ts
- packages/picasso/src/TopBarItem/TopBarItem.tsx
- packages/picasso/src/TopBarItem/index.ts
- packages/picasso/src/TopBarItem/styles.ts
- packages/picasso/src/TopBarMenu/TopBarMenu.tsx
- packages/picasso/src/TopBarMenu/index.ts
- packages/picasso/src/TopBarMenu/styles.ts
[FX-3139]
Add `TopBarMenu` and `TopBarItem` components.
Created `black` variant for `PageTopBar` component and added `centerContent` prop for the `TopBarMenu`
- check the code
- check locally the [Variants](http://localhost:9001/?path=/story/layout-page--page#page-topbar-variants) and [CenterContent](http://localhost:9001/?path=/story/layout-page--page#page-topbar-center-content) example in storybook
> **GitHub Bot: …
> feat(TopBarMenu): add TopBarMenu and TopBarItem components

- packages/picasso/src/Page/story/index.jsx
- packages/picasso/src/PageTopBar/story/index.jsx
- packages/picasso/src/TopBarItem/story/index.jsx
- packages/picasso/src/TopBarMenu/story/Default.example.tsx
- packages/picasso/src/TopBarMenu/story/WithIcons.example.tsx
- packages/picasso/src/TopBarMenu/story/WithSidebar.example.tsx
- packages/picasso/src/TopBarMenu/story/index.jsx
[FX-3139]
Pull storybook examples from Layout/Page into Components/PageTopBar.
With creating center menu in TopBar, there are now new examples added and I decided to separate them into standalone page. 
- check local storybook [PageTopBar examples](http://localhost:9001/?path=/story/components-pagetopbar--pagetopbar)
- Ensure the changed/created components have …
> feat(PageTopBar): separate PageTopBar into storybook components

- .changeset/breezy-moose-doubt.md
Added changeset for forgotten `picasso-shared` package
- bootstrap app from alpha package. It should run without errors
> All …
> chore: add changeset for useHasMultilineCounter hook

- .github/workflows/danger.yaml
- davinci.yaml
- package.json
- yarn.lock
[FX-3285]
Update davinci to the latest version and set the danger to check to require an assignee in PR.
- assign/unassign yourself and danger check should be triggered
n/a
- [n/a] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [n/a] Ensure that deployed demo has expected results and good examples
- [n/a] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …
> chore: force assigne in dangerJs

- .github/workflows/pr.yaml
[FX-3300]
Add PR check for missing changesets
- Already tested in [this PR](https://github.com/toptal/picasso/pull/3286)
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/ …
> chore: add CI check for missing changesets

- packages/picasso/src/AvatarUpload/AvatarUpload.tsx
- packages/picasso/src/AvatarUpload/hooks/use-avatar-states/index.ts
- packages/picasso/src/AvatarUpload/hooks/use-avatar-states/test.ts
- packages/picasso/src/AvatarUpload/hooks/use-avatar-states/useAvatarStates.ts
- packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/index.ts
- packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/test.ts
- packages/picasso/src/AvatarUpload/hooks/use-avatar-upload/useAvatarUpload.ts
[FX-3071]
- This PR is about extracting stateful code and visual changes to two separate hooks to ease management of them for the future.
- I have also added some unit tests for these hooks.
- no visual changes. green CI && code review is enough
N/A
- [N/A] Annotate …
> chore: extract stateful code from AvatarUpload to hooks

- .changeset/tricky-ears-retire.md
- packages/picasso/src/TagRectangular/index.ts
- packages/picasso/src/index.ts
The title says it all. Follow up of https://toptal-core.slack.com/archives/CERF5NHT3/p1674135314902339
- CI should be green :green_circle: 
No screenshots
- [NA] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [NA] Ensure that deployed demo has expected results and good examples
- [NA] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [NA] Covered with tests
- [NA] codemod is created and showcased …
> feat: export TagRectangular VariantType on main package

- .github/workflows/davinci-integration-tests.yml
Fix small typo in integration tests workflow
no need
- codemod is created and …
> fix: workflow typo

- .changeset/silly-donkeys-lick.md
[FX-NNNN]
Added a missing changeset from https://github.com/toptal/picasso/pull/3301
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> chore: add missing changeset

- .changeset/quick-ducks-hammer.md
- packages/picasso/src/Dropdown/Dropdown.tsx
[no-jira]
This PR is about adding a comment to the Dropdown component `placement` prop to make it appear in the props table.
go to template Dropdown [page](https://picasso.toptal.net/dropdown-placement-prop/?path=/story/components-dropdown--dropdown)
- [N/A] test …
> chore(Dropdown): add comment for placement prop

- .github/workflows/danger.yaml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
[FX-3734]
We need to use an exact 16 version in GH Actions
- All tests must be green
<details>
<br />
</details>
<details>
<br />
1. There are …
> chore: [FX-3734] set up 16 node version in GH Actions

- .changeset/stupid-moose-decide.md
- packages/picasso-pictograms/CHANGELOG.md
This pull request fixes the `CHANGELOG` file for `picasso-pictograms` package.
> **GitHub …
> fix: changelog file

- package.json
- yarn.lock
[FX-3776]
Bump `json5` to use a fixed version on each major release
- https://github.com/toptal/picasso/security/dependabot/119
- https://github.com/toptal/picasso/security/dependabot/118
I had to add `json5@0.5.1` that comes with `@toptal/davinci-engine` to resolutions since it is not fixable right now. `@toptal/davinci-engine` cannot be removed as it is `peerDependency` of `@toptal/davinci-qa`
- `N/A` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `N/A` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- `N/A` Make sure that …
> chore(deps): bump json5

- .changeset/big-cows-run.md
- packages/picasso-charts/package.json
- packages/picasso-charts/src/BarChart/BarChart.tsx
- packages/picasso-charts/src/LineChart/LineChart.tsx
- packages/picasso-charts/src/types.ts
- packages/picasso-charts/src/utils/calculate-tooltip-position/calculate-tooltip-position.ts
- yarn.lock
[FX-3776]
The old version of `recharts` is coming with the old version of `d3-color` https://github.com/toptal/picasso/security/dependabot/98
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. …
> chore(deps): bump recharts

- .changeset/fifty-keys-sit.md
- cypress/component/Dropdown.spec.tsx
- packages/picasso/src/Dropdown/Dropdown.tsx
- packages/picasso/src/Dropdown/__snapshots__/test.tsx.snap
- packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap
[FX-3750](https://toptal-core.atlassian.net/browse/FX-3750)
Remove RootRef relying on the deprecated `findDOMNode`
- Visual tests should pass with no difference
| [imagine any dropdown] | [imagine any dropdown again, looks exactly the same] |
<details>
<br />
</details>
<details> …
> fix(Dropdown): remove RootRef

- .github/workflows/davinci-alpha-package.yml
[FX-3832](https://toptal-core.atlassian.net/browse/FX-3832)
Hehe
<details>
<br />
</details>
<details> …
> chore(ci): fix alpha package

- .github/workflows/danger.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
[FX-3788](https://toptal-core.atlassian.net/browse/FX-3788)
⚠️ No changeset, internal repo change.
This pull request refactors GHA code that uses deprecated methods `set-state` and `set-output` and updates GHA dependencies.
- All checks should not emit any deprecation warning for `set-state` or `set-output`
- [N/A] Ensure that deployed demo has expected results and good …
> fix: remove deprecated methods and update dependencies

- .github/workflows/davinci-alpha-package.yml
This pull request updates the version of one of the reused GHAs (https://github.com/xt0rted/pull-request-comment-branch/blob/main/CHANGELOG.md#200---2023-03-29) and fixes the error with alpha releases.
- version bump
- [N/A] Ensure the changed/created components have not caused …
> fix: use proper version of reused GHA

- .changeset/bright-kids-cheat.md
- packages/picasso/src/Notification/Notification.tsx
[FX-2779](https://toptal-core.atlassian.net/browse/FX-2779)
Update prop description and test new changeset formatting
<details>
<br />
</details>
<details>
<br /> …
> fix(Notification): update prop description

- .changeset/silent-lamps-arrive.md
- packages/picasso-pictograms/package.json
[FX-NNNN]
- Tree-shaking should work when importing pictograms from the package root
<details>
<br />
</details>
<details>
<br /> …
> fix(Pictograms): enable side-effects: false

- .changeset/warm-rivers-beg.md
- cypress/component/BarChart.spec.tsx
- packages/picasso-charts/src/BarChart/BarChart.tsx
- packages/picasso-charts/src/BarChart/story/VerticalBar.example.tsx
- packages/picasso-charts/src/BarChart/story/index.jsx
- packages/picasso-charts/src/types.ts
[TI-1191](https://toptal-core.atlassian.net/browse/TI-1191)
[FX-3845](https://toptal-core.atlassian.net/browse/FX-3845)
add vertical layout to the `barChart` component 
- navigate to the `BarChart` component try and edit the code and add the prop `layout='vertical'` 
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. …
> feat(BarChart): add vertical layout

- .changeset/metal-lies-deny.md
- packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx
- yarn.lock
[FX-3873]
Some time ago we added a guard to Picasso root so it only render children after the root itself is mounted on the DOM, this is because when loading a page for the first time on a modal/popup, it was attached to the body of the page instead of the proper location of Picasso root. This guard doesn't make sense on SSR, where no component is truly "mounted"
- On a project with SSR enabled the first render should respond with a proper static HTML ready for hydratation
No screenshots
<details>
<br />
List of …
> fix: add check for SSR on Picasso root guard

- .changeset/five-meals-appear.md
- packages/picasso-provider/src/Picasso/PicassoLight/PicassoLight.tsx
As a follow up action of https://github.com/toptal/picasso/pull/3445/files, we also have to fix an issue in `PicassoLight`
- Use https://github.com/toptal/next-and-picasso-isuue branch
- Add an alpha version of picasso-provider
- Repeat the pages walk
- Expected: the appearance of components still the same
<details>
<br />
</details>
<details>
<br />
**You are not OK** …
> fix: class names creator in PicassoLight

- docs/decisions/13-breakpoints.md
[FX-3859](https://toptal-core.atlassian.net/browse/FX-3859)
This pull requests adds a decision on breakpoints in Picasso and their compatibility with BASE design. Please see https://github.com/toptal/picasso/blob/FX-NULL-add-breakpoints-docs/docs/decisions/13-breakpoints.md for the actual proposal.
- [N/A] Ensure that deployed demo has …
> docs: add new breakpoints and breakpoint ranges

- .changeset/fair-tables-heal.md
- packages/picasso/src/PageHead/PageHead.tsx
[CRT-5815]
This PR aims to add `className` prop to `PageHead` components. 
<details>
<br />
</details>
<details>
<br /> …
> feat: add className property to PageHead components

- docs/decisions/13-breakpoints.md
- docs/decisions/14-page-layout.md
[FX-3859](https://toptal-core.atlassian.net/browse/FX-3859)
This pull requests updates breakpoints and adds decision on layouts in Picasso and their compatibility with BASE design. Please see https://github.com/toptal/picasso/blob/FX-3859-add-grids-layout/docs/decisions/14-page-layout.md for the proposal.
- [N/A] Ensure that deployed demo …
> feat: add docs for grid and layout proposal

- docs/decisions/13-breakpoints.md
This pull request fixes minor documentation error.
- Documentation update
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md …
> fix: breakpoints docs

- .changeset/green-countries-table.md
- .changeset/red-countries-thank.md
[FX-3931]
This pull request prepares the changeset message that will summarise all the breaking changes made as part of the https://toptal-core.atlassian.net/browse/FX-3859 epic.
⚠️ Please review it as if you have no context about the breaking changes.
🐛 Failing visual tests are addressed in https://github.com/toptal/picasso/pull/3541
- Review the https://github.com/toptal/picasso/blob/FX-3931-add-breakpoints-changeset/.changeset/green-countries-table.md changeset
- [N/A] Ensure that deployed demo has expected …
> chore: add changeset

- docs/decisions/13-breakpoints.md
- packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/Radio/__snapshots__/test.tsx.snap
- packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx
- packages/picasso-provider/src/Picasso/config/theme.ts
- packages/picasso/src/Dropdown/styles.ts
- packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
- packages/picasso/src/Grid/Grid.tsx
- packages/picasso/src/Modal/Modal.tsx
- packages/picasso/src/Modal/styles.ts
- packages/picasso/src/Page/styles.ts
- packages/picasso/src/PageArticle/styles.ts
- packages/picasso/src/PageFooter/styles.ts
- packages/picasso/src/PageHamburger/styles.ts
- packages/picasso/src/PageSidebar/styles.ts
- packages/picasso/src/PageTopBar/styles.ts
- packages/picasso/src/PageTopBarMenu/styles.ts
- packages/picasso/src/Popover/styles.ts
- packages/picasso/src/Popper/styles.ts
- packages/picasso/src/Radio/__snapshots__/test.tsx.snap
- packages/picasso/src/ScrollMenu/styles.ts
- packages/picasso/src/TopBarMenu/styles.ts
- yarn.lock
[FX-3931]
This pull request fixes visual tests for the https://github.com/toptal/picasso/tree/feature/new-picasso-breakpoints branch before getting to the last step – https://github.com/toptal/picasso/pull/3549.
Please see the failing tests in https://github.com/toptal/picasso/pull/3549 pull request, particularly in the following Happo runs:
- https://happo.io/a/675/p/848/compare/2f7bccb12e790de4364f3f44f77c8ce059aa6afd/0260b9c72c8736c21f6782d953c3c1ccf1fb5336
- https://happo.io/a/675/p/1189/compare/2f7bccb12e790de4364f3f44f77c8ce059aa6afd/0260b9c72c8736c21f6782d953c3c1ccf1fb5336
- [N/A] Annotate all `props` in …
> fix: visual tests

- .changeset/light-pandas-explain.md
- packages/picasso-provider/src/Picasso/config/breakpoints.ts
- packages/picasso-provider/src/Picasso/config/test.ts
- yarn.lock
Media queries in Picasso's breakpoints mechanism do not cover the 1px gap problem. The problem is that pixel values are not integers but float under certain conditions in web browsers.
Please see the problem by checking out [this](https://codepen.io/adamraider/full/MMKdeR) code pen.
The way it is treated by Twitter Bootstrap: https://github.com/twbs/bootstrap/blob/f0be063c9792f6fd123d933335efd0d8cc7f6f1f/site/content/docs/5.3/layout/breakpoints.md?plain=1#L122
The way it is treated by Flarum: https://github.com/flarum/framework/commit/761cc06697ae2921f69d896a3d54fabc715bb136#diff-e6448a88dd71c4d2959700443b3c8c642af1a8a759efb806df1f4e1a827784b2R125 (https://github.com/flarum/framework/issues/2915)
Example of engineers frustrated with this problem: …
> fix: pixel gap problem

- .github/workflows/danger.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
[FX-4029]
We want to keep temploy deployment active for each PR and not only 1 deployment active.
The actual change is in https://github.com/toptal/davinci-github-actions/pull/179
- CI should be gren
- `n/a` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `n/a` Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- `n/a` Create `examples` for component
- `n/a` Ensure that deployed demo has expected results and good examples
- `n/a` Ensure the changed/created components have not caused accessibility issues. [How to use …
> ci: update github temploy deploy

- .github/workflows/danger.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/pr.yaml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
This pull request bumps the version of `davinci-github-actions`.
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/ …
> chore: update davinci-github-actions

- .changeset/hungry-hornets-clean.md
- .changeset/stupid-bears-turn.md
- packages/picasso/package.json
- packages/picasso/src/Calendar/Calendar.tsx
- packages/picasso/src/Calendar/__snapshots__/test.tsx.snap
- packages/picasso/src/Calendar/index.ts
- packages/picasso/src/Calendar/styles.ts
- packages/picasso/src/Calendar/test.tsx
- packages/picasso/src/Calendar/types.ts
- packages/picasso/src/CalendarContainer/CalendarContainer.tsx
- packages/picasso/src/CalendarContainer/index.ts
- packages/picasso/src/CalendarContainer/styles.ts
- packages/picasso/src/CalendarContext/CalendarContext.tsx
- packages/picasso/src/CalendarContext/index.ts
- packages/picasso/src/CalendarDay/CalendarDay.tsx
- packages/picasso/src/CalendarDay/index.ts
- packages/picasso/src/CalendarDay/styles.ts
- packages/picasso/src/CalendarIndicators/CalendarIndicators.tsx
- packages/picasso/src/CalendarMonthHeader/CalendarMonthHeader.tsx
- packages/picasso/src/CalendarMonthHeader/index.ts
- packages/picasso/src/DatePicker/DatePicker.tsx
- packages/picasso/src/DatePicker/story/WithTwoMonths.example.tsx
- packages/picasso/src/DatePicker/story/index.jsx
- packages/picasso/src/index.ts
- yarn.lock
[FX-3966]
This pull request merges the `feature/replace-calendar-library` branch into `master` and fixes a bug in https://github.com/toptal/picasso/pull/3602/commits/4c6708d9ae67bed1046dacb238fba6ae4b8c6f78 (bug was caught during Client Portal tests)
Most of the changes have been already reviewed in previous pull requests:
- https://github.com/toptal/picasso/pull/2996
- https://github.com/toptal/picasso/pull/3584
- https://github.com/toptal/picasso/pull/3579
---
Alpha packages were tested in the following apps (and migration was done along the way):
- Client Portal (https://github.com/toptal/client-portal/pull/6667) tests are ✅ 
- Staff Portal (https://github.com/toptal/staff-portal/pull/10443) tests are ✅ 
- Top Scheduler Frontend …
> feat: replace Calendar library

- .changeset/chilly-actors-thank.md
- packages/picasso/src/utils/Breakpoints/story/index.jsx
Show the `useBreakpoint` code example in storybook here - https://picasso.toptal.net/?path=/story/utils-breakpoints--breakpoints#usebreakpoint
- n/a Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
<details>
<br />
1. Add …
> fix: show useBreakpoint code example in storybook

- packages/picasso/src/LexicalEditor/LazyLexicalEditor.test.tsx
- packages/picasso/src/LexicalEditor/LexicalEditor.test.tsx
- packages/picasso/src/LexicalEditor/LexicalEditor.tsx
- packages/picasso/src/LexicalEditor/types.ts
- packages/picasso/src/LexicalTextLengthPlugin/LexicalTextLengthPlugin.tsx
- packages/picasso/src/LexicalTextLengthPlugin/index.ts
- packages/picasso/src/RichTextEditor/RichTextEditor.tsx
- packages/picasso/src/RichTextEditor/hooks/useCounter/useCounter.tsx
- packages/picasso/src/RichTextEditor/test.tsx
- packages/picasso/src/RichTextEditor/types.ts
[FX-4010]
We need to integrate `maxLength`, `maxLengthMessage`, `minLength`, `minLengthMessage` props to `RichTextEditor`
- Use [temploy](https://picasso.toptal.net/fx-4010-limits/) to check functionality
<details>
<br />
</details>
<details>
<br />
**You are not …
> chore: [FX-4010] Integrate limits to rich text editor

- .changeset/afraid-elephants-bake.md
- .changeset/famous-pears-crash.md
- .changeset/stupid-onions-peel.md
- cypress/component/Modal.spec.tsx
- cypress/component/PromptModal.spec.tsx
- cypress/component/Tooltip.spec.tsx
- packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx
- packages/picasso/src/ButtonLoader/ButtonLoader.tsx
- packages/picasso/src/HeaderLoader/HeaderLoader.tsx
- packages/picasso/src/Logo/Logo.tsx
- packages/picasso/src/Logo/styles.ts
- packages/picasso/src/MediaSkeletonLoader/MediaSkeletonLoader.tsx
- packages/picasso/src/Modal/Modal.tsx
- packages/picasso/src/PageTopBar/PageTopBar.tsx
- packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap
- packages/picasso/src/PageTopBar/styles.ts
- packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
- packages/picasso/src/TypographyLoader/TypographyLoader.tsx
[FX-4048]
1. reverting the Root component render guard to not render null on the first render in the browser
2. `SkeletonLoader` - add `uniqueKey` property to disable generating random uid
3. `Page.TopBar` - conditional rendering of components can't be done by JS to match HTML output on server and browser
to reproduce the issue in Client-Signup
1. clone the project locally `git clone https://github.com/toptal/client-signup`
2. `cd apps/admins`
3. `yarn install && yarn start:dev`
4. open `http://localhost:4201/` in the browser
5. open the console and you will see multiple errors/warnings about HTML mismatch 
---
6. kill the process
7. checkout to the testing branch `git checkout CC-868-picasso-update`
8. `yarn install && yarn start:dev`
9. open `http://localhost:4201/` in the browser
10. …
> fix: adjust for SSR

- .storybook/components/PicassoBook/components/TabsSection/TabsSection.tsx
This pull request removes two unused imports. …
> fix: remove unused imports

- packages/picasso/package.json
- packages/picasso/src/LexicalEditor/LexicalEditor.test.tsx
- packages/picasso/src/LexicalEditor/LexicalEditor.tsx
- packages/picasso/src/LexicalEditor/styles.ts
- packages/picasso/src/LexicalEditor/utils/createLexicalTheme.ts
- packages/picasso/src/LexicalEditor/utils/getLexicalNode.ts
- packages/picasso/src/LexicalEditor/utils/index.ts
- packages/picasso/src/LexicalEditor/utils/registerLexicalEvents.test.ts
- packages/picasso/src/LexicalEditor/utils/registerLexicalEvents.ts
- packages/picasso/src/LexicalEditor/utils/synchronizeToolbarState.test.ts
- packages/picasso/src/LexicalEditor/utils/synchronizeToolbarState.ts
- packages/picasso/src/LexicalEditor/utils/toolbarState.ts
- packages/picasso/src/LexicalEditorMaxIndentLevelPlugin/LexicalEditorMaxIndentLevelPlugin.ts
- packages/picasso/src/LexicalEditorMaxIndentLevelPlugin/index.ts
- packages/picasso/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
- packages/picasso/src/LexicalEditorView/index.ts
- packages/picasso/src/LexicalListPlugin/LexicalListPlugin.tsx
- packages/picasso/src/LexicalListPlugin/index.ts
- yarn.lock
[FX-4007](https://toptal-core.atlassian.net/browse/FX-4007)
Integrated ordered / unordered lists into Lexical RTE.
- Check the deployed storybook
- Check if the lists nest properly
- Check copy/paste functionality
- Check if the styles are consistent
- Ensure the changed/created components have not caused …
> feat: lists in LexicalEditor

- .changeset/long-rice-sneeze.md
- packages/picasso/src/Calendar/Calendar.tsx
- packages/picasso/src/Calendar/__snapshots__/test.tsx.snap
[FX-4102]
The legacy `calendar-month` class name needs to be added to ease the migration to the new Calendar.
- open the deployed Storybook and make sure that it is added …
> fix: add legacy classname

- docs/decisions/16-custom-label-for-overview-block.md
[SDE-1114]
It adds the RFC docs for implementing a custom label to the Overview Block component.
<details>
<br />
</details>
<details>
<br />
1. …
> docs: add RFC for custom label in overview block

- cypress/component/TypographyOverflow.spec.tsx
This pull request adds waiting until the first tooltip is gone. Related Slack thread – https://toptal-core.slack.com/archives/GG3F4AS4T/p1685387540176209
- all checks should pass …
> fix: flaky test

- Dockerfile
Fix the issue with building a storybook with RTE
- temploy must be built successfully
<details>
<br />
</details>
<details>
<br />
3. Code …
> fix: build image for rte

- cypress/component/RichTextEditor.spec.tsx
- packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.test.tsx
- packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
- packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
[FX-4123]
Integrate undo/redo functionality
- play with temploy, write some text and try to use CTRL + Z
- Ensure the …
> feat: integrate History plugin

- cypress/component/RichTextEditor.spec.tsx
- packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
[FX-4128]
This PR updates the old RTE cypress test to work after the migration. 
There are still multiple tests not working, I skipped them in this PR and I created bug tickets for each of them
- as we don't have feature branch yet, we can test cypress tests only locally  …
> test: update cypress tests

- packages/picasso-rich-text-editor/src/RichText/story/Default.example.tsx
- packages/picasso-rich-text-editor/src/RichText/story/HTML.example.tsx
- packages/picasso-rich-text-editor/src/RichText/types.ts
- packages/picasso-rich-text-editor/src/plugins/EmojiPlugin/nodes/CustomEmojiNode.tsx
- packages/picasso-rich-text-editor/src/utils/html-to-hast.ts
[FX-4113]
Improve stories for RichText to make sure that all supported features in `RichTextEditor` look well in `RichText`
- Check temploy
-Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
-Annotate all `props` in component with documentation
- Ensure the changed/created components have not caused accessibility issues. [How to use …
> chore: improve RichText stories

- .changeset/modern-brooms-sing.md
- cypress/component/BarChart.spec.tsx
- packages/picasso-charts/src/BarChart/BarChart.tsx
- packages/picasso-charts/src/BarChart/story/BarIndicator.example.tsx
- packages/picasso-charts/src/BarChart/story/index.jsx
- packages/picasso-charts/src/BarChartIndicator/BarChartIndicator.tsx
- packages/picasso-charts/src/BarChartIndicator/index.ts
- packages/picasso-charts/src/BarChartIndicators/BarChartIndicators.tsx
- packages/picasso-charts/src/BarChartIndicators/index.ts
- packages/picasso-charts/src/index.ts
- packages/picasso-charts/src/types.ts
[SDE-1141](https://toptal-core.atlassian.net/browse/SDE-1141)
This PR adds the `renderBarIndicators` option to the `BarChart` component, allowing us to customize bar indicators as needed.
- Run the storybook locally (`yarn start`)
- Navigate to the `BarChart` component ( https://picasso.toptal.net/?path=/story/picasso-charts-barchart--barchart#bar-indicator) and find the example provided
| Insert screenshots or screen recordings | ![image](https://github.com/toptal/picasso/assets/5639968/330bd4e1-c4a3-414a-af81-25bd468be921) | …
> feat(barchart): add option to customize a bar indicator

- cypress/component/RichTextEditor.spec.tsx
After discussion at Daily, there is no need in checking how toolbar resets when pressing `Delete`. …
> chore: remove test

- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/update-body.js
- .github/workflows/pr.yaml
- package.json
- yarn.lock
[FX-4126]
We need to show link to temploy
- [Temploy](https://picasso.toptal.net/FX-NULL-temploy-link)
<details>
<br />
</details>
<details>
<br />
1. …
> ci: [FX-4126] write temploy link to the PR description

- packages/picasso/src/Calendar/Calendar.tsx
- packages/picasso/src/Calendar/story/Default.example.tsx
- packages/picasso/src/Calendar/story/index.jsx
[FX-4061]
Expose Calendar component through Storybook. In this PR we expose only Default story. Extra stories are to come.
- check `https://picasso.toptal.net/fx-4061-expose-calendar-with-default-story/?path=/story/components-calendar--calendar`
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename …
> chore(calendar): expose in story book with default story

- packages/picasso/src/Calendar/story/Default.example.tsx
- packages/picasso/src/Calendar/story/Range.example.tsx
- packages/picasso/src/Calendar/story/WithCustomDayRendering.example.tsx
- packages/picasso/src/Calendar/story/WithDisabledIntervals.example.tsx
- packages/picasso/src/Calendar/story/WithIndicatedIntervals.example.tsx
- packages/picasso/src/Calendar/story/WithSelectableDaysLimit.example.tsx
- packages/picasso/src/Calendar/story/WithTwoMonths.example.tsx
- packages/picasso/src/Calendar/story/WithWeekStartsOnSunday.example.tsx
- packages/picasso/src/Calendar/story/index.jsx
[FX-4061]
In PR https://github.com/toptal/picasso/pull/3710 we exposed Calendar in Storybook. Now, let's add few stories to showcase its capabilities
Check URL: https://picasso.toptal.net/fx-4061-add-stories-to-calendar/?path=/story/components-calendar--calendar
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. …
> chore(Calendar): add stories

- packages/picasso/src/Calendar/story/WithTwoMonths.example.tsx
- packages/picasso/src/Calendar/story/WithWeekStartsOnSunday.example.tsx
This pull request sets fixed date values for Calendar stories so they do not cause diffs in visual testing (related to https://happo.io/a/675/p/1189/compare/0ecdbb4cfa3fb2129776c985c4bff3a6bce48efa/a88bad139b9361f0b7a5ba47b9b9fe4dfccff10f and https://toptal-core.slack.com/archives/GG3F4AS4T/p1689155367432289).
- All tests should pass
- [N/A] Ensure …
> fix: use fixed month for Calendar stories

- .github/workflows/ci.yaml
This pull request updates the job names based on https://toptal-core.slack.com/archives/GG3F4AS4T/p1689772912040219 discussion. …
> fix: job name

- packages/picasso-forms/src/Form/story/BackendCommunication.example.tsx
[FX-NNNN]
A Form example for backend communication did not include the appropriate example for inline errors
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-form-example)
- Check the temploy story for Picasso Forms => Backend Communication => Login with Inline Error
- When the button is pressed, inline error should appear on the "First name" field
| ![image](https://github.com/toptal/picasso/assets/18409292/aba65134-8355-4466-91fa-9489da064bc9) |![image](https://github.com/toptal/picasso/assets/18409292/fff501cf-c142-4c88-afe8-ce9cdd4b1212) |
> …
> chore: fix Form backend communication example story

- package.json
- yarn.lock
[FX-4177]
To allow to update snapshots via `yarn test:unit -u` we need to upgrade version of `davinci-qa`.
- Test locally
<details>
<br />
</details>
<details>
<br />
2. …
> chore: [FX-4177] update davinci-qa version

- .github/workflows/ci.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/release.yml
Bump davinci Jira Deployment GH Action
- wait for the CI job
<details>
<br />
</details>
<details>
<br />
**You want …
> chore: upgrade jira deployment version

- cypress/component/Dropdown.spec.tsx
- packages/picasso/src/Dropdown/styles.ts
[FX-4198]
This pull request adds visual tests for `Dropdown` component (it takes into account both width and height of the screen).
- [Temploy](https://picasso.toptal.net/fx-4198-add-all-breakpoints-as-targets-in-cypress-tests)
- All checks should pass, the images should be generated
> All **_development checks_** should be done and …
> test: add visual tests for dropdown

- .changeset/hip-poems-pay.md
- packages/picasso/src/Modal/styles.ts
[FX-4186]
* full-screen size property has to take 100% of width and height of the screen (not 100% - Nrem as it is now)
- use [temploy](https://picasso.toptal.net/fx-4186-fix-modal/?path=/story/overlays-modal--modal) to check all states in all screen sizes
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this …
> chore: [FX-4186] update Modal to align with Design

- .github/PULL_REQUEST_TEMPLATE.md
- docs/contribution/visual-testing.md
[FX-4091]
Adding documentation on how to visual test a responsive component
- [Temploy](https://picasso.toptal.net/fx-4091-update-contribution-guidelines-to-include-responsiveness-testing)
- Review the content of the docs
No screenshots
- [NA] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [NA] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …
> docs: add docs on breakpoints screenshots

- lerna.json
- nx.json
- package.json
- tsconfig.json
- yarn.lock
> fix: revert bump lerna from 6.6.2 to 7.1.4

- cypress/component/RichTextEditor/CodeBlockPlugin.spec.tsx
[FX-4184]
Cover the CodeBlockPlugin with cypress tests
-  Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- codemod is created and showcased in the …
> test: cover CodeBlockPlugin with cypress tests

- .changeset/wet-taxis-cheat.md
- packages/picasso/src/Page/styles.ts
[FX-4251]
This pull request fixes background color of `Pages` that do not have sidebar (the ones with sidebar have proper background color set automatically).
- [Temploy](https://picasso.toptal.net/fx-4251-recently-you-ve-introduced-a-new-background-color-for-the-page-component-to-align-wit)
- Please see the updated visual tests in https://happo.io/a/675/p/1189/compare/bbb61613f39160ea44da2ab3bb6703e8daa3d801/162f0aab81e757f064d4ef0e68c22a80f37358c3
> All **_development checks_** …
> fix: page background color

- docs/decisions/11-autosave.md
- docs/decisions/15-value-axis-formatter-for-barchart.md
- docs/decisions/16-custom-label-for-overview-block.md
- docs/decisions/17-bar-indicators-for-barchart.md
This pull request fixes titles for some of the RFC documents.
- check changed decisions at https://github.com/toptal/picasso/tree/FX-NULL-fix-docs/docs/decisions
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin …
> fix: rfc headers

- .github/workflows/ci.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/release.yml
[FX-NNNN]
- [Temploy](https://picasso.toptal.net/fx-upgrade-create-jira-deployment)
<details>
<br /> …
> ci: upgrade create-jira-deployment version

- .changeset/thick-dolls-heal.md
- packages/picasso-forms/package.json
- yarn.lock
This pull request reverts the accidental push in https://github.com/toptal/picasso/commit/8339dd12f6260f71a4b70411f499c6df6acc6cf6
- Revert …
> fix: revert accidental push

- yarn.lock
This pull request fixes the lockfile in `master`.
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-lockfile) …
> fix: lockfile

- docs/decisions/19-responsive-component-spacing-properties.md
[FX-4320]
This pull request extends the https://github.com/toptal/picasso/blob/master/docs/decisions/19-responsive-component-spacing-properties.md RFC to answer common questions that may rise during migration.
- [Temploy](https://picasso.toptal.net/fx-4320-add-cases-to-documentation)
- [N/A] Ensure that …
> feat: extend responsive spacing RFC

- .gitignore
- cypress.config.mjs
- jest.spec.mjs
- package.json
- yarn.lock
[FX-4210](https://toptal-core.atlassian.net/browse/FX-4210)
This PR removes existing build steps for Cypress allowing it to fully handle the transpilation. This allows to instrument code and collect Cypress + combined code coverage with Jest.
- [Temploy](https://picasso.toptal.net/fx-4210-add-code-coverage-reporting-to-picasso-cypress-tests)
- Check out the branch locally
- Run `yarn install && yarn test:coverage`
- After quite some time, both Cypress and Jest be done running and you'll have the following in your `coverage` folder:
- `coverage/cypress` for Cypress only
- `coverage/jest` having Jest coverage report
- and `coverage/combined` that will have both combined
- Feel free to browse around (`index.html`)
- Existing tests shold not be slower on the CI
- Existing tests should all …
> chore(ci): add combined coverage for Cypress & Jest

- package.json
- yarn.lock
[FX-NNNN]
This PR resolves https://github.com/toptal/picasso/security/dependabot/126
`yaml` library is used in multiple packages that affects:
- storybook
- manually checked
- tests
- [Temploy](https://picasso.toptal.net/fix-yaml-vulnerability)
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …
> chore(deps): add yaml to resolutions to remove vulnerability

- package.json
- yarn.lock
[FX-4396]
⚠️ Based on https://github.com/toptal/picasso/pull/3915 fix
This pull request updates `react-markdown` package, so broken stories are restored
- [Temploy](https://picasso.toptal.net/fx-4396-broken-stories-on-picasso-storybook)
- Compare (`staging` and `temploy`)
- https://picasso.toptal.net/?path=/story/layout-container--container and https://picasso.toptal.net/fx-4396-broken-stories-on-picasso-storybook/?path=/story/layout-container--container
- https://picasso.toptal.net/?path=/story/picasso-forms-form--form and https://picasso.toptal.net/fx-4396-broken-stories-on-picasso-storybook/?path=/story/picasso-forms-form--form
- https://picasso.toptal.net/?path=/story/picasso-forms-submitbutton--submitbutton and https://picasso.toptal.net/fx-4396-broken-stories-on-picasso-storybook/?pa …
> fix: update react-markdown

- .github/workflows/ci.yaml
- .github/workflows/danger.yaml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
- Dockerfile
- package.json
[FX-4402]
This pull request update `node` version to 18. The change does not affect consumers in any way.
- [Temploy](https://picasso.toptal.net/FX-4373-update-to-node-18)
- All checks should pass, the change does not affect consumers in any way (alpha package was tested in https://github.com/toptal/staff-portal/pull/11219 just in case)
- [N/A] Ensure that deployed …
> feat: update to node 18

- packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
[no-jira]
Dynamic id generation on storybook requires happo change on every PR. Collapsed the accordion which shows that id initially so it will not effect visual tests.
- [Temploy](https://picasso.toptal.net/update-query-builder-default-example)
- Confirm that dynamic generated id (visible on before screenshot) is not visible initially.
| <img width="1170" alt="Screen Shot 2023-10-24 at 16 45 02" src="https://github.com/toptal/picasso/assets/694469/faf75c00-470b-4253-90ef-b61e7b679cb9">|<img width="1175" alt="Screen Shot 2023-10-24 at 16 45 13" src="https://github.com/toptal/picasso/assets/694469/670e4320-fb91-46ae-8fda …
> chore: collapse accordion in story for visual tests

- cypress/component/QueryBuilder/Default.spec.tsx
- cypress/component/QueryBuilder/QueryBuilder.spec.tsx
- packages/picasso-query-builder/src/AddGroupButton/AddGroupButton.tsx
- packages/picasso-query-builder/src/AutoComplete/AutoComplete.tsx
- packages/picasso-query-builder/src/FieldSelector/FieldSelector.tsx
- packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
- packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
- packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
- packages/picasso-query-builder/src/RangeInput/RangeInput.tsx
- packages/picasso-query-builder/src/RunQueryButton/RunQueryButton.tsx
- packages/picasso-query-builder/src/Select/Select.tsx
- packages/picasso-query-builder/src/TextInput/TextInput.tsx
- packages/picasso-query-builder/src/ValueEditor/ValueEditor.tsx
- packages/picasso-query-builder/src/types/query-builder.ts
[CPT-1023](https://toptal-core.atlassian.net/browse/CPT-1023)
Add component tests for the query builder.
- [Temploy](https://picasso.toptal.net/add-integration-tests-query-builder)
- CI should pass.
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use …
> chore: add integration tests for query builder

- .github/CODEOWNERS
[CPT-1363](https://toptal-core.atlassian.net/browse/CPT-1363)
Update ownership of `picasso-query-builder`
- [Temploy](https://picasso.toptal.net/update-codeowners-query-builder)
- Check that CODEOWNERS file is updated and up to standards.
- [N/A] Annotate all …
> chore: update ownership of query builder

- lerna.json
- nx.json
- package.json
- tsconfig.json
- yarn.lock
[FX-4497]
To remove https://security.snyk.io/vuln/SNYK-JS-SEMVER-3247795 we have to update `lerna` to the latest version. Luckily lerna has `lerna repair` command that covers all breaking changes. In Picasso we use lerna only to build packages, so as soon the CI is green we are ready to go.
- [Temploy](https://picasso.toptal.net/fx-4497-semver)
- CI is green
- Make sure that additions and changes on the design follow [Toptal's BASE …
> chore(deps): update lerna

- .github/workflows/davinci-alpha-package.yml
[FX-NNNN]
- Merge to master
<details>
<br />
</details>
<details>
<br /> …
> ci: fix alpha packages

- .github/workflows/format-dependabot-prs.yml
This pull request provides token for the `pr-conventional-to-toptal-commits` workflow to fix the problem in https://github.com/toptal/picasso/actions/runs/6928338185/job/18843941110?pr=4000.
- Temploy
- Merge and rerun the https://github.com/toptal/picasso/actions/runs/6928338185/job/18843941110?pr=4000
- [N/A] Ensure that deployed demo has expected …
> Provide token to pr-conventional-to-toptal-commits

- .github/workflows/release.yml
Replacing external proxy with IAP
Test the workflow triggering jenkins job
<details>
<br />
</details>
<details>
<br />
1. You have no extra …
> Replace external proxy with IAP

- .github/workflows/ci.yaml
Remove HTTP_PROXY from steps that are not necessary
- [Temploy](https://picasso.toptal.net/fix/remove-http-proxy-from-build)
No screenshots
- [NA] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- [NA] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [NA] …
> Let HTTP_PROXY only on necessary locations

- .changeset/funny-snakes-pull.md
- .github/workflows/ci.yaml
- .github/workflows/release.yml
[no-jira]
The CI team is currently working on replacing the `external-proxy` with Google Identity Aware Proxy (IAP).
In this PR, we use the trigger-jenkins-job action to implement the IAP when triggering a jenkins job from a GitHub workflow.
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this …
> [CI-X] Replace external proxy with IAP

- .changeset/ninety-readers-build.md
- packages/picasso-provider/package.json
- packages/picasso/package.json
- packages/picasso/src/utils/Notifications/__snapshots__/test.tsx.snap
- packages/shared/package.json
- yarn.lock
[FX-4539]
This pull request bumps `notistack` package version. 
- [Temploy](https://picasso.toptal.net/fx-4539-reduce-number-of-npm-warnings-notistack)
- Compare https://picasso.toptal.net/fx-4539-reduce-number-of-npm-warnings-notistack/?path=/story/components-notification--notification and https://picasso.toptal.net/?path=/story/components-notification--notification
- Alpha packages was tested in https://github.com/toptal/staff-portal/pull/11819
- [N/A] Covered with tests ([visual …
> [FX-4539] Update notistack

- .github/workflows/ci.yaml
- .github/workflows/danger.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/format-dependabot-prs.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/visual-testing.yml
[FX-4757]
Format dependabot PR title github action needs to be updated to be green https://github.com/toptal/davinci-github-actions/pull/265
- [Temploy](https://picasso.toptal.net/fx-4757-update-dgha) …
> [FX-4757] Update davinci github actions

- .gitignore
This pull request adds `.nx` to Git ignore file not to show it in results of search in IDEs.
- Check out branch locally, files from `.nx` folder should not appear in search
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use …
> [FX-NULL] Add nx folder to gitignore

- README.md
[FX-4736]
This pull request add information about supported browsers to `README` file.
- Check `README` in https://github.com/toptal/picasso/tree/FX-4736-extend-readme?tab=readme-ov-file#supported-browsers
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How …
> [FX-4736] Add browsers and release policy sections to README

- .github/workflows/davinci-alpha-package.yml
[FX-NNNN]
Temporary change the root folder for publishing
- Temploy
<details>
<br />
</details>
<details>
<br />
**You are OK** …
> Adjust root folder in alpha gh action

- .github/workflows/ci.yaml
- .github/workflows/danger.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/format-dependabot-prs.yml
- .github/workflows/handle-contribution.yml
- .github/workflows/visual-testing.yml
[FX-4787](https://toptal-core.atlassian.net/browse/FX-4787)
This pull request updates `davinci-github-actions` version and enables creation of contribution Jira tickets for major update `dependabot` pull request.
- [N/A] Ensure the changed/created components have not …
> [FX-4787] Update davinci-github-actions version

- packages/picasso/README.md
[FX-4590]
Update storybook introduction story with Tailwind installation steps
- [Temploy](https://picasso.toptal.net/fx-4590-introduction)
- Check the introduction story in the temploy
- `n/a` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `n/a` Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- `n/a` Annotate all …
> [FX-4590] Update introduction with Tailwind

- .changeset/ninety-timers-wink.md
- packages/picasso-provider/src/Picasso/FontsLoader.tsx
- packages/picasso-provider/src/Picasso/config/fonts.ts
- packages/picasso-provider/src/Picasso/config/index.ts
- packages/picasso-provider/src/index.ts
[FX-4979]
We need to update `picasso-provider` to export fonts definition
- Use an alpha version in a product
- N/A Annotate all `props` in component with documentation
- N/A Create `examples` for component
- N/A Ensure that deployed demo has expected results and good examples
- N/A Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- N/A Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
List of available …
> [FX-4979] Make fonts exportable

- .storybook/styles.css
- packages/picasso/README.md
- tailwind.config.js
[FX-4989]
In the Client Portal we realized that we need to use `@tailwind base` as it is not only CSS reset as I thought before, but it also includes lot of util classnames. Luckily TailwindCSS enables us to disable CSS reset in the config
- [Temploy](https://picasso.toptal.net/fx-null-update-tailwind-setup)
- Make sure that additions and changes on the design follow [Toptal's BASE …
> [FX-4989] Update TailwindCSS setup

- .prettierignore
- nx.json
- package.json
- yarn.lock
Updating lerna to the latest version. New features and enhancements
- [Temploy](https://picasso.toptal.net/feature/update-lerna)
- [NA] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included) …
> Update lerna to 8.1.2

- .changeset/sweet-singers-knock.md
- packages/base/EmptyState/src/EmptyStatePage/EmptyStatePage.tsx
[FX-5038]
Update spacing to match BASE
- [Temploy](https://picasso.toptal.net/fx-5038-empty-state)
| ![image](https://github.com/toptal/picasso/assets/6830426/8dcbc767-0032-44a2-9cf5-25a3f7a06743) | ![image](https://github.com/toptal/picasso/assets/6830426/17192db6-c54d-4d3f-a62e-665d535b15cb) |
- Create …
> [FX-5038] Update spacing

- packages/base/Button/src/Button/Button.tsx
- packages/base/Button/src/Button/__snapshots__/test.tsx.snap
- packages/base/Button/src/Button/styles.ts
- packages/base/Button/src/ButtonAction/ButtonAction.tsx
- packages/base/Button/src/ButtonAction/styles.ts
- packages/base/Button/src/ButtonBase/ButtonBase.tsx
- packages/base/Button/src/ButtonBase/index.ts
- packages/base/Button/src/ButtonBase/styles.ts
- packages/picasso-tailwind/src/index.js
[FX-5057]
We are going to migrate ButtonAction to TailwindCSS and new MUI Base Button
- [Temploy](https://picasso.toptal.net/fx-5057-migrate-button-action)
- N/A Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- N/A Create `examples` for component
<details>
<br />
</details>
<details>
<br />
2. You …
> [FX-5057] Migrate ButtonAction to TailwindCSS

- .changeset/sixty-jars-try.md
- packages/base/Table/src/TableCell/TableCell.tsx
[FX-XXX]
Picasso TableCell must put renderable children to the `MUITableCell`
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-picasso-table-cell)
<details>
<br />
</details>
<details>
<br /> …
> [FX-XXX] Fix Picasso TableCell issue

- .changeset/sweet-experts-call.md
- packages/base/Accordion/src/AccordionCompound/index.ts
- packages/base/Alert/src/AlertCompound/index.ts
- packages/base/ApplicationUpdateNotification/src/ApplicationUpdateNotificationCompound/index.ts
- packages/base/Avatar/src/AvatarCompound/index.ts
- packages/base/Breadcrumbs/src/BreadcrumbsCompound/index.ts
- packages/base/Button/src/ButtonCompound/index.ts
- packages/base/Form/src/FormCompound/index.ts
- packages/base/Grid/src/GridCompound/index.ts
- packages/base/Helpbox/src/HelpboxCompound/index.ts
- packages/base/Menu/src/MenuCompound/index.ts
- packages/base/Modal/src/ModalCompound/index.ts
- packages/base/Note/src/NoteCompound/index.ts
- packages/base/Notification/src/NotificationCompound/index.ts
- packages/base/OverviewBlock/src/OverviewBlockCompound/index.ts
- packages/base/Page/src/PageCompound/index.ts
- packages/base/Page/src/PageTopBarCompound/index.ts
- packages/base/Radio/src/RadioCompound/index.ts
- packages/base/Step/src/StepperCompound/index.ts
- packages/base/Table/src/TableCompound/index.ts
- packages/base/Tabs/src/TabsCompound/index.ts
- packages/base/Tag/src/TagCompound/index.ts
- packages/base/Tagselector/src/TagSelectorCompound/index.ts
- packages/picasso-forms/src/FormCompound/index.ts
> Revert "[FX-5115] Update types of compound components"

- packages/base/Button/src/ButtonAction/ButtonAction.tsx
- packages/base/Button/src/ButtonCircular/ButtonCircular.tsx
- packages/base/Button/src/ButtonCircular/styles.ts
- packages/picasso-tailwind/src/index.js
- yarn.lock
[FX-5059]
We need to migrate Button.Circle to TailwindCSS
- [Temploy](https://picasso.toptal.net/fx-5059-migrate-circular-button)
- N/A Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: …
> [FX-5059] Migrate circular button

- cypress/component/Typography.spec.tsx
[FX-NNNN]
- [Temploy](https://picasso.toptal.net/fx-5124-create-a-visual-tests-covering-all-typography-cases-in-cypress)
<details>
<br />
- `@toptal-anvil ping …
> [FX-5124] Add full visual tests for Typography

- .changeset/lovely-singers-visit.md
- packages/base/Page/package.json
- [Temploy](https://picasso.toptal.net/fix/react-dom-peer-deps)
No screenshots
<details>
<br />
</details>
<details>
<br /> …
> Move react-dom from dep to peerDep on picasso-page

- .changeset/clever-icons-report.md
- packages/base/Button/package.json
- packages/base/Button/src/Button/Button.tsx
- packages/base/Button/tsconfig.json
- yarn.lock
[FX-XXX]
There is a broken appearance when Button is used with "as=Link" prop. Because incorrect ordering of "style" tags between Button and MUI-Typography. MUI-Typography is used by MUI-Link, which is used by Picasso Link.
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-style-ordering)
<details>
<br />
</details>
<details>
<br /> …
> [FX-XXX] Fix incorrect style ordering

- nx.json
- packages/picasso-provider/package.json
- yarn.lock
Sometimes, changing a package didn't trigger the rebuild of other packages that depended on the changed package. The reason is that I thought that declaring `^build:package` on `dependsOn` would automatically mark the task output as an input for the current task, which, after a few experiments, is not really what NX is doing.
I now explicitly set the dependencies source code as an input for each `build:package`, making any changes trigger all affected packages, correctly.
- Remove all the local NX cache:
```bash
rm -rf .nx
```` 
- Run `build:package`:
```bash
yarn build:package
```
- Make a change to a package that is a dependency of another. Let's say `OutlinedInput` for example: 
```bash
echo 'console.log()' >> packages/base/OutlinedInput/src/OutlinedInput/OutlinedInput.tsx
```
- Run …
> Correctly define dependency sources for build:package

- bin/generate-responsive-icons.js
- packages/base/Icons/src/Icon/_generatorTemplate.js
[FX-5226](https://toptal-core.atlassian.net/browse/FX-5226)
Fixes the icon generation post-migration to split packages
- Temploy
- Add 16 and 24 svg icon variants to the `packages/base/Icons/src/Icon/svg` and run `yarn generate:icons`
- You should see all the required variants (including responsive) to be generated and available in Storybook
<details>
<br />
</details>
<details>
<br />
2. You …
> [FX-5226] Update generator templates for new icon paths

- .changeset/kind-camels-type.md
- packages/base/Paper/package.json
- packages/base/Paper/src/Paper/Paper.tsx
[FX-5186]
Use `twMerge` in Paper instead of `classnames`.
- [Temploy](https://picasso.toptal.net/fx-5186-use-twmerge-in-paper)
<details>
<br />
</details>
<details>
<br />
**You are not …
> [FX-5186] Use twMerge in Paper

- packages/base/Checkbox/tsconfig.json
- packages/base/Form/tsconfig.json
- packages/base/Radio/tsconfig.json
This pull request updates references for last merged changes to `master`. Some commits of https://github.com/toptal/picasso/pull/4276 were pushed with `--no-verify`, so the `yarn refresh:tsconfig-references` was not run. Now it runs on release in `master` and breaks the pipeline.
- Temploy
- …
> [FX-NULL] Refresh git references

- .changeset/shaggy-moons-matter.md
- packages/base/Paper/src/Paper/Paper.tsx
Minor refactoring to get away from unmanageable comments with Tailwind class names.
- [Temploy](https://picasso.toptal.net/FX-NULL-add-shadows-in-mapping)
- Minor refactoring, visual tests should pass
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contributi …
> [FX-NULL] Refactor shadows mapping

- .changeset/nine-foxes-sip.md
- .changeset/sour-chairs-heal.md
- packages/base/Button/package.json
- packages/base/Helpbox/package.json
- packages/base/Modal/package.json
- packages/base/Page/package.json
- packages/base/Pagination/package.json
- packages/base/PasswordInput/package.json
- packages/picasso-rich-text-editor/package.json
- packages/picasso/package.json
- packages/picasso/tsconfig.json
[FX-NNNN]
As decided in https://toptal-core.atlassian.net/wiki/spaces/FE/pages/3835068492/PI-3379+Decision+Log, we need to use open range for component packages
- [Temploy](https://picasso.toptal.net/fx-null-fix-peer) …
> Fix peer dependencies

- .changeset/healthy-snakes-compete.md
- packages/base/Checkbox/package.json
- packages/base/Collapse/package.json
- packages/base/Fade/package.json
- packages/base/Form/package.json
- packages/base/Grid/package.json
- packages/base/Radio/package.json
[FX-NNNN]
Update rest of the packages with peer dependency on `@toptal/picasso-tailwind` to follow our guideline.
- [Temploy](https://picasso.toptal.net/fx-null-fix-peer-2)
- Ensure the changed/created components have not caused accessibility issues. [How to use …
> Update peer dependencies

- packages/base/Table/package.json
- packages/base/Table/tsconfig.json
[FX-NNNN]
This PR updates the dependencies for the `Table` component to accommodate the Tailwind migration.
- [Temploy](https://picasso.toptal.net/fx-null-fix-table-dependencies)
- ~Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)~
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API …
> [FX-NULL] Update dependencies for Table

- .changeset/rude-bees-pump.md
- packages/base/Badge/package.json
- packages/base/Badge/src/Badge/Badge.tsx
- packages/base/Badge/src/Badge/__snapshots__/test.tsx.snap
- packages/base/Badge/src/Badge/styles.ts
- packages/base/Badge/tsconfig.json
[FX-4608]
Migrate Badge to TailwindCSS.
- [Temploy](https://picasso.toptal.net/fx-4608-migrate-badge)
<details>
<br />
</details>
<details>
<br /> …
> [FX-4608] Migrate Badge to TailwindCSS

- .changeset/little-bobcats-draw.md
- packages/base/Select/src/index.ts
- packages/picasso/src/index.ts
[TOP-4660]
- [Temploy](https://picasso.toptal.net/TOP-4660-update-exports)
- CI is green
<details>
<br />
</details>
<details>
<br />
1. …
> [TOP-4660] Update exports

- packages/base/TreeView/src/StaticTreeView/story/index.jsx
[FX-5215]
Skipping visual tests for `StaticTreeView` that are flaky since forever
- [Temploy](https://picasso.toptal.net/fx-5215-fix-flaky-happo-test-for-statictreeview)
- Happo should point out a missing screenshot
- [NA ] Create `examples` for component
- [NA] codemod is created and showcased in the changeset …
> [FX-5215] Skip visual tests for flaky StaticTreeView

- .changeset/blue-mails-tan.md
- packages/base/Page/src/PageHead/PageHead.tsx
- packages/base/Page/src/PageHead/story/WithEnabledMinHeight.example.tsx
- packages/base/Page/src/PageHead/story/index.jsx
- packages/base/Page/src/PageHead/styles.ts
[CRT-7570]
This PR aims to improve `PageHeadMain` component to allow using `minHeight`.
- [Temploy](https://picasso.toptal.net/CRT-7570-improve-page-head-main)
- review Happo screenshots
- n/a test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details>
<br />
1. Add …
> [CRT-7570] Improve `PageHeadMain` to allow using `minHeight`

- packages/picasso/README.md
There's a missing comma in one of the codesnippets in the README.md
N/A
- [-] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [-] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [-] Annotate all `props` in component with documentation
- [-] Create `examples` for component
- [-] Ensure that deployed demo has expected results and good examples
- [-] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [-] Covered with …
> Fix typo in README.md

- package.json
- yarn.lock
[FX-4698]
Fixes https://github.com/toptal/picasso/security/dependabot/159
<details>
<br />
</details>
<details>
<br />
1. There are leftovers like …
> [FX-4698] Fix braces vulnerability

- yarn.lock
[FX-5698]
Fixes https://github.com/toptal/picasso/security/dependabot/155
<details>
<br />
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an opinionated comment regarding the code that requires a discussion.
3. You have questions.
1. An owner of a comment is the only one who can resolve it.
2. An owner …
> [FX-5698] Fix tar vulnerability

- package.json
- yarn.lock
[FX-5708]
This pull request aliases `ip` package usages with `@toptal/davinci-ip` package.
- [Temploy](https://picasso.toptal.net/fx-5708-fix-vulnerability-for-ip-dependency)
- Check out the branch, run `yarn start` locally
- [N/A] Ensure the changed/created components have not caused …
> [FX-5708] Replace ip with @toptal/davinci-ip

- .changeset/thirty-spoons-brake.md
- packages/base/Checkbox/src/Checkbox/__snapshots__/test.tsx.snap
- packages/base/Form/src/FieldsLayout/FieldsLayoutContext.tsx
- packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
- packages/base/Form/src/FormLabel/FormLabel.tsx
- packages/base/Form/src/FormLabel/__snapshots__/test.tsx.snap
- packages/base/Form/src/FormLabel/styles.ts
- packages/base/Radio/src/Radio/__snapshots__/test.tsx.snap
- packages/base/Switch/src/Switch/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/FieldLabel/__snapshots__/test.tsx.snap
- packages/picasso-forms/src/Radio/__snapshots__/test.tsx.snap
[FX-5532]
- [Temploy](https://picasso.toptal.net/fx-5532-formlabel)
- ~Ensure that deployed demo has expected results and good examples~
- ~Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)~
- ~test alpha package of Picasso in StaffPortal~
> All …
> [FX-5532] Migrate FormLabel to TailwindCSS

- Dockerfile
This pull request fixes the Storybook deployment, as it breaks with the following error in https://jenkins-deployment.toptal.net/job/picasso-docs/1507/console
```
11:15:23  info => Manager built (53 s)
11:17:29  ERR! => Failed to build the preview
11:17:29  ERR! Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
11:17:29  ERR! Error: Cannot find module '@toptal/base-tailwind'
11:17:29  ERR! Require stack:
11:17:29  ERR! - /app/tailwind.config.js
11:17:29  ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1140:15)
11:17:29  ERR!     at Function.resolve (node:internal/modules/helpers:188:19)
11:17:29  ERR!     at _resolve (/app/node_modules/jiti/dist/jiti.js:1:251148)
11:17:29  ERR!     at jiti (/app/node_modules/jiti/dist/jiti.js:1:253746)
11:17:29 …
```
> [FX-NULL] Fix storybook build

- .changeset/slow-gifts-hang.md
- packages/base/Tabs/package.json
- packages/base/Tabs/src/Tabs/Tabs.tsx
- packages/base/Tabs/src/Tabs/test.tsx
[FX-NNNN]
- [Temploy](https://picasso.toptal.net/fx-null-fix-tabs-types)
<details>
<br />
</details>
<details> …
> Fix types for mui@4 tabs

- .changeset/twelve-fans-invent.md
- packages/base/Quote/package.json
- packages/base/Quote/src/Quote/__snapshots__/test.tsx.snap
- packages/base/Quote/src/QuoteMark/QuoteMark.tsx
- packages/base/Quote/src/QuoteMark/styles.ts
- packages/base/Quote/tsconfig.json
[FX-5655]
This PR removes material-ui styles and replace them with Tailwind CSS classes.
- [Temploy](https://picasso.toptal.net/fx-5655-migrate-quote)
<details>
<br />
</details>
<details>
<br />
**You are …
> [FX-5655] Migrate Quote to TailwindCSS

- .changeset/twelve-stingrays-nail.md
- cypress/component/QueryBuilder/QueryBuilder.spec.tsx
- packages/picasso-query-builder/src/CloneRuleButton/CloneRuleButton.tsx
- packages/picasso-query-builder/src/RemoveRuleButton/RemoveRuleButton.tsx
- packages/picasso-query-builder/src/types/query-builder.ts
[CPT-1075]
- This PR adds cypress tests for QueryBuilder removing and cloning rules.
- It adds test ids for clone and remove buttons.
- Tests should be running
None
<details>
<br />
</details>
<details>
<br />
1. …
> [CPT-1075] Add tests to remove and clone query builder rules

- .github/workflows/security-secrets-scan.yaml
[FX-NNNN]
Based on https://toptal-core.slack.com/archives/C2W28V7L7/p1721830635687409
- [Temploy](https://picasso.toptal.net/fx-null-use-secret-action)
<details>
<br />
</details> …
> Add security scan

- .changeset/lovely-zebras-destroy.md
- .changeset/tall-mirrors-brake.md
- packages/base/AccountSelect/src/AccountSelect/__snapshots__/test.tsx.snap
- packages/base/Avatar/src/Avatar/AvatarWrapper/AvatarWrapper.tsx
- packages/base/Avatar/src/Avatar/IconAvatar/IconAvatar.tsx
- packages/base/Avatar/src/Avatar/ImageAvatar/ImageAvatar.tsx
- packages/base/Avatar/src/Avatar/TextAvatar/TextAvatar.tsx
- packages/base/Avatar/src/Avatar/index.ts
- packages/base/Avatar/src/Avatar/story/LongName.example.tsx
- packages/base/Avatar/src/Avatar/story/Sizes.example.tsx
- packages/base/Avatar/src/Avatar/story/ToptalLogo.example.tsx
- packages/base/Avatar/src/Avatar/story/Variants.example.tsx
- packages/base/Avatar/src/AvatarCompound/index.ts
- packages/base/Page/src/PageTopBarMenu/__snapshots__/test.tsx.snap
- packages/base/UserBadge/src/UserBadge/__snapshots__/test.tsx.snap
- packages/base/UserBadge/src/UserBadge/story/WithIcon.example.tsx
- packages/base/UserBadge/src/UserBadge/story/index.jsx
[FX-5854]
Export `Avatar.Wrapper` to support custom icons
- [Temploy](https://picasso.toptal.net/fx-5854-user-badge-with-icon)
- Check [the new story](https://picasso.toptal.net/fx-5854-user-badge-with-icon/?path=/story/components-userbadge--userbadge#with-icon)
- Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- codemod is created and showcased in the …
> [FX-5854] Export `Avatar.Wrapper` to support custom icons

- .changeset/blue-timers-share.md
- packages/base/Backdrop/package.json
- packages/base/Badge/package.json
- packages/base/Button/package.json
- packages/base/Drawer/package.json
- packages/base/Dropdown/package.json
- packages/base/Menu/package.json
- packages/base/Modal/package.json
- packages/base/OutlinedInput/package.json
- packages/base/Slider/package.json
- packages/base/Switch/package.json
- yarn.lock
[TI-2847]
Update mui/base lib to fix the issue with the textarea resize in `@toptal/picasso-outlined-input`. The rest of the packages are updated for consistency.  
- [Temploy](https://picasso.toptal.net/ti-2847): Go to Multiline expand and resize | Textarea
Before:
https://github.com/user-attachments/assets/7791af72-fe9c-4e6f-b0cb-42081374d768
After:
https://github.com/user-attachments/assets/66083503-7be7-45d2-9a46-ada3225b88b0
- [-] Annotate all `props` in component with documentation
- [-] Create `examples` for component
- [-] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- [-] codemod is created and showcased in the changeset
- [-] test alpha package of Picasso in StaffPortal
> All …
> [TI-2847] Update mui/base lib

- yarn.lock
[FX-6025]
- [Temploy](https://picasso.toptal.net/fx-6025-path-to-regexp-vulnerability-fix)
- ~Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)~
- ~Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)~
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~ …
> [FX-6025] Fix path-to-regexp vulnerability

- .github/workflows/automerge-release.yaml
Fixes error for auto-release script.
- Will test after merge to master …
> [MP-NULL] Fix auto release script

- .github/workflows/ci.yaml
- .github/workflows/danger.yaml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/visual-testing.yml
To fix the issue with integration tests:
we need to upgrade davinci yarn-install GHA
<details>
<br />
</details>
<details>
<br /> …
> [BILL-💵] Update yarn-install GHA to latest

- packages/base/Section/src/Section/story/Controlled.example.tsx
Updates Section example to address [this](https://github.com/toptal/picasso/pull/4678#discussion_r1968048816) comment.
- [Temploy](https://picasso.toptal.net/MP-NULL-change-story-jey82)
https://github.com/user-attachments/assets/b275802f-cced-4821-816a-c796dc060baf
- [N/A] …
> [MP-NULL] Update Section example

- .github/workflows/ci.yaml
- .github/workflows/davinci-alpha-package.yml
- .github/workflows/release.yml
Quick fix for CI workflow to unblock 
- [Temploy](https://picasso.toptal.net/ff-quick-fix-ci)
<details>
<br />
</details>
<details>
<br …
> [FF] Quick fix for CI workflow

- .changeset/nasty-bats-clean.md
- packages/base/Page/src/SidebarItem/__snapshots__/test.tsx.snap
- packages/base/Page/src/SidebarItemContent/SidebarItemContent.tsx
- packages/base/Page/src/SidebarItemContent/styles.ts
[FF-3]
Migration from JSS to TW to remove dependency on MUI v4
- [Temploy](https://picasso.toptal.net/FF-3-SidebarItemContent-JSS-TW)
<details>
<br />
</details>
<details> …
> [FF-3] Migrate SidebarItemContent from JSS to TW

- .changeset/clean-teachers-look.md
- packages/base/Page/src/SidebarMenu/SidebarMenu.tsx
[FF-5] 
Migrate cx to tailwind-merge in SidebarMenu
- No visual changes should occur
No visual changes 
<details>
<br />
</details>
<details>
<br />
2. Acceptance …
> [FF-5] Migrate cx to tailwind-merge in SidebarMenu

- .github/workflows/ci.yaml
This PR updates build-push-image to v17.1.0
> Upgrade build-push-image to v17.1.0

- .changeset/old-candles-sort.md
- .github/workflows/ci.yaml
- .github/workflows/danger.yaml
- .github/workflows/davinci-integration-tests.yml
- .github/workflows/release.yml
- .github/workflows/visual-testing.yml
- packages/picasso-forms/src/index.ts
[BILL-6036]
Expose FieldLabel to build form components.
UPDATED: We must fix the Node version to 20.18, as tests do not run in 20.19 due to conflicts between Jest config files and ESM modules. A new error started to appear on the Node 20.19
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable …
> [BILL-6036] Expose FieldLabel to build form components

- .github/workflows/ci.yaml
[FX-NNNN]
- [Temploy](https://picasso.toptal.net/FF-update-workflow-toptal-actions)
<details>
<br />
</details> …
> [FF-] Update to latest toptal/actions

- .github/workflows/release.yml
Upgrade build-image GHA action, as it seems it doesn't have access to push image now.
N/A
<details>
<br />
</details>
<details>
<br /> …
> Upgrade build-image GHA action

- .github/workflows/release.yml
Upgrade trigger jenkins action
<details>
<br />
</details>
<details>
<br />
1. There are leftovers like unnecessary logs, comments, etc.
2. You have an …
> Upgrade trigger jenkins action

- .github/workflows/release.yml
Fix trigger jenkins gha private repo hack
<details>
<br />
</details>
<details>
<br />
1. There are leftovers like unnecessary logs, comments, etc.
2. You …
> Fix trigger jenkins gha private repo hack

- .changeset/kind-bats-warn.md
- packages/base/Modal/package.json
- packages/base/Modal/src/Modal/Modal.tsx
- packages/base/Modal/src/ModalActions/ModalActions.tsx
- packages/base/Modal/src/ModalContent/ModalContent.tsx
- packages/base/Modal/src/ModalPaper/ModalPaper.tsx
- packages/base/Modal/src/ModalTitle/ModalTitle.tsx
- packages/base/Modal/tsconfig.json
[TAPS-X]
- Green CI
- n/a Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- n/a Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- n/a test alpha package of Picasso in StaffPortal
<details>
<br />
- …
> [TAPS-X] Allow overriding of classNames in Modal components

- .eslintrc.js
Add a rule to prohibit imports from main Picasso
CI checks passed
<details>
<br />
</details>
<details>
<br />
1. There are leftovers like unnecessary …
> Add a rule to prohibit imports from the main Picasso

- .changeset/spicy-worms-carry.md
- packages/base/Table/src/TableSectionHead/TableSectionHead.tsx
- packages/base/Table/src/TableSectionHead/__snapshots__/test.tsx.snap
- packages/base/Table/src/TableSectionHead/test.tsx
[HG-1413]
Make TableSectionHead apply incoming className prop
- [Temploy](https://picasso.toptal.net/HG-1413-add-className-to-TableSectionHead)
- [n/a] Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)
- [n/a] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [n/a] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- [n/a] codemod is created and showcased in …
> [HG-1413] Make TableSectionHead apply incoming className prop

- .github/workflows/ci.yaml
- .github/workflows/release.yml
[BILL-6530]
<details>
<br />
</details>
<details>
<br />
**You want …
> [BILL-6530] Pass happo secrets to integration tests

- .github/actions/cleanup-preview/action.yml
- .github/actions/deploy-to-gh-pages/action.yml
- .github/actions/prepare-deployment/action.yml
- .github/actions/setup-gh-pages/action.yml
- .github/workflows/ci.yaml
- .github/workflows/cleanup-previews.yml
- .github/workflows/release.yml
[FF-50]
- [Temploy](https://picasso.toptal.net/PF-deploy-picasso-docs-with-actions)
<details>
<br />
</details> …
> [FF-50] Deploy Picasso docs with actions

- .github/workflows/publish.yml
[FF-49]
Provides proper token to publish workflow (same token source as in https://github.com/toptal/picasso/pull/4816)
- [N/A] Ensure the changed/created components have not caused accessibility …
> [FF-49] Provide proper token

- .github/workflows/publish.yml
[FF-49]
Fixes workflow permissions. …
> [FF-49] Fix workflow permission

- .github/workflows/publish.yml
[FF-49]
Fixes permissions for publishing, publish workflow needs to created pull requests in some cases.
- …
> [FF-49] Fix permissions for publishing

- .changeset/crazy-towns-greet.md
- packages/base/Icons/src/Icon/story/index.jsx
Somehow publishing fails as NPM insists that `@toptal/picasso-icons@1.13.1` already exists  (https://github.com/toptal/picasso/actions/runs/18160087060/job/51691554889#step:3:1887).
Will be tested after merge …
> [NEWOFF-NULL] Trigger icons release
