toptal/picasso

ci/jobs/build-image/Jenkinsfile

From last 20 builds, 4 failed because of timeout errors (and only 12 were actually built without using a prepared docker image), let's try to increase the timeout and see how will it change statistics of failures
<details>
<br />
- `@toptal-bot run deploy:documentation` - Deploy …

chore: increase build-image timeout

---

Dockerfile
bin/release

No ticket
Both release and alpha release commands need `.npmrc` in the Dockerfile. 
`release` created it by it's own
`alpha` relied on one from Dockerfile
Let's make it consistent so both release and alpha release will rely on file presence based Dockerfile without additional manipulations
<details>
<br />
- `@toptal-bot run visual` - …

chore: make alpha and main releases more consistent

---

packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/__snapshots__/test.tsx.snap
packages/picasso-lab/src/Section/test.tsx

[FX-1849]
If `Section` does not receive any of the following: `title`, `subtitle`, `actions`, it'll render an empty header div. This PR fixes it.
<details>
<br />
- `@toptal-bot run package:alpha-release` - Release alpha …

feat(Section): prevent rendering empty header

---

packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/Modal/__snapshots__/test.tsx.snap
packages/picasso/src/Modal/test.tsx

[FX-NNNN]
https://github.com/toptal/platform/pull/47429 would benefit from having a readable locator to close modal windows.
~~Ensure there is `data-testid="close-modal"` on the button to close modal in https://picasso.toptal.net/add-testid-for-close-modal/?path=/story/overlays-modal--modal.~~
Add test IDs to modal in Storybook:
```diff
diff --git a/packages/picasso/src/Modal/story/Default.example.tsx b/packages/picasso/src/Modal/story/Default.example.tsx
index c62a5cdb..56eca8ec 100644
--- a/packages/picasso/src/Modal/story/Default.example.tsx
+++ b/packages/picasso/src/Modal/story/Default.example.tsx
@@ -14,6 +14,10 @@ const STATES = [
}
]
+const testIds = {
+  closeButton: 'close-modal'
+}
+
const ModalDialog = ({
open,
onClose
@@ -25,7 +29,7 @@ const ModalDialog = ({
const [date, …
```

chore: add data-testid for button to close modal

---

packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
packages/picasso/src/NonNativeSelectOptions/__snapshots__/test.tsx.snap
packages/picasso/src/NonNativeSelectOptions/test.tsx
packages/picasso/src/Select/story/Grouped.example.tsx

Fix indexing for grouped options that caused jumping while scrolling options.
<details>
<summary>Old behaviour</summary>
</details>
- Open `Grouped options` example in storybook
- Open the non-native select and check that scroll works and you can pick any option.
<details>
<br />
</details>
[TEA-2562]: https://toptal-core.atlassian.net/browse/TEA-2562

fix(select): [TEA-2562] Fix indexing for grouped options

---

packages/picasso/src/Dropdown/Dropdown.tsx

[FX-1890]
- `yarn test`
<details>
<br />
</details>
[FX-1890]: https://toptal-core.atlassian.net/browse/FX-1890

fix(dropdown): render popper only when opened

---

.github/CODEOWNERS
.github/workflows/request-review-on-pr.yml

This is to have FX team members automatically assigned to the tickets.
`@toptal/fx-codeowners` reduced to non FX engineers
FX team as an owner of this repo has now the following seting of assignment:
I expect all this setting to request whole `FX & Codeowners` + 2 random reviewers from FX.
<details>
<br />
</details>

chore: restructure code owners

---

packages/picasso-lab/src/ListItem/ListItem.tsx

When we render a Typography element inside <List.Item> it leads
to two nested `<p>` and React displays a warning:
`Warning: validateDOMnesting(...): <p> cannot appear as a descendant of <p>`
Treat List.Item as a block element with `<div>` tag so it's easier to
use Typography inside of it.
- See List component still working
<details>
<br />
</details>

fix(list): render ListItem as div to avoid nested paragraph warning

---

packages/picasso/src/NonNativeSelect/test.tsx
packages/picasso/src/Select/hooks/use-select-props/use-blur-handler/index.ts
packages/picasso/src/Select/hooks/use-select-props/use-blur-handler/test.ts
packages/picasso/src/Select/hooks/use-select-props/use-blur-handler/use-blur-handler.ts
packages/picasso/src/Select/hooks/use-select-props/use-click-handler/test.ts
packages/picasso/src/Select/hooks/use-select-props/use-click-handler/use-click-handler.ts
packages/picasso/src/Select/hooks/use-select-props/use-select-blur-handler/index.ts
packages/picasso/src/Select/hooks/use-select-props/use-select-props.ts
packages/picasso/src/SelectCaret/styles.ts

[FX-965](https://toptal-core.atlassian.net/browse/FX-965)
Fixed the bug when you click on open Select and it doesn't close.
1. Go to `Select` chapter.
2. Click on select in the default example.
3. Click on select again.
4. Be sure that the menu is closed.
1. Go to `Select` chapter.
2. Click on select in the multiple example.
3. Choose an option.
4. Click on select again.
5. Be sure that the menu is closed.
<details>
<br />
- …

fix(Select): close menu on second click

---

packages/picasso/src/utils/Utils/story/Browser.example.tsx
packages/picasso/src/utils/Utils/story/Colors.example.tsx
packages/picasso/src/utils/Utils/story/Generic.example.tsx
packages/picasso/src/utils/Utils/story/React.example.tsx
packages/picasso/src/utils/Utils/story/Strings.example.tsx
packages/picasso/src/utils/Utils/story/index.jsx

[FX-1906](https://toptal-core.atlassian.net/browse/FX-1906)
Add a section for Color utils.
<details>
<br />
</details>

chore: add color utils docs section

---

cypress/component/Tooltip.spec.tsx
cypress/support/index.js
cypress/tsconfig.json
package.json
packages/picasso/src/Tooltip/Tooltip.tsx
yarn.lock

[SPT-1531](https://toptal-core.atlassian.net/browse/SPT-1531)
To prevent reappearing tooltip while moving mouse pointer within boundaries of triggered button, `onMouseLeave` has to be added.
There is no way to have "real hover" with cypress, please see cypress [docs](https://docs.cypress.io/api/commands/hover#See-also).
- Tooltip -> Trigger section -> "hover" version
- Click on button to hide tooltip
- Try to move mouse over the button
- Tooltip shouldn't reapper again
| <img src="https://user-images.githubusercontent.com/4816942/117996278-36abca00-b36c-11eb-8a66-d4ee278b6cc6.gif" width="600" /> | <img …

fix: reappearing tooltip after moving mouse within boundaries of triggered button

---

packages/picasso/src/Modal/styles.ts

[FX-1833]
When the modal is top-aligned it is wider than the window on small screens. Also, the max height of the modal is set to 2rem vertical margin instead of 1rem margin that should be on small screens.
- Go to  the ["Max Height" section](https://picasso.toptal.net/fx-1833-fix-top-aligned-modal/?path=/story/overlays-modal--modal#max-height) of the Modals page
- Edit the code as follows:
```diff
- 14    <Modal onClose={onClose} open={open}>
+ 14    <Modal align='top' onClose={onClose} open={open}>
```
- Change emulated screen size to small mobile
- Click the "Open" button in the "Max Height" section. The modal should fit the screen with 1rem margins.
- Click the "Open Top Aligned Modal" button at the bottom of the Modals page. The modal should fit the screen with 1rem margins.
| …

fix(Modal): fix width and height of top aligned modal on small screens

---

packages/picasso-lab/package.json
packages/picasso/package.json
packages/picasso/src/Alert/story/index.jsx
packages/picasso/src/Badge/story/index.jsx
packages/picasso/src/Breadcrumbs/story/index.jsx
packages/picasso/src/List/story/index.jsx
packages/picasso/src/OverlayBadge/story/index.jsx
packages/picasso/src/PageHead/story/index.jsx
packages/picasso/src/ProgressBar/story/index.jsx
packages/picasso/src/Quote/story/index.jsx
packages/picasso/src/Rating/story/index.jsx
packages/picasso/src/SkeletonLoader/story/index.jsx
packages/picasso/src/Switch/story/index.jsx
packages/picasso/src/TimePicker/story/index.jsx
packages/picasso/src/TreeView/TreeViewContainer.tsx
packages/picasso/src/TreeView/story/index.jsx
yarn.lock

Move dependencies from Picasso lab to Picasso after moving components
<details>
<br />
</details>

fix: move dependencies to picasso from lab

---

packages/picasso-forms/src/index.ts

Re-export FormAPI and MutableState types from the final-form library.
- See the interfaces exported right from the picasso-forms
- n/a Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
<details>
<br /> …

feat(forms): export additional types from final-form

---

.github/CODEOWNERS

[CI-480](https://toptal-core.atlassian.net/browse/CI-480)
Adding CI team as code owners for all CI-related files - both Jenkins and GitHub Actions related.

chore: add ci as codeowners

---

packages/picasso-forms/src/index.ts

[BILL-X]
Add `AnyObject`, `FieldValidator`, `SubmissionErrors` export from `final-form`
<details>
<br />
</details>

feat: add `final-forms` exports

---

packages/picasso/package.json

d3-array v3 was published a few days ago and contains ES module syntax. That breaks unit tests, we
would need to be transpiled in tests. Start by pinning the version to the latest that worked in jest
environment.
I tested it with davinci
- Comment out projectTeardown so the test project is kept
- Run `yarn test` 
- See it red
- Discard any local changes
- Check out https://github.com/toptal/davinci/tree/integration-test-fix-test
- Modify test project to install `"@toptal/picasso": "9.2.1-alpha-pin-d3-array-dependency-v2.2398",`
- Run `yarn test`
- See it green
- n/a Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

fix(picasso): pin d3-array version

---

packages/picasso/src/TreeView/useNodes.ts

[SP-1467]
Tree view layout got broken some time ago. It can be reproduced in a story book example. The issue was introduced in this PR:
https://github.com/toptal/picasso/pull/1991/files#diff-bba08a19095e57ef714e10873c5ac21c44a8682a8590920d0f89fa64520a33e0R68
It wipes out the refs to DOM nodes whenever the `rootNode` reference changes. This makes coordinates broken. This PR restores the initial behavior.
- Go to TreeView storybook
- Try clicking "Reset selection" in "With selected node" example
- Tree should not get broken
**Before**
https://user-images.githubusercontent.com/763624/121415371-571d7300-c970-11eb-9788-c6a8829c7ca6.mov
**After**
https://user-images.githubusercontent.com/763624/121415517-7e744000-c970-11eb-9ec0-7427f58531ab.mov
<details>
<br /> …

fix(TreeView): fix tree view node selection

---

packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/FormConfig/test.tsx

[FX-NNNN]
There was no initial object for `errors` so `setIn` doesn't work.
- Go to Form story
- Scroll down to `Validate only on submit` example
- It should work normally
<details>
<br />
</details>

fix(picasso-forms): validation on submit

---

cypress/component/ApplicationUpdateNotification.spec.tsx
packages/picasso/package.json
packages/shared/package.json
yarn.lock

[ER-12060]
Because of this change https://github.com/iamhosseindhv/notistack/blob/066cb52f2c8cbdd57e1ba9c4f7937d0d603f5e50/src/SnackbarContainer.tsx#L25 in Notistack (which is released in `1.0.7` version) our Notifications got non-interactable (we can't click on action buttons which are on the Notification). It affected mostly `ApplicationUpdateNotificaton`.
<details>
<br />
</details>
[ER-12060]: https://toptal-core.atlassian.net/browse/ER-12060

fix(AppUpdateNotification): [ER-12060] Fix non-intractable action buttons

---

cypress/component/Tooltip.spec.tsx
packages/picasso/src/Checkbox/Checkbox.tsx
packages/picasso/src/FormControlLabel/FormControlLabel.tsx
packages/picasso/src/Radio/Radio.tsx

[FX-1874](https://toptal-core.atlassian.net/browse/FX-1874)
The tooltip for the radio and checkbox with the label was positioned incorrectly and was not visible if we hover over the label. It was always centered relatively on radio or checkbox. Now it is either in the center of the button or in the center of the button and label. 
The problems that I solved here:
1. Pass only one `ref` to the child component. In case we have `label` pass `ref` to the `label`, otherwise, pass it to the `button`(`checkbox` or `radio`)
2. Pass listeners (`onMouseLeave`, `onMouseOver`) from `Tooltip` to the `label`
3. Created two examples in `Radio` and `Checkbox` components instead of `Tooltip`, because changes were done in these components 
- Go to Radio and Checkbox story
- Scroll down to the `With …

feat(tooltip): show tooltip on both label and control

---

packages/picasso/src/TagSelector/TagSelector.tsx

To avoid TS error we need to add a definition of `popperContainer` to `TagSelector` interface
<details>
<br />
</details>

fix(TagSelector): add definition of popperContainer prop

---

cypress/component/Section.spec.tsx
packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/story/Variant.example.tsx
packages/picasso-lab/src/Section/story/index.jsx
packages/picasso-lab/src/Section/styles.ts

[FX-1985]
Add the `bordered` variant to the Section component.
Check the `bordered` variant on [Storybook](https://picasso.toptal.net/fx-1985-add-block-variant-section-component/?path=/story/picasso-lab-section--section#variant)
<details>
<br />
</details>
[FX-1985]: https://toptal-core.atlassian.net/browse/FX-1985

feat(Section): [FX-1985] Add bordered variant

---

packages/picasso-lab/src/TypographyOverflow/TypographyOverflow.tsx
packages/picasso-lab/src/TypographyOverflow/styles.ts

[SPC-1148]
TypographyOverflow is implemented in a way that it always spawns the new style tag whenever new component is rendered. E.g. on the talent list page more than 1000 style tags were spawned. It turned out those style tags were causing style recalculations and unnecessary reflows (and generally they are pretty expensive).
This was happening because we were using the dynamic styles (https://cssinjs.org/jss-plugin-rule-value-function/?v=v10.7.1). This plugin works in a way that it spawns a new stylesheet which holds all dynamic rules for any particular instance of the component. And then updates it with dynamic values when props are changing:
https://github.com/mui-org/material-ui/blob/next/packages/material-ui-styles/src/makeStyles/makeStyles.js#L107 …

fix(TypographyOverflow): improve performance

---

packages/picasso/src/OutlinedInput/OutlinedInput.tsx

We do not trigger the `onBlur` event for the whole input after clicking start or end adornments.
- set a focus on an input element
- try clicking the button adornment
expectation:
the input element must still be focused
actual:
focus is lost
before:
https://monosnap.com/file/WXK4hkoCSjl19QfjnzbyQ3hexGPcdh
after:
https://monosnap.com/file/MmWgAp5TTOerigB3Qk8w6PU2IzyYfd
<details>
<br />
</details>

fix(OutlinedInput): do not trigger onBlur event after clicking adornment

---

packages/picasso/src/Select/hooks/use-select-state/test.ts
packages/picasso/src/Select/hooks/use-select-state/use-select-state.ts

As soon as the Select `disabled` state was switched to `true`, we have to close `Popper`
it's mostly related to multiple options `Select`:
Reuse this code:
```
const [values, setValues] = useState<string[]>([])
const [disabled, setDisabledState] = useState<boolean>(false)
const handleChange = (event: React.ChangeEvent<{ value: string[] }>) => {
setValues(event.target.value)
setDisabledState(true)
setTimeout(() => {
setDisabledState(false)
}, 2000)
}
return (
<Select
onChange={handleChange}
options={OPTIONS}
value={values}
placeholder='Choose an option...'
width='auto'
multiple
disabled={disabled}
/>
)
}
```
before:
https://monosnap.com/file/ULYlXtLGMm31NY3mmGXX3o8YncWfrT
after:
https://monosnap.com/file/A6nRdBSfhXouBDjxm8tbXZ1vfhcXHJ
<details>
<summary>PR …

fix(Select): close Popper after disabling Select

---

cypress/component/TagSelector.spec.tsx
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelector/test.tsx

[FX-1995]
When setting initial values on `TagSelector` those (initial values) are not filtered out from the available choices.
[Sandbox example](https://codesandbox.io/s/tender-meadow-jjdol?file=/src/App.tsx)
This is happening because `isIncluded` function is comparing items by reference.
- TagSelector component should work exactly the same as before
<details>
<br />
</details>
[FX-1995]: https://toptal-core.atlassian.net/browse/FX-1995

fix(TagSelector): compare by value

---

cypress/component/ButtonCircular.spec.tsx
packages/picasso/src/ButtonCircular/styles.ts

[FX-2004](https://toptal-core.atlassian.net/browse/FX-2004)
Remove white background from flat Button. The background must be transparent by default.
<details>
<br />
</details>

fix(Button): replace background of flat button

---

cypress/component/Autocomplete.spec.tsx
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/story/Disabled.example.tsx
packages/picasso/src/Autocomplete/story/index.jsx
packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts

We have to add the possibility to have Autocomplete disabled
<details>
<br />
</details>

chore(Autocomplete): implement a disabled state of autocomplete

---

packages/picasso/src/Popper/Popper.tsx
packages/picasso/src/Popper/test.tsx

[TOP-1523]
Sometimes Menu is shaking when a user is walking across a menu items. It happens due to creating a completely new instance of `Popper.js` on each render of the Picasso's `Popper`. To avoid this, we should avoid creating new instances of props that are passed to `MUI`'s `Popper`.
https://monosnap.com/file/WRc2TdNnsGtlZwCXIWoUegTO2xuyvx
https://monosnap.com/file/JFlgVWiqBIsgu1zQmRARoRDNZaVQ0f
<details>
<br />
</details>
[TOP-1523]: …

fix(Popper): fix popper shaking on each render

---

packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/story/TitleSize.example.tsx
packages/picasso-lab/src/Section/story/index.jsx

[SPT-1793](https://toptal-core.atlassian.net/browse/SPT-1793)
Add the possibility to change the title font size for the section component.
- Check the title size example for the Section component
<details>
<br />
</details>

feat: add title size for section component

---

packages/picasso-forms/src/Checkbox/Checkbox.tsx
packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Checkbox/test.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso-forms/src/CheckboxGroup/test.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
packages/picasso-forms/src/Form/story/TitleCase.example.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/RadioGroup/test.tsx

[SPT-1830](https://toptal-core.atlassian.net/browse/SPT-1830)
Add support to display the checkbox group or the radio button group label in the title case.
- Check the title case form examples - https://picasso.toptal.net/SPT-1830-add-title-case-for-radio-group/?path=/story/picasso-forms-form--form#title-case
<details>
<br />
</details>

feat: add title case for radio or checkbox groups

---

packages/picasso/src/Slider/Slider.tsx

[SP-1564]
Allow default tooltip to be overwritten by a user-defined one on a range slider.
<details>
<br />
</details>
[SP-1564]: https://toptal-core.atlassian.net/browse/SP-1564

fix: allow default tooltip to be overwriten on slider

---

ci/jobs/picasso-master-release/Jenkinsfile

When docs job failed on Jenkins the master-release job has to fail as well, so slack notification will be reported
<details>
<br />
</details>

fix: failing master-release job when docs not deployed

---

_templates/component/example/example.ejs.t
_templates/component/example/index.js
_templates/component/example/story.ejs.t
_templates/component/new/component.ejs.t
_templates/component/new/componentsIndex.ejs.t
_templates/component/new/index.ejs.t
_templates/component/new/index.js
_templates/component/new/story.ejs.t
_templates/component/new/styles.ejs.t
_templates/component/new/test.ejs.t
packages/picasso-charts/src/index.ts
packages/picasso-forms/src/index.ts
packages/picasso-lab/src/index.ts
packages/picasso/src/index.ts

[FX-2040]
I was trying to generate empty components (as it is recommended in the storybook) with `yarn generate:component` and it created files in the wrong folder and files were outdated. So this PR updates path and template files
- try to generate some component using `yarn generate:component TestComponent`
- it should create files in Picasso package
- n/a Ensure that tests pass by running `yarn test`
- n/a Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-vi …

fix: fix path of generated component

---

packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/__snapshots__/test.tsx.snap
packages/picasso-lab/src/Section/styles.ts

Section component: removes header padding if collapsed
Collapse Section, header should have 0 padding bottom
<details>
<br />
</details>

fix(Section): removes header padding when collapsed

---

packages/picasso-lab/src/TypographyOverflow/TypographyOverflow.tsx

[SPT-1892](https://toptal-core.atlassian.net/browse/SPT-1892)
Had an issue, shown in the video below that when we passed `disableTooltip` prop to `TypographyOverflow` the tooltip would still show on click event and be stuck as there is no backdrop event
1. Go to [TypographyOverflow](https://picasso.toptal.net/SPT-1892-disabled-tooltip-visible-on-click-for-typography-overflow/?path=/story/picasso-lab-typographyoverflow--typographyoverflow)
2. Add the 'disableTooltip' prop to one of the overflown components
3. Click on the overflown text, the tooltip should not be showing
https://user-images.githubusercontent.com/79158829/132018858-a07f35d4-40bf-4b02-9c3f-b055c07979ed.mov
https://user-images.githubusercontent.com/79158829/132018865-7b2e06ab-c41f-4b05-b296-68905ea29e82.mov
<details> …

fix: [SPT-1892] updated TypographyOverflow click event for tooltip

---

packages/picasso/src/TreeView/PointLink/PointLink.tsx
packages/picasso/src/TreeView/TreeView.tsx
packages/picasso/src/TreeView/story/Compact.example.tsx
packages/picasso/src/TreeView/story/Compacted.example.tsx
packages/picasso/src/TreeView/story/Horizontal.example.tsx
packages/picasso/src/TreeView/story/index.jsx
packages/picasso/src/TreeView/types.ts
packages/picasso/src/TreeView/useNodes.ts
packages/picasso/src/TreeView/useTree.ts
packages/picasso/src/TreeView/useZoom.ts
packages/picasso/src/TreeView/utils/getDefaultMargins.ts
packages/picasso/src/TreeView/utils/getFinalMargins.ts
packages/picasso/src/TreeView/utils/index.ts
packages/picasso/src/TreeView/variables.ts
yarn.lock

[FX-2016]
[TOP-1535]
Added horizontal layout, vertical and horizontal margin props that allow to override default margins & compact variant of TreeView that allows for less bloated trees if tree has one or zero nodes with children per depth level
'Horizontal layout' & 'Compacted tree' examples in TreeView storybook
<details>
<br />
</details>
[FX-2016]: https://toptal-core.atlassian.net/browse/FX-2016
[TOP-1535]: https://toptal-core.atlassian.net/browse/TOP-1535

feat(TreeView): [FX-2016] Horizontal layout, margin props & compact variant for TreeView

---

packages/picasso-charts/package.json
packages/picasso-forms/package.json
packages/picasso-lab/package.json
packages/picasso/package.json
yarn.lock

Move debounce from devDependencies to dependencies as it's used in https://github.com/toptal/picasso/blob/0cdd7fc5084a08eaf652f1a45bf2fb5798f7e332/packages/picasso/src/ModalContent/use-scrollable-shades.ts#L2
- See green CI
<details>
<br />
</details>

fix(picasso): add explicit dependency on debounce

---

packages/picasso/src/NativeSelect/NativeSelect.tsx
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/NonNativeSelect/test.tsx
packages/picasso/src/NonNativeSelectOptions/NonNativeSelectOptions.tsx
packages/picasso/src/NonNativeSelectOptions/styles.ts
packages/picasso/src/ScrollMenu/ScrollMenu.tsx
packages/picasso/src/Select/Select.tsx
packages/picasso/src/Select/hooks/use-select-state/test.ts
packages/picasso/src/Select/hooks/use-select-state/use-select-state.ts
packages/picasso/src/Select/story/Limit.example.tsx
packages/picasso/src/Select/story/SearchBehavior.example.tsx
packages/picasso/src/Select/story/index.jsx
packages/picasso/src/Select/types.ts
packages/picasso/src/Select/utils/constants.ts

[TACO-1037]
This PR introduces maxSearchItems property for Form.Select. It allows to render only first 200 (by default) elements of the searchable. This is more or less back port of functionality that we have in platform which allows us to render and search lists that contains more than 1000 elements easily. 
1. Flat and Grouped Selects are now going to be trimmed depending `maxSearchItems` property value
2. Search input is going to be shown whenever the list has to be trimmed
3. Information about trimming of the list will be shown when necessary  
- Go to Form.Select story book and play around it
-  …

feat: add maxSearchItems for Form.Select

---

package.json
packages/picasso-provider/package.json
packages/picasso-provider/src/Picasso/Picasso.tsx
packages/picasso/package.json
packages/picasso/src/Link/Link.tsx
yarn.lock

follow-up to #2148
Remove dependency on  "@material-ui/styles": "4.10.0" because we have this package installed already with "@material-ui/core" and not pinned to 4.10. This causes possible clash of dependencies, the project may depend on 2 version:
- "@material-ui/styles": "4.10.0" from Picasso
- "@material-ui/styles": "4.11.4" from material-ui/core
Styled created with 4.10 can't access the theme created with 4.11.4 and crash.
This dependency is not needed as the material-ui core exports the same hooks, which are always compatible with it, so instead of that additional dependency we should have fixed the imports instead.
<details>
<br />
- …

fix: remove material-ui/styles dependency

---

packages/picasso-lab/src/Note/Note.tsx
packages/picasso/src/Accordion/Accordion.tsx
packages/picasso/src/Alert/Alert.tsx
packages/picasso/src/Badge/Badge.tsx
packages/picasso/src/Breadcrumbs/Breadcrumbs.tsx
packages/picasso/src/Button/Button.tsx
packages/picasso/src/Checkbox/Checkbox.tsx
packages/picasso/src/Dropdown/Dropdown.tsx
packages/picasso/src/Form/Form.tsx
packages/picasso/src/Grid/Grid.tsx
packages/picasso/src/Helpbox/Helpbox.tsx
packages/picasso/src/Menu/Menu.tsx
packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/Notification/Notification.tsx
packages/picasso/src/OverlayBadge/OverlayBadge.tsx
packages/picasso/src/Page/Page.tsx
packages/picasso/src/PageBanner/PageBanner.tsx
packages/picasso/src/PageHead/PageHead.tsx
packages/picasso/src/Radio/Radio.tsx
packages/picasso/src/Sidebar/Sidebar.tsx
packages/picasso/src/Table/Table.tsx
packages/picasso/src/Tabs/Tabs.tsx
packages/picasso/src/Tag/Tag.tsx
packages/picasso/src/TagSelector/TagSelector.tsx
packages/shared/src/types.ts

[FX-NNNN]
@teimurjan found a cool approach (I saw a couple of times) to have proper typings of static props on compound components with no explicit type coercing. 
To me it makes sense to simplify our types and apply Teimur's idea for whole the codebase
<details>
<br /> …

chore: simplify types for components with static properties

---

packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/test.tsx

[TACO-1050]
This feature add ability to disable rendering of `NoOptionsMenuItem` by letting `null` value to be passed through `Autocomplete.noOptionsText`
- In tests we trust
<details>
<br />
</details>
[TACO-1050]: …

fix(Autocomplete): do not render noOptions item when no options available

---

packages/picasso-forms/src/Form/Form.tsx

[FX-2132](https://toptal-core.atlassian.net/browse/FX-2132)
To be able to use `submit` from Cypress https://docs.cypress.io/api/commands/submit#Usage we'd like to use `data-testid` to get a specific form.
- go to `/?path=/story/picasso-forms-form--form`
- add `data-testid` for specific form
- check in devTools if `<form />` has `data-testid`
<details>
<br />
</details>

feat: add possibility to pass data-testid for picasso-forms Form

---

cypress/component/Badge.spec.tsx
cypress/component/Tag.spec.tsx
packages/picasso/src/ButtonSplit/__snapshots__/test.tsx.snap
packages/picasso/src/ButtonSplit/story/Sizes.example.tsx
packages/picasso/src/ButtonSplit/story/Variants.example.tsx
packages/picasso/src/Container/Container.tsx
packages/picasso/src/Container/styles.ts
packages/picasso/src/Select/story/Disabled.example.tsx
packages/picasso/src/Tag/story/Checkable.example.tsx
packages/picasso/src/Tag/story/Default.example.tsx
packages/picasso/src/Tag/story/Variants.example.tsx
packages/picasso/src/TagRectangular/story/Variants.example.tsx

Make `gap` property accept the same values as other size properties. For example `'small' | 'medium' | 'large'`.
It is a breaking change, but I believe that most users will not have to change anything because this property was introduced in the last major release.
- no tests should be broken
<details>
<br />
</details>

refactor(Container): make gap to fuction as other size props

---

packages/picasso/src/PromptModal/PromptModal.tsx

[FX-2217](https://toptal-core.atlassian.net/browse/FX-2217)
Added data-testid's according to the https://toptal-core.atlassian.net/wiki/spaces/TA/pages/1528758363/Data-TestID+naming+convention
- `N/A` Ensure that deployed demo has expected results and good examples
- `N/A` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
<details>
<br />
- …

feat(prompt modal): [FX-2217] add data-testid into PromptModal

---

packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/Input/utils/get-input-name.test.ts
packages/picasso-forms/src/Input/utils/get-input-name.ts

[SPT-2070](https://toptal-core.atlassian.net/browse/SPT-2070)
or [FX-2224](https://toptal-core.atlassian.net/browse/FX-2224)
Chrome introduced this bug recently https://bugs.chromium.org/p/chromium/issues/detail?id=1255609, so our users lost their autocomplete feature for `[name='title']` input. So we try to add a postfix `-picasso` to all inputs with `title|field|input` name.
- Use Chrome browser
- Go to an example in picasso form
- Modify one input's name to `title`
- After submitting, the input's native autocomplete should work
https://user-images.githubusercontent.com/18625278/140458763-383f68df-9f55-49c6-bcf1-bb5053acbe09.mp4
<details>
<br /> …

fix: bring back autocomplete to input

---

packages/picasso/src/Tag/Tag.tsx
packages/picasso/src/Tag/__snapshots__/test.tsx.snap
packages/picasso/src/Tag/test.tsx
packages/picasso/src/TagCheckable/TagCheckable.tsx

[FX-2232](https://toptal-core.atlassian.net/browse/FX-2232)
Extended props type for the Tag, to allow Link
should be possible to use
```
<Tag
as={Link}
href='http://toptal.com'
>
Toptal
</Tag>
```
<details>
<br />
</details>

feat(tag): [FX-2232] extended Tag props type

---

cypress/component/DatePicker.spec.tsx
packages/picasso-lab/src/DatePicker/DatePicker.tsx
packages/picasso-lab/src/DatePicker/constants.ts
packages/picasso-lab/src/DatePicker/index.ts
packages/picasso-lab/src/DatePicker/story/AllowCustomValue.example.tsx
packages/picasso-lab/src/DatePicker/story/WithNoHideOnSelect.example.tsx
packages/picasso-lab/src/DatePicker/story/WithOnBlurHandler.example.tsx
packages/picasso-lab/src/DatePicker/story/index.jsx
packages/picasso-lab/src/DatePicker/test.tsx
packages/picasso-lab/src/DatePicker/types.ts
packages/picasso-lab/src/DatePicker/utils.ts
packages/picasso-lab/src/index.ts

[SPT-2061](https://toptal-core.atlassian.net/browse/SPT-2061)
Add a boolean flag that allows using string values. It is useful for Staff Portal's users because we have this behavior in [Platform](https://staging.toptal.net/platform/staff/engagements/283531)
https://user-images.githubusercontent.com/16545305/139810245-20266335-8fad-4da0-a059-c48cfb647071.mov
There is also a `DatePicker/types.ts` file. In this file, I tried to achieve a dynamic `Props` interface based on the value of `allowCustomValue`.
So I wanted to make it work like this:
If `allowCustomValue` is provided:
- `value` should have type `DateOrDateRangeType | null | string`. Extended with a `string` compared to default type
- `onCahnge` should have type `onChange: (value: DateOrDateRangeType | string | null) => void`. …

feat(datepicker): add support for custom value

---

.changeset/famous-melons-check.md
bin/generate-icons
packages/picasso/src/Icon/Dialpad16.tsx

[FX-2181]
When new icons are generated via `yarn generate:icons`, there is a prettier command that updates all generated icons. This command however doesn't use our `.prettierrc.js` config, so the end result is that all icons are slightly changed (it adds semicolons to Props interface).
This change fixes it by running prettier with our config
[EDIT] I also updated one icon component `packages/picasso/src/Icon/Dialpad16.tsx` that didn't comply to our rules
run `yarn generate:icons` locally and there shouldn't be any changes when the script is done (assuming you haven't updated or added any icons of course)
<details>
<br /> …

fix: updated generate-icons script with .prettierrc.js config

---

packages/picasso-charts/package.json
packages/picasso-codemod/package.json
packages/picasso-forms/package.json
packages/picasso-lab/package.json
packages/picasso-provider/package.json
packages/picasso/package.json
packages/shared/package.json
packages/topkit-analytics-charts/package.json

[FX-NNNN]
Changeset publish has probably problem to find `./dist-package`, we are trying to set it without relative path.
<details>
<br />
</details>

chore: fix directory path in publishConfig

---

packages/picasso-charts/package.json
packages/picasso-codemod/package.json
packages/picasso-forms/package.json
packages/picasso-lab/package.json
packages/picasso-provider/package.json
packages/picasso/package.json
packages/shared/package.json
packages/topkit-analytics-charts/package.json

Same as `module` and `main` properties are working with path as the package.json is already copied to `dist-package` we need to change path for `prepublishOnly` the same way
<details>
<br />
</details>

chore: fix path to prepublish.js

---

bin/prepublish.js
packages/picasso-charts/package.json
packages/picasso-codemod/package.json
packages/picasso-forms/package.json
packages/picasso-lab/package.json
packages/picasso-provider/package.json
packages/picasso/package.json
packages/shared/package.json
packages/topkit-analytics-charts/package.json

`prepublish` should copy `packages/picasso/package.json` to `packages/picasso/dist-package`, but this is already done by `yarn build:packages`
so the issue was, that `prepublish` was being called from `dist-package/package.json`
- run `yarn build:packages` and check, that generated `dist-package` has package.json inside
<details>
<br />
</details>

chore: fix release through changesets

---

.changeset/angry-steaks-worry.md
packages/picasso/src/Select/utils/get-selected-options/get-selected-options.ts
packages/picasso/src/Select/utils/get-selected-options/test.ts

[FX-2252](https://toptal-core.atlassian.net/browse/FX-2252)
Using values of type `number` in `Select` breaks option selection.
1. Open `Custom options` example.
2. Pick an option.
3. Be sure that `Select`'s input has the correct value.
<details>
<br /> …

fix(Select): fix number value has no display value

---

.changeset/dull-avocados-chew.md
packages/picasso/src/Autocomplete/test.tsx
packages/picasso/src/ScrollMenu/ScrollMenu.tsx

[FX-2068]
TagSelector and Autocomplete were closing when you clicked on scroll in its overlay. This bug is fixed.
- Open https://picasso.toptal.net/fx-fix-closing-TagSelector-and-Autocomplete-when-scrolling/?path=/story/forms-tagselector--tagselector, Default example. 
- Scroll with the mouse by clicking on scroll now using the wheel.
- `TagSelector` should not close
<details>
<br />
</details>
[FX-2068]: https://toptal-core.atlassian.net/browse/FX-2068?atlOrigin=eyJpIjoiNWRk …

fix(TagSelector): closing when being scrolled

---

.github/workflows/pr.yaml
.github/workflows/release.yml
.github/workflows/visual-testing.yml
ci/jobs/picasso-pr-specs/Jenkinsfile

We don't want to run tests in "Version Packages" PR from changesets and ideally, we want to be able merge "Version Packages" immediately.
- replaced yarn cache functionality, the old one never could find cache folder
- skip GHA
- skip Jenkins steps in build
- add [skip ci] to PR title automatically
**test run** - https://github.com/toptal/picasso/runs/4235712965?check_suite_focus=true
**test changeset PR** - https://github.com/toptal/picasso/pull/2251
<details>
<br /> …

chore: disable GHA for changesets PR

---

.changeset/new-items-bake.md
packages/picasso/src/Button/__snapshots__/test.tsx.snap
packages/picasso/src/Button/test.tsx
packages/picasso/src/Link/Link.tsx

[FX-2278](https://toptal-core.atlassian.net/browse/FX-2278)
Added aria-disabled prop into the Link, to prevent overriding prop by the Disabled prop, which is undefined by default.
Check that disabled Button with component as Link, contains aria-disabled='true'
<details>
<br />
</details>
<details>
<br />
**You are OK** with merging this …

fix(link): [FX-2278] add aria-disabled prop

---

.changeset/fast-plums-try.md
packages/picasso-lab/src/DatePicker/DatePicker.tsx
packages/picasso-lab/src/DatePicker/test.tsx
packages/picasso-lab/src/DatePicker/utils.ts

[SPT-2117]
In staff-portal for many `DatePicker`'s we're using `minDate` property in the following way:
```
const minDate = useMemo(() => new Date(), [])
<DatePicker minDate={minDate} />
```
But currently, this causes a bug when the user manually entered the current date inside `DatePicker`'s input.
This is because internally in `isDateBefore` (and `isDateAfter`) we're comparing `date` and `dateToCompare` as is, so because of the `minDate={new Date()}`,  `dateToCompare` contains current time and helper returns `false`:
```
date: Thu Nov 18 2021 00:00:00 GMT+0300 
dateToCompare: Thu Nov 18 2021 15:23:46 GMT+0300
```
In this PR i added normalization of `min` and `max` dates, so just the resetting of the time to the `00:00:00:000` values
- Open …

fix(DatePicker): normalize min/max dates before comparison

---

.changeset/orange-kids-approve.md
cypress/component/Autocomplete.spec.tsx
cypress/component/Menu.spec.tsx
cypress/component/Select.spec.tsx
cypress/component/Tooltip.spec.tsx
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-lab/src/DatePicker/DatePicker.tsx
packages/picasso-lab/src/DatePicker/test.tsx
packages/picasso/src/Accordion/Accordion.tsx
packages/picasso/src/Accordion/test.tsx
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/test.tsx
packages/picasso/src/FileListItem/FileListItem.tsx
packages/picasso/src/FileListItem/test.tsx
packages/picasso/src/Input/Input.tsx
packages/picasso/src/Input/__snapshots__/test.tsx.snap
packages/picasso/src/Input/test.tsx
packages/picasso/src/InputAdornment/InputAdornment.tsx
packages/picasso/src/Menu/Menu.tsx
packages/picasso/src/NativeSelect/NativeSelect.tsx
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/OutlinedInput/OutlinedInput.tsx
packages/picasso/src/PageAutocomplete/PageAutocomplete.tsx
packages/picasso/src/PageAutocomplete/test.tsx
packages/picasso/src/Paper/Paper.tsx
packages/picasso/src/ProgressBar/ProgressBar.tsx
packages/picasso/src/Select/types.ts
packages/topkit-analytics-charts/src/CategoriesChartTooltip/CategoriesChartTooltip.tsx
packages/topkit-analytics-charts/src/CategoriesChartTooltip/test.tsx

[FX-2205](https://toptal-core.atlassian.net/browse/FX-2205)
- Replace hardcoded data testid values with dynamic ones
> This PR is done, even though team hasn't yet decided which property to use to test components. Answer will be available after survey.
- For example, in `packages/picasso/src/Input/test.tsx`, change `testIds.inputAdornment` to whatever value you want. The tests should not fail.
```javascript
const testIds = {
// inputAdornment: 'limit-adornment-multiline-label', // original
inputAdornment: "something-else"
}
```
<details>
<br />
- `@toptal-bot run deploy:documentation` - Deploy …

refactor: [FX-2205] Remove hardcoded data testid values

---

.changeset/tough-laws-pull.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/test.tsx

[FX-2312](https://toptal-core.atlassian.net/browse/FX-2312)
Updated testid for autocomplete autofill input
<details>
<br />
</details>
<details>
<br /> …

fix(Autocomplete): [FX-2312] add separate testid for autocomplete autofill input

---

.changeset/empty-gorillas-walk.md
packages/picasso/src/Tag/Tag.tsx
packages/picasso/src/Tag/story/Default.example.tsx
packages/picasso/src/Tag/styles.ts
packages/picasso/src/TagCheckable/TagCheckable.tsx

[FX-2303]
When `Tag` accepts `onClick` prop it triggers native MUI `clickable` classname. This classname was changed to style Tag.Checkable. This PR makes sure, that these styles are used only for Tag.Checkable.
The main issue is when we wrap `Tag` to `Tooltip`, which adds internally `onClick` to `Tag`, I have added example to storybook as it seems it is widely used in other projects.
- Open temploy and check 
- new example `With Tooltip`, 
- `Tag.Checkable` has correct styling
<details>
<br />
- `@toptal-bot run package:alpha-release` - …

fix(Tag): make checkable styles work only for Tag.Checkable

---

.changeset/witty-beds-do.md
packages/picasso/src/ApplicationUpdateNotification/story/InAction.example.tsx
packages/picasso/src/utils/Notifications/use-notifications.tsx

[FX-2284]
Add `onClose` to be fired when notification is closed. This is necessary for use cases when we need to react on the fact that the user has closed a notification, ex. `AppUpdateNotification`
<details>
<br />
</details>
<details>
<br />
1. Add `nit: ` to your comment. (ex. `nit: I'd rename this variable from makeCircle to …

feat: [FX-2284] Add cancel callback for notifications

---

packages/picasso/src/Button/story/Augmentation.example.tsx

[FX-NNNN]
[Context](https://toptal-core.slack.com/archives/CERF5NHT3/p1638272318498300)
There is a bug when using Augmentation with Button - `variant` prop has incorrect typing. 
It happens because:
1. `OverridableComponent` merges base component props (`ButtonProps`) & `as` component props (`LinkProps`) internally.
2. When it tries to merge `variant` prop, the only type in common is `undefined` so it sets `variant` to undefined.
Check this example to understand:
```tsx
interface Props1 {
variant?: 'foo'
}
interface Props2 {
variant?: 'bar'
}
type Props = Props1 & Props2
Props['variant'] // undefined
```
To fix the problem we should omit `variant` from `LinkProps` because `ActionLink` has this prop set statically. It'll resolve the merge conflict and use `variant` prop from `ButtonProps`. …

chore(Button): add forwardRef to Augmentation example

---

.changeset/curvy-peas-confess.md
cypress/component/Link.spec.tsx
packages/picasso/src/AccountSelect/__snapshots__/test.tsx.snap
packages/picasso/src/Button/__snapshots__/test.tsx.snap
packages/picasso/src/Button/styles.ts
packages/picasso/src/Link/Link.tsx
packages/picasso/src/Link/__snapshots__/test.tsx.snap
packages/picasso/src/Link/styles.ts
packages/picasso/src/Link/test.tsx
packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap

[FX-2328]
Add missing `visited` state of [Link](https://picasso.toptal.net/?path=/story/components-link--link)
Base docs: https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=218%3A4060
You can verify the behaviour by opening `Link` page ([storybook link](https://picasso.toptal.net/fx-2328-add-visited-state-to-link/?path=/story/components-link--link)) and clicking a link. 
Its color should change to `#0F256E`
<details>
<br />
- `@toptal-bot run deploy:documentation` - …

feat: update visited state of link

---

packages/picasso-lab/src/TextEditor/hooks/useHandleAutofocus.tsx
packages/picasso-lab/src/TextEditor/hooks/useHandleChangeFromController.tsx
packages/picasso-lab/src/TextEditor/story/Default.example.tsx

[FX-2293](https://toptal-core.atlassian.net/browse/FX-2293)
There was a problem with `autofocus`. `dangerouslyPasteHTML` was [stealing the focus](https://github.com/quilljs/quill/issues/2156).
1. Go to temploy.
2. Open `TextEditor` page.
3. Be sure that the first editor has focus.
4. Be sure that the second editor has a default value.
<details>
<br />
- `@toptal-bot run visual` - Run visual …

chore: fix autofocus

---

.changeset/kind-donkeys-think.md
packages/picasso/src/ModalTitle/styles.ts

[FX-2338]
Currently for in Modal Title we have no padding for the div that wraps Typography and if the text is too long it may go under the cross mark
1. In Storybook: Overlays -> Modal
2. Open first modal
3. Add more text to the h2 tag using the developer tools
4. Text should not go under the cross mark
|![2021 12 07_18 16 36_shot](https://user-images.githubusercontent.com/59695245/145107493-7bf12565-3036-49d3-9afe-e7bf7918416e.png)|![2021 12 07_17 52 20_shot](https://user-images.githubusercontent.com/59695245/145107293-2edbb787-2b40-43c8-a928-d92f1132b164.png)|
- `N/A` Annotate all `props` in component with …

feat(modals): [FX-2338] add right padding to modal title

---

.changeset/curly-apricots-tease.md
packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/Form/test.tsx
packages/picasso-forms/src/utils/scroll-to-error-decorator.ts
packages/picasso-forms/src/utils/scroll-to.ts

[FX-2356]
[SPB-2864]
1. If there multiple form on page and we submit them, we have to manually control auto-focus, since, Picasso is doing it wrong.
2. Sometimes you don't need an auto-focus for error fields or auto-sroll to error fields.
Submit form with an error (try switching off internet connection), see no scroll or auto-focus.
N/A
<details>
<br />
</details>
<details>
<br />
1. You have no …

feat(Forms): add ability to disable auto-focus and auto-scroll on Form submission error

---

.changeset/witty-brooms-sin.md
cypress/component/List.spec.tsx
packages/picasso/src/List/styles.ts

Fixes ListItem bullets misalignment when List is rendered withing container with reduced font-size (e.g. picasso/Table)
- Ensure unordered List items bullets are vertically aligned correctly 
| <img width="229" alt="image" src="https://user-images.githubusercontent.com/903437/147462824-7f780332-93a2-4e45-b3fa-a6033a8d193e.png"> | <img width="264" alt="image" src="https://user-images.githubusercontent.com/903437/147462841-67b02fa2-9471-450e-9d25-c2f20aed4568.png"> |
<details>
<br />
- `@toptal-bot run build` - Check …

fix(List): add font-size to List root to fix bullets alignment

---

.changeset/small-seahorses-speak.md
packages/picasso/src/Select/hooks/use-select-props/use-select-keydown-handler/test.ts
packages/picasso/src/Select/hooks/use-select-props/use-select-keydown-handler/use-select-keydown-handler.ts

[SPT-2254]
Related issue
https://toptal-core.atlassian.net/browse/SPT-2254
This pr adds additional symbols to `useSelectKeyDownHandler` RegExp for Select component
That allows triggering focus to Select Input when typing `+`, `-` and other special symbols
PR is adding support for only a few special symbols
1. Open https://picasso.toptal.net/SPT-2254-select-focus-regexp/?path=/story/forms-select--select
2. Click on Select component, when its popup opens, press one of the following characters `@#$%^()_+-=.,`. After pressing, search input should be focused
3. When its popup opens, press one of the following characters `!?&*|`. These characters should not trigger focus to search input …

chore(picasso): change key press focus logic for Select component

---

.changeset/healthy-dolls-sort.md
packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/styles.ts

[SPC-1575]
There are 2 fixes:
- `title` and `subtitle` accepts `ReactNode`  as value and it is wrapping it in `Typography` resulting in some potential invalid DOM syntax in case we pass something like `Container`. We keep regular `Typography` wrapper only when value is string otherwise we render as `div`
- add missing `minWidth: 0` to make ellipsis work
1. Pass a `TypographyOverflow` to title in storybook
<details>
<br />
</details> …

fix(section): [SPC-1575] allow ellipsis in title and subtitle content

---

packages/picasso-codemod/README.md
packages/picasso-codemod/bin/build.sh
packages/picasso-codemod/bin/cli.mjs
packages/picasso-codemod/bin/picasso-codemod.mjs
packages/picasso-codemod/package.json
yarn.lock

[FX-2401]
Make usage of codemods simpler:
- codemods don't need to be installed in the projects anymore
- don't need a special command for monorepo/spa apps
Now codemods can be run via
```
npx @toptal/picasso-codemod v17.0.0/typography-sizes
```
without a need to install the package directly.
<details>
<br />
</details>
<details>
<br />
2. You have optional …

chore: [FX-2401] Simplify usage of codemods

---

.github/CODEOWNERS

[CI-988]
Description
[CI-988] Remove CI infra team as co-owners of workflow files.
How to test
Everything should work as before.
[CI-988]: https://toptal-core.atlassian.net/browse/CI-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CI-988]: https://toptal-core.atlassian.net/browse/CI-988?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: remove ci infra team as coowners of workflow files

---

.changeset/young-sloths-train.md
packages/picasso/src/MenuItem/MenuItem.tsx
yarn.lock

`MenuItem` has some weird behavior when using `Link` as `as`. Here is more info - https://toptal-core.slack.com/archives/CCC3GP6CC/p1642067846008000
<details>
<br />
</details>
<details>
<br /> …

fix(MenuItem): use anchor as a link for menu item component

---

.changeset/pretty-swans-wait.md
packages/picasso-lab/src/TextEditor/TextEditor.tsx
packages/picasso-lab/src/TextEditor/TextEditorButton.tsx
packages/picasso-lab/src/TextEditor/TextEditorToolbar.tsx
packages/picasso-lab/src/TextEditor/styles.ts

[FX-2434]
[Abstract](https://share.goabstract.com/2de8e3f4-5704-4139-8a68-9e9519ed09f8?mode=design&sha=4f1f6493dfac89015cc6c71ea348807e931fe3bc)
- Add disabled styling.
> Note: According to the [design](https://share.goabstract.com/2de8e3f4-5704-4139-8a68-9e9519ed09f8?mode=design&sha=4f1f6493dfac89015cc6c71ea348807e931fe3bc), resize icon should be a different color. As it's too complicated to implement we agreed to ignore it and leave it as a native color.
- Visit [TextEditor Picasso component](https://picasso.toptal.net/fx-2434-texteditor-add-styles-for-disable-state/?path=/story/picasso-lab-texteditor--texteditor) and check `Disabled` example, it should be according to the design.
| …

[FX-2434] Add styles for disable state

---

.changeset/poor-needles-raise.md
cypress/component/Section.spec.tsx
packages/picasso-lab/src/Section/Section.tsx
packages/picasso-lab/src/Section/styles.ts

[SPC-1534]
Update Picasso Section component bordered and withHeaderBar variants to use white background for content and keep transparent for the default variant
- Check the background for `bordered` and `withHeaderBar` section component is white
| ![Captura de pantalla de 2022-01-18 13-19-40](https://user-images.githubusercontent.com/86490403/149936410-17f1d62e-7b17-463a-90a5-089eac93386c.png) | ![Captura de pantalla de 2022-01-18 13-18-56](https://user-images.githubusercontent.com/86490403/149936435-fd9439ce-ec06-47d5-b232-fb215687ce41.png) |
<details>
<br />
- …

fix: [SPC-1534] white background for bordered and with header bar section

---

packages/picasso-lab/package.json
packages/picasso-lab/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
packages/picasso-lab/src/QuillEditor/styles.ts
packages/picasso-lab/src/QuillEditor/utils/getEditorChangeHandler/getEditorChangeHandler.tsx
yarn.lock

[FX-2293]
[FX-2449]
fix the issue when pasting formatted text
There were multiple issues with pasting
1. pasting anything threw an error
- when passing undefined to `quill.getFormat()`, quill internally calls `quill.getSelection(true)`, so it first focuses editor and get latest selection
2. after pasting wrapping `Container` lost focus, even we had a cursor inside the Editor.
3. quill keeps styling of pasted text by default
- 2. and 3. issue was solved by adding library `quill-smart-paste`, that handles all these issues for us.
4. after pasting there was a styling issue in the editor.
- fixed by adding some styles to `ql-clipboard`. I have copied these styles from the default theme of the quill.
<details>
<br /> …

fix(TextEditor): update toolbar correctly on paste

---

__tests__/matchMedia.js
packages/picasso/src/DatePicker/test.tsx
packages/picasso/src/FileListItem/test.tsx
packages/picasso/src/Tooltip/__snapshots__/test.tsx.snap
packages/picasso/src/Tooltip/test.tsx
packages/picasso/src/TypographyOverflow/test.tsx

There is problem with current way how we mock functions from `@toptal/picasso/utils`, when we want to use another function from utils that actually does not have to be mocked.
I have found the proper way how to mock `window.matchMedia` in [Jest docs](https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom). With the previous mock, I had difficulties making tests in RichTextEditor work.
all unit tests should pass
<details>
<br />
</details> …

test: add proper mock for global `window.matchMedia`

---

packages/picasso/src/QuillEditor/styles.ts
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/styles.ts

[FX-2450]
RichTextEditor is still form input, so we need to follow styles as normal Input has. Here we add black border on hover and blue outline with blue border on focus. Copied from OutlineButton styles.
- Check [storybook](https://picasso.toptal.net/FX-2450-outline/?path=/story/components-richtexteditor--richtexteditor), hover and focus states should be the same as for normal input. (We don't have these styles in design for TextEditor)
| ![image](https://user-images.githubusercontent.com/6830426/153834369-4c920519-9d0f-45c5-97b0-477033078b01.png) | ![image](https://user-images.githubusercontent.com/6830426/153834093- …

style(RichTextEditor): add hover and focus styles

---

bin/build.js

No ticket.
In some cases, when running `yarn build:package` we'd have the following error multiple times:
```
Error: ENOENT: no such file or directory, stat 'dist-package'
```
This PR fixes that error.
<details>
<br />
- …

fix: fix dist-package directory not found errors

---

.github/workflows/release.yml

Release Picasso storybook even if PR doesn't have changesets and Picasso packages should not be released.
<details>
<br />
</details>
<details>
<br /> …

chore: release storybook even if package is not released

---

packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/styles.ts

[FX-2504]
When I click on disabled editor it gets focus outline, but it should not
1. click on disabled RichTextEditor
2. focus outline should not appear
| ![image](https://user-images.githubusercontent.com/6830426/154667147-1b93924f-05a3-47ab-bf54-43de9d8e23ac.png) | ![image](https://user-images.githubusercontent.com/6830426/154667183-6bd685a3-f4c3-4bdb-88b1-8a46751c0b92.png) |
<details>
<br /> …

style: remove focus outline when disabled

---

.changeset/metal-cherries-drive.md
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/DatePicker/test.tsx

[SPT-2424]
**PLEASE, DO NOT MERGE THIS PR UNTIL I TEST IT IN STAFF-PORTAL!**
When timezone is passed, we call `onChange` with `nextTimezoneValue` first and then set the same `nextTimezoneValue` via `setCalendarValue`. But we should not use `setCalendarValue` here, instead we should use just raw `nextValue`, to follow the same behavior as in `useEffect` hook:
```
useLayoutEffect(() => {
setCalendarValue(() => {
if (!value) {
return null
}
return timezoneConvert(value, timezone)
})
}, [value, timezone])
```
This bug causes behavior when after date selection, displayed selected date is `selected date - 1 day`
Tests should cover this problem
<details>
<br />
- `@toptal-bot run build` - …

chore(date-picker): fix an invalid displayed date after clicking in calendar when timezone is set

---

packages/picasso/src/RichTextEditor/hooks/useToolbarHandlers/useToolbarHandlers.tsx

[FX-2507]
When we have one type of list selected and want to change to another, it firstly unformats and on second click proper format is selected
**reproducing steps:**
1. write hello world
2. format it to unordered list
3. format it to ordered list
**expected:**
- we have one ordered list item with hello world
**current issue:**
- we have unformatted text hello world
<details>
<br />
</details>
<details>
<br /> …

fix: enable switching directly between lists

---

packages/picasso/src/QuillEditor/hooks/useDefaultValue/useDefaultValue.tsx
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/getEditorChangeHandler.tsx
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/test.ts

[FX-2506]
When switching between the header and list format, the state is not updated properly, both formats are selected until we write something.
**reproducing steps:**
1. switch text format from normal to heading in select
2. click the list button (ordered/unordered)
**expected:**
- only the list button is highlighted and normal is selected in text format selectbox
**current:**
- list button is highlighted and the heading is selected in text format selectbox 
<details>
<br />
- `@toptal-bot run package:alpha-release` - Release alpha …

fix: switch between block elements

---

.changeset/dirty-points-applaud.md
.changeset/silent-bananas-mate.md
.prettierignore
cypress/component/FieldRequirements.spec.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/Form/story/FieldRequirements.example.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
packages/picasso-forms/src/PasswordInput/test.ts
packages/picasso-forms/src/PasswordInput/validators.ts
packages/picasso/src/FieldRequirements/FieldRequirementItem.tsx
packages/picasso/src/FieldRequirements/FieldRequirements.tsx
packages/picasso/src/FieldRequirements/index.ts
packages/picasso/src/FieldRequirements/story/Default.example.tsx
packages/picasso/src/FieldRequirements/story/Error.example.tsx
packages/picasso/src/FieldRequirements/story/index.jsx
packages/picasso/src/FieldRequirements/styles.ts
packages/picasso/src/FieldRequirements/test.tsx
packages/picasso/src/FieldRequirements/types.ts
packages/picasso/src/FormField/FormField.tsx
packages/picasso/src/PasswordInput/PasswordInput.tsx
packages/picasso/src/index.ts

[FX-2525]
- FieldRequirements: added a new component
- forms/PasswordInput: now supporting FieldRequirements as default but it can be hidden with `hideRequirements` (ex: confirm password field)
- I had to touch `FormField` and `FieldWrapper` so please share your considerations for the future
- PasswordInput: https://picasso.toptal.net/fx-2525-add-strength-validations-section-to-passwordinput/?path=/story/forms-passwordinput--passwordinput
- FieldRequirements: https://picasso.toptal.net/fx-2525-add-strength-validations-section-to-passwordinput/?path=/story/components-fieldrequirements--fieldrequirements
- Form version(bottom of the page): https://picasso.toptal.net/fx-2525-add-strength-validations-section-to-passwordinput/?path=/story/picasso-forms-form--form
<details>
<summary>PR …

feat(FieldRequirements): add new component

---

.changeset/angry-eels-doubt.md
cypress/component/Colors.spec.tsx
cypress/component/Link.spec.tsx
packages/picasso-provider/src/Picasso/config/palette.ts
packages/picasso/src/Link/styles.ts
packages/picasso/src/utils/Colors/index.ts
packages/picasso/src/utils/Colors/story/index.jsx

[FX-2539]
Aligned color for visited state with [BASE](https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=218%3A4060). Changed to `#6727cf`
- open [Link component in storybook](https://picasso.toptal.net/fx-2539-typography-change-color-for-visited-links/?path=/story/components-link--link) and click on a default link
| ![image](https://user-images.githubusercontent.com/22159416/156577982-1e07223b-971d-4094-9813-40fd594c51fc.png) | ![image](https://user-images.githubusercontent.com/22159416/156578055-7da44be9-d466-4eab-b72e-14a59e9f2dad.png) |
<details> …

feat(Link): changed color for visited links

---

cypress/component/RichTextEditor.spec.tsx
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/getEditorChangeHandler.tsx

[FX-2541]
Test to cover this already [solved bug](https://toptal-core.atlassian.net/browse/FX-2505)
It adds formatted text than CTRL + A; DEL. Everything should be removed even formats.
During writing the first test I figured that we introduced back already solved bug, so I fixed it and handled it too.
When we are using block format and enter new empty line, format should disappear. But for inline formats we should preserve it.
**Reproducing steps:**
**First scenario:**
1. Enter some heading
2. Press enter
**expected:** `normal` text **should be** selected in the Toolbar
**Second scenario:**
1. Enter any list item
2. Press enter (new list item should appear)
3. Press enter (new list item should be removed)
**expected:** list **should not be** active the Toolbar
**Third scenario:**
1. …

test: add test for removing all formats

---

cypress/component/RichTextEditor.spec.tsx

[FX-2541]
Test that bold and italic buttons are disabled when the heading format is active.
<details>
<br />
</details>
<details>
<br />
2. …

test(RichTextEditor): inline formats are disabled when heading is active

---

.changeset/cyan-games-relax.md
package.json
packages/picasso-forms/src/Form/story/Default.example.tsx
packages/picasso-forms/src/Form/story/TitleCase.example.tsx
packages/picasso-forms/src/Rating/Rating.tsx
packages/picasso-forms/src/Rating/test.tsx

[FX-2538](https://toptal-core.atlassian.net/browse/FX-2538)
Add the a component wrapper of `Rating.Thumbs` to `picasso-forms`, and some story examples as well
- Go to the [storybook](https://picasso.toptal.net/fx-2538-add-rating-thumbs-to-picasso-forms/?path=/story/picasso-forms-form--form) and check out the code and functionality
<details>
<br />
</details>
<details>
<br />
1. You have no extra …

feat(ratingthumbs): add rating thumbs to picasso forms

---

packages/picasso/src/QuillEditor/utils/getTextChangeHandler/getTextChangeHandler.tsx
packages/picasso/src/QuillEditor/utils/getTextChangeHandler/test.ts

[FX-2549]
When we remove content from the editor, we should provide empty value, so `required` validation could work properly (done in different task)
**Reproducing steps:**
1. write any text in the editor
2. remove all the text
**expected:**
- value is `''`
**current:**
- value is `<p><br></p>`
- Checkout storybook and try to follow reproducing steps.
<details>
<br />
</details>
<details>
<br /> …

feat(RichTextEditor): return empty string when no content

---

packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
packages/picasso-forms/src/ButtonCheckbox/ButtonCheckbox.tsx
packages/picasso-forms/src/Checkbox/Checkbox.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso-forms/src/DatePicker/DatePicker.tsx
packages/picasso-forms/src/Dropzone/Dropzone.tsx
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
packages/picasso-forms/src/FieldLabel/__snapshots__/test.tsx.snap
packages/picasso-forms/src/FieldLabel/index.ts
packages/picasso-forms/src/FieldLabel/test.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
packages/picasso-forms/src/FileInput/FileInput.tsx
packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/NumberInput/NumberInput.tsx
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
packages/picasso-forms/src/Rating/Rating.tsx
packages/picasso-forms/src/Select/Select.tsx
packages/picasso-forms/src/Switch/Switch.tsx
packages/picasso-forms/src/TagSelector/TagSelector.tsx
packages/picasso-forms/src/TimePicker/TimePicker.tsx
packages/picasso/src/PageHead/PageHead.tsx
packages/picasso/src/test-utils/TestingPicasso.tsx
packages/shared/src/types.ts

Extract FieldLabel from FieldWrapper, remove multiple unnecessary props.
<details>
<br />
</details>
<details>
<br /> …

chore: extract label from field wrapper

---

packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
packages/picasso-forms/src/ButtonCheckbox/ButtonCheckbox.tsx
packages/picasso-forms/src/Checkbox/Checkbox.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso-forms/src/DatePicker/DatePicker.tsx
packages/picasso-forms/src/Dropzone/Dropzone.tsx
packages/picasso-forms/src/Field/Field.tsx
packages/picasso-forms/src/Field/index.ts
packages/picasso-forms/src/Field/story/index.jsx
packages/picasso-forms/src/FieldWrapper/index.ts
packages/picasso-forms/src/FileInput/FileInput.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/InputField/InputField.tsx
packages/picasso-forms/src/InputField/index.ts
packages/picasso-forms/src/InputField/test.ts
packages/picasso-forms/src/InputFieldWrapper/index.ts
packages/picasso-forms/src/NumberInput/NumberInput.tsx
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
packages/picasso-forms/src/Rating/Rating.tsx
packages/picasso-forms/src/Select/Select.tsx
packages/picasso-forms/src/Switch/Switch.tsx
packages/picasso-forms/src/TagSelector/TagSelector.tsx
packages/picasso-forms/src/TimePicker/TimePicker.tsx
packages/picasso-forms/src/index.ts
packages/picasso-forms/src/utils/use-field-validation/use-field-validation.ts

Rename `FieldWrapper` to `Field`, so later we can introduce `FieldWrapper` as a combination of `Field` + `FieldLabel`.
<details>
<br />
</details>
<details>
<br /> …

chore: rename FieldWrapper to Field

---

packages/picasso-forms/src/utils/scroll-to.ts

[FX-2174]
- removed focusing functionality after scrolling to the first field with the error
- go to form stories under picasso form
- click and leave one of the required fields
- scroll down a bit and click any of the submit buttons
- it should scroll but not focus on the failed field
<details>
<br />
- `@toptal-bot run deploy:documentation` - …

chore: remove focus after scroll to invalid

---

ci/jobs/picasso-master-publish-docs/Jenkinsfile

This is required for Jenkins to connect to the docs instance
- https://jenkins-build.toptal.net/job/picasso-docs/10947/console

ci: add sshagent to picasso-master-publish-docs job

---

packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
packages/picasso-forms/src/FieldWrapper/index.ts
packages/picasso-forms/src/FieldWrapper/story/index.jsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/index.ts

Return back the old `FieldWrapper` component for external usage, due to other teams using it when it was removed.
<details>
<br />
</details>
<details>
<br /> …

fix: return back old field wrapper

---

.changeset/three-coins-yell.md
packages/picasso-provider/src/Picasso/FontsLoader.tsx
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/TreeView/useNodes.ts
packages/picasso/src/utils/use-safe-state.ts

[FX-2558]
Replace `useIsomorphicLayoutEffect` (previously `useLayoutEffect`) with `useEffect` where it makes sense. 
I understand that useLayoutEffect fits where there are some DOM measurement or/and updating the DOM.
You can walk through the project and search for `useIsomorphicLayoutEffect` and check that every use-case has DOM related measurements and/or manipulations. But application should behave the same, for useEffect and useLayoutEffect acts almost the same way, only difference is that useLayoutEffect is run synchronously after DOM update but **before browser paint**.
<details>
<br />
- …

refactor: replace useIsomorphicLayoutEffect with useEffect

---

packages/picasso-forms/src/FieldWrapper/index.ts

Fix typescript issue, causing a warning when running `yarn build:storybok`.
<details>
<br />
</details>
<details>
<br /> …

fix: type export for field props

---

.changeset/popular-beans-turn.md
packages/picasso/src/DatePicker/DatePicker.tsx

[TOP-2072]
[FX-2565]
We at TopTeam use [data-private attribute to control visibility of some parts of UI for LogRocket](https://docs.logrocket.com/docs/privacy#exclude-data-in-videos). On of the things we need to hide this way is a DatePicker-powered input on member termination modal. Though currently if we render `<DatePicker data-private />` it's only going to be applied to the `<input` within date picker, while calendar popup still stays visible.
This PR adds proper support of `data-private` prop to DatePicker component, so that both input and calendar popup are hidden when you do render `<DatePicker data-private />`
<details>
<br />
- …

feat(DatePicker): add popperProps that allow data-* attrs for the Popper

---

.changeset/sour-monkeys-design.md
packages/picasso/src/DatePicker/DatePicker.tsx

[FX-X]
Fix disabled state of DatePicker, which at the moment of this PR still open calendar on input click even if disabled
| Insert screenshots or screen recordings 
https://user-images.githubusercontent.com/65539882/161556155-9dd38b21-a401-4846-a653-c2ad98612723.mov
| Insert screenshots or screen recordings |
<details>
<br />
- `@toptal-bot run deploy:documentation` - …

fix(DatePicker): fix DatePicker disabled state

---

.github/dependabot.yml

Fix dependabot, by removing secrets. They are not needed, due to the fact, that Picasso is open-source
<details>
<br />
</details>
<details>
<br /> …

chore: fix dependabot by removing secrets

---

.storybook/main.js
.storybook/utils/documentation-generator.ts
packages/topkit-analytics-charts/src/AnalyticsChart/AnalyticsChart.tsx
packages/topkit-analytics-charts/src/AnalyticsChart/story/index.jsx

There was a leftover detected:
But it's possible to convert docs for `AnalyticsCharts` also to automatically-generated 👍  
<details>
<br />
</details>
<details>
<br /> …

chore: replace manual docs with auto for AnalyticsChart

---

.github/workflows/pr.yaml
ci/jobs/picasso-master-publish-docs/Jenkinsfile
ci/jobs/picasso-pr-specs/Jenkinsfile

Move docs publishing and triggering old visual tests to GH Actions. This would help us to make clean `Version Package` PR, that would not have GH checks in a pending state.
<details>
<br />
</details>
<details>
<br />
**You are not OK** …

chore: move docs publishing to GHA

---

.github/workflows/release.yml

Change commit message `Version Packages` to `Version Packages [skip ci]` for changesets release PR.
It should skip all CI pr checks.
<details>
<br />
</details>
<details>
<br />
1. Something …

fix: skip ci commit message for changesets

---

.github/workflows/handle-contribution.yml

Remove check for Version Package PR ⚔️ 
<details>
<br />
</details>
<details>
<br />
**You …

fix: remove handle contributions from Version Package check

---

.changeset/rare-chefs-remain.md
packages/picasso-charts/src/BarChart/test.tsx
packages/picasso-charts/src/types.ts

[FX-2598]
`BarChart` uses [ResponsiveContainer from recharts](https://recharts.org/en-US/api/ResponsiveContainer) which throws warning console.log when static numbers are used - which is exactly our case, we do not allow strings as width or height (e.g. "100%").
One solution (that I used) is to extend width/height props to allow strings as well. Another would be to remove the ResponsiveContainer. 
running `yarn test:unit packages/picasso-charts/src/BarChart` locally should not throw any warning
<details>
<br /> …

fix: removed BarCharts warnings

---

.changeset/wild-vans-enjoy.md
packages/picasso/src/Tooltip/Tooltip.tsx
packages/picasso/src/Tooltip/story/FollowCursor.example.tsx
packages/picasso/src/Tooltip/story/index.jsx
packages/picasso/src/Tooltip/test.tsx
packages/picasso/src/Tooltip/types.ts
packages/picasso/src/Tooltip/useTooltipFollowCursor.ts
packages/picasso/src/Tooltip/useTooltipHandlers.ts
packages/picasso/src/Tooltip/useTooltipState.ts

[SPT-2577]
Add `followCursor` prop based on implementation from `@material-ui@5+` but with improvements
https://github.com/mui/material-ui/issues/14270
Improvements:
- when the cursor is moved 50+ pixels in any direction, we close the tooltip during moving, because the tooltip becomes annoying during such long moving action. After moving the tooltip is shown again.
- when the cursor is moved less than 50 pixels, we do not close the tooltip
When this option is enabled, the tooltip is completely disabled for touch devices, same as in `material-ui@5`
Open https://picasso.toptal.net/SPT-2577-tooltip-follow-cursor-prop/?path=/story/overlays-tooltip--tooltip, scroll to `Follow Cursor` example. Hover and move mouse over text. Test it carefully, especially logic when we move cursor outside of …

chore(tooltip): add `followCursor` prop based on implementation from `@material-ui@5+`

---

jest.config.js
package.json
packages/picasso-charts/src/BarChart/utils/find-top-domain/test.ts
packages/picasso-charts/src/LineChart/utils/find-top-domain/test.ts
packages/picasso-codemod/src/v18.0.0/picasso-lab/utils.ts
packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/story/Deserialization.example.tsx
packages/picasso-provider/src/Picasso/config/test.ts
packages/picasso/src/Autocomplete/test.tsx
packages/picasso/src/DatePicker/test.tsx
packages/picasso/src/FileListItem/test.tsx
packages/picasso/src/NonNativeSelect/test.tsx
packages/picasso/src/NonNativeSelectOption/test.tsx
packages/picasso/src/PromptModal/test.tsx
packages/picasso/src/RatingThumbs/test.tsx
packages/picasso/src/RichText/hooks/useRichText/test.tsx
packages/picasso/src/Select/hooks/use-select-state/test.ts
packages/picasso/src/Select/utils/count-options/test.ts
packages/picasso/src/Select/utils/get-multiple-selection/test.ts
packages/picasso/src/Select/utils/get-next-wrapping-index/test.ts
packages/picasso/src/Select/utils/get-single-selection/test.ts
packages/picasso/src/Select/utils/normalize-arrow-key/test.ts
packages/picasso/src/TagSelector/test.tsx
packages/picasso/src/Typography/utils/to-mui-variant/test.ts
packages/picasso/src/TypographyOverflow/test.tsx
yarn.lock

in order to upgrade ESLint to 8 version in Davinci. We need to apply the latest Davinci version in Picasso.
- Conduct all CI jobs
<details>
<br />
</details>
<details>
<br /> …

chore: upgrade davinci to 12 version

---

.changeset/bright-phones-think.md
packages/picasso/src/Select/Select.tsx
packages/picasso/src/Select/hooks/use-select-props/mocks.ts
packages/picasso/src/Select/hooks/use-select-props/use-search-change-handler/test.ts
packages/picasso/src/Select/hooks/use-select-props/use-search-change-handler/use-search-change-handler.ts
packages/picasso/src/Select/test.tsx
packages/picasso/src/Select/types.ts

[FX-2644]
A prop deprecation leftover is being removed here. We should mostly see deleted code.
- Select component still works as expected, for both Native and NonNative
<details>
<br />
</details>
<details>
<summary>PR …

fix: remove `onSearchChange` prop deprecation leftover

---

.changeset/sixty-doors-type.md
packages/picasso/src/Badge/Badge.tsx
packages/picasso/src/Badge/test.tsx

[FX-2659]
In our [Slack core channel](https://toptal-core.slack.com/archives/CERF5NHT3/p1650444203438359) user reported a bug in our Badge component.
The problem was, that MUIBadge also has `max` and it is set by default to `99`.
- when we passed `string` to MUIBadge, for example `'+999'`, it was treated as a string and not trimmed.
- when we passed `number` to MUIBadge, it was always trimmed to `+99`
I have added a new test case to cover this bug.
- CI is green
<details>
<br />
- `@toptal-bot run package:alpha-release` - Release alpha …

fix(Badge): use mui  prop

---

.changeset/large-cobras-jam.md
packages/picasso/src/Pagination/utils/has-ellipsises/has-ellipsises.ts
packages/picasso/src/Pagination/utils/has-ellipsises/test.ts

[FX-NNNN]
@alexvcasillas [pointed out](https://toptal-core.slack.com/archives/CERF5NHT3/p1650451875451999), that we don't calculate correctly left ellipses.
I have added multiple test cases to cover edge cases.
- CI is green
- play with Pagination in storybook
| ![image](https://user-images.githubusercontent.com/6830426/164430544-aaf65323-b553-4586-a684-e13d5e7c61e9.png) | ![image](https://user-images.githubusercontent.com/6830426/164430463-aac23d32-2ea0-4d25-be9a-51b6f0cf0fbb.png) |
<details>
<br />
- `@toptal-bot …

fix(Notification): do not show left ellipses if not needed

---

.changeset/prevent-avatar-image-blur.md
packages/picasso/src/Avatar/ImageAvatar/styles.ts

[SPB-3288]
A little ~~tweak~~ hack that prevents downscaled image to be blurred
Try to use this image as image source for Avatar in storybook.
The difference in clear on `medium` Avatar size for 100% page scale in Chrome. Also on `small` size for 125% scale.
To see the difference toggle
`image-rendering: -webkit-optimize-contrast`
```https://user-images.githubusercontent.com/17253416/165481990-58f6b95b-08c3-4075-b4b8-7fbcf12e821e.jpg```
- `N/A` Ensure that deployed demo has expected results and good examples
- `N/A` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/con …

fix(ImageAvatar): prevent image blur on downscaled image

---

.changeset/olive-keys-protect.md
.changeset/polite-apricots-drive.md
packages/picasso-forms/package.json
packages/picasso-forms/src/Field/Field.tsx

[SPT-2611]
There is an issue in React that breaks Firefox browser behavior for autofill/autocomplete in controlled inputs.
https://github.com/mui/material-ui/issues/16943
https://github.com/facebook/react/issues/15739
https://github.com/facebook/react/issues/18986
The solution is taken from one of the comment:
https://github.com/facebook/react/issues/18986#issuecomment-636354428
- open Firefox
- go to https://codesandbox.io/s/withered-worker-0njelw (latest Picasso)
- add some values for plain and controlled Picasso input and submit the form
- check autofill for each input, you will notice that Picasso input will not have any autofill options
- <video src="https://user-images.githubusercontent.com/4816942/165672090-2bbb4cbf-79af-4506-b68f-bcc95402d71b.mp4" width="600" />
- go to …

fix: make autofill work for controlled input in Firefox

---

.changeset/khaki-moons-change.md
cypress/component/Select.spec.tsx
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/Select/story/SearchBehavior.example.tsx
packages/picasso/src/Select/story/index.jsx
packages/picasso/src/Select/types.ts

[FX-2668]
We got an edge case bug when we use Select with search behavior is used inside the Drawer. You can check the bug in [codesandbox](https://codesandbox.io/s/misty-sea-xg3ugm?file=/src/App.tsx:120-126)
To reproduce:
- try to search inside the drawer. By typing/clicking
I couldn't find any other solution than disabling the portal for Popper.
- open storybook locally
- go to select stories
- check search behavior story
- try the new example inside the drawer
- search should be focusable and usable
- codemod is created
<details>
<br />
- `@toptal-bot run visual` - Run visual …

feat(Select): introduce disablePortal

---

.storybook/components/PicassoBook/Chapter.tsx
src/utils/url-generator.ts

- If storybook component has child component section, and that section's example has same id as parent component's example id, they collide.
For example:
- `Alert` has child component `Alert.Inline`
- Both have examples with id `Default`
- If we copy `Alert.Inline`'s example link with id `Default`, and copy it in new tab, it would jump to `Alert`'s example instead
1. Visit any [Picasso component with child component section](https://picasso.toptal.net/correct-links-in-storybook/?path=/story/components-alert--alert)
2. Copy [link of child component section](https://picasso.toptal.net/correct-links-in-storybook/?path=/story/components-alert--alert#alert-inline-default)
3. Paste it in new tab and it would jump to that example
before: …

fix: storybook links

---

cypress/component/Select.spec.tsx
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/NonNativeSelect/styles.ts
packages/picasso/src/Select/types.ts

[FX-2668]
Follow up to [previous PR](https://github.com/toptal/picasso/pull/2690) that fixes the behavior of search input in Select.
- Open select story with search behavior
- Click the select to open options
- Click the search icon in the search input
- Search input should be focused
<details>
<br />
</details>
<details>
<br />
1. Add …

fix(Select): click on search icon focuses the input

---

.changeset/warm-ducks-move.md
cypress/component/Calendar.spec.tsx
packages/picasso-forms/src/Select/Select.tsx

[SPT-2636]
This PR fixes the accessibility issue for `<Form.Select />`. Now we are able to open Select's options while clicking on the label.
- go to https://picasso.toptal.net/SPT-2636-pass-proper-name-to-field-label/iframe.html?id=picasso-forms-form--form&viewMode=story
- go to `Default` story
- scroll to `Business type` select
- try to click on `Business type` label
- select's options will pop up
**Before (missing `for` attribute)**
<video src="https://user-images.githubusercontent.com/4816942/166855537-43f0dc91-8034-4ba4-9689-2c2bbc344e50.mp4" width="600" />
**After**
<video src="https://user-images.githubusercontent.com/4816942/166855542-bf23be9d-51a2-47f6-b5e6-c8c7cf053054.mp4" width="600" />
- n/a Create `examples` for …

fix(Select): pass proper `name` to `FieldLabel`

---

docs/decisions/01-jest-snapshots-breaking-change.md

Add a decision about jest snapshots to treat as non-breaking changes
<details>
<br />
</details>
<details>
<br /> …

docs(decision): jest snapshot update as breaking changes

---

cypress/support/commands.js
cypress/types/index.d.ts

[FX-2705]
- Add the `getByTestId` command to Cypress to improve the readability of tests and to enable the same usage as in jest.
-  Annotate all `props` in component with documentation
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md#fixing-broken-visual-tests-inside-a-pr)
- Ensure the …

chore: add getByTestId to cypress

---

packages/shared/package.json

[FX-NNNN]
We forgot to update the provider version in shared. Syncpack found this issue.
- everything should work as before
<details>
<br />
</details>
<details>
<br /> …

chore: bump provider version in shared

---

.changeset/shiny-spiders-complain.md
packages/picasso/src/Badge/Badge.tsx
packages/picasso/src/Badge/test.tsx

[FX-2777](https://toptal-core.atlassian.net/browse/FX-2777)
Badge is hidden when content is `0`. In order to fix this behavior, the `showZero` property was added to the reused `<MuiBadge/>`.
- Navigate to `Badge` Story book and display the badge with `content={0}`, it **should be** displayed (https://picasso.toptal.net/SPT-NULL-fix-zero-badges-case/?path=/story/components-badge--badge)
<details>
<br />
</details>
<details> …

fix: zero content case for Badge

---

.changeset/large-socks-give.md
packages/picasso/src/Input/Input.tsx
packages/picasso/src/Input/__snapshots__/test.tsx.snap
packages/picasso/src/Input/story/Status.example.tsx
packages/picasso/src/InputLimitAdornment/styles.ts
packages/picasso/src/InputMultilineAdornment/InputMultilineAdornment.tsx
packages/picasso/src/InputMultilineAdornment/index.ts
packages/picasso/src/InputMultilineAdornment/styles.ts
packages/picasso/src/InputValidIconAdornment/InputValidIconAdornment.tsx
packages/picasso/src/InputValidIconAdornment/index.ts
packages/picasso/src/OutlinedInput/OutlinedInput.tsx

[TACO-1436]
This PR aims to improve the visuals of the success state of the multiline inputs.
We noticed that the current solution works great for single line inputs but not for multiline ones:
The inspiration for the new visual is based on a design file (https://www.figma.com/file/Lp9meoy0qlvH05GNUeQ2lW/Talent-Application-Form?node-id=201%3A9579):
Check the Forms > Input > Status section of the storybook.
| ![image](https://user-images.githubusercontent.com/4757057/168047033-99d1a026-4c34-4793-b54b-f5e5bfa7eeb3.png) | ![image](https://user-images.githubusercontent.com/4757057/168047300-f4838e4a-1514-43b3-a74d-3c8e39c425 …

style(Input): show success icon at the bottom of multiline input

---

packages/picasso-charts/src/LineChart/LineChart.tsx
packages/picasso-charts/src/LineChart/index.ts
packages/picasso-charts/src/index.ts
packages/picasso-charts/src/types.ts
packages/picasso-charts/src/utils/to-recharts-highlight-format/to-recharts-highlight-format.tsx
packages/picasso/src/RichTextEditor/index.ts
packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
packages/picasso/src/RichTextEditorToolbar/types.ts

[FX-2739]
Fix circularity issues in LineChart and RichTextEditor
- `yarn circularity`
- You should see no circularity issues 🎉 
<details>
<br />
</details>
<details>
<br /> …

fix: [FX-2739] Fix circularity in RichTextEditor and LineChart - part 6

---

packages/picasso-charts/src/BarChart/story/index.jsx
packages/topkit-analytics-charts/src/CategoriesChart/story/index.jsx

The PR is about skipping happo visual testing for stories with animations. This is a temporary fix and they will be taken care of later.
- `Picasso/Storybook` happo CI job should be green now
<details>
<br />
</details>
<details>
<br /> …

chore: skip stories with animations for happo storybook

---

jest.spec.js
packages/picasso/src/PromptModal/test.tsx

[FX-2702]
We want to be consistent and use Davinci config for jest as much as possible. We remove `restoreMocks` from our custom config, so the value will be `true`.
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix …

chore: use davinci config for `restoreMocks`

---

jest.spec.js
packages/picasso/src/Autocomplete/use-autocomplete/test.ts
packages/picasso/src/DatePicker/test.tsx
packages/picasso/src/Popper/test.tsx
packages/picasso/src/QuillEditor/hooks/useDefaultValue/test.ts
packages/picasso/src/SelectBase/hooks/use-select-state/test.ts
packages/picasso/src/TypographyOverflow/test.tsx

[FX-2702]
We want to be consistent and use Davinci config for jest as much as possible. We remove `resetMocks` from our custom config, so the value will be `true`.
- Ensure that visuals tests pass by running `yarn test:visual`. If not - check the documentation [how to fix …

chore: use davinci config for `resetMocks`

---

.changeset/ninety-ligers-scream.md
packages/picasso/src/Select/Select.tsx
packages/picasso/src/utils/forward-ref.ts

`Select` component does not forward ref to the `NativeSelect` and `NonNativeSelect` components although they handle that properly. Attempt to pass `ref` to the `Select` results in the following error:
Try to pass a `ref` to the `Select` component, something like:
```js
import React, { useEffect, useRef } from "react";
import { Select } from "@toptal/picasso";
const TestComponent = () => {
const ref = useRef<HTMLInputElement>(null);
useEffect(() => {
console.log(ref.current);
}, [ref]);
return <Select options={[]} ref={ref} />;
};
```
- n/a ~~Annotate all `props` in component with documentation~~
- n/a ~~Create `examples` for component~~
- ~~Covered with tests~~ 
- ~~codemod is created and showcased in the changeset~~
-  ~~test alpha package of Picasso in StaffPortal~~ …

fix(Select): forward ref properly

---

.changeset/polite-kiwis-rush.md
packages/picasso-provider/src/Picasso/Picasso.tsx

[SP-2562]
We have an issue in Storybook that's coming from the fast that we use two styling libraries simultaneously. The issue is: `styled-components` library doesn't always destroy the style tags it created, even when components are unmounted. While Picasso works correctly and unmounts all of the `style` tags.
The issue appears when we render a new instance of Picasso (e.g. new storybook story), so it adds style tags back. But it appends them in the end of the `<head>` tag, so they appear after the ones related to `styled-components`. The order of styles changes and in some places it breaks the styling.
In this PR we allow to always add Picasso styles first, by using the same option provided by MUI framework:
https://v4.mui.com/styles/advanced/#injectfirst
- Open some story
- Add …

feat: allow injecting Picasso styles first

---

.changeset/tame-boats-kick.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/TagSelector/TagSelector.tsx

[SPT-2729]
PR allows passing popper options to `Autocomplete` and `TagsSelector` components
Sometimes in some specific cases we want to override default popper options, for example to disable `preventOverflow` modifier
- n/a
- [n/a] Covered with tests
- [n/a] codemod is created and showcased in the changeset
- [n/a] test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details>
<br />
**You are OK** …

feat(autocomplete): allow passing popper options

---

docs/decisions/06-picasso-provider-as-a-peer-dependency.md

[FX-2781](https://toptal-core.atlassian.net/browse/FX-2781)
Add RFC for solving the problem of multiple `picasso-provider` runtime instances in monorepo projects as they contain different versions of `picasso` and/or `picasso-provider`. It also solves the problem were all dependencies must update `picasso-provider` when `picasso` is bumped, when declaring the provider as a `peerDep` we only need to bump it on the host project. 
When running the `changesets` plugin on a `picasso-provider` release with this configuration only the `devDependency` on `picasso` and `picasso-shared` will be bumped, not the `peerDependency`
- You can check the branch on #2864 and run `yarn changeset version` it should bump all necessary versions and create a changelog the same as the `Version Packages` PR …

docs: add RFC for using picasso-provider as a peerDependency

---

.changeset/bright-students-crash.md
packages/picasso/package.json
packages/shared/package.json

[FX-2781](https://toptal-core.atlassian.net/browse/FX-2781)
Change `picasso-provider` to a `peerDependency` on `picasso` and `picasso-shared`. This should solve the problem of conflicts between different versions and runtime instances in a monorepo scenario.
- You can use the alpha package to test on staff-portal
<details>
<br />
</details>
<details>
<br />
1. …

feat: change picasso provider to a peerDep

---

.github/workflows/pr.yaml
.husky/pre-commit
packages/picasso/package.json
packages/shared/package.json
yarn.lock

Fix missmatch of `picasso-provider` versions between packages
<details>
<br />
</details>
<details>
<br />
**You want your comments to be …

chore: fix picasso-provider version missmatches

---

packages/picasso-forms/src/Form/story/BackendCommunication.example.tsx
packages/picasso-forms/src/Form/story/CustomFormLevelConfiguration.example.tsx
packages/picasso-forms/src/Form/story/CustomValidator.example.tsx
packages/picasso-forms/src/Form/story/Default.example.tsx
packages/picasso-forms/src/Form/story/Dropzone.example.tsx
packages/picasso-forms/src/Form/story/FieldRequirements.example.tsx
packages/picasso-forms/src/Form/story/FileInput.example.tsx
packages/picasso-forms/src/Form/story/NoScrolling.example.tsx
packages/picasso-forms/src/Form/story/ParseInput.example.tsx
packages/picasso-forms/src/Form/story/RichTextEditor.example.tsx
packages/picasso-forms/src/Form/story/Status.example.tsx
packages/picasso-forms/src/Form/story/TitleCase.example.tsx
packages/picasso-forms/src/Form/story/ValidateOnSubmit.example.tsx

While testing something else, I realized that field names are incorrect for form stories. So, this PR is about fixing the field names to have correct form values.
While working on removing some of the dev environment warnings in this [PR](https://github.com/toptal/picasso/pull/2744), I had added dot notation for the field names. But I forgot to update the code parts that actually use values object for validation/submission. If you check this example from prod: https://picasso.toptal.net/?path=/story/picasso-forms-form--form#field-requirements
you will see that it is actually comparing wrong values from form-values API. Therefore, you can't submit the form in any case. There are some other examples also.
- All form stories should be working fine now. You can enter some values and compare …

fix(Form): fix field names for form story examples

---

.storybook/components/PicassoBook/TabChapter.tsx
.storybook/components/PicassoBook/components/TabsSection/TabsSection.tsx
.storybook/utils/documentation-generator.ts

- removed the unused `hideOnCompactLayout` prop from the storybook components
- fixed a type issue on storybook utils
- No visual difference. You can run the storybook on your local and check for terminal errors.
- Ensure the changed/created components have not caused accessibility issues. [How to …

fix: fix type errors and remove redundant prop for storybook components

---

.changeset/gorgeous-donkeys-call.md
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelector/test.tsx

[FX-2845]
- fixed the bug about being unable to filter selected items if custom `getKey` provided
- I will also add a new test for `TagSelector` on this PR: https://github.com/toptal/picasso/pull/2873. I didn't do it here to avoid conflicts with that PR.
go to https://picasso.toptal.net/?path=/story/forms-tagselector--tagselector#custom-option-rendering and try to select more than one item
- from the temploy, go to `TagSelector` page and select more than one item on both `custom-label` and `custom-option` examples.
- Create `examples` …

fix(TagSelector): fix selected items filtering for custom key

---

.changeset/happy-dolls-wave.md
packages/picasso-forms/src/FormConfig/FormConfig.ts
packages/picasso-forms/src/InputField/InputField.tsx
packages/picasso-forms/src/InputField/test.ts

[FX-2822]
Fix the incorrect valid state of the input field when it was fixed after submitting an invalid value.
- Open ["Form Level Status Configuration" on picassot.toptal.net](https://picasso.toptal.net/?path=/story/picasso-forms-form--form#form-level-status-configuration)
- Click "Submit". You'll see the validation error (that's correct behavior).
- Enter a text in the input field. Instead of the green check icon, you'll see no valid state.
- Repeat action from the `How to reproduce` section. But instead, use ["Form Level Status Configuration" section from the demo](https://picasso.toptal.net/fx-2822-form-shows-incorrect-validation-status/?path=/story/picasso-forms-form--form#form-level-status-configuration)
- You should be able to submit the form with Enter and see the green check …

fix(InputField): fix input valid state when it's changed after submit

---

cypress/component/Checkbox.spec.tsx
cypress/component/Dropdown.spec.tsx
cypress/component/TagSelector.spec.tsx
cypress/support/commands.jsx
cypress/support/index.d.ts
yarn.lock

Happo has a workaround for hovered state screenshots. To not remember and copy this workaround, I introduced a cypress command to use.
- there shouldn't be a happo change (except renames)
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin …

feat: introduce happo hover screenshot command for cypress

---

.changeset/nice-guests-act.md
cypress/component/RichTextEditor.spec.tsx
packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/Form/FormRenderer.tsx
packages/picasso-forms/src/Form/test.tsx
packages/picasso/src/RichTextEditor/story/index.jsx

[FX-2828]
Fix form validation when submitting by clicking Enter.
- The issue has been reported in the `final-form` package in 2019 and it hasn’t been solved since then. https://github.com/final-form/final-form/issues/213.
- The only solution, for now, is to trigger validation of the active input field manually. The best solution to do that is to use the `FromApi#blur` function of `final-form`. It changes only the state of final form objects and it doesn't trigger the native blur event or callbacks of input fields. 
- Open ["Form Level Status Configuration" on picassot.toptal.net](https://picasso.toptal.net/?path=/story/picasso-forms-form--form#form-level-status-configuration)
- Add `validateOnBlur` property to the `<Form />` element
- Type something in the input and press Enter
- You'll …

fix(Form): fix form validation when submit with clicking Enter

---

.changeset/sweet-pugs-fail.md
.github/dependabot.yml
.github/workflows/davinci-alpha-package.yml
.github/workflows/davinci-integration-tests.yml
.github/workflows/handle-contribution.yml
.github/workflows/pr.yaml
.github/workflows/visual-testing.yml

We need to use davinci GH Actions directly
- Run CI command
<details>
<br />
</details>
<details>
<br />
**You want your comments to be …

chore: use davinci github actions directly

---

package.json
packages/picasso-forms/src/FormConfig/FormConfig.ts

Fix incorrect TS validator
Fix type issue on FormConfig context provider
- there shouldn't be a TS error anymore
<details>
<br />
</details>
<details>
<br /> …

chore: fix typescript validator

---

.changeset/slow-oranges-approve.md
packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/Modal/test.tsx
packages/picasso/src/utils/Modal/modal-manager.ts

[TOP-2262]
[FX-1069]
* ~Improve Modal's scroll lock logic to only remember previous body overflow once modal is open, so that additional modals that might be mounted to the react tree but closed won't remember 'overflow=hidden' into their `bodyOverflow` ref.~
* ~Prevent double-execution of `resetBodyOverflow` whenever modal closes~
Completely revised body scroll lock implementation to allow multiple modals mounted, properly drop scroll lock whenever any of them opens and lift scroll lock only after all of previously open modals are closed
| Insert screenshots …

fix(Modal): refactor Modal's scroll lock to allow multiple modals mounted

---

packages/picasso-forms/src/utils/scroll-to.ts

[FX-2569]
Some time ago, we decided to remove the focusing errored field after form submission feature due to a lack of ability to discriminate the focused field with or without error. Soon, we will introduce new design for focused & errored field so this feature can be reverted back.
- open the Form page on storybook and pick one of the form examples
- try to submit with an error, the browser should scroll to the first errored field
- check if the field is already focused without any of your interactions …

chore: revert back focusing errored field after form submission

---

packages/picasso/src/TreeView/story/index.jsx

No ticket.
TreeView tests are flaky. Need to disable them first, so that we don't block anyone.
- Happo tests pass

chore: disable flaky TreeView story screenshots temporarily

---

.changeset/fast-ears-hang.md
packages/picasso/src/OutlinedInput/styles.ts

[FX-2571]
Add red shadow when error input is focused according to [design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=1002%3A14361)
- Open [temploy on form](https://picasso.toptal.net/fx-2571-outlinedinput-add-errored-focused-state/?path=/story/picasso-forms-form--form#default) and focus input with error
<details>
<summary>PR …

feat(OutlinedInput): add shadow for error-focused state

---

cypress/component/ApplicationUpdateNotification.spec.tsx
cypress/component/BarChart.spec.tsx
cypress/component/ButtonSplit.spec.tsx
cypress/component/DatePicker.spec.tsx
cypress/component/Form.spec.tsx
cypress/component/Link.spec.tsx
cypress/component/List.spec.tsx
cypress/component/Menu.spec.tsx
cypress/component/PasswordInput.spec.tsx
cypress/component/RichTextEditor.spec.tsx
cypress/component/Select.spec.tsx
cypress/component/ShowMore.spec.tsx
cypress/component/Table.spec.tsx
cypress/component/TagSelector.spec.tsx

No ticket.
This is a quick cleanup for using the `getByTestId` and `getByRole` utilities everywhere in Cypress.
- tests pass, inspect code
~- [ ] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)~
~- [ ] Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~
~- [ ] Annotate all `props` in component with documentation~
~- [ ] Create `examples` for component~
~- [ ] Ensure that deployed demo has expected results and good examples~
~- [ ] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

chore: use getByTestId and getByRole in Cypress

---

.changeset/famous-poets-stare.md
cypress/component/RichTextEditor.spec.tsx
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/story/Status.example.tsx
packages/picasso/src/RichTextEditor/styles.ts

[FX-2918]
Currently we don't use `FieldLabel` to render `label`, we just render it as plain text and it has different styling.
- check [RichTextEditor story](https://picasso.toptal.net/fix-rich-text-label/?path=/story/picasso-forms-form--form#rich-text-editor) inside picasso-forms. The label should have the same styling as other inputs
- you can test it out in [codesandbox](https://codesandbox.io/s/currying-cherry-dkbuu7?file=/package.json) with aplha package
| ![image](https://user-images.githubusercontent.com/6830426/175938515-6e739e82-85cf-40f2-9e53-242fd0b707fa.png) | …

fix(RichTextEditor): use `FieldLabel`

---

.changeset/tame-plums-unite.md
packages/picasso/src/Autocomplete/Autocomplete.tsx

[TACO-1656]
When `TagSelector` has enough options selected to wrap on two lines or more clicking on it may not open the popper menu. This is due to the fact the click event is attached to the autocomplete input inside the component. This PR fixes this by attaching the same click handler to the parent container.
Use the "Initially set value" sub-section under "TagSelector" page in the story book to test it.
**Before**
https://user-images.githubusercontent.com/4757057/177348074-7119ba4e-6936-4520-882c-d00da2932232.mp4
**After**
https://user-images.githubusercontent.com/4757057/177347758-b1e20732-4164-442b-b187-d755df86e00b.mp4
- n/a ~~codemod is created and showcased in the changeset~~
- n/a ~~test alpha package of Picasso in StaffPortal~~
<details>
<summary>PR …

fix(TagSelector): fix options not showing on every click

---

.github/workflows/davinci-alpha-package.yml
.github/workflows/release.yml
.github/workflows/request-review-on-pr.yml

[FX-2938]
Bump github-script action to v6 and adjusting workflows for [breaking change](https://github.com/actions/github-script#breaking-changes-in-v5)
- code review should be enough
- simplified version of alpha package release was conducted [in topapp](https://github.com/toptal/topapp-frontend/pull/124)
- Ensure the …

chore: bump github-script to latest

---

.changeset/sweet-squids-crash.md
packages/picasso/src/ModalContent/styles.ts

[no-jira]
There is a difference between the `Modal.Content` component in Picasso and [Figma Product Library](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=280%3A15387). This change fixes this issue. Topic has discussed in the slack [channel](https://toptal-core.slack.com/archives/CERF5NHT3/p1657183527652579)
| <img width="655" alt="image" src="https://user-images.githubusercontent.com/24292362/177963975-7fbb7528-9f07-4296-a305-a2c9f5906ded.png"> | <img width="653" alt="image" …

feat(modal): adjust modal content top padding

---

.changeset/lemon-cups-jump.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/use-autocomplete/test.ts
packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelector/story/KeepOpen.example.tsx
packages/picasso/src/TagSelector/story/index.jsx

[TACO-1656]
This PR introduces `closeOnSelect` prop to the `TagSelector` component. 
When `closeOnSelect` is `true` (the default value) the options menu is closed after selecting an option. When `false` it does not :smile: 
Keeping the menu around makes selecting multiple values faster instead of having to go back and click on the input again. This is mostly a slowdown when using mouse/touchpad, navigating with the keyboard is not that troublesome.
Open `TagSelector` section in story book and checkout the new "Keep options open" sub-section.
**Before**
https://user-images.githubusercontent.com/4757057/177340738-8edaf1bb-5965-4bce-9d99-950936e3926a.mp4
**After**
https://user-images.githubusercontent.com/4757057/177341419-8bc5c5ff-5848-4d65-9966-05a36fe023c0.mp4
- n/a …

feat(TagSelector): add `closeOnSelect` prop

---

.github/workflows/release.yml

Don't add `[skip-ci]` text into "Version Package" PR as its not needed any longer.
Also merged two jobs into one since they did basically the same thing - get all opened "Version Package" PRs and iterate over to:
- add `no-jira` label
- update PR body
- code review should be enough
- Ensure the changed/created components have …

chore: dont add [skip-ci] to Version Package PR

---

.changeset/light-mugs-prove.md
cypress/component/Stepper.spec.tsx
packages/picasso/src/StepLabel/StepLabel.tsx
packages/picasso/src/StepLabel/styles.ts
packages/picasso/src/Stepper/Stepper.tsx
packages/picasso/src/Stepper/story/Overflow.example.tsx
packages/picasso/src/Stepper/story/index.jsx
yarn.lock

[SPT-2844]
Add `overflowEllipsis` prop to enable proper ellipsis overflow with the tooltip for `Stepper` labels
- Open https://picasso.toptal.net/SPT-2844-stepper-overflow/?path=/story/components-stepper--stepper
- Scroll to the `overflow` section
- Check that tooltip is visible when hovering over labels with `overflow: ellipsis`
- Check that tooltip is not visible when hovering over labels without `overflow: ellipsis`
<details>
<br />
- `@toptal-bot run package:alpha-release` - …

feat(stepper): add `overflowEllipsis` prop

---

.changeset/long-sloths-pump.md
packages/picasso/src/TagSelector/TagSelector.tsx

The `TagSelector` component has its own property definition that allows to pass the `validationIcon` of the `testids` property only. In some cases there is a need to specify, e.g. `input` field of `testids` property, but there is no way to do it for now.
This PR extends `testids` property of the `TagSelector` component and allows to specify any field that is supported by internally used `Autocomplete` component.
- There must be no visual changes
- ~test alpha …

fix(TagSelector): update testids property definition

---

.changeset/young-grapes-type.md
packages/picasso-forms/src/Form/story/Default.example.tsx
packages/picasso-forms/src/Form/test.tsx
packages/picasso-forms/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelector/TagSelector.tsx

[FX-2913]
Due to the default prop value of initialValue, it wasn't possible to set initialValues for TagSelector field.
- use Form's default story to see TagSelector working fine
- bug was visible after creating a new app from `davinci new app`
From newly created davinci app
- codemod is created and showcased in the …

fix(TagSelector): fix using TagSelector with initialValue

---

.changeset/proud-ligers-grab.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/story/WithOnResetClick.example.tsx
packages/picasso/src/Autocomplete/story/index.jsx
packages/picasso/src/Autocomplete/use-autocomplete/test.ts
packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts

[COMM-1025]
Add new `onResetClick` callback prop that is called after clearing autocomplete.
This task is blocking other teams
- check [example in temploy](https://picasso.toptal.net/feat-add-onresetclick-to-autocomplete/?path=/story/forms-autocomplete--autocomplete#with-onresetclick-callback) or locally
<details>
<br /> …

feat(Autocomplete): add onResetClick prop

---

.changeset/fluffy-hairs-argue.md
cypress/component/DatePicker.spec.tsx
packages/picasso/src/Calendar/Calendar.tsx
packages/picasso/src/Calendar/styles.ts
packages/picasso/src/CalendarIndicators/CalendarIndicators.tsx
packages/picasso/src/CalendarIndicators/index.ts
packages/picasso/src/CalendarIndicators/styles.ts
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/DatePicker/story/WithFooter.example.tsx
packages/picasso/src/DatePicker/story/WithIndicatedRange.example.tsx
packages/picasso/src/DatePicker/story/index.jsx
packages/picasso/src/DatePicker/styles.ts
packages/picasso/src/DatePicker/test.tsx

[SDE-374](https://toptal-core.atlassian.net/browse/SDE-374)
In our current [initiative](https://toptal-core.atlassian.net/browse/PI-1934), we'll need some improvements in the DatePicker component to be used in Client Portal and Staff Portal. So in this PR, we have developed some features listed below:
- Option to highlight with a yellow indicator a specific range of dates
- Option to add a customized footer to the bottom of the calendar
- Access [https://picasso.toptal.net/sde-374-improve-date-picker-features/](https://picasso.toptal.net/sde-374-improve-date-picker-features/?16717e025189d3d36ab4e71ddaf4e01018d3a5fd)
- Verify each feature example at Datepicker section
- Compare requirements in the ticket with implementation
| Features                             | Screenshots …

feat(DatePicker): add footer and indicated in a range of dates

---

.github/workflows/pr.yaml

[FX-NNNN]
We were using `env.HTTP_PROXY` but forgot to set it up.
<details>
<br />
</details>
<details>
<br /> …

ci: add http proxy to env

---

.changeset/proud-emus-destroy.md
packages/picasso/src/TagSelectorInput/styles.ts

[FX-1944]
According to the ticket description, I have added a meaningful min-width to the input class.
- you can play with the custom option story and add your own options to squeeze the width.
| <img width="373" alt="Screen Shot 2022-07-26 at 15 55 31" src="https://user-images.githubusercontent.com/7733167/181010956-d972db0f-3c05-46ef-ab08-15079cc68f40.png"> | <img width="373" alt="Screen Shot 2022-07-26 at 15 55 25" src="https://user-images.githubusercontent.com/7733167/181010990-d2031c33-488e-4b59-a06c-50edeaee96f9.png"> |
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and …

chore(TagSelector): add min-width to underlying input

---

.changeset/five-comics-care.md
packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
packages/picasso/src/utils/html-to-hast.ts

[NO-JIRA]
`picassoMapper` was not implemented correctly and it wasn't passing `child.props` when creating the React Element and therefore, links were not working as they were loosing `href` since it wasn't being passed down to the `Link` component
- `RichText` component should be working as expected and links also have their `href` and redirecting to the appropriate URL
- CI should be 💚 
<details>
<br />
</details>
<details>
<br />
**You are …

fix: pass missing props to children when mapping

---

.changeset/strong-beans-perform.md
packages/picasso/src/Avatar/Avatar.tsx
packages/picasso/src/Avatar/story/Editable.example.tsx
packages/picasso/src/Avatar/story/index.jsx
packages/picasso/src/Avatar/styles.ts
packages/picasso/src/Avatar/test.tsx

[FX-3062]
- according to designs, I have added a permanent(not on hover) editable state for Avatar
- there is a separate story for this new state on storybook
<details>
<br />
</details> …

feat(Avatar): add editable state

---

packages/picasso/src/Badge/Badge.tsx
packages/picasso/src/Badge/__snapshots__/test.tsx.snap
packages/picasso/src/Modal/Modal.tsx

[FX-3059]
- fix for deprecation warnings for MUIv5:
- `disableBackdropClick` for Modal
- `overlap="rectangle"` for Badge component
- there shouldn't be any errors related to Modal and Badge
- Create `examples` …

fix: fix MUI deprecation warnings

---

.changeset/blue-eels-compete.md
cypress/component/AvatarUpload.spec.tsx
packages/picasso/src/AvatarUpload/AvatarUpload.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
packages/picasso/src/AvatarUpload/DropzoneSvg/utils.ts
packages/picasso/src/AvatarUpload/__snapshots__/test.tsx.snap
packages/picasso/src/AvatarUpload/story/Sizes.example.tsx
packages/picasso/src/AvatarUpload/story/WithUpload.example.tsx
packages/picasso/src/AvatarUpload/story/index.jsx
packages/picasso/src/AvatarUpload/styles.ts

[FX-2889]
- `size` prop added with following values `small`, `large`
- disabled keyboard and drag functionality while `onEdit` functionality
- go to [component page](https://picasso.toptal.net/fx-2889-implement-basic-avatar-upload/?path=/story/components-avatarupload--avatarupload)
- you can see the new story for sizes.
- HOVERING state of the component will be handled in upcoming PR
> All **_development checks_** should be done and set checked to pass …

feat(AvatarUpload): add size variant

---

.changeset/quiet-cameras-carry.md
packages/picasso/src/AvatarUpload/AvatarUpload.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
packages/picasso/src/AvatarUpload/story/States.example.tsx
packages/picasso/src/AvatarUpload/story/index.jsx
packages/picasso/src/AvatarUpload/styles.ts

[FX-2889]
- added focused, hovered, active (also dragActive) and error states to the AvatarUpload
figma designs for this component: https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=2599%3A18280
- go to [component page and check new story](https://picasso.toptal.net/fx-2889-add-visual-states-avatar-upload/?path=/story/components-avatarupload--avatarupload#states)
> …

feat(AvatarUpload): add visual states

---

.changeset/cold-parrots-hide.md
.changeset/giant-shrimps-hope.md
packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
packages/picasso-forms/src/AvatarUpload/index.ts
packages/picasso-forms/src/FieldBase/types.ts
packages/picasso-forms/src/Form/story/AvatarUpload.example.tsx
packages/picasso-forms/src/Form/story/Default.example.tsx
packages/picasso-forms/src/Form/story/TitleCase.example.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/FormCompound/index.ts
packages/picasso/src/AvatarUpload/AvatarUpload.tsx
packages/picasso/src/AvatarUpload/types.ts

[FX-3072]
- I have added a new component into `picasso-forms` and wrapped `AvatarUpload` with `InputField`
- I have added `value`, `onFocus` and `onBlur` props for `picasso/AvatarUpload`
- there are two different stories that include `AvatarUpload` examples:
https://picasso.toptal.net/fx-3072-avatarupload-form-wrapper/?path=/story/picasso-forms-form--form#default
https://picasso.toptal.net/fx-3072-avatarupload-form-wrapper/?path=/story/picasso-forms-form--form#avatarupload 
You can check them both and confirm that they are working as expected.
- …

feat(AvatarUpload): add field wrapper

---

.changeset/mighty-radios-sniff.md
packages/picasso/src/AvatarUpload/AvatarUpload.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/DropzoneSvg.tsx
packages/picasso/src/AvatarUpload/DropzoneSvg/styles.ts
packages/picasso/src/AvatarUpload/DropzoneSvg/utils.ts
packages/picasso/src/AvatarUpload/__snapshots__/test.tsx.snap
packages/picasso/src/AvatarUpload/story/Sizes.example.tsx
packages/picasso/src/AvatarUpload/styles.ts

[FX-3074]
- added remaining size variants from Avatar: `xxsmall`, `xsmall`, and `medium`
- fine-tuned AvatarUpload's border and outline shapes
- provide some more comments to ease understanding how DropzoneSvg works
- go and check the sizes story https://picasso.toptal.net/fx-3073-avatar-upload-remaining-size-variants/?path=/story/components-avatarupload--avatarupload#sizes
> …

chore(AvatarUpload): add remaining size variants

---

.changeset/light-cats-argue.md
packages/picasso/src/utils/__tests__/html-to-hast.test.tsx
packages/picasso/src/utils/html-to-hast.ts
packages/picasso/src/utils/test.tsx

Previously on `htmlToHast` we were always getting the children of the resulting AST and returning them as a root. That would work greatly when the input HTML had multiples elements and no single root HTML element. The problem is when the input HTML would already have a single root element, we would take the children of it anyway, and ignore the element itself. Example:
``` javascript
/*
Because there are multiple elements without an wrapping container, hast would
return an AST with the first node being `type: root` and the children being the elements:
{ type: 'root', children: [ { type: 'element', tagName: 'p' }, { type: 'element', tagName: 'p' } ]}
Only in this scenario should we take the children and the returning AST
*/
htmlToAst(`<p></p>  <p></p>`)
/*
In this case, because the HTML …
```

fix: test for root containers on hast to html

---

.changeset/unlucky-vans-study.md
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx

[FX-3088]
[TACO-1515]
- Change the error message of `PasswordInput` so it has the same phrasing as the error message of [the required validator](https://github.com/toptal/picasso/blob/master/packages/picasso-forms/src/utils/validators.ts#L15)
The change is approved by Matt Vella (designer of the BASE)
- Open https://picasso.toptal.net/taco-1515-fix-password-input/?path=/story/picasso-forms-form--form#field-requirements
- Enter "Password" in the password field and click outside
- You should see `Please enter a valid password.` instead of `Invalid password`
| ![image](https://user-images.githubusercontent.com/3861498/18959 …

chore(PasswordInput): update error message for invalid password

---

.changeset/tame-zebras-accept.md
packages/picasso/src/Tab/Tab.tsx
packages/picasso/src/Tab/__snapshots__/test.tsx.snap
packages/picasso/src/Tab/styles.ts
packages/picasso/src/Tabs/Tabs.tsx
packages/picasso/src/Tabs/__snapshots__/test.tsx.snap
packages/picasso/src/Tabs/story/Vertical.example.tsx
packages/picasso/src/Tabs/story/index.jsx
packages/picasso/src/Tabs/styles.ts
packages/picasso/src/Tabs/test.tsx

[TACO-1038]
This introduces the `orientation` prop on `Tabs`. This is already supported by MUI itself so I just had to expose it and style the varient.
I bounced this off BASE already - https://toptal-core.slack.com/archives/CCC3GP6CC/p1662703900679159
- Check the new vertical tabs example in storybook
- n/a ~~codemod is created and showcased in the changeset~~
- n/a ~~test alpha package of Picasso in StaffPortal~~
<details>
<br />
</details>
<details> …

feat(Tabs): introduce `orientation` prop

---

.changeset/lovely-forks-battle.md
packages/picasso/src/PasswordInput/PasswordInput.tsx

PasswordInput exposes confusing `startAdornment` and `endAdornment` props which are ignored.
Try using PasswordInput and you should not be able to pass adornments anymore
| <img width="637" alt="Screenshot 2022-09-14 at 16 42 07" src="https://user-images.githubusercontent.com/9164266/190186357-dd6e1d8e-3de0-43b3-b0c1-3a9af168b29b.png"> | <img width="608" alt="Screenshot 2022-09-14 at 16 41 53" src="https://user-images.githubusercontent.com/9164266/190186347-28a0c00e-8213-4d58-b66e-99efdc943596.png"> | 
> **GitHub Bot: …

chore: omit PasswordInput adornments

---

.changeset/green-shrimps-dream.md
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
yarn.lock

[FX-3097]
[TACO-1515]
When we remove the focus of the password input, the requirements get hidden after a small delay (500ms). If during this delay we focus the password input again we get in a wrong state, i.e. the password input is focused, but requirements are hidden.
1. Open https://picasso.toptal.net/?path=/story/picasso-forms-form--form#field-requirements
1. Click inside the password input field
1. Click on the label "Password". That will trigger a blur effect and a focus event right away
You will see that the input is focused but requirements are hidden. That's a bug.
https://user-images.githubusercontent.com/3861498/190341099-89555816-ec37-484a-b3b3-df2a1b979439.mp4
- Open https://picasso.toptal.net/fix-password-input-requirements/?path=/story/picasso-forms-form--form#field-require …

fix(PasswordInput): fix visibility of the password requirements

---

.changeset/silent-mugs-peel.md
packages/picasso/src/AvatarUpload/story/index.jsx

[no-jira]
Added source link to 
- Go to [this link](https://picasso.toptal.net/add-sourcelink-to-avatarupload/?path=/story/components-avatarupload--avatarupload) (Visit AvatarUpload component (if not opened))
- Click on the link named `Source link`
- **Check:** Link should redirect you to the component's source code.
- [N/A] test alpha package of Picasso in StaffPortal
> All **_development checks_** should be done …

chore(AvatarUpload): add sourcelink to AvatarUpload

---

.changeset/wet-beans-pump.md
packages/picasso/src/Tab/styles.ts
packages/picasso/src/Tabs/story/Vertical.example.tsx
packages/picasso/src/Tabs/styles.ts

[TACO-1038]
This PR fixes few visual issues related to the newly introduced (by me :see_no_evil: ) vertical tabs:
1. The active tab has no background and according to the design it should have `#FCFCFC`  https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=1413%3A15705
2. The labels are center aligned and they should be left aligned. This one wasn't obvious because my example was using the same label :unamused: Now the example is using different labels
3. The active tab shadow gets trimmed on the left side because the `Tabs` scrollable container has a `overflow-x: hidden`. I've added a :pinching_hand: of `padding-left`
- Use the example in storybook
| …

fix(Tabs): fix alignment, shadow, and background color for vertical tabs

---

.changeset/hip-yaks-move.md
packages/picasso/src/NonNativeSelect/test.tsx
packages/picasso/src/SelectBase/hooks/use-select-props/mocks.ts
packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/test.ts
packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/use-select-handler.ts
packages/picasso/src/SelectBase/hooks/use-select-state/use-select-state.ts
packages/picasso/src/SelectBase/types.ts

[no-jira]
A reported bug shows that the `Select` component changes its internal value even without changing the `value` prop from outside. This is the opposite of being a `controlled` component so I got rid of the internal value state.
- All stories of the `Select` component should be working as are. 
no visual change
- Ensure the …

fix(Select): remove internal value state

---

.changeset/empty-bulldogs-sneeze.md
packages/picasso/src/Dropzone/story/Multiple.example.tsx
packages/picasso/src/FileList/__snapshots__/test.tsx.snap
packages/picasso/src/FileListItem/FileListItem.tsx
packages/picasso/src/FileListItem/__snapshots__/test.tsx.snap
packages/picasso/src/FileListItem/styles.ts

[SPT-2973](https://toptal-core.atlassian.net/browse/SPT-2973)
Fix showing the file name inside the Dropzone when the file name is long.
Use TypographyOverflow instead of Typography.
- Navigate to https://picasso.toptal.net/SPT-2973-fix-showing-file-name-inside-dropzone/?path=/story/components-dropzone--dropzone#completed-multiple-files
- The long file name should contain ellipses.
| ![Screenshot 2022-09-23 at 10 18 49](https://user-images.githubusercontent.com/2583281/191910108-8af53ac3-bfe0-49e4-bef6-200c2562c6a1.png) | ![Screenshot 2022-09-23 at 10 15 22](https://user-images.githubusercontent.com/2583281/191910139-e71f …

fix: use `TypographyOverflow` to show file name inside `Dropzone`

---

.github/workflows/automerge-release.yaml

[FX-3025](https://toptal-core.atlassian.net/browse/FX-3025)
Non-major release PRs (only containing minor and patch changes) generated by changeset should be automatically merged.
- Checkout the testing branch of picasso `git checkout changeset-release/test-automerge` (the only [difference](https://github.com/toptal/picasso/commit/bfdca11c707476e5a65ae7c7511bfc344c84bd1e) from this PR is branch names to avoid testing on master)
- Push any change to the branch
- Create a pull request against `test/FX-3025-automerge-release` ([link](https://github.com/toptal/picasso/compare/test/FX-3025-automerge-release...changeset-release/test-automerge?expand=1))
- Test different PR body variations from existing Picasso changeset PRs ([minor/patch …

chore: automatically merge non-major changeset PRs

---

.changeset/rude-cameras-shake.md
packages/picasso/src/Dropzone/Dropzone.tsx
packages/picasso/src/Dropzone/test.tsx

[no-jira]
Added `hideContentText` property to the Dropzone to not put the default text in Dropzone
- Check out this branch
- Apply [this diff](https://github.com/toptal/picasso/files/9682102/story-to-test.txt) in your local
- Run storybook 
- Go to the storybook, `dropzone` component
- **Check:** The last example on the page doesn't have any content text. (See `Screenshots` sections.)
- [N/A] Create `examples` for property **(I didn't want to add this property to the examples, as it is not that much important. You can check the diff.)**
- [N/A] Ensure that deployed demo has expected results and good examples **(I didn't want to add this property to the examples, as it is not that much important. You can check the diff.)**
- [N/A] codemod is created and showcased in the …

chore: add parameter to remove content text of dropzone

---

.changeset/proud-bobcats-hunt.md
packages/picasso-forms/src/Field/Field.tsx
packages/picasso-forms/src/Switch/Switch.tsx
packages/picasso/src/Switch/Switch.tsx

[FX-3116]
There was a warning related to missing `Switch`'s field type in `picasso-forms`:
To fix that, I had to omit HTMLButtonElement's `type` prop for Switch. The reason for this is that TS was arguing about providing `type='checkbox'` to the Switch field because the `type` could be `button | submit | reset` which doesn't make any sense since MUISwitch underneath is still input and these values are not convenient for an input.
- checkout master locally and run storybook (warning only visible in dev environment)
- go to http://localhost:9001/?path=/story/picasso-forms-form--form
- click any Switch component and see the warning in console
- [no-need] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelin …

chore(Switch): add type for switch field

---

CONTRIBUTING.md

[no-jira]
I updated the `CONTRIBUTING.md` markdown file with updated info with respect to Davinci version of it here: https://github.com/toptal/davinci/pull/1602
- text review only
no visual change
- Create `examples` for …

fix: fix contributing markdown file

---

.changeset/nervous-goats-hunt.md
packages/picasso/src/Typography/Typography.tsx
packages/picasso/src/Typography/utils/get-typography-class-name/get-typography-class-name.ts

[FX-3151](https://toptal-core.atlassian.net/browse/FX-3151?atlOrigin=eyJpIjoiNDhlZDkyZTFlZDc5NGY0MjgxMWNiZTU2YjkxN2VlNTciLCJwIjoiaiJ9)
- `Italic` `Typography` does not inherit `font-weight` when placed inside `bold` `Typography`
- Visit [demo](https://picasso.toptal.net/fx-3151-typography-component-does-not-render-italic-bold-text-correctly/?path=/story/components-typography--typography#normal-text)
- Update example to:
```jsx
import { Typography } from '@toptal/picasso'
const Example = () => (
<div>
<Typography as='strong' weight='semibold'>
<Typography as='em'>Just text</Typography>
</Typography>
</div>
)
export default Example
```
- We should see **_Just text_** (bold + italic) in generated example
|                                  | …

fix: [FX-3151] bold and italic interaction in typography

---

.changeset/brave-hounds-travel.md
packages/picasso/src/ButtonAction/styles.ts

[FX-3126]
Unify font-weight of action button.
- compare [storybook examples](https://picasso.toptal.net/fx-3126-button-action-button/?path=/story/components-button--button#action-button-default) with [Figma](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=109%3A297)
- All usages of action button needs to have `font-weight: 600`
- Check changes in Happo
| ![image](https://user-images.githubusercontent.com/6830426/195335182-2fdd202c-2ef5-4b4c-b7c1-70cd981a6642.png) | ![image](https://user-images.githubusercontent.com/6830426/195335262-408ea382-bf45-46b2-ae2f-981cb3daf85c.png) |
> All …

style(ButtonAction): unify font-weight to semibold

---

.changeset/purple-hotels-behave.md
packages/picasso/src/Modal/Modal.tsx

[FX-3167]
This PR is about fixing `onBackdropClick` deprecation warning coming from MUI
- go to https://picasso.toptal.net/fx-3167-fix-onbackdropclick-warning/?path=/story/overlays-modal--modal#default
- provide `onBackdropClick` with a callback function
- click on the backdrop and check if there is a console error related to deprecation
no visual change
- Create …

fix(Modal): fix `onBackdropClick` deprecation warning

---

.changeset/breezy-singers-compare.md
cypress/component/Form.spec.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso/src/Checkbox/Checkbox.tsx

[FX-3175]
This PR is about fixing the types of `value` and `initialValue` props for `Form.CheckboxGroup`. It was `string` before while the actual value type was `string[]` and it wasn't possible to pass inline `initialValue` to the component.
- everything should work as expected before
- when you try to pass `value` or `initialValue` for a `Form.CheckboxGroup` component, you shouldn't see any type errors related to that.
- Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers …

fix(CheckboxGroup): fix value type for form usage

---

package.json
yarn.lock

[FX-NNNN]
Remove [vulnerability](https://github.com/toptal/picasso/security/dependabot/99) by updating `minimatch` to fixed version `3.0.5`.
We need to use resolutions to fix this issue since there are no updates for parent dependencies. Minimatch is widely used and we need to affect only specific repo.
| ![image](https://user-images.githubusercontent.com/6830426/197492960-9f166158-0756-491b-a8dc-89f80cc6a2dd.png) | ![image](https://user-images.githubusercontent.com/6830426/197492911-62f1be04-3f81-46b8-917c-29476f7c34af.png) | …

chore(deps): bump minimatch to fixed version

---

.changeset/slow-spies-refuse.md
packages/picasso/src/Menu/story/Default.example.tsx
packages/picasso/src/Menu/story/Multilevel.example.tsx
packages/picasso/src/MenuItem/MenuItem.tsx

[FX-3128]
Add new prop `icon` to `Menu.Item` to allow rendering any icon inside the Dropdown menu
- check [temploy](https://picasso.toptal.net/fx-3128-dropdown-with-icon/?path=/story/components-dropdown--dropdown#dropdown-menu) and compare with [design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=191%3A2806)
- check Happo changes
<details>
<br />
</details>
<details>
<br />
1. You have no extra …

feat(MenuItem): add new prop icon

---

.storybook/addons/anchor-link-handler/index.js

[FX-NNNN]
With storybook using react@18 in the latest version 6.5.x, rendering stories changed a little bit and our custom `scroll to anchor` functionality stopped working because the calculation of the scroll position was calculated before the all stories were rendered. We hack it with `setTimeout` to move the calculation to the later tick.
- check fixed [anchor](https://picasso.toptal.net/fix-anchor/?path=/story/components-dropdown--dropdown#custom-anchor)
<details>
<br />
</details>
<details> …

chore: fix scroll to anchor in storybook

---

.changeset/old-pandas-tie.md
packages/picasso/src/Dropzone/Dropzone.tsx
packages/picasso/src/Dropzone/story/Error.example.tsx
packages/picasso/src/Dropzone/story/Uploader.example.tsx
packages/picasso/src/Dropzone/test.tsx

[FX-3177](https://toptal-core.atlassian.net/browse/FX-3177?atlOrigin=eyJpIjoiNmMzNDcwZjVmMDdhNDkwMmIyNjkyNjlhODJlZTllNTYiLCJwIjoiaiJ9)
- In **BASE** we have a different design of failed upload than we have implemented in Picasso.
- `Dropzone`'s [Upload Failed example](https://picasso.toptal.net/fx-3177-dropzone-error-state/?path=/story/components-dropzone--dropzone#upload-failed) should be complied with the one in BASE design
- also: ![Screenshot from 2022-10-28 10-12-40](https://user-images.githubusercontent.com/72510037/198516121-6ea2aaca-69e8-46c2-bdd4-abb703672200.png), error will be shown this way, from now on, because we are deprecating `errorMessages` (I've commented below why)
| …

chore: comply dropzone with base design

---

.changeset/slimy-weeks-film.md
packages/picasso-forms/package.json
packages/picasso-forms/src/Form/story/AutoSave.example.tsx
packages/picasso-forms/src/index.ts
packages/picasso-forms/src/utils/form-values-change-decorator/form-values-change-decorator.ts
packages/picasso-forms/src/utils/form-values-change-decorator/index.ts
packages/picasso-forms/src/utils/index.ts
packages/picasso-forms/src/utils/use-form-auto-save/index.ts
packages/picasso-forms/src/utils/use-form-auto-save/use-form-auto-save.ts

[FX-3208]
This PR is about adding a new hook for utilizing the changed form values and hiding the part of the creation of form values change decorator.
I have just printed a `Saving` message for now but there will be a followup PR for introducing a new component for better UX.
https://user-images.githubusercontent.com/7733167/200324319-de8026d6-4e97-4c32-8aeb-1e6f77fc4cf4.mov
- go to Form component's [auto-save story](https://picasso.toptal.net/fx-3208-add-auto-save-hook/?path=/story/picasso-forms-form--form#auto-save) and test the hook
- Make sure that additions and …

feat(AutoSave): add form auto-save hook

---

yarn.lock

[FX-NNNN]
bump v2 of loader-utils to fix https://github.com/toptal/picasso/security/dependabot/101
<details>
<br />
</details>
<details>
<br /> …

chore(deps): bump loader-utils to fix critical vulnerability

---

package.json
yarn.lock

[FX-NNNN]
`recursive-readdir` have new patch that bumps `minimatch` to the fixed version, so we don't need in resolutions anymore 🎉 
- CI is green
<details>
<br />
</details>
<details>
<br /> …

chore(deps): bump and remove recursive-readdir from resolutions

---

package.json

[no-jira]
This PR is about unblocking happo reports on master branch and removing `run` from the `happo` command to enable using `compare` like `yarn happo compare <sha1> <sha2>`
- CI should be green except happo reports

chore: remove run from happo command

---

.changeset/great-boxes-design.md
packages/picasso-forms/src/Form/story/AutoSave.example.tsx
packages/picasso/src/FormAutoSaveIndicator/FormAutoSaveIndicator.tsx
packages/picasso/src/FormAutoSaveIndicator/index.ts
packages/picasso/src/FormAutoSaveIndicator/styles.ts
packages/picasso/src/FormAutoSaveIndicator/test.tsx
packages/picasso/src/index.ts

[FX-3209]
This PR is about adding an indicator component for auto-save functionality.
I'm totally up for different opinions and refactoring 🙇‍♂️ 
- go to [auto-save story](https://picasso.toptal.net/fx-3209-add-autosave-indicator/?path=/story/picasso-forms-form--form#auto-save) and test the component 
https://user-images.githubusercontent.com/7733167/200835695-156b2437-f361-4a54-aced-2b4395b72287.mov
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/access …

feat(AutoSave): add indicator component

---

.github/workflows/danger.yaml
.github/workflows/pr.yaml

This change was [introduced in davinci](https://github.com/toptal/davinci/pull/1669) some time back, its time to move it [also to picasso](https://github.com/toptal/davinci/pull/1669#pullrequestreview-1144088998)
> Sometimes you generate your PR with incorrect title. But because Danger was until now part of PR checks workflow, which runs only when PR new changes are pushed into the PR, changing the title wouldn't resolve the danger failure.
This PR yanks the danger job into separate PR that runs even when PR is edited.
- You can try to edit title of this PR
- Make sure that additions and changes on design follow [Toptal's BASE …

chore: run danger check when PR title changes

---

.changeset/rotten-shrimps-do.md
cypress/component/Tooltip.spec.tsx
packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx
packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
packages/picasso/src/Tooltip/__snapshots__/test.tsx.snap

[FX-3257]
When dialog based components are used on the first-render of a page they may not be correctly placed inside PicassoRoot. This is because on the first render the PicassoRoot element ref is not set, it is only set after mounted. This PR adds a guard to PicassoProvider to only render anything after the PicassoRoot element is mounted in HTML.
**About the Visual tests Failing**
As it looks like, some of the visual tests components were mounted outside PicassoRoot, consequently without the PicassoRoot styles. This is why Happo is failing some of the tests. Some fonts were wrong before and now follow the correct Picasso definitions
- You can check [this sandbox](https://codesandbox.io/s/competent-bash-ub7lup?file=/src/Page.tsx) when you click on the datepicker it correctly shows up on …

fix: add guard for picasso root not mounted

---

.changeset/warm-berries-sleep.md
packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
packages/picasso-provider/src/Picasso/NotificationsProvider/index.ts
packages/picasso-provider/src/Picasso/NotificationsProvider/test.tsx
packages/picasso-provider/src/Picasso/index.ts
packages/picasso-provider/src/index.ts
packages/picasso/src/utils/Notifications/story/CustomPosition.example.tsx
packages/picasso/src/utils/Notifications/story/MaxNotifications.example.tsx
packages/picasso/src/utils/Notifications/story/index.jsx

[TDESKAPP-967]
Expose `maxSnack` from internal `SnackbarProvider` as `maxNotifications`.
More details https://toptal-core.slack.com/archives/CERF5NHT3/p1668017294156079.
- run `yarn start`
- got to http://localhost:9001/?path=/story/components-notificationsprovider--notificationsprovider
|  | ![image](https://user-images.githubusercontent.com/3688905/202464782-7a9e0ea5-0e47-4f0b-978a-84315a09d728.png) |
<details>
<br />
- `@toptal-bot …

feat(NotificationsProvider): provide maxNotifications props

---

.changeset/good-carpets-change.md
cypress/component/Tabs.spec.tsx
packages/picasso/src/Tab/Tab.tsx
packages/picasso/src/Tab/story/Vertical.example.tsx
packages/picasso/src/Tab/story/index.jsx
packages/picasso/src/Tab/styles.ts
packages/picasso/src/TabDescription/TabDescription.tsx
packages/picasso/src/TabDescription/index.ts
packages/picasso/src/TabDescription/styles.ts
packages/picasso/src/TabLabel/TabLabel.tsx
packages/picasso/src/TabLabel/index.ts
packages/picasso/src/Tabs/__snapshots__/test.tsx.snap
packages/picasso/src/Tabs/story/Vertical.example.tsx
packages/picasso/src/Tabs/story/index.jsx
packages/picasso/src/Tabs/styles.ts
packages/picasso/src/utils/index.ts

[FX-3140]
- enhance `Tabs.Tab` with `description` and `avatar` as we agreed in [the RFC](https://github.com/toptal/picasso/blob/master/docs/decisions/12-vertical-tabs.md)
- update styles to comply with [BASE](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=238%3A10918&t=9yzEloERLafMAVal-0)
- showcase all possible states [in the storybook](https://picasso.toptal.net/fx-3220-vertical-tab-item/?path=/story/layout-tabs--tabs#tabs-tab-vertical-tab)
- showcase possible real usage example [in the storybook](https://picasso.toptal.net/fx-3220-vertical-tab-item/?path=/story/layout-tabs--tabs#vertical) (It is just an example, it will not be in BASE)
- I tried to use atomic commits, if you find the PR too big, try to review commit by commit 🙇 
- compare examples in the …

feat(TabItem): add `description` and `image`

---

.changeset/tasty-snails-prove.md
packages/picasso/src/PageSidebar/PageSidebar.tsx
packages/picasso/src/PageSidebar/__snapshots__/test.tsx.snap
packages/picasso/src/PageSidebar/story/Size.example.tsx
packages/picasso/src/PageSidebar/story/index.jsx
packages/picasso/src/PageSidebar/styles.ts
packages/picasso/src/SidebarItem/__snapshots__/test.tsx.snap

[FX-3279]
- [Figma](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=408%3A15410&t=WvXC7OMI8HNnEpAF-0)
When working on the task I noticed, that we don't follow the BASE width of the Sidebar, so I have created a new prop `size`. By default `medium` has the same size as it had before, so there is no breaking change.
- check t[he temploy](https://picasso.toptal.net/sidebar-size/?path=/story/components-pagesidebar--pagesidebar#sizes)
<details>
<br />
</details>
<details> …

feat: add `size` prop to Sidebar

---

.changeset/rude-schools-drum.md
packages/picasso/src/TimelineRow/styles.ts

[FX-3281](https://toptal-core.atlassian.net/browse/FX-3281)
Added `flex-grow: 1` to the row content so it can fit the entire container width
- Code looks good, you can't see the possibility of something being broken
- Use the code snippet to test in deployed storybook and on current [Picasso master](https://picasso.toptal.net/?path=/story/components-timeline--timeline). [Deployed storybook](https://picasso.toptal.net/fx-3281-timeline-row-does-not-allow-the-content-to-be-expanded-to-full-width/?path=/story/components-timeline--timeline) should have the button all the way to the left, content taking up the entire width of the container.
<details>
<summary>Code example</summary>
```javascript
import React from "react";
import {
Grid,
Timeline,
Typography,
Link,
Container,
Button
} from …
```

fix(TimelineRow): add flex-grow

---

.changeset/proud-terms-poke.md
packages/picasso/src/Dropdown/Dropdown.tsx
packages/picasso/src/PageHamburger/PageHamburger.tsx
packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap

Previously hamburger content had a `role="tooltip"` attribute (default for Popper component). 
Since picasso `v28.11.0` the hamburger content is always present in the DOM via `keepMounted` prop, and that causes failings in cucumber tests for SP.
This PR change introduce `popperOption` property through which we can adjust the role to `navigation`.
- check the code/temploy page 
> All **_development …

fix: change role from  to  for hamburger

---

.changeset/few-wasps-sip.md
cypress/component/PageSidebar.spec.tsx
packages/picasso/src/MenuItem/styles.ts
packages/picasso/src/SidebarItem/ParentItemContextProvider.tsx
packages/picasso/src/SidebarItem/SidebarItemAccordion.tsx
packages/picasso/src/SidebarItem/SidebarItemCompact.tsx
packages/picasso/src/SidebarItem/SidebarItemHeader.tsx
packages/picasso/src/SidebarItem/__snapshots__/test.tsx.snap
packages/picasso/src/SidebarItem/story/WithBadgeAndTag.example.tsx
packages/picasso/src/SidebarItem/story/index.jsx
packages/picasso/src/SidebarItem/styles.ts
packages/picasso/src/SidebarItem/types.ts
packages/picasso/src/SidebarItem/utils/getBadgeProps/getBadgeProps.ts
packages/picasso/src/SidebarItem/utils/getBadgeProps/test.ts
packages/picasso/src/SidebarItem/utils/getTagProps/getTagProps.ts
packages/picasso/src/SidebarItem/utils/getTagProps/test.ts
packages/picasso/src/SidebarItemContent/SidebarItemContent.tsx
packages/picasso/src/SidebarItemContent/index.ts
packages/picasso/src/SidebarItemContent/styles.ts
packages/picasso/src/SidebarItemContent/types.ts
packages/picasso/src/SidebarItemContent/useIndicatorOnParentItem.ts
packages/picasso/src/TagRectangular/TagRectangular.tsx
packages/picasso/src/TagRectangular/index.ts
packages/picasso/src/TagRectangular/test.tsx
packages/picasso/src/TagRectangular/types.ts

[FX-3279]
I have extracted some commits to different PRs
- https://github.com/toptal/picasso/pull/3257
- https://github.com/toptal/picasso/pull/3258
- [Design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=7071%3A20020&t=VkUIbNxY0CxmMmjY-0)
- We were discussing a lot this ticket with Matt, there might be still some inconsistencies in the Design since he is still working on it.
- 🔴 indicator should be visible for both variants of the sidebar only on closed parent items when children have a tag or badge
- badge and tag are aligned to the right
- parent item will not display the badge or tag
- long text should be overflowed by ellipsis
- collapsed sidebar's items (when only icon is visible) will not display tag
- ⚠️ PR has quite a lot of changes, please try to …

feat(SidebarItem): add `tag` prop

---

.changeset/tall-eagles-joke.md
packages/picasso/src/Input/Input.tsx
packages/picasso/src/Input/__snapshots__/test.tsx.snap
packages/picasso/src/Input/story/Status.example.tsx

This is a fix for multiline input with counter and success state. 
- Check added temploy example of multiline input with success state and counter
<details>
<br />
</details>
<details>
<br />
2. You …

fix: success state for multiline input with counter

---

.github/workflows/pr.yaml

[FX-NNNN]
I think, that might be useful to have static checks in one workflow job and storybook visual tests in a separate job, so if in the future some flaky visual test appears in the Happo, we can simply rerun the Happo part and we don't have to run all the static analysis for no reason.
- [n/a] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [n/a] Ensure that …

ci: move storybook visual tests to separate step

---

packages/picasso/src/StaticTreeView/story/index.jsx

[FX-3287]
We have a flaky test of StaticTreeView. Happo has [internal function](https://github.com/Galooshi/happo/pull/163/files#diff-1f258a895efc2f2440ec95bbe515ea54713a7f2363d78a380f15b4bc8b94fb72) to wait for images to load before taking a screenshot, but in our case we don't have simple `img`, but we have `svg>g>image`, so I copied the function from happo and adjusted to our needs, I believe that this function is useful only for this example, therefore I didn't move it util functions
- The flake test should not appear, it is hard to test.
N/A
- [n/a] Make sure that additions and changes on design follow [Toptal's BASE …

test: fix flaky test of StaticTreeView

---

.changeset/weak-radios-clap.md
packages/picasso/src/Input/__snapshots__/test.tsx.snap
packages/picasso/src/InputLimitAdornment/InputLimitAdornment.tsx
packages/picasso/src/InputLimitAdornment/test.tsx

[TACO-2080]
Translating the page with google translate breaks the limit text. This PR aims to improve this.
Check https://toptal-core.slack.com/archives/CERF5NHT3/p1670406303204869 for details
Check https://toptal-core.slack.com/archives/CERF5NHT3/p1670406303204869 for videos on how to reproduce behaviour 
Before
https://user-images.githubusercontent.com/4757057/206159171-f856c1ff-2c2b-4c05-a563-67e04dec2074.mp4
After
https://user-images.githubusercontent.com/4757057/206159239-d9887a74-bb89-4394-a4f5-079284e70b5c.mp4
- n/a ~~Annotate all `props` in component with documentation~~
- n/a ~~Create `examples` for component~~
- n/a ~~codemod is created and showcased in the changeset~~
- n/a ~~test alpha package of Picasso in StaffPortal~~
> All **_development checks_** …

fix(InputLimitAdornment): handle google translate better

---

.changeset/sharp-wolves-learn.md
packages/picasso-forms/src/Field/Field.tsx
packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx

Pass `setHasMultilineCounter` mutator to only those form components that need it.
Previously, `Field` component passed this function to every form element and it propagated into dom via `...rest`.
With this change, mutator is passed only to `Input` and `RichTextEditor` components.
- go to Picasso Forms page and search for error `setHasMultilineCounter`
| ![image](https://user-images.githubusercontent.com/22159416/206543259-b147fa75-7b1e-4232-a455-98bb2d601bba.png) | ![image](https://user-images.githubusercontent.com/22159416/206543132-c8735075-f6d4-414e-ae67-f742bc581f03.png) |
- Make sure that additions and changes on …

fix: target form mutator for components with multiline counter

---

.changeset/afraid-queens-drive.md
cypress/component/Page.spec.tsx
packages/picasso/src/Page/story/WithBannerAndSidebar.example.tsx
packages/picasso/src/Page/story/index.jsx
packages/picasso/src/PageSidebar/PageSidebar.tsx
packages/picasso/src/PageSidebar/__snapshots__/test.tsx.snap
packages/picasso/src/PageSidebar/styles.ts
packages/picasso/src/PageTopBar/styles.ts
packages/picasso/src/SidebarItem/__snapshots__/test.tsx.snap
packages/picasso/src/SidebarLogo/styles.ts

[FX-3290]
Sidebar sticks to TopBar on scroll. Also the Sidebar has set a max height and is scrollable, if needed.
This functionality can be disabled with `sticky` property.
UPDATE: with Matt we decided to hide scrollbar on collapsed sidebar. But adding shadows on top&bottom like its in ModalContent proved problematic, since the scrollable content has set width and height, and the shadows should stretch to the edge of sidebar. We decided to leave it as it is. If you have an idea how to tackle it better, please share in comments or DM me 🙇 
- Check out the [sticky example in temploy](https://picasso.toptal.net/fx-3290-sidebar-scrollable-sidebar/?path=/story/layout-page--page#with-banner-and-sidebar)
https://user-images.githubusercontent.com/22159416/206434319-61bb6a38-835c-495e-9a22-4250abad …

feat(PageSidebar): make sidebar sticky

---

.gitignore

No ticket.
Ignore cypress screenshots folder. Just a small annoying thing that needed a small fix.
For me, Cypress took a screenshot when execution failed during a before hook.
You can make something fail, and generate the screenshots folder. See it's ignored.
However, I think it's overkill. :smile: 
Just check the .gitignore file. It's trivial.
Proof that the folder is ignored.
- [] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- [] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [] Annotate all `props` in component with documentation
- [] Create `examples` for component
- …

fix: ignore cypress generated files

---

.changeset/shy-pets-accept.md
.changeset/two-lamps-jam.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/test.tsx
packages/picasso/src/Autocomplete/use-autocomplete/use-autocomplete.ts
packages/shared/src/utils/index.ts
packages/shared/src/utils/is-forward-ref.ts

[FX-3119]
Currently, when clicking on [Autocomplete adornments](https://picasso.toptal.net/?path=/story/forms-autocomplete--autocomplete#with-adornments), the Input does not focus, leading to opened Select that does not close when clicking outside of Autocomplete. This bug also appears in TagSelector, where values (Tags) are displayed as adornments. 
There are two ways to handle this issue:
**1. Do not open Select when clicking on adornments**
This has a drawback for TagSelector, because values can take up most of the space in Autocomplete, leaving the Input that opens the Select hard to click on. It also reduces UX
**2. Trigger focus on Input when Select is open**
This requires having a reference to Input. Possible drawback is when user defines a reference to Autocomplete as a function - …

fix(Autocomplete): focus input after clicking on adornment

---

.storybook/stories/tutorials/form-components/story/Components.1.example.tsx
.storybook/stories/tutorials/form-components/story/Components.2.example.tsx
.storybook/stories/tutorials/form-components/story/Components.3.example.tsx
.storybook/stories/tutorials/form-components/story/index.jsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso/src/Form/story/index.jsx

[FX-3424](https://toptal-core.atlassian.net/browse/FX-3424)
Adds a documentation clearing out the key difference between `Form` Picasso and Picasso Forms
- Take a look at the new page on the [temploy](https://picasso.toptal.net/fx-3424-create-documentation-on-picasso-forms/?path=/story/tutorials-difference-between-picasso-forms-and-base-form-components--difference-between-picasso-forms-and-base-form-components) and see if it's missing something. 
- [n/a] Add changeset according to …

chore(docs): add form difference documentation

---

.changeset/nice-donuts-check.md
packages/picasso/src/Drawer/Drawer.tsx
packages/picasso/src/Drawer/story/WithBodyScrollLock.example.tsx
packages/picasso/src/Drawer/story/index.jsx
packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/utils/Modal/modal-manager.ts
packages/picasso/src/utils/__tests__/use-body-scroll-lock.test.tsx
packages/picasso/src/utils/use-body-scroll-lock.ts

[TOP-2735]
Decoupled body scroll management logic from ModalManager class to make it independent from modals and reusable. Added a prop to Drawer that allows to opt-in for body scroll lock enabled mode. 
- Ensure modals lock body scrolling just like they would do it previously
- Ensure drawers lock body scrolling when rendered with `maintainBodyScrollLock=true`
- ~test alpha package of Picasso in StaffPortal~
<details>
<br /> …

feat(Drawer): add body scroll lock

---

.changeset/pink-experts-cheat.md
packages/picasso/src/PageSidebar/PageSidebar.tsx
packages/picasso/src/PageSidebar/story/Collapsible.example.tsx

[TRN-4574]
On Talent Portal we're working on removing an option for collapsing the sidebar from our settings page and we want to keep only built-in collapse option of Sidebar but we want to keep an ability to store the state or sidebar talent choose on our Backend so we can retain it on next visit and display sidebar at same state your left in on previous visit.
For that purpose, we're introducing `onCollapse` callback which will allow us to trigger our API each time collapse button in Sidebar is clicked.
- `Collapsible` story is modified to trigger `onCollapse` callback, check the temploy
<details>
<br />
List of available …

chore(Sidebar): introduce `onCollapse` callback

---

.changeset/forty-snails-compete.md
packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/Modal/story/DisableBackdropClick.example.tsx
packages/picasso/src/Modal/story/index.jsx

[no-jira]
According to the [discussions](https://toptal-core.slack.com/archives/CERF5NHT3/p1673903476781539), it is decided to add functionality to the backdrop to trigger onClose when clicked.
With this update (inspired by MUIv5 Dialog component [updates](https://mui.com/material-ui/migration/v5-component-changes/#%E2%9C%85-remove-disablebackdropclick-prop)), onClose callback will be triggered with closing reason so anyone can decide to let Modal stay even after backdrop clicked.
- according to discussions in the PR, codemod can be considered to remove `onBackdropClick` prop usage.
- I have added a new story, check temploy
- no visual updates
- [N/A] Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed …

chore(Modal): remove onBackdropClick and update onClose

---

.changeset/flat-beans-kick.md
packages/picasso/src/QuillEditor/QuillEditor.tsx
packages/picasso/src/QuillEditor/hooks/useDisabledEditor/test.ts
packages/picasso/src/RichTextEditor/story/Disabled.example.tsx

[FX-3572](https://toptal-core.atlassian.net/browse/FX-3572)
`RichTextEditor` when is disabled the default value appear  for this ticket: [SCX-555](https://toptal-core.atlassian.net/browse/SCX-555)
|![image](https://user-images.githubusercontent.com/25435884/213496906-b5b4c3ad-4309-45a2-96b4-a7362cdef288.png)|![image](https://user-images.githubusercontent.com/25435884/213497035-00183abe-690a-4f08-8f5a-19c8b8fa5219.png)|
<details>
<br /> …

fix(RichTextEditor): when disabled it shows defaultValue

---

.changeset/neat-pianos-allow.md
packages/picasso/src/PageTopBar/story/Variants.example.tsx
packages/picasso/src/PageTopBarMenu/PageTopBarMenu.tsx
packages/picasso/src/PageTopBarMenu/styles.ts

[FX-3494]
Long time ago, a [customization to Avatar in PageTopBarMenu](https://github.com/toptal/picasso/pull/1955) was made to comply with talent portal needs.
Since then, [Avatar was refactored](https://github.com/toptal/picasso/pull/2202) and this change caused specific error that can be reproduced when using small screen and avatar without image.
The customization is no longer needed, since the AvatarWrapper has correct dimensions set.
- Check [temploy PageSideBar](https://picasso.toptal.net/fx-3494-avatar-variant-with-initials-is-broken-on-smaller-screen/?path=/story/components-pagetopbar--pagetopbar#variants) and resize to smaller screen
| --------------------------------------- | …

fix(PageTopBarMenu): initials in Avatar are centered on small screen

---

.changeset/pretty-suits-beg.md
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/__snapshots__/test.tsx.snap

[FX-2222]
A typo that prevents users to use `getByTestId`
- n/a Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- n/a test alpha package of Picasso in …

fix(Autocomplete): use currect data-testid

---

.changeset/ninety-scissors-cheat.md
packages/picasso/src/Autocomplete/Autocomplete.tsx

[FX-2223]
Pass `data-testid` only when it is available
- check the code
- n/a Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- n/a Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

fix(Autocomplete): pass data-testid to Menu.Item only when available

---

cypress/component/Menu.spec.tsx

[FX-NNNN]
We have a flaky cypress test for the menu. We are checking that menu is closed right after mounting, it seems that in some rare cases, the menu is opened, so I have added an additional div where I put the mouse on the start of the test so I'm sure that we don't have a mouse over the menu (It opens on hover)
<details>
<br />
</details>
<details>
<br />
1. You have no extra …

test: remove flaky test

---

.changeset/brown-phones-worry.md
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/NonNativeSelect/test.tsx
packages/picasso/src/Select/story/FilterOptions.example.tsx
packages/picasso/src/Select/story/index.jsx
packages/picasso/src/SelectBase/hooks/use-select-state/use-select-state.ts
packages/picasso/src/SelectBase/types.ts
packages/picasso/src/SelectBase/utils/filter-options/filter-options.ts
packages/picasso/src/SelectBase/utils/filter-options/index.ts
packages/picasso/src/SelectBase/utils/index.ts

[no-jira]
This PR is about adding a new `filterOptions` prop to Select component to enable custom filtering for options.
- go to Select component storybook page and test both existing and new story
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: …

feat(Select): introduce new filterOptions prop

---

.changeset/small-dolls-jam.md
packages/picasso/src/Tabs/Tabs.tsx
packages/picasso/src/Tabs/__snapshots__/test.tsx.snap
packages/picasso/src/Tabs/story/FullWidth.example.tsx
packages/picasso/src/Tabs/story/index.jsx
packages/picasso/src/Tabs/test.tsx

[TDESKAPP-1215](https://toptal-core.atlassian.net/browse/TDESKAPP-1215)
In this PR we're adding support for `variant` prop in `Tabs` component (supported by `material-ui/core` under the hood).
It maintains backward-compatibility [here](https://github.com/toptal/picasso/pull/3378/files#diff-0350b1564ab53d9d068e1eb2fa36cf3abdbbafd74d0e05b4a3cc69d007ffc837R47).
This topic was discussed [here](https://toptal-core.slack.com/archives/CERF5NHT3/p1674754770715829).
- See Tabs new story
- Review code and provide any feedback
| <img width="1792" alt="image" src="https://user-images.githubusercontent.com/1213542/218568191-00b56d12- …

feat(Tabs): add variant prop

---

.changeset/afraid-clocks-shave.md
packages/picasso/src/Calendar/Calendar.tsx
packages/picasso/src/Calendar/styles.ts

[SDE-842](https://toptal-core.atlassian.net/browse/SDE-842)
Adds `disabled` attribute to disabled days in Calendar, along with the default cursor instead of the pointer
- Go to the Calendar component with disabled days, the day button should have the attribute `disabled` and the cursor should be `default` instead of `pointer`
|![image](https://user-images.githubusercontent.com/17644982/218646647-8165ede1-d4d3-4bb1-9093-90870af45256.png)|![image](https://user-images.githubusercontent.com/17644982/218646698-f85b7bf4-d2bd-4580-a073-29a3719d670b.png)|
> All **_development checks_** should be done and set …

fix(calendar): add disabled attribute & default cursor to disabled days

---

.changeset/twelve-shrimps-obey.md
packages/picasso/src/Tabs/Tabs.tsx
packages/picasso/src/Tabs/test.tsx

[TDESKAPP-1168]
Tabs have wrong typings on their `onChange` handler. The `value` returned equals the `value` given when creating a Tab, so if you do not use `index` values, it does not return a `number` type.
- Create Tabs with custom values
- trigger the `onChange` handler
- notice that the second value in the callback is not of type `number` (not an index)
I also created a test that mimicks this behavior to make it clear what is happening.
<details>
<br />
</details>
<details> …

fix: typings for Tabs onChange callback

---

.changeset/nervous-chicken-trade.md
packages/picasso/src/ShowMore/ShowMore.tsx
packages/picasso/src/ShowMore/story/OnToggle.example.tsx
packages/picasso/src/ShowMore/story/index.jsx
packages/picasso/src/ShowMore/test.tsx

[FX-3724]
We had [a discussion](https://toptal-core.slack.com/archives/CERF5NHT3/p1676299119242719) in Slack about users who would like to have information about the current state of the ShowMore component in `onToggle` callback
- check updated unit tests
- play with the storybook
n/a
- n/a Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
<details>
<br />
</details> …

feat(ShowMore): pass new state to the `onToggle` callback

---

.changeset/three-spiders-sit.md
packages/picasso/src/Calendar/Calendar.tsx

[SDE-897]
This is a revert from #3379 because I wasn't able to add tooltips for calendar days with the disabled attribute, even wrapping the component with a `<span>`, as mentioned in [Tooltip on disabled element section](https://picasso.toptal.net/?path=/story/overlays-tooltip--tooltip).
<details>
<br />
List of …

fix(datepicker): revert calendar disabled attribute to allow render tooltips

---

.changeset/happy-humans-repair.md
packages/picasso/src/Calendar/Calendar.tsx
packages/picasso/src/Calendar/__snapshots__/test.tsx.snap
packages/picasso/src/Calendar/styles.ts

[FX-2885]
BASE updated [design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=1941%3A15847&t=lnPVM0FD5VVXHlN5-0) of Calendar. We need to highlight weekends. Also, I found out that we were having some discrepancies between BASE and Picasso so also fixed these small issues.
- Compare [the storybook](https://picasso.toptal.net/fx-2885-calendar/?path=/story/components-datepicker--datepicker) example with [BASE design](https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=1941%3A15847&t=lnPVM0FD5VVXHlN5-0)
- Check new screenshots in Happo
| …

style(Calendar): highlight weekends

---

ci/jobs/build-image/Jenkinsfile

As discussed in https://toptal-core.slack.com/archives/GUR3Y9J69/p1679473077788469, the timeout needs to be increased.
- Timeout increase
-  …

fix: increase timeout for build-image

---

.changeset/neat-icons-end.md
packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx

[FX-3819]
RichText should use the same font-size as RichTextEditor, 14px. 
- check [the storybook](https://picasso.toptal.net/fx-3819-rte-font-size/?path=/story/components-richtext--richtext)
- `n/a` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- `n/a` Create `examples` for component
- `n/a` codemod is created and showcased in the changeset
- `n/a` test alpha package of Picasso in StaffPortal
<details>
<br />
List of …

style(RichText): update font-size

---

.changeset/calm-kiwis-taste.md
packages/picasso-provider/src/Picasso/Picasso.tsx

[FX-3823]
Picasso + Next.js has a significant issue.
The initial load of Picasso components on a page is fine. 
But when we walk across pages, the same page with the same components becames broken in context of styles.
It happens, because of broken counter in `StylesProvider`. the `StylesProvider` uses `generateClassName` function that generate class name for each component and increases the counter after class name generation.
`generateClassName` function is created via `createGenerateClassName`. It happens inside a `Picasso` component.
For some reason, after switching a page, the `createGenerateClassName` is called again, therefore the counter is becoming 0 again.
- Use https://github.com/toptal/next-and-picasso-isuue branch
- Add an alpha version of picasso-provider
- Repeat the pages …

fix: [FX-3823] class names creator in Picasso

---

.changeset/swift-pears-sleep.md
cypress/component/InputHiglightAutofill.spec.tsx
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/Input/Input.tsx
packages/picasso/src/Input/styles.ts
packages/picasso/src/InputBase/highlightStyles.ts
packages/picasso/src/NativeSelect/NativeSelect.tsx
packages/picasso/src/NativeSelect/styles.ts
packages/picasso/src/NonNativeSelect/NonNativeSelect.tsx
packages/picasso/src/NonNativeSelect/styles.ts
packages/picasso/src/NumberInput/NumberInput.tsx
packages/picasso/src/NumberInput/styles.ts
packages/picasso/src/PasswordInput/PasswordInput.tsx
packages/picasso/src/PasswordInput/styles.ts
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/styles.ts
packages/picasso/src/SelectBase/types.ts
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelectorInput/TagSelectorInput.tsx
packages/picasso/src/TagSelectorInput/styles.ts
packages/picasso/src/TimePicker/TimePicker.tsx

[FX-3780]
@OleksandrNechai had a good point, that basic Picasso input components should not need to know anything about why they are highlighted. So before we release the main update in [Picasso forms](https://github.com/toptal/picasso/pull/3444), we want to update the name `highlightAutofill` 👉 `highlight` for better design
`N/A`
- `N/A` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- `N/A` Ensure that deployed demo has expected results and good examples
- `N/A` Ensure the changed/created components have not caused …

chore: rename highlightAutofill to highlight

---

.changeset/hot-ligers-invent.md
.changeset/many-spies-share.md
packages/picasso-forms/package.json
packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
packages/picasso-forms/src/ButtonCheckbox/ButtonCheckbox.tsx
packages/picasso-forms/src/Checkbox/Checkbox.tsx
packages/picasso-forms/src/Dropzone/Dropzone.tsx
packages/picasso-forms/src/Field/Field.tsx
packages/picasso-forms/src/FileInput/FileInput.tsx
packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso-forms/src/FormConfig/FormConfig.ts
packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
packages/picasso-forms/src/Rating/Rating.tsx
packages/picasso-forms/src/Switch/Switch.tsx
packages/picasso/src/DatePicker/DatePicker.tsx

[FX-3780]
This is a follow-up to https://github.com/toptal/picasso/pull/3439. In this PR we introduce `highlightAutofill` on final-form level. Users can enable this feature in form config.
- check [the new example](https://picasso.toptal.net/fx-3780-highligh-autofill/?path=/story/picasso-forms-form--form#highlight-autofill) in storybook
- `N/A` codemod is created and showcased in the changeset
- `N/A` test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details> …

feat(Forms): add `highlightAutofill` functionality

---

.changeset/changelog.config.js
.changeset/config.json
package.json
yarn.lock

[FX-2779](https://toptal-core.atlassian.net/browse/FX-2779)
Updated changeset to use the custom changeset formatter to properly handle newlines in the changelog.
There is no good way to test this, however, there are some steps to verify the changes:
- Take a look at the code
- Go to https://github.com/mkrl/changesets/commit/432e788243e37f120c396b0cb508594ea97da6a2 - this is a fork of changeset repo with the desired function updated
- Take a look at the changes made for the accurate comparison
- Run ` y test packages/changelog-github/src/index.test.ts`, you can play around with different changeset formats in the `getPicassoStyleChangeset` function
After merging, we should no longer see `---` in the changelog + lint rule for having extra line in the changelog can be disabled.
| Before. …

chore(ci): update changeset config to handle new lines

---

packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx

[FX-NNNN]
We have flaky test, because of `new Date()`
- `N/A` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `N/A` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- `N/A` Make sure that additions and changes on design follow [Toptal's BASE …

fix: set static date for visual tests

---

.changeset/sweet-emus-punch.md
cypress/component/RichTextEditor.spec.tsx
packages/picasso/src/QuillEditor/hooks/useDefaultValue/test.ts
packages/picasso/src/QuillEditor/hooks/useDefaultValue/useDefaultValue.tsx
packages/picasso/src/QuillEditor/hooks/useDisabledEditor/test.ts
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/getEditorChangeHandler.tsx

[FX-2895]
Bug fix
**Steps to reproduce:**
- write “test bold” into the RichTextEditor
- bold icon in the toolbar is active
- manually remove the “bold” text
- write “this should not be bold”
**expected:**
- text is not bold
- bold button in toolbar is not active
- apply the reproducing steps in the storybook
<details>
<br />
</details>
<details>
<br />
2. You have optional …

fix: update toolbar when formatted word is deleted

---

.changeset/little-pillows-clean.md
packages/picasso/src/StepLabel/StepLabel.tsx
packages/picasso/src/StepLabel/styles.ts
packages/picasso/src/Stepper/__snapshots__/test.tsx.snap
packages/picasso/src/StepperVertical/__snapshots__/test.tsx.snap

[FX-3885]
[EXP-2638]
This PR fixes the issue where the `StepLabel` of an active `Step` is hidden on mobile resolutions
- visit https://picasso.toptal.net/EXP-2638-always-show-active-stepper-label-on-mobile/?path=/story/components-stepper--stepper
- resize the page to a width below 576px
- verify that only the labels for non-active step are hidden
| ![image](https://user-images.githubusercontent.com/291348/231813978-5936e959-9e57-4706-9c57-84656eae8bbf.png) | ![image](https://user-images.githubusercontent.com/291348/231813431-ed08e28f-15e0-46ba-a6b1-cbd75fbf3c18.png) |
- [n/a] Annotate all `props` in component with …

fix(Stepper): always show active Step's StepLabel

---

cypress/component/BarChart.spec.tsx

[FX-NNNN]
More and more we start seeing flaky test of BarChart
I have removed the tooltip and labels from the test as it is already tested in different scenario.
- Check and Approve the Happo change
`n/a`
- `n/a` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `n/a` Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- `n/a` Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- …

test: update BarChart visual test to remove flaky test

---

.changeset/selfish-kids-boil.md
@types/quill-emoji/index.d.ts
package.json
packages/picasso/package.json
packages/picasso/src/QuillEditor/QuillEditor.tsx
packages/picasso/src/QuillEditor/blots/emoji.ts
packages/picasso/src/QuillEditor/constants.ts
packages/picasso/src/QuillEditor/hooks/useQuillInstance/useQuillInstance.tsx
packages/picasso/src/QuillEditor/hooks/useSubscribeToTextEditorEvents/useSubscribeToTextEditorEvents.tsx
packages/picasso/src/QuillEditor/types.ts
packages/picasso/src/QuillEditorView/styles.ts
packages/picasso/src/RichText/hooks/useRichText/useRichText.tsx
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/hooks/useToolbarHandlers/useToolbarHandlers.tsx
packages/picasso/src/RichTextEditor/index.ts
packages/picasso/src/RichTextEditor/story/Emoji.example.tsx
packages/picasso/src/RichTextEditor/story/index.jsx
packages/picasso/src/RichTextEditor/types.ts
packages/picasso/src/RichTextEditorButton/RichTextEditorButton.tsx
packages/picasso/src/RichTextEditorEmojiPicker/RichTextEditorEmojiPicker.tsx
packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
packages/picasso/src/utils/html-to-hast.ts
yarn.lock

[COMM-2200]
Our product team has the need of sending Slack mass messages that include emojis and custom Toptal emojis and they would like to do it via a specific Staff Portal page. We would need to extend RichTextEditor to support emojis and also custom emojis. This PR implements such a feature into Quill Editor as an opt-in feature that won't break existing RichTextEditor instances
- Access the Storybook
- Navigate to RichTextEditor
- ScrollDown to "Emojis" example
- Play around with adding the emojis, searching them, and inserting them into the editor.
- CI should be 💚 
<details>
<br />
- `@toptal-bot …

feat: support emojis and custom emojis in richtexteditor

---

.changeset/chatty-sheep-watch.md
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/DatePicker/test.tsx

[FX-3932](https://toptal-core.atlassian.net/browse/FX-3932)
Prevent opening the datepicker calendar when clicking on the reset button.
- Go to https://picasso.toptal.net/FX-3932-fix-reset-button-for-datepicker/?path=/story/forms-datepicker--datepicker#with-reset-button
- Select a date
- Click the reset button
- The calendar should not be visible
- Click on the datepicker
- The calendar should be visible
| ![Kapture 2023-04-20 at 08 39 47](https://user-images.githubusercontent.com/2583281/233336041-e9c9f8c1-c1c0-483d-a97a-79b327951124.gif)  | ![Kapture 2023-04-20 at 13 14 …

fix: reset button when datepicker calendar is closed

---

.storybook/components/PicassoBook/components/PropsTable/styles.ts
.storybook/preview-head.html

[FX-NNNN]
Added `overflow-x: auto` to the table that is used to display props in Picasso Storybook. `flex-direction` on the root node was also necessary to prevent overflow of the rest of the content.
Previously it was forcing the entire content (including stories) to be the width of the prop table.
- Open any page and switch to small/large mobile view (or resize the browser window)
- Compare with master
| ![image](https://user-images.githubusercontent.com/18409292/233626347-773a59b6-ddd5-4f07-9ca8-00d72fc5c42d.png) | ![image](https://user-images.githubusercontent.com/18409292/233626541-4d98d04f-1c12-4a83-b010-8b2b9188e5 …

chore: make prop table responsive in Picasso Storybook

---

.changeset/cold-teachers-refuse.md
packages/picasso/src/QuillEditor/utils/quillDecodeIndent/quillDecodeIndent.ts
packages/picasso/src/QuillEditor/utils/quillDecodeIndent/test.ts

[ER-31406]
[ER-31433]
Fix unhandled errors
- new unit test added, so CI should be green
<details>
<br />
</details>
<details>
<br />
**You are not …

fix: catch unhandled error

---

packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx
packages/picasso/src/QuillEditor/hooks/useDefaultValue/useDefaultValue.tsx

[FX-NNNN]
`Form.RichTextEditor` does not populated `initialValue` at all, you can check it in [this example](https://picasso.toptal.net/?path=/story/picasso-forms-form--form#highlight-fields-with-default-value):
**Actual:**
Even though the field is highlighted, the value is empty. 
**Expected**
The field got populated with the `initialValues` provided on the `Form` or `initialValue` on the field itself.
BREAKING CHANGES:
Providing `defaultValue` prop won't emit a change event anymore, which is expected IMO.
- Go to [this example](https://picasso.toptal.net/?path=/story/picasso-forms-form--form#highlight-fields-with-default-value)
- The rte field should be populated by default, field should also be highlighted.
| Before.                                 | After. …

fix(RichTextEditor): default value not populated

---

.changeset/red-countries-thank.md
packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Radio/__snapshots__/test.tsx.snap
packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx
packages/picasso-provider/src/Picasso/RootContext.ts
packages/picasso-provider/src/Picasso/config/breakpoints.ts
packages/picasso-provider/src/Picasso/config/index.ts
packages/picasso-provider/src/index.ts
packages/picasso/src/Grid/Grid.tsx
packages/picasso/src/Grid/story/ResponsiveSpacing.example.tsx
packages/picasso/src/Grid/story/index.jsx
packages/picasso/src/Radio/__snapshots__/test.tsx.snap
yarn.lock

[FX-3930]
[According to the BASE design](https://www.figma.com/file/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?type=design&node-id=4533%3A28468&t=NpdofDozEQJAvCJX-1), grid gutters depend on the screen size. This pull request adjusts gutters depending on the screen size unless spacing is explicitly specified by users.
- Test different screen sizes at https://picasso.toptal.net/FX-3930-make-grid-spacing-responsive/?path=/story/layout-grid--grid
https://user-images.githubusercontent.com/1390758/236229973-8199a4fa-e35e-46dd-8fad-39771dcb6a1e.mp4
> All **_development checks_** should be done and set checked …

feat: add responsive grid spacing

---

.changeset/moody-cooks-walk.md
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/story/ShowEveryNthTick.example.tsx
packages/picasso-charts/src/BarChart/story/index.jsx

[FX-3957](https://toptal-core.atlassian.net/browse/FX-3957)
This pull request adds the `showEveryNthTickOnXAxis` and `showEveryNthTickOnYAxis` properties to `BarChart`, so ticks can be skipped on both axes.
- Navigate to https://picasso.toptal.net/fx-3957-provide-an-option-to-show-or-hide-x-axis-ticks-in-picasso-barchart/?path=/story/picasso-charts-barchart--barchart and check out the `Show every Nth tick on X or Y-axis` section
<details>
<br />
</details>
<details> …

feat: skip ticks for x and y axes

---

.changeset/brave-eyes-raise.md
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/getEditorChangeHandler.tsx
packages/picasso/src/QuillEditor/utils/getEditorChangeHandler/test.ts

[FX-3974]
Quill has an issue with ranges in Safari: https://github.com/quilljs/quill/issues/3093
We need to handle it on our side by providing the latest range index. So, we need to use an internal `selection` object to do it or provide `0` manually
- on Temploy, you need to paste the following code:
```
import { Accordion } from '@toptal/picasso'
import {
FormNonCompound,
SubmitButton,
RichTextEditor,
} from '@toptal/picasso-forms'
import { htmlToHast } from '@toptal/picasso/utils'
const defaultValue = '<p>Position Description</p>'
const Example = () => (
<Accordion content={<DetailsDogDefinitionPanel />}>
<Accordion.Summary>Job description</Accordion.Summary>
</Accordion>
)
const RTE = () => {
return (
<FormNonCompound
onSubmit={console.log}
initialValues={{ …
```

fix: quill issue in Safari when editor is hidden

---

.changeset/brave-snails-accept.md
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/story/Stacked.example.tsx
packages/picasso-charts/src/BarChart/story/index.jsx
packages/picasso-charts/src/BarChart/utils/define-stack-id/define-stack-id.ts
packages/picasso-charts/src/BarChart/utils/define-stack-id/index.ts
packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts
packages/picasso-charts/src/BarChart/utils/find-top-domain/test.ts
packages/picasso-charts/src/BarChart/utils/index.ts

[FX-3955](https://toptal-core.atlassian.net/browse/FX-3955)
Added a possibility to stack bars in Picasso Charts
- Check the deployed [storybook](https://picasso.toptal.net/fx-3955-enable-stacked-bars-in-picasso-barchart/?path=/story/picasso-charts-barchart--barchart)
| [not implemented]| ![image](https://github.com/toptal/picasso/assets/18409292/7851472f-56e8-427f-9589-e9fd9dd57cf5) |
<details>
<br /> …

feat: add stacked bars

---

.changeset/shiny-files-peel.md
packages/picasso/src/DrawerTitle/styles.ts

[TOP-3211](https://toptal-core.atlassian.net/browse/TOP-3211)
Fix `Drawer` close button and standard title overlap when the title text is too big.
- Go to the [Drawer page](http://localhost:9001/?path=/story/components-drawer--drawer)
- Go to the **Default** example and edit the code by adding a bigger title
- Click on `Show drawer` and make sure the title and close button don't overlap
| ![image](https://github.com/toptal/picasso/assets/82273361/a2f0c2bb-1014-4c32-b859-75205cb08ef9) | ![image](https://github.com/toptal/picasso/assets/82273361/8f8ca6fa-3a9d-4808-b0a3-7c68057572e8) |
> All …

fix(Drawer): close button and standard title overlap

---

.changeset/calm-students-refuse.md
packages/picasso-provider/src/Picasso/config/breakpoints.ts
packages/picasso-provider/src/Picasso/config/test.ts

[FX-3999]
This pull request fixes the overlap in breakpoints media queries that was causing ambiguity when detecting breakpoint ranges.
Taken from https://github.com/toptal/picasso/blob/a9e8c9189dc7a11ddb159f3c08eddffa081a1e2f/docs/decisions/13-breakpoints.md#proposal:
```
...
// Breakpoint ranges
xs:  0-479px
sm:  480-767px
md:  768-1023px
lg:  1024-1439px
xl:  1440px+
...
```
> **GitHub Bot: TODOLess** …

fix: overlap in breakpoints

---

.changeset/tender-insects-accept.md
packages/picasso/src/Indicator/Indicator.tsx
packages/picasso/src/Indicator/story/Default.example.tsx
packages/picasso/src/Indicator/styles.ts
packages/picasso/src/TagRectangular/story/Indicators.example.tsx

[SDE-1065](https://toptal-core.atlassian.net/browse/SDE-1065)
Add light blue color in `Indicator` and `TagRectangular`
- Go to `Indicator` component page
- Light-blue section should appear 
- Go to `TagRectangular` component page
- Light-blue section should appear 
| ![Screenshot from 2023-05-23 19-24-12](https://github.com/toptal/picasso/assets/33624918/60080573-3ff4-48b5-b328-7102a3d38e3b) | ![Screenshot from 2023-05-23 19-23-50](https://github.com/toptal/picasso/assets/33624918/166f01e9-1ef0-4b19-ac86-ead1550314fe) |
- [n/a] codemod is …

chore: add light blue color in indicator

---

.changeset/cyan-plums-cheat.md
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/story/ValueAxisTickFormatter.example.tsx
packages/picasso-charts/src/BarChart/story/index.jsx

[SDE-1048]
This PR adds the `valueAxisTickFormatter` option to the BarChart component, allowing us to format the value axis ticks as needed!
- Run the storybook locally (`yarn start`)
- Navigate to the `BarChart` component (http://localhost:9001/?path=/story/picasso-charts-barchart--barchart) and find the example provided
| N/A | ![image](https://github.com/toptal/picasso/assets/65467711/47122d29-1394-4d39-a556-eefe955540eb) |
<details>
<br />
List of available …

feat(BarChart): add option to format the value axis

---

.changeset/stupid-rice-shop.md
packages/picasso/src/PageHamburger/PageHamburger.tsx
packages/picasso/src/PageHamburger/PageHamburgerContext.tsx
packages/picasso/src/PageHamburger/PageHamburgerPortal.tsx
packages/picasso/src/PageHamburger/hooks/use-portal-to-hamburger.ts
packages/picasso/src/PageSidebar/PageSidebar.tsx
packages/picasso/src/PageTopBar/PageTopBar.tsx

[FX-4033]
For some reason, when the application is running on react@16, it has not the correct value of `hasTopBar` from the global context. To not break it's usage in the rest of the application, I'm using local context which works exactly as it should.
- check this [sandbox](https://codesandbox.io/s/flamboyant-bartik-mrvdlj?file=/package.json&resolutionWidth=1252&resolutionHeight=675)
- `n/a` Create `examples` for component
- `n/a` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).
- `n/a` Covered with tests
- `n/a` codemod is created and showcased in the …

chore: use local state istead of global context

---

packages/picasso/src/Tooltip/__snapshots__/test.tsx.snap
packages/picasso/src/Tooltip/test.tsx

[FX-NNNN]
A new flaky snapshot started to show up only in CI after upgrading `@testing-library/react` from v13 to v14
`n/a`
- `n/a` Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- `n/a` Make sure that additions and changes on design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- `n/a` Create `examples` for component
- `n/a` Ensure that deployed demo has expected results and good examples
- `n/a` Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

test: remove flaky snapshot

---

packages/picasso/package.json
packages/picasso/src/LexicalEditor/LexicalEditor.tsx
packages/picasso/src/LexicalEditor/plugins/LexicalEditorToolbar.tsx
packages/picasso/src/LexicalEditor/utils/index.ts
packages/picasso/src/LexicalEditor/utils/registerLexicalEvents.test.ts
packages/picasso/src/LexicalEditor/utils/registerLexicalEvents.ts
packages/picasso/src/LexicalEditor/utils/synchronizeToolbarState.test.ts
packages/picasso/src/LexicalEditor/utils/synchronizeToolbarState.ts
packages/picasso/src/LexicalEditor/utils/toolbarState.ts
packages/picasso/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso/src/LexicalEditorToolbarPlugin/index.ts
yarn.lock

[FX-4006](https://toptal-core.atlassian.net/browse/FX-4006)
Add a functional toolbar to Lexical implementation of the rich text editor.
Bold and italic formatting is supported, with some foundation for future formatters.
- Take a look at the [deployed storybook](https://picasso.toptal.net/fx-4006-integrate-inline-plugins/?path=/story/components-richtext--richtext)
- Most importantly, see if the code makes sense and it's clear where to add future features
- The toolbar should look identical to the [original RTE](https://picasso.toptal.net/?path=/story/components-richtext--richtext)
| (same as before) | (looks exactly the …

feat: add Toolbar for LexicalEditor

---

packages/picasso/src/Calendar/Calendar.tsx
packages/picasso/src/Calendar/__snapshots__/test.tsx.snap
packages/picasso/src/Calendar/styles.ts
packages/picasso/src/CalendarContainer/CalendarContainer.tsx
packages/picasso/src/CalendarContainer/styles.ts
packages/picasso/src/CalendarMonthHeader/CalendarMonthHeader.tsx
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/DatePicker/story/WithTwoMonths.example.tsx
packages/picasso/src/DatePicker/story/index.jsx

[FX-3963](https://toptal-core.atlassian.net/browse/FX-3963)
Add support for rendering two months at the same time to DatePicker.
This is only available on screens > `sm` range.
- Take a look at the [deployed storybook](https://picasso.toptal.net/fx-3963-support-two-month-calendar-visualization-in-the-datepicker-component/?path=/story/forms-datepicker--datepicker#with-two-months)
- Check if the code looks good
- Check if combinations of other props work well with two month view.
| ![image](https://github.com/toptal/picasso/assets/18409292/4ff5797a-cedf-43e8-9274-f1ca6a050130) | …

feat: add support for multi-month display to DatePicker

---

.changeset/cyan-seas-enjoy.md
packages/picasso/src/DatePicker/DatePicker.tsx

[FX-NNNN]
I think this is just a leftover that we missed in the [previous PR](https://github.com/toptal/picasso/pull/3606/files#diff-eee96e563cc335645633cd9bb0f93db4a756a3a95e1c152749121312dea6539eR471)
- n/a Covered with tests
- n/a test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details>
<br />
**You …

fix: remove unused showTwoMonths

---

.changeset/curly-rice-cough.md
packages/picasso/src/ModalContent/hooks/use-scrollable-shades.ts

[TOP-3334]
On some screen sizes el.scrollTop is rounder in wrong direction which results in shade not disappearing even though user scrolled to the very bottom of the content. This definitely reproduces on Chrome/Windows. This PR aims to fix this. 
- Ensure scrolling shade at the bottom properly disappears once you scroll to the end of the container
- [Temploy link](https://picasso.toptal.net/TOP-3334-fix-scrollable-shades-on-screens-of-fractional-size/?path=/story/overlays-modal--modal)
https://github.com/toptal/picasso/assets/903437/9be16563-d0f9-4405-9ca7-44b8f9b17a1c
- ~Covered with tests~
- ~test alpha package of …

fix(ModalContent): [TOP-3334] proper bottom edge detection for scrolling shades

---

packages/picasso/package.json
packages/picasso/src/LexicalEditor/LexicalEditor.tsx
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/test.tsx
yarn.lock

[FX-4015]
We need to integrate a new RTE to Picasso Forms.
- Check the regress on temploy
<details>
<br />
</details>
<details>
<br />
3. …

chore: [FX-4015] Integrate Rich Text Editor to Forms

---

.changeset/lazy-poets-change.md
packages/picasso/src/Button/styles.ts
packages/picasso/src/ButtonGroup/story/ButtonGroupDisabled.example.tsx
packages/picasso/src/ButtonGroup/story/index.jsx
packages/picasso/src/ButtonGroupItem/ButtonGroupItem.tsx
packages/picasso/src/ButtonGroupItem/styles.ts
packages/picasso/src/PaginationButton/styles.ts

[SDE-1090](https://toptal-core.atlassian.net/browse/SDE-1090)
Add support for disabled appearance to `ButtonGroup`.
- Take a look at the [deployed storybook](https://picasso.toptal.net/sde-1090-add-disabled-appearance-button-group/?path=/story/components-button--button#group-of-buttons-button-group-disabled)
- Check if the code looks good
- Compare implementation with ticket requirements.
| ![image](https://github.com/toptal/picasso/assets/5639968/5fcc4a03-b512-4302-8b62-99ae9813f1bd) | ![image](https://github.com/toptal/picasso/assets/5639968/4b56b2ba-558f-48c7-8e3e-77b36a48c949) |
- [n/a] codemod …

feat(ButtonGroup): [SDE-1090] Add disabled appearance

---

packages/picasso/src/LexicalEditor/LexicalEditor.tsx
packages/picasso/src/LexicalEditor/styles.ts
packages/picasso/src/LexicalEditor/utils/createLexicalTheme.ts
packages/picasso/src/LexicalEditor/utils/registerLexicalEvents.test.ts
packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx

[FX-4087]
The only thing that we need to do is to add class to HTML tags in the editor. As you can see from the screenshot from the current feature branch, we have both bold and italic on the output.
- play with[ temploy ](https://picasso.toptal.net/fx-4087-italic-bold/?path=/story/forms-richtexteditor--richtexteditor)
| ![image](https://github.com/toptal/picasso/assets/6830426/e1256b91-74ea-415c-afe4-60dd6dffab1a) | ![image](https://github.com/toptal/picasso/assets/6830426/170ee389-15d2-47ab-b71b-f93a0b50ad09) |
- Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/cha …

feat: add styles for bold and italic

---

.changeset/soft-steaks-cheer.md
packages/picasso-rich-text-editor/src/QuillEditorView/QuillEditorView.tsx

[FX-4121]
Grammarly is still enabled in some clients, probably due to the Grammarly version that does not take into account the already existing `data-gramm="false"` property. Please see more details in https://toptal-core.slack.com/archives/CERF5NHT3/p1687974164415239.
- Testing does not appear to make sense, as it requires multiple versions of Grammarly for testing
Additional resources:
- https://github.com/quilljs/quill/issues/574
- https://github.com/jinjor/elm-break-dom/issues/27
- https://stackoverflow.com/a/46777787/1860213
- [N/A] Create `examples` …

fix: add properties to ignore grammarly

---

.changeset/khaki-experts-tan.md
packages/picasso-codemod/src/v36.0.0/rich-text-editor-replacement.ts

Need to set up a proper version of RTE package
- use alpha version of codemod v36.0.0
<details>
<br />
</details>
<details>
<br />
3. Code …

fix: version in RichTextEditor codemod

---

packages/picasso/src/LexicalEditor/LexicalEditor.test.tsx
packages/picasso/src/LexicalEditor/LexicalEditor.tsx
packages/picasso/src/LexicalEditor/styles.ts
packages/picasso/src/LexicalEditor/types.ts
packages/picasso/src/LexicalEditor/utils/createLexicalTheme.ts
packages/picasso/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso/src/LexicalEmojiPlugin/LexicalEmojiPlugin.test.ts
packages/picasso/src/LexicalEmojiPlugin/LexicalEmojiPlugin.tsx
packages/picasso/src/LexicalEmojiPlugin/commands/index.ts
packages/picasso/src/LexicalEmojiPlugin/index.ts
packages/picasso/src/LexicalEmojiPlugin/nodes/CustomEmojiNode.tsx
packages/picasso/src/LexicalEmojiPlugin/nodes/index.ts
packages/picasso/src/LexicalEmojiPlugin/types.ts
packages/picasso/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/RichTextEditor/styles.ts
packages/picasso/src/RichTextEditorEmojiPicker/RichTextEditorEmojiPicker.tsx
packages/picasso/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx

[FX-4012]
- Create context to enable/disable optional features
- Add emoji plugin
- Play with emojis [in the temploy](https://picasso.toptal.net/FX-4012-emoji)
| ![image](https://github.com/toptal/picasso/assets/6830426/47ba7341-02d7-4bfe-96ce-6136544cb697) | ![image](https://github.com/toptal/picasso/assets/6830426/8d8b2095-60fd-4c6d-a153-ecf48ea1ce54) |
<details> …

feat(RichTextEditor): add Emoji plugin

---

cypress/component/RichTextEditor.spec.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/utils/setEditorValue.ts
packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx

[FX-4129]
This pull request fixes the editor state initialization.
According to the source code (https://github.com/facebook/lexical/blob/2bcf11bec944cd3bd69b7e7b40903e593b716a06/packages/lexical-react/src/LexicalComposer.tsx#L119), the editor state needs to be initialized either by Lexical itself or inside of the `editorConfig` if it is a function. This pull request removes the case when the function is provided, but the state is not initialized by anybody.
- Navigate to https://picasso.toptal.net/fx-4129-insert-list-to-empty-editor-2/?path=/story/forms-richtexteditor--richtexteditor
https://github.com/toptal/picasso/assets/1390758/0a0a72a8-d276-4bb5-a6dd-5a4d89044d0c
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset- …

fix: editor state initialization

---

cypress/component/RichTextEditor.spec.tsx
packages/picasso-rich-text-editor/src/FocusOnLabelClickPlugin/FocusOnLabelClickPlugin.tsx
packages/picasso-rich-text-editor/src/FocusOnLabelClickPlugin/index.ts
packages/picasso-rich-text-editor/src/FocusOnLabelClickPlugin/styles.ts
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/picasso-rich-text-editor/src/RichTextEditor/styles.ts

[FX-4130]
To simulate native behave of form inputs, when we click on `<label for='id-of-input'>` we expect to focus on related input. As RTE is actually div, we need to replicate this functionality on our own.
- try in the [temploy](https://picasso.toptal.net/fx-4130-focus-on-label/?path=/story/picasso-forms-form--form#rich-text-editor)
| https://github.com/toptal/picasso/assets/6830426/0b9d70b0-bac1-4132-ab5b-522ca0dbdac2 | https://github.com/toptal/picasso/assets/6830426/784f51b6-af99-4ca8-8451-2d408c6c9b4f |
- Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/chang …

fix: focus editor on label click

---

packages/picasso-rich-text-editor/src/LexicalEditor/utils/cleanupHtmlOutput.test.ts
packages/picasso-rich-text-editor/src/LexicalEditor/utils/cleanupHtmlOutput.ts

[FX-4136]
After discussion with Augusto, we decided that it is much simpler to output old HTML for nested lists as it is more complex to play with AST and also we would need to extend List component to work new structure.
- check [temploy](https://picasso.toptal.net/fx-4136-lists/?path=/story/components-richtext--richtext#html-from-fe-for-live-editing-preview) and play with nested lists, they should look nice in the RichText component
- we noticed that currently ordered list does not look as it should in RichText and I will create ticket to fix it in List component.
| …

feat: output proper nested list semantics

---

docs/decisions/17-bar-indicators-for-barchart.md

[SDE-1141](https://toptal-core.atlassian.net/browse/SDE-1141)
This PR introduces the RFC to add the bar indicators to the [BarChart](https://picasso.toptal.net/?path=/story/picasso-charts-barchart--barchart) component.
<details>
<br />
</details>
<details>
<br />
2. Acceptance …

docs: add RFC for bar indicators in bar chart

---

packages/picasso-rich-text-editor/src/RichTextEditorToolbar/styles.ts

[FX-4142](https://toptal-core.atlassian.net/browse/FX-4142)
Hides the empty group divider in the toolbar.
- Compare to the Storybook on the base branch
- When link plugin is disabled and emojis are enabled, empty group should not be visible in the toolbar
| ![image](https://github.com/toptal/picasso/assets/18409292/86418f9b-b941-4b8c-adff-e0216891ac49) | ![image](https://github.com/toptal/picasso/assets/18409292/f462da64-402d-490d-85f9-85c230285f34) |
- [n/a] Annotate all …

fix: remove unused group separator from toolbar

---

packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx

[FX-4118]
Incorrect output when inserting custom emoji to an empty editor
Expected: '<img ...'
Actual: ''
- use temploy to check
<details>
<br />
</details>
<details>
<br />
2. …

fix: [FX-4118] incorrect output for custom emoji

---

packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/hooks/useOnFocus/test.ts
packages/picasso-rich-text-editor/src/LexicalEditor/hooks/useOnFocus/useOnFocus.ts
packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx
packages/picasso-rich-text-editor/src/plugins/api.tsx

[FX-4146]
Buttons in the toolbar need to be disabled even when the editor is not focused
- check [temploy](https://picasso.toptal.net/fx-4146-link-button-disabled/?path=/story/forms-richtexteditor--richtexteditor#links)
| ![image](https://github.com/toptal/picasso/assets/6830426/1b7b0011-d1a3-4c2c-85a1-f888498ce42a) | ![image](https://github.com/toptal/picasso/assets/6830426/59a698ab-ad34-4f25-8767-901a00bed127) |
- Read …

fix: disable link button when editor not focused

---

packages/picasso-rich-text-editor/src/LexicalEditor/utils/setEditorValue.ts

[FX-4148](https://toptal-core.atlassian.net/browse/FX-4148)
Prevents scrolling down to the initialized RTE.
- Compare to the base branch
- Navigate to the [Form](http://localhost:9001/?path=/story/picasso-forms-form--form) story page, the page should not scroll down to the auto-save story
- Integration tests look good
- [n/a] Covered with tests
<details>
<br />
- `@toptal-anvil ping reviewers` - Ping FX team for …

fix: remove selection of newly created root node

---

cypress/component/RichTextEditor.spec.tsx

[FX-4131]
This pull request restores skipped integration tests.
- All integration tests should pass
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/access …

fix: disable scroll on click

---

.changeset/perfect-spies-clean.md
packages/picasso/src/List/List.tsx
packages/picasso/src/List/__snapshots__/test.tsx.snap
packages/picasso/src/ListItem/index.ts

[FX-4139]
Add appropriate list item types for ordered list
- Use temploy to check `List` and `RichText` stories
<details>
<br />
</details>
<details>
<br />
2. Acceptance …

feat: [FX-4139] add appropriate list item types

---

.changeset/fresh-suns-hang.md
packages/picasso-rich-text-editor/src/RichText/components/Emoji.tsx
packages/picasso-rich-text-editor/src/RichText/components/Image.tsx
packages/picasso-rich-text-editor/src/RichText/components/index.ts
packages/picasso-rich-text-editor/src/RichText/hooks/useRichText/useRichText.tsx
packages/picasso-rich-text-editor/src/RichText/story/Default.example.tsx
packages/picasso-rich-text-editor/src/RichText/types.ts
packages/picasso-rich-text-editor/src/utils/__tests__/is-custom-emoji-component.test.ts
packages/picasso-rich-text-editor/src/utils/index.ts
packages/picasso-rich-text-editor/src/utils/is-custom-emoji-component.ts

[FX-4111]
This pull request adds support for images in the in `RichText`.
- Please see the https://picasso.toptal.net/fx-4111-image-show-image-in-richtext/ for demo
Big picture (takes full width of the container)
Regular picture (takes its full width)
> All **_development checks_** should be done and set …

feat: add support for images in RichText

---

.changeset/blue-pugs-sleep.md
cypress/component/BarChart.spec.tsx
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/story/StackedWithBarChartIndicators.example.tsx
packages/picasso-charts/src/BarChart/story/index.jsx
packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts
packages/picasso-charts/src/BarChartIndicators/BarChartIndicators.tsx
packages/picasso-charts/src/BarChartLabel/BarChartLabel.tsx
packages/picasso-charts/src/types.ts

[SDE-1142](https://toptal-core.atlassian.net/browse/SDE-1142)
This PR adds the `dataItem` option to `renderBarIndicators` and `renderBarIndicators`, allowing us to customize bar indicators as needed.
- Run the storybook locally (`yarn start`)
- Navigate to the `BarChart` component (http://localhost:9001/?path=/story/picasso-charts-barchart--barchart#stacked-with-bar-chart-indicators) and find the example provided
| ![image](https://github.com/toptal/picasso/assets/5639968/40981c23-72be-4d25-97c0-1a9355d7a36e) | ![image](https://github.com/toptal/picasso/assets/5639968/90a7a7af-c0bd-457b-8bf9-3a991a45123a) |
**Breaking …

feat(barchart): add entry option to customize a bar indicator

---

.changeset/good-actors-glow.md
.changeset/tender-kangaroos-shout.md
packages/picasso-rich-text-editor/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
packages/picasso-rich-text-editor/src/plugins/Toolbar/Toolbar.tsx
packages/picasso-rich-text-editor/src/plugins/Toolbar/index.ts
packages/picasso-rich-text-editor/src/plugins/Toolbar/styles.ts
packages/picasso-rich-text-editor/src/plugins/api.tsx
packages/picasso/src/utils/index.ts
packages/picasso/src/utils/use-multiple-forward-refs.ts

[FX-4137]
On this PR, we are wrapping all toolbar plugins on groups. For now, every Toolbar has its group, in the future, we can think of a mechanism for controlling groups more precisely
- Temploy
- Check happo and temploy, last toolbar vertical bar
| ![image](https://github.com/toptal/picasso/assets/5845160/9cb61cb5-1f40-4ae9-93d6-65261b0c185a) | ![image](https://github.com/toptal/picasso/assets/5845160/72b39226-4d0b-447f-add8-653ac34efdc4) |
- [NA] codemod is created and showcased in the changeset
- [NA] test alpha package of Picasso in StaffPortal
> All **_development checks_** should be done and …

feat(rich-text-editor): move toolbar plugin groups to portal

---

packages/picasso/src/Calendar/story/index.jsx

[FX-4165]
We tried to expose the Calendar component. It turned out there was no Calendar designs in BASE.
Since noone needed it at the time, we decided to 1) pospone the work on stand alone Calendar 2) hide it back to discourage its usage.
When the work is resumed - just uncomment the code below and work from there. Also check out PR #3729 where we refactored Calendar to remove its Container and footer.
- [Temploy](https://picasso.toptal.net/fx-4165-remove-calendar-from-storybook)
- Check Calendar is not in Storybook
**Breaking …

chore(Calendar): remove from Storybook

---

.changeset/short-cows-shave.md
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.test.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso-rich-text-editor/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx

[FX-4172]
For backward compatibility, we need to keep the HTML structure closest as possible to the previous version. In feature tests, they are using the id of the toolbar as a selector.
- [Temploy](https://picasso.toptal.net/fx-4172-return-toolbar-id)
> **GitHub …

chore: return RTE toolbar id for feature tests

---

.changeset/tiny-dodos-lie.md
cypress/component/DatePicker.spec.tsx
packages/picasso/src/DatePicker/DatePicker.tsx

[FX-4183](https://toptal-core.atlassian.net/browse/FX-4183)
When an external async value update is issued to DatePicker value while it is disabled (as demonstrated in this [example](https://codesandbox.io/s/thirsty-swartz-d83chh?file=/src/Page.tsx)), a `isFocused` state is not set back to `false` when input becomes disabled. This causes the logic that relied on the flag to not function properly.
- [Temploy](https://picasso.toptal.net/fx-4183-datepicker-does-not-reset-value-if-it-s-in-disabled-state)
- All tests should pass
- The new test added for the case should pass
https://github.com/toptal/picasso/assets/18409292/28afb89f-81e3-4e09-aa59-b7c467bdfd1a
https://github.com/toptal/picasso/assets/18409292/408c64fe-eab9-4aef-8bcc-b4cd69fa8ac2
> All **_development checks_** should be done and …

fix(DatePicker): react to external updates accordingly

---

.changeset/fast-bulldogs-study.md
packages/picasso/src/PageHamburger/PageHamburger.tsx
packages/picasso/src/PageHamburger/styles.ts
packages/picasso/src/PageTopBar/__snapshots__/test.tsx.snap

[FX-4200]
This pull request fixes the hamburger menu offset and the hamburger button is vertically centered.
Design https://www.figma.com/file/5SCTOPrCDcHuk5We091GBn/Product-Library?type=design&node-id=9938-40726&mode=design&t=brwuhESCM5CsNynL-0
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-compact-dropdown-menu)
- Compare with https://picasso.toptal.net/?path=/story/layout-page--page side-by-side by opening the hamburger menu
Hamburger button position before
Hamburger button position after
Hamburger button position in design
---
Please see the side-by-side comparison of hamburger button position and menu (in `master` / in this pull request)
https://github.com/toptal/picasso/assets/1390758/81442492-a25c-4b75-b9c0-85aaddfcd606
- [N/A] Annotate all `props` in component with …

fix: hamburger menu offset

---

.changeset/sour-bees-tie.md
packages/picasso-rich-text-editor/src/LexicalEditor/utils/setEditorValue.ts

[FX-4190](https://toptal-core.atlassian.net/browse/FX-4190)
When `{ root: { children: [] } }` is provided as a default value to the RichTextEditor, the internal editor state is initialized without an empty paragraph. According to Lexical docs, this is not a valid state, there should always be at least one paragraph node by default.
This causes the editor to crash when trying to append items to the root node (for example, creating an empty list in editor with an empty default value).
- [Temploy](https://picasso.toptal.net/fx-4190-richtexteditor-throws-error-when-initialized-with-empty-default-value)
- Story for `RichText` can be used for testing
- Change the `HTML` story example code to have the default value of `root: { children: [] } `
- Without doing anything else, click on any list …

fix: initialize editor with empty paragraph if root is empty

---

.changeset/tame-coins-breathe.md
packages/picasso/src/Drawer/styles.ts

[FX-4181]
Use full-width size for narrow Drawer in XS screens.
Will be covered with integration tests in a separate task
- Use temploy 
- test `Drawer` with prop `width="narrow"`, 
- use screen width between "0-479px"
- Drawer width must be full-sized
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable …

fix: [FX-4181] use proper width for narrow Drawer

---

.changeset/serious-poets-argue.md
.changeset/silent-carpets-move.md
packages/picasso-forms/package.json
packages/picasso-rich-text-editor/package.json
packages/picasso-rich-text-editor/src/LexicalEditor/styles.ts
packages/picasso-rich-text-editor/src/LexicalEditor/utils/createLexicalTheme.ts
packages/picasso-rich-text-editor/src/RichText/components/CodeBlock.tsx
packages/picasso-rich-text-editor/src/RichText/components/index.ts
packages/picasso-rich-text-editor/src/RichText/components/styles.ts
packages/picasso-rich-text-editor/src/RichText/hooks/useRichText/useRichText.tsx
packages/picasso-rich-text-editor/src/RichText/story/Default.example.tsx
packages/picasso-rich-text-editor/src/RichText/story/HTML.example.tsx
packages/picasso-rich-text-editor/src/RichText/types.ts
packages/picasso-rich-text-editor/src/RichTextEditor/story/Code.example.tsx
packages/picasso-rich-text-editor/src/RichTextEditor/story/Default.example.tsx
packages/picasso-rich-text-editor/src/RichTextEditor/story/index.jsx
packages/picasso-rich-text-editor/src/index.ts
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/CodeBlockButton.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/CodeBlockPlugin.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/index.ts
packages/picasso-rich-text-editor/src/plugins/index.ts
packages/picasso-rich-text-editor/src/utils/html-to-hast.ts

[FX-4184]
This PR brings the default structure for the `CodeBlockPlugin`
- stories
- toolbar button
- RichText component
- styles
- types
The logic will be in different PR
- [Temploy](https://picasso.toptal.net/fx-4184-rte-code-block)
- check the code and [the story](https://picasso.toptal.net/fx-4184-rte-code-block/?path=/story/forms-richtexteditor--richtexteditor#code)
<details>
<br />
- `@toptal-anvil ping reviewers` - Ping FX team for …

feat: create base for CodeBlockPlugin

---

.changeset/eleven-badgers-judge.md
cypress/component/RichTextEditor/LinkPlugin.spec.tsx
packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx

[FX-4180](https://toptal-core.atlassian.net/browse/FX-4180)
This PR makes it possible to insert a link while no text is selected. In this case, a link will be inserted as a new `LinkNode` with text content being the link itself.
- [Temploy](https://picasso.toptal.net/fx-4180-rte-linkplugin-wraps-whole-line-when-nothing-selected)
- Check out the `Links` story for `RichTextEditor`
- Try to insert the link with nothing selected
- Try different combinations of inserting (next to other nodes, next to lists, inside/outside other formats)
- Compare to the traditional way of inserting links. There should be no difference in the output
<details>
<br />
List of …

feat: add support for standalone links

---

packages/picasso/src/Select/story/index.jsx

[FX-4207]
Instead of using the function contents as the defaultValue, I tried to summarize its definition on a proper function name.
- [Temploy](https://picasso.toptal.net/fx-4207-select-props-are-displayed-incorrectly)
- Check https://picasso.toptal.net/?path=/story/forms-select--select on temploy, on small screens it should not mess up the width of the props table.
| ![image](https://github.com/toptal/picasso/assets/5845160/74db4f29-4309-4c1b-8184-97f90e0c64a6) | ![image](https://github.com/toptal/picasso/assets/5845160/9cb6a095-c2f9-4978-8b6c-7c91b38d6f04) |
- [NA] Add changeset according to …

docs: summarize defaultValue for filterOptions in a sentence

---

cypress/component/DatePicker.spec.tsx
cypress/component/Dropdown.spec.tsx
cypress/component/Modal.spec.tsx
cypress/component/Select.spec.tsx
packages/picasso/src/test-utils/get-happo-targets/get-checkpoints.test.ts
packages/picasso/src/test-utils/get-happo-targets/get-happo-targets.test.ts

[FX-4198]
This pull request adds visual tests for
- `DatePicker` `numberOfMonths` property (as it is behaviour is influenced by screen width)
- `Modal` behaviour on all screens
- [Temploy](https://picasso.toptal.net/fx-4198-add-all-breakpoints-as-targets-in-cypress-tests)
- All checks should pass, the images should be generated
> All …

test: modal and date picker

---

jest.setup.js
jest.spec.mjs
packages/picasso-rich-text-editor/src/LexicalEditor/utils/hasChildDOMNodeTag.test.ts
packages/picasso-rich-text-editor/src/LexicalEditor/utils/hasChildDOMNodeTag.ts
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/CodeBlockNode.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/index.ts

[FX-4184]
This PR brings `CodeBlockNode`, which is block level element.
```jsx
<CodeBlockNode>
// text node will be in different PR
<CodeBlockTextNode>any text</CodeBlockTextNode><LineBreakNode />
<CodeBlockTextNode>  any other text and so on</CodeBlockTextNode>
</CodeBlockNode>
```
- check the code
<details>
<br /> …

feat: add CodeBlockNode

---

.changeset/poor-buckets-provide.md
packages/picasso/src/PageContent/styles.ts

[FX-4213]
Page content should have a different background color according to the BASE design.
- [Temploy](https://picasso.toptal.net/fx-4213-align-page-background-with-base)
- Check visual changes
- https://picasso.toptal.net/?path=/story/picasso-introduction--introduction and https://picasso.toptal.net/fx-4213-align-page-background-with-base/?path=/story/picasso-introduction--introduction
- [N/A] Covered with tests ([visual …

fix: page background color

---

packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/CodeBlockPlugin.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/CodeBlockTextNode.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/index.ts

[FX-4184]
In this pull request, we
- add `CodeBlockTextNode` which is inline level element (text).
- register new node transform, where we check TextNode and if its parent is CodeBlockNode, we transform it to CodeBlockTextNode. It is similar to how Lexical is doing it internally.
```jsx
<CodeBlockNode>
<CodeBlockTextNode>any text</CodeBlockTextNode><LineBreakNode />
<CodeBlockTextNode>  any other text and so on</CodeBlockTextNode>
</CodeBlockNode>
```
You might ask why we need `CodeBlockTextNode`. 
Because inside `CodeBlock` we don't allow any inline formatting (bold, italic, ...)
- check the code
- codemod …

feat: add CodeBlockTextNode

---

packages/picasso-rich-text-editor/src/LexicalEditor/styles.ts
packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso-rich-text-editor/src/RichText/components/styles.ts
packages/picasso-rich-text-editor/src/RichTextEditor/story/Code.example.tsx
packages/picasso-rich-text-editor/src/RichTextEditor/story/Default.example.tsx
packages/picasso-rich-text-editor/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
packages/picasso-rich-text-editor/src/plugins/CodePlugin/CodeButton.tsx
packages/picasso-rich-text-editor/src/plugins/ImagePlugin/components/ImagePluginButton/ImagePluginButton.tsx
packages/picasso-rich-text-editor/src/plugins/LinkPlugin/LinkPluginButton.tsx
packages/picasso-rich-text-editor/src/plugins/api.tsx
packages/picasso-rich-text-editor/src/utils/html-to-hast.ts

[FX-4184]
When we are using codeBlock or heading, we don't allow to format inner text nodes. We used to have this condition locally only for heading, but now we need to share this information across custom plugins
- [Temploy](https://picasso.toptal.net/fx-4184-rte-code-block-4)
- check the code and you can test that when you use heading, all inline formats are disabled. You can do it only locally, till all other PRs are merged to feature/branch.
- Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- …

feat: add disableFormatting functionality

---

packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/CodeBlockNode.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/utils/getFirstCodeNodeOfLine.test.ts
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/utils/getFirstCodeNodeOfLine.ts
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/utils/index.ts

[FX-4184]
move `getFirstCodeNodeOfLine` to separate function and cover it with tests
- Temploy
- Make sure that additions and changes on …

test: cover getFirstCodeNodeOfLine with unit tests

---

packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/CodeBlockButton.tsx

[FX-4184]
We had two issues:
- when an empty line was converted CodeBlock, it was not looking nice. The problem was that even if there was no text, we were appending the CodeBlock with TextNode. Empty TextNode has no height, so I added a condition to not add the empty TextNode. Instead the BR appears by default.
- Disabling inline formatting was not working correctly as it was triggered from two places that were overlapping, so after moving it into one place it works as expected
- [Temploy](https://picasso.toptal.net/fx-4184-rte-code-block-8)
| Insert …

fix: disabled inline formating and empty line in code block

---

.changeset/strange-kids-play.md
packages/picasso-provider/src/Picasso/PicassoGlobalStylesProvider.tsx

[FX-4218](https://toptal-core.atlassian.net/browse/FX-4218)
Previously the context setters for `PicassoGlobalStylesProvider` were not taking the previous context value into account properly. This caused the property values of `hasDrawer`, `hasSidebar` and `hasTopbar` to be overridden when one of them changes.
- [Temploy](https://picasso.toptal.net/fx-4218-sidebar-changes-color-after-drawer-is-opened)
- Change any `Page` story code to the following:
<details>
<summary>reproduction code</summary>
<br />
```ts
import React, { useState } from 'react'
// In actual application you can simply do
// import Picasso from '@toptal/picasso-provider'
import { default as Picasso } from '@toptal/picasso-provider'
import {
Grid,
Page,
Container,
Drawer,
Menu,
Typography,
} from '@toptal/picasso'
const …
```

fix: properly set context value in PicassoGlobalStylesProvider

---

.changeset/honest-stingrays-lick.md
cypress/component/RichTextEditor/Default.spec.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/styles.ts

[FX-4231]
This pull request fixes the placeholder wrapping in Rich Text Editor.
- [Temploy](https://picasso.toptal.net/fx-4231-rte-word-wrap-is-not-working)
- Check the added visual test
| <img width="355" alt="Screenshot 2023-08-14 at 13 44 07" src="https://github.com/toptal/picasso/assets/1390758/e9294cdd-ddf8-4c14-bdfd-77ba8833fe47"> | <img width="394" alt="Screenshot 2023-08-14 at 13 43 28" src="https://github.com/toptal/picasso/assets/1390758/6099fafa-57ad-4337-8eeb-5c7c547f29cc"> |
- [N/A] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been …

fix: placeholder wrap in RTE

---

cypress/component/BarChart.spec.tsx

[FX-NNNN]
The screenshot in question sometimes has tooltip triggered, causing unwanted diffs in happo report.
Tooltip is not relevant to this test so it can be safely disabled.
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-flaky-test)
- Happo report should have no changes (or the final state should have no tooltip)
- Tests pass
- [n/a] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [n/a] Ensure that deployed demo …

chore: fix flaky screenshot

---

.changeset/silly-snails-tickle.md
packages/picasso-forms/src/Form/mutators/set-active-field-touched.ts

We have the final form mutator crashing sometimes https://toptal-core.slack.com/archives/CERF5NHT3/p1692093998693089?thread_ts=1691993118.653259&cid=CERF5NHT3
This PR attempts to fix the problem by applying defencive coding without understanding the root cause because user could not reproduce. 
- [Temploy](https://picasso.toptal.net/fx-fix-crashing-form-mutator)
> **GitHub Bot: …

fix: sometimes crashing mutator

---

.changeset/light-trainers-walk.md
packages/picasso/src/TagRectangular/story/Variants.example.tsx
packages/picasso/src/TagRectangular/styles.ts
packages/picasso/src/TagRectangular/types.ts

[FX-3949]
Added blue light color to TagRectangular
- Check Temploy
| ![image](https://github.com/toptal/picasso/assets/14070311/52a083f4-dc27-4503-a7da-04485c5b02c4) | ![image](https://github.com/toptal/picasso/assets/14070311/ba3ff87b-2d44-4138-8aea-99af00289241)|
<details>
<br />
</details>
<details>
<summary>PR …

feat: add blue light color to TagRectangular

---

docs/decisions/18-spacings.md

[FX-4226]
This pull request adds an RFC for introducing new BASE design spacings described in https://toptal-core.atlassian.net/wiki/spaces/Base/pages/3217031216/Spacing.
The overall plan is presented in https://toptal-core.atlassian.net/wiki/spaces/FE/pages/3389194785/Spacing.
- Please review the https://github.com/toptal/picasso/blob/FX-4426-expose-base-spacing/docs/decisions/18-spacings.md
<details>
<br />
</details>
<details>
<br /> …

docs: add decision on spacing in picasso

---

.changeset/soft-pans-fail.md
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/utils/create-lexical-theme.ts

[FX-4256]
The heading on RTE assumed the default styling from the browser. We are now providing the styles for it from our own typography package
- [Temploy](https://picasso.toptal.net/fx-4256-set-proper-styles-to-h3-in-richtexteditor)
- Check temploy and Happo
No Screenshots
<details>
<br />
</details>
<details>
<br /> …

fix(rich-text-editor): apply typography styles to RTE headings

---

.changeset/calm-wombats-joke.md
packages/picasso-rich-text-editor/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx

[FX-4294]
Currently, we have a fixed value for the heading select width of `123px`, I'm 100% sure why that number specifically. The value is too short for the menu and causes a scrollbar to show. I'm setting the value to auto, so it automatically size itself to the needed size without using scrollbars
- [Temploy](https://picasso.toptal.net/fx-4294-scrollbar-on-rte-heading-select)
- Check temploy
| ![image](https://github.com/toptal/picasso/assets/5845160/ba1a8db7-5c35-4388-8736-80065d2b5845) | ![image](https://github.com/toptal/picasso/assets/5845160/968973ae-f42f-4e2b-8c21-99140e1eac0d) |
- [NA] Covered with tests …

fix(rich-text-editor): set width auto to headings select

---

.changeset/chatty-rice-design.md
.changeset/eleven-games-occur.md
packages/picasso-provider/src/Picasso/PicassoProvider.tsx
packages/picasso-provider/src/Picasso/config/theme.ts
packages/picasso/src/Modal/story/Tooltips.example.tsx

[FX-4241]
Tooltip and Modal now have the same z-index CSS prop, which means the one to be
written last on HTML will be the one on top. This allows Modal to overlay
tooltips behind, and allow Tooltips to work inside Modals.
To be noted, that this is a very special case, most Tooltips will close
automatically when a Modal is open, if, for whatever reason, they still need to
be open, they will be overlaid by Modal.
- [Temploy](https://picasso.toptal.net/fx-4241-tooltips-are-rendered-over-the-modal-and-backdrop)
- Check on temploy
| ![image](https://github.com/toptal/picasso/assets/5845160/82ad3c15-f0b0-46f2-ad2a-17a6ca95a31 …

feat(tooltip): change tooltip zindex to the same as modal

---

.changeset/lovely-socks-cheat.md
packages/picasso-provider/src/Picasso/PicassoProvider.tsx
packages/picasso-provider/src/Picasso/config/index.ts
packages/picasso-provider/src/Picasso/config/spacings.ts
packages/picasso-provider/src/Picasso/config/theme.ts
packages/picasso-provider/src/Picasso/utils/index.ts
packages/picasso-provider/src/Picasso/utils/spacings.test.ts
packages/picasso-provider/src/Picasso/utils/spacings.ts
packages/picasso-provider/src/index.ts
packages/picasso/src/Container/Container.tsx
packages/picasso/src/Container/story/Default.example.tsx
packages/picasso/src/utils/index.ts
packages/shared/src/types.ts

[FX-4259]
Add new spacing values to Picasso, described in BASE. 
RFC: https://github.com/toptal/picasso/blob/master/docs/decisions/18-spacings.md#technical-details
- Use temploy to play with SPACING variables
Example:
```
import { SPACING_4, SPACING_6 } from '@toptal/picasso/utils'
const Example = () => (
<div>
<Container bottom={SPACING_6}>Some text</Container>
<Container left={SPACING_4}>Some more text with a small margin</Container>
</div>
)
```
Example of new `spacings` variable coming from the theme:
```
export default ({ palette, sizes: { borderRadius }, spacings: { SPACING_6 } }: Theme) => {
...
}
```
<details>
<br /> …

feat: [FX-4259] add new spacing values to picasso

---

.changeset/gold-frogs-itch.md
packages/picasso-rich-text-editor/src/utils/html-to-hast.ts

[SCR-3753]
This PR fixes a bug where the alt prop was not working on RichTextEditor component
- Go to https://picasso.toptal.net/SCR-3753-rich-text-fix-html-to-hast-util?path=/story/components-richtext--richtext
- Open the Devtools and inspect the image (as I did on the screenshots below)
- You should be able to see the `alt` property
|![image](https://github.com/toptal/picasso/assets/99184582/c981e8e8-74ca-45a7-8c12-457b2eaaeebd)|![image](https://github.com/toptal/picasso/assets/99184582/19c604c8-ded9-4139-8ee8-d8913c328568)
| …

fix(rich-text-editor): enable alt prop

---

.changeset/blue-dodos-allow.md
packages/picasso-rich-text-editor/src/LexicalEditor/styles.ts
packages/picasso-rich-text-editor/src/RichText/components/styles.ts
packages/picasso-rich-text-editor/src/plugins/CodeBlockPlugin/nodes/CodeBlockTextNode.tsx

[FX-4270]
Tab sizes between RichText and RichTextEditor must be equal (in CodeBlocks).
Right now, tab size in RichText is 8, in RichTextEditor is 1. 
They both must be 2.
- Check RichText stories on temploy
- Add code block and try adding several tabs.
- Compare appearance in RTE and RichText
<details>
<br />
</details>
<details>
<br /> …

fix: [FX-4270] align tab sizes in RichText and RichTextEditor

---

Dockerfile

Setting the mirror is optional, and recently we are having problems with the mirror [we setup a long time ago](https://github.com/toptal/picasso/commit/446974cf9b434fc9ac5e891a42d4093157f1fcd1), for unknown reasons
- [Temploy](https://picasso.toptal.net/fix/change-alpine-mirror)
No screenshots
- [NA] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [NA] Ensure the changed/created components have not …

ci(Dockerfile): remove setting of alpine mirror

---

.changeset/swift-bugs-sparkle.md
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx

[FX-4318]
Users want to be able to do complex things with labels, like for example have in label icon and Tooltip. For this we change label type on FieldWrapper from `string` to `ReactNode`
- [Temploy](https://picasso.toptal.net/fx-4318-allow-reactnode-type-for-labels-in-form-elements)
<details>
<br />
</details>
<details>
<br />
1. You have no …

fix: allow label on FieldWrapper to be ReactNode

---

.changeset/random-changeset-name.md
packages/picasso-forms/package.json
yarn.lock

This pull request reverts the package update done in https://github.com/toptal/picasso/pull/3758 due to the error reported in https://github.com/final-form/final-form-arrays/issues/95 (introduced in https://github.com/final-form/final-form-arrays/releases/tag/v3.1.0).
The problem was discovered when tests started to fail in https://github.com/toptal/staff-portal/pull/10993.
Staff Portal with this pull request applied
- [N/A] Ensure that deployed demo has expected results …

fix: revert dependency update

---

.changeset/shaggy-paws-hide.md
packages/picasso-forms/src/Field/Field.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
yarn.lock

[FX-4344]
This pull request restores the typing after https://github.com/toptal/picasso/pull/3856/files#diff-08a8fe1a5f1850b294d0ab3c9d60773422eb33ec29d310a6c98fdd48e0b0eefcL8 change. Additionally, it fixes the lockfile in main branch.
The reason why type check fails in consumer projects is not clear.
It was discovered that if the following type definition 
```ts
// packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
export type Props<TWrappedComponentProps, TInputValue> = FieldProps<TWrappedComponentProps, TInputValue>
```
is replaced with
```ts
// packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
export type Props<TWrappedComponentProps, TInputValue> = Omit<FieldProps<TWrappedComponentProps, TInputValue>, 'randomText'>
```
type checks starts working in Staff Portal. Adding …

fix: field typing and lockfile

---

.changeset/neat-impalas-notice.md
cypress/component/Drawer.spec.tsx
cypress/component/Page.spec.tsx
packages/picasso/src/Drawer/Drawer.tsx

[FX-4247](https://toptal-core.atlassian.net/browse/FX-4247)
Due to the original Picasso implementation, `PicassoRoot` is the default container for all popup dialogs. This causes most popup items to lock scroll on `PicassoRoot` instead of `body`. While it works in most scenarios, when `Drawer` is open on a page with a sticky sidebar and long content that is scrolled down, scroll should be locked on `body`, otherwise it prevents the proper sticky positioning of the sidebar.
- [Temploy](https://picasso.toptal.net/fx-4247-wrong-sidebar-appearance-when-drawer-opens)
- Verify the new Happo screenshot has the proper sidebar state
- All the other tests should pass
- Check the client-portal PR https://github.com/toptal/client-portal/pull/7246 (test examples are in the description)
| Before. …

fix: lock body scroll for `Drawer`

---

.storybook/stories/tutorials/spacings/story/index.jsx

[FX-4261]
⚠️ Changes to stories are updated in https://github.com/toptal/picasso/pull/3870
This pull request updates the `How to use spacings` tutorial to depict the latest changes in spacing.
- [Temploy](https://picasso.toptal.net/fx-4261-update-guidelines-on-spacing-usage-3)
- See the https://picasso.toptal.net/fx-4261-update-guidelines-on-spacing-usage-3/?path=/story/tutorials-how-to-use-spacings--how-to-use-spacings
- [N/A] Annotate all `props` in component with …

fix: spacings in tutorial

---

.changeset/fresh-crabs-laugh.md
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx

Fix form  field's label rendering when label is not provided
- [Temploy](https://picasso.toptal.net/fix-form-datepicker-label)
| <img width="284" alt="Screenshot 2023-09-07 at 17 31 22" src="https://github.com/toptal/picasso/assets/65539882/bed8d6c4-c3e3-4fe4-90bf-5f2570a38196">| <img width="312" alt="Screenshot 2023-09-07 at 17 31 43" src="https://github.com/toptal/picasso/assets/65539882/a36a2dbb-526a-406d-b4b3-3b387b0404eb">|
<details>
<summary>PR …

fix(FieldLabel): form label rendering

---

.changeset/gold-toys-unite.md
cypress/component/Page.spec.tsx
packages/picasso-provider/src/Picasso/NotificationsProvider/NotificationsProvider.tsx
packages/picasso-provider/src/Picasso/RootContext.ts
yarn.lock

[FX-4367]
This pull request fixes the notifications display when drawer is opened on the page – even if there is a TopBar on the page, notifications should not have `4.5rem` top padding when the drawer is opened (discussed in https://toptal-core.slack.com/archives/GG3F4AS4T/p1695287511772779).
⚠️ This fix is blocking the https://toptal-core.atlassian.net/browse/FX-4344
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-notifications-in-drawer)
- Test in Staff Portal
- check out https://github.com/toptal/staff-portal/pull/11085, run `yarn install`
- log in as any user who has open operational issues (for example, https://staff-portal.toptal.net/staff/3254509)
- run Staff Portal via `yarn start`, open operational issues drawer, and click `Resolve` button for any of issues
- the notification …

fix: notifications display in drawer

---

.changeset/tender-boxes-marry.md
packages/picasso-provider/src/Picasso/config/spacings.ts

[FX-4379]
This pull request makes at least one property of the `PicassoSpacing` class public. It is needed for Jest comparison to work, as now Jest does not see difference between `SPACING_2` and `SPACING_4` as both spacings are just `{ }`.
```jsx
<Container left={SPACING_2} />
...
expect.objectContaining({
left: SPACING_2, // succeeds, as there is no difference between SPACING_2, SPACING_4, etc. as all of them are { }
})
```
This pull request makes the code below fail and actually check if the proper spacing is provided
```jsx
<Container left={SPACING_2} />
...
expect.objectContaining({
left: SPACING_4, // fails
})
```
- [Temploy](https://picasso.toptal.net/FX-NULL-introduce-public-property)
- [N/A] Make sure that additions and changes on the design follow …

fix: make field public

---

.changeset/stale-cherries-clap.md
packages/picasso-rich-text-editor/src/RichText/hooks/useRichText/styles.ts
packages/picasso-rich-text-editor/src/RichText/hooks/useRichText/useRichText.tsx
packages/picasso-rich-text-editor/src/RichText/story/HTML.example.tsx

[FX-4302]
This pull request fixes the display of formatted text inside of links. The color should follow the link color, plus it should react when link is visited.
- [Temploy](https://picasso.toptal.net/fx-4302-rte-link-formatting-is-missing-when-italic-bold-is-applied)
- Play around with links at https://picasso.toptal.net/fx-4302-rte-link-formatting-is-missing-when-italic-bold-is-applied?path=/story/components-richtext--richtext
Before
https://github.com/toptal/picasso/assets/1390758/cf720963-3362-4e97-8c18-089b3340a622
After
https://github.com/toptal/picasso/assets/1390758/570ba7cd-95b5-44ea-a786-d70f0701cf40
> …

fix: display of formatted text in links

---

.changeset/many-papayas-serve.md
cypress/component/BarChart.spec.tsx
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/utils/find-top-domain/find-top-domain.ts

[SDE-1274]
Hi guys! We in Service Delivery are using `BarChart` to render spend chart and add label to all columns which are related to periods with breaks.
In some cases it may happen that we don't have spend data for given period but still want to show breaks icon. Currently it looks incorrect (see the original ticket). The reason for this is inability of BarChart to determine correct boundaries for value axis. In this PR I introduce a property that allows controlling boundaries of the axis manually.
Please let me know if the change is incorrect or there's a better way to achieve it. My goal here is to fix the bug so I'm pretty flexible with choosing the way to do it.
Update:
following comments to the PR I changed the implementation. Now instead of adding a prop to customize boundaries …

fix(picasso-charts): fix BarChart for cases with 0 values

---

.storybook/components/PicassoBook/Page.js
packages/picasso-rich-text-editor/src/RichText/story/index.jsx

[FX-4437]
Visual test for rich text (_HTML from FE for live-editing preview_ in https://picasso.toptal.net/?path=/story/components-richtext--richtext) is flaky and sometimes does not have enough time to render fully, so the screenshot is taken before it renders.
This pull request sets delay so story can properly render (there are other approaches available in https://docs.happo.io/docs/storybook#setting-delay-for-a-story).
The delay is applied
- [Temploy](https://picasso.toptal.net/fx-4437-fix-flaky-rich-text-visual-test)
The behaviour can be observed by going to https://picasso.toptal.net/?path=/story/components-richtext--richtext and quickly scrolling to the story
https://github.com/toptal/picasso/assets/1390758/262681b2-c31d-4fa5-89fa-a8c78fc1c4df
- [N/A] Add …

fix: set delay for the screenshot

---

.changeset/two-foxes-type.md
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/DatePicker/constants.ts
packages/picasso/src/Modal/story/Default.example.tsx
yarn.lock

[FX-4445]
This pull request makes DatePicker popper fit the **viewport** in the most extreme cases when the screen is small, so overlapping the input is allowed ([confirmed with Design Team in Slack](https://toptal-core.slack.com/archives/CERF5NHT3/p1698319400470039?thread_ts=1697120927.351179&cid=CERF5NHT3))
- [Temploy](https://picasso.toptal.net/FX-NULL-fit-date-picker)
- [Storybook] Navigate to https://picasso.toptal.net/FX-NULL-fit-date-picker/?path=/story/overlays-modal--modal and trigger the date picker from the `Default` case modal on different screen sizes
- [Talent Portal] Follow the steps
- check out branch from https://github.com/toptal/talent-portal-frontend/pull/5535
- run `yarn install`
- log in as https://staff-portal.toptal.net/talents/4220731
- run `yarn start:staging`
- …

fix: always keep date picker calendar popup inside of viewport

---

.changeset/orange-falcons-fix.md
packages/picasso/src/Section/Section.tsx

[FX-4465](https://toptal-core.atlassian.net/browse/FX-4465)
A bug in Section can be encountered in master when passing non-string children as a section subtitle. This resulted in  `<p>` to contain `<div>` or other invalid DOM elements, which is caused by incorrectly checking the type of `title` instead of `subtitle`.
- [Temploy](https://picasso.toptal.net/fx-4465-i-am-facing-an-issue-while-section-component-with-subtitle-as-the-test-for-it-fai)
- Using any story in Storybook, paste the following code into the story editor:
```
import { Section, Tag } from '@toptal/picasso'
return (
<Section
variant='withHeaderBar'
title='String title'
subtitle={
<Tag.Rectangular variant='light-grey'>
Non-string child
</Tag.Rectangular>
}
>Hello</Section>
) …
```

fix(section): correct type condition for subtitle

---

.changeset/curvy-papayas-explain.md
cypress/component/RichTextEditor/Default.spec.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.test.tsx
packages/picasso-rich-text-editor/src/LexicalEditor/LexicalEditor.tsx
packages/picasso-rich-text-editor/src/LexicalEditorToolbarPlugin/LexicalEditorToolbarPlugin.tsx
packages/picasso-rich-text-editor/src/RichTextEditorToolbar/RichTextEditorToolbar.tsx
packages/picasso-rich-text-editor/src/plugins/api.tsx

[FX-4435]
By default when the Lexical editor starts with the selection `null`, as soon as we enter the editable area, the selection is set. When we focus the editor for the first time by clicking in the toolbar area, the editor still does not have any selection, so clicking triggers no action as the editor does not know to what position to insert new nodes.
I fixed the issue by disabling the toolbar buttons until the selection is selected.
As mentioned, this edge case is only happening for the first focus of the editor.
- [Temploy](https://picasso.toptal.net/fx-4435-rte-image-button)
1. check any story of RichTextEditor
2. click in the toolbar area of the editor
- The toolbar should still be disabled
- editor should be in focus state
3. click in the editable area
- the toolbar should not …

fix: disable toolbar when no selection is available

---

.changeset/blue-tables-vanish.md
packages/picasso/src/Modal/Modal.tsx
packages/picasso/src/Modal/__snapshots__/test.tsx.snap
packages/picasso/src/PromptModal/__snapshots__/test.tsx.snap
packages/picasso/src/utils/Modal/__snapshots__/test.tsx.snap

[FX-4353]
We have the same issue as we had with Drawer before. We use Dialog from MUI, which is not using body lock, but container lock. We already use our custom body scroll lock, so we just need to disable the one from MUI. 
You can use this [codesandbox](https://codesandbox.io/s/picasso-master-39-forked-ysl6g8?file=/package.json) with alpha package. The easiest is to check the page in [full screen](https://ysl6g8.csb.app/) and just try to open the modal. The sidebar should look the same as when closed.
| ![image](https://github.com/toptal/picasso/assets/6830426/1c4533b1-2365-470a-a196-0ca892023ce7) | …

fix: disable mui scroll lock

---

.github/workflows/format-dependabot-prs.yml
.husky/pre-push
README.md
commitlint.config.js
davinci.yaml
docs/contribution/github-workflow.md
lerna.json

[FX-4409]
After [RFC-39](https://toptal-core.atlassian.net/wiki/spaces/TECHX/pages/3243901281/RFC-39+Unify+commit+messages+and+PR+titles) being completed, we now need to move on to [Toptal commit messages](https://toptal-core.atlassian.net/wiki/spaces/ENG/pages/210665897/Commit+Message+Quality)
- [Temploy](https://picasso.toptal.net/fx-4409-adoption-of-toptal-commit-message-format)
- Checkout branch and try to commit something and push, it should fail when the message follows conventional commits and succeed on Toptal's format
No screnshots
- [NA] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution …

[FX-4409] Change commit format to Toptal's

---

package.json
yarn.lock

[FX-4497]
Our old storybook plugins are still using PostCSS on v7, which has vulnerability right now. I added newer version to resolutions and tested that storybook still works the same
- [Temploy](https://picasso.toptal.net/fx-4497-postcss)
- Storybook should work as before
-  Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed) …

[FX-4497] Add PostCSS to resolutions to fix vulnerability

---

.changeset/few-deers-care.md
packages/picasso/src/Alert/Alert.tsx
packages/picasso/src/Alert/__snapshots__/test.tsx.snap
packages/picasso/src/Alert/story/Actions.example.tsx
packages/picasso/src/Alert/story/index.jsx
packages/picasso/src/Alert/test.tsx

[FX-4502](https://toptal-core.atlassian.net/browse/FX-4502)
An ability to add action buttons has been added. Either `primary` or `secondary` can be passed, size and variants can't be changed beyond what's dictated by BASE. 
- [Temploy](https://picasso.toptal.net/fx-4502-add-option-for-a-cta-button-in-the-alert-component)
- Play around with the `Alert` component on the temploy, there is a new story for alert with actions
- Existing visual tests should not break
| ![image](https://github.com/toptal/picasso/assets/18409292/6108dfa2-57e5-4b5e-8183-df28bbf1e0c4) | …

[FX-4502] Add actions to Alert

---

.changeset/lovely-pumpkins-help.md
packages/picasso/src/Tag/styles.ts
packages/picasso/src/TagRectangular/styles.ts

[FX-4492](https://toptal-core.atlassian.net/browse/FX-4492)
Remove the default transitions from all `Tag` components.
I was not able to disable them in a single place (in theory, it should be possible to use `overrides` in `PicassoProvider`, however, in practice it just didn't work at all, probably due to class overrides inside components).
- [Temploy](https://picasso.toptal.net/fx-4492-tag-components-have-leftover-styles-from-mui)
- You can use the code below to test the transition, both on master and temploy
```
import React, { useState } from 'react'
import { Button, Container, Tag } from '@toptal/picasso'
const [type, setType] = useState('red')
return (
<Container flex>
<Button
onClick={() =>
setType(prevType => (prevType === 'green' ? 'red' : 'green'))
} …
```

[FX-4492] Remove unwanted tag transitions

---

.github/workflows/release.yml

Reverting changes because IAP supporting jenkins actions doesn't work with public repositories yet.
A bit of context https://toptal-core.slack.com/archives/C03GLMT6L7N/p1700480270433659
Run the workflows
<details>
<br /> …

Revert IAP changes and fix proxy

---

.changeset/hip-lions-invite.md
packages/picasso-tailwind/package.json

- [Temploy](https://picasso.toptal.net/hotfix/picasso-tailwind-exports)
<details>
<br />
</details>
<details> …

Fix picasso-tailwind package.json exports

---

.github/workflows/format-dependabot-prs.yml

[FX-4525]
This pull request makes workflow that updates `dependabot` pull request title to use regular GitHub token.
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-token-passing)
- Tested at https://github.com/toptal/davinci/pull/2232, the pull request title was updated
- [N/A] Ensure that deployed demo has expected results and good …

[FX-4525] Do not use GSM for getting GitHub token

---

.changeset/red-tigers-join.md
packages/picasso-forms/package.json

[FX-4504]
To make the work easy for users using RTE we don't require it as a `peerDependency` anymore, but as direct dependency. This effectively removes the need to install RTE as a dependency on the host project
- [Temploy](https://picasso.toptal.net/fx-4504-set-rich-text-editor-as-direct-dependency-in-forms)
- Check temploy if RTE is working
No screenshots
<details>
<br />
</details>
<details>
<br /> …

[FX-4504] Move RTE to a direct dependency of forms

---

.changeset/pink-carrots-protect.md
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelector/story/Status.example.tsx

[FX-4509]
Users want to be able to highlight problematic tag inside tag selector.
- [Temploy](https://picasso.toptal.net/fx-4509-tagselector)
<details>
<br />
</details>
<details>
<br />
1. Something …

[FX-4509] Add a possibility to show an error status on tags

---

.changeset/perfect-apricots-buy.md
packages/picasso/src/Alert/Alert.tsx
packages/picasso/src/Alert/__snapshots__/test.tsx.snap
packages/picasso/src/Alert/story/Actions.example.tsx

[FX-4529](https://toptal-core.atlassian.net/browse/FX-4529)
According to BASE, the action buttons in `Alert` should also support their split variants with dropdown menus. 
Each button can either be normal or split, with only two variants available (one of each at the time only).
- [Temploy](https://picasso.toptal.net/fx-4529-extend-cta-button-in-the-alert-component-to-use-the-split-button-variant-as-well)
- See if the code and API looks good
- Look at the new examples for `Alert` on the temploy
<details>
<br />
- `@toptal-anvil ping …

[FX-4529] Add split button support to `Alert`

---

.storybook/preview.js

[FX-4541]
This pull requests adds BASE viewports to Storybook `@storybook/addon-viewport` addon configuration (https://storybook.js.org/docs/react/essentials/viewport).
- [Temploy](https://picasso.toptal.net/FX-NULL-tune-storybook)
- Verify new viewports at the temploy
https://github.com/toptal/picasso/assets/1390758/af6063a3-96f0-4982-a14e-8f13787f3636
- [N/A] …

[FX-4541] Use BASE viewports in Picasso Storybook

---

ci/jobs/build-image/Jenkinsfile

[FX-3913]
This pull request removes extra check for existing image in Google Container Registry (GCR), we no longer hope there there is anything there due to migration to Google Artifact Registry (GAR). Also, we no longer push anything to GCR, only to GAR.
- [Temploy](https://picasso.toptal.net/fx-3913-replace-gcr-with-ar-in-temploy-helm-run-in-davinci)
- The ✅ https://jenkins-build.toptal.net/job/picasso-build-image/13963/console was built, it
- reuses updated Jenkinsfile from this branch
- builds image for the last commit from this branch
- the image is created in https://console.cloud.google.com/artifacts/docker/toptal-hub/us-central1/containers/picasso/sha256:767105823eadf9b0c1104137a5164cd553c2044f0d1fbd53147194302081adb3?authuser=1&hl=en&project=toptal-hub …

[FX-3913] Remove GCR from Jenkinsfile

---

.storybook/stories/tutorials/optimizing-for-bundle-size/story/index.tsx
yarn.lock

[FX-4505]
Add documentation on optimizing Picasso usage for bundle size
- [Temploy](https://picasso.toptal.net/fx-4505-add-guidelines-on-minimising-bundle-size-when-using-picasso-forms)
- Check temploy for new Tutorial
No screenshots
- [NA] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- [NA] codemod is created and showcased in the changeset
- [NA] test alpha package of Picasso in StaffPortal
<details>
<br …

[FX-4505] Add doc on optimizing Picasso for bundle size

---

.changeset/loud-geese-destroy.md
packages/picasso/src/TimePicker/TimePicker.tsx
packages/picasso/src/TimePicker/story/Default.example.tsx
packages/picasso/src/TimePicker/test.tsx

[FX-3114]
This pull request fixes the behavior of `TimePicker`. It **no longer emits incorrect time values** like "12:--", it either emits proper value that was entered or it emits empty value so the form validation is properly triggered.
Chrome and Firefox prove their own in-browser validation, but even latest Safari fails to do so, so we should not rely on the browser-implementation.
**Chrome**
**Firefox**
**Safari** 
- Check the very first example in [temploy](https://picasso.toptal.net/fx-3114-timepicker-validation-of-the-value-is-not-working-properly-in-safari?path=/story/forms-timepicker--timepicker) and try to submit the form
Before
https://github.com/toptal/picasso/assets/1390758/0620c7fa-e868-49bb-8c08-8545116c7c28
After …

[FX-3114] Do not emit incorrect time values

---

.changeset/brown-pigs-tie.md
.changeset/neat-lies-mate.md
packages/picasso-forms/src/Form/story/index.jsx
packages/picasso/src/index.ts

[FX-4554]
This pull requests exports `useFieldsLayoutContext()` hook, so consumers can build their own form extensions to match the layout.
- [Temploy](https://picasso.toptal.net/FX-NULL-export-useFieldsLayoutContext)
- Test the code below in Storybook, the buttons form footer should be adaptable
```
import { Container } from '@toptal/picasso'
import { useFieldsLayoutContext } from '@toptal/picasso'
import {
FormNonCompound as Form,
Input,
SubmitButton,
Switch,
} from '@toptal/picasso-forms'
const initialValues = {}
const Buttons = () => {
const { layout } = useFieldsLayoutContext()
return (
<Container style={layout === 'horizontal' ? {
display: 'grid',
gridTemplateRows: 'auto auto',
gridTemplateAreas: `"label input" "hint error"`,
gridTemplateColumns: '272px …
```

[FX-4554] Export useFieldsLayoutContext hook

---

.changeset/purple-onions-glow.md
packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.test.tsx
packages/picasso-query-builder/src/ValidationErrors/ValidationErrors.tsx
packages/picasso-query-builder/src/types/query-builder.ts
yarn.lock

[CPT-1489]
This PR introduces data test id to the validation errors component in the query builder
- Verify testIds includes validationErrors.
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
List …

[CPT-1489] Add data-testid to ValidationErrors in QueryBuilder

---

.changeset/stale-geese-carry.md
packages/picasso/src/Avatar/Avatar.tsx
packages/picasso/src/Avatar/ImageAvatar/ImageAvatar.tsx
packages/picasso/src/Avatar/TextAvatar/TextAvatar.tsx
packages/picasso/src/Checkbox/Checkbox.tsx
packages/picasso/src/PageTopBarMenu/PageTopBarMenu.tsx
packages/picasso/src/Radio/Radio.tsx
packages/picasso/src/Tooltip/Tooltip.tsx
packages/shared/src/types.ts

[FX-4635](https://toptal-core.atlassian.net/browse/FX-4635)
Some components pass `{...rest}` to a particular DOM element, however `data-private` sometimes has to be set for different DOM elements (for example, for Checkbox, label has to be private, not the checkbox itself).
This PR adresses most problems we found.
- [Temploy](https://picasso.toptal.net/fx-4635-adjust-picasso-components-to-properly-handle-data-private-attribute)
- Code should look good, attributes should be passed to proper elements
<details>
<br />
- `@toptal-anvil ping …

[FX-4635] Pass data-private to some components manually

---

.changeset/tidy-jokes-end.md
packages/shared/src/types.ts

[FX-4635](https://toptal-core.atlassian.net/browse/FX-4635)
There was a mistake in https://github.com/toptal/picasso/pull/4056, `data-private` is boolean, not string 
- Temploy
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this …

[FX-4635] Fix `data-private` type

---

.changeset/strange-squids-retire.md
Dockerfile
packages/picasso-tailwind/bin/build.sh
packages/picasso-tailwind/package.json
packages/picasso-tailwind/src/index.js
packages/picasso-tailwind/tsconfig.build.json
tsconfig.json

[FX-4590]
Refactor Tailwind preset from typescript, so it can be also used in Picasso itself for development.
- [Temploy](https://picasso.toptal.net/FX-4590-tailwind-preset)
- It was tested in the Picasso [here](https://github.com/toptal/staff-portal/pull/10932/files)
- and in the Staff Portal [here](https://github.com/toptal/staff-portal/pull/11681)
- Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

[FX-4590] Refactor from typescript to plain javascript

---

.eslintrc.js
eslint-local-rules.js
package.json
yarn.lock

[FX-4486](https://toptal-core.atlassian.net/browse/FX-4486)
When we deprecate something, it MUST have a referencing ticket number for the scheduled removal.
This new set of eslint rules covers that, both `@deprecated` comments and deprecation warning hooks.
- [Temploy](https://picasso.toptal.net/fx-4486-create-eslint-rule-to-catch-deprecated-parts-not-scheduled-for-removal)
- Check out the branch
- Search for `@deprecated` comments, they should now all be warnings
- Try to add a ticket number to it, the warning should go away
- Look for `usePropDeprecationWarning` or `useDeprecationWarning` calls in the codebase
- it should also not be possible to use a hook without a TODO + ticket comment combo without spawning a warning
- [n/a] Add changeset according to …

[FX-4486] Lint all deprecation warnings to have a ticket number

---

.changeset/lemon-chairs-compare.md
packages/picasso/src/Pagination/__snapshots__/test.tsx.snap
packages/picasso/src/PaginationButton/PaginationButton.tsx

[FX-4630]
Add aria-current to the active button in Pagination
- [Temploy](https://picasso.toptal.net/fx-4630-archive-template-project-frontend-monorepo-repository)
- Open http://localhost:9001/?path=/story/components-pagination--pagination
- Inspect page
- See `aria-current="true"` is added to all active buttons on the page
<details>
<br />
</details>
<details>
<br />
2. …

[FX-4630] Add aria-current to the active button in Pagination

---

.changeset/tidy-crabs-hammer.md
packages/shared/src/types.ts

The `data-private` attribute can have a value of `lipsum` (https://docs.logrocket.com/docs/privacy)
This PR amends the base type to accommodate that
Related thread https://toptal-core.slack.com/archives/CERF5NHT3/p1703713796242789
- Typechecks pass
- [-] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [-] Annotate all `props` in component with documentation
- [-] Create `examples` for component
- [-] Ensure that deployed demo has expected results and good examples
- [-] Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibilit …

Fix data-private type to allow lipsum value

---

.github/workflows/ci.yaml
.github/workflows/davinci-alpha-package.yml
.github/workflows/release.yml

[CI-3043]
The CI team is currently working on replacing the `external-proxy` with Google Identity Aware Proxy (IAP). More info [here](https://cloud.google.com/iap/docs/concepts-overview).
IAP is a Google service that allows control access to web applications running on GCP. It provides a security layer for applications by ensuring that only authenticated and authorized users/service accounts can access them. To programmatically access a resource protected by the IAP, we need to generate a JWT token and pass it alongside the request to authenticate before accessing the protected resource.
Currently, we use the `jenkins-job-trigger-action` to trigger Jenkins jobs from a GH workflow. Since this is a public action repo and to not expose our internal infrastructure implementation, we created …

[CI-3043] Switch to actions/create-jira-deployment

---

jest.spec.mjs
packages/picasso-forms/src/index.ts
packages/picasso-provider/src/Picasso/config/spacings.ts
packages/picasso-rich-text-editor/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/Autocomplete/Autocomplete.tsx
packages/picasso/src/Autocomplete/index.ts
packages/picasso/src/Checkbox/index.ts
packages/picasso/src/DatePicker/DatePicker.tsx
packages/picasso/src/Dropdown/Dropdown.tsx
packages/picasso/src/Dropzone/Dropzone.tsx
packages/picasso/src/FileInput/index.ts
packages/picasso/src/Form/index.ts
packages/picasso/src/Input/Input.tsx
packages/picasso/src/Input/index.ts
packages/picasso/src/ListItem/ListItem.tsx
packages/picasso/src/NumberInput/NumberInput.tsx
packages/picasso/src/OutlinedInput/OutlinedInput.tsx
packages/picasso/src/PasswordInput/PasswordInput.tsx
packages/picasso/src/Radio/index.ts
packages/picasso/src/RadioGroup/index.ts
packages/picasso/src/Select/Select.tsx
packages/picasso/src/SelectBase/types.ts
packages/picasso/src/Switch/index.ts
packages/picasso/src/TagSelector/TagSelector.tsx
packages/picasso/src/TagSelectorInput/TagSelectorInput.tsx
packages/picasso/src/TimePicker/TimePicker.tsx
packages/picasso/src/Tooltip/index.ts
packages/picasso/src/TreeView/TreeView.tsx
packages/picasso/src/utils/kebab-to-camel-case.ts

[FX-4483]
Add Jira tickets for deprecated annotations
- [Temploy](https://picasso.toptal.net/fx-4483-review-and-create-follow-ups-for-deprecated-parts-of-picasso)
- No testing, just check if all docs are ok
No screenshots
- [NA] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
- [NA] codemod is created and showcased in the changeset
- [NA] test alpha package of Picasso in StaffPortal
<details>
<br />
List of …

[FX-4483] Add Jira tickets for deprecated functionality

---

.changeset/few-buckets-knock.md
packages/picasso-query-builder/package.json
packages/picasso-query-builder/src/MultiSelect/MultiSelect.tsx
packages/picasso-query-builder/src/QueryBuilder/story/Default.example.tsx
packages/picasso-query-builder/src/types/query-builder.ts

[CPT-1479](https://toptal-core.atlassian.net/browse/CPT-1479)
- [Temploy](https://picasso.toptal.net/CPT-1479-enable-select-clear-button-for-the-qb)
- Open Query builder story
- On the Default story select `Also plays` rule
- Check if `enableReset` property is working as expected
| ![image](https://github.com/toptal/picasso/assets/112090359/94e1520e-90fc-4d8f-8b6f-d1708850b5e1)| ![Screenshot from 2024-01-10 10-50-17](https://github.com/toptal/picasso/assets/112090359/d41f3590-5b0b-4d83-9c85-1f767215aec9)|
- n/a codemod is created and …

[CPT-1479] Enable select clear button for the qb

---

.changeset/four-chairs-call.md
packages/picasso/src/NativeSelect/NativeSelect.tsx

[FX-4737]
This pull request fixes the bug with passed `enableResetSearch ` prop, introduced in https://github.com/toptal/picasso/pull/4075.
Reason – spread operator is not type safe in this case (`packages/picasso/src/NativeSelect/NativeSelect.tsx`)
No type check using spread operator (no error detected)
Normal typescheck when passing prop directly (error is detected)
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-passing-of-property)
- Tests pass when alpha package is applied in Staff Portal in (please check out https://github.com/toptal/staff-portal/pull/11832 locally and run `yarn test namespaces/jobs/libs/jobs/src/containers/SendJobAwayModal/test.tsx`)
- Another error in Staff Portal Jest tests that appears is fixed in https://toptal-core.atlassian.net/browse/FX-4727
- [N/A] …

[FX-4737] Do not pass enableResetSearch property

---

.changeset/red-weeks-hang.md
packages/picasso-query-builder/src/types/query-builder.ts

[no-jira]
- [Temploy](https://picasso.toptal.net/fix-qb-multiselect-type)
- Fix typing for query builder multiselect
- [N/A] Covered with tests ([visual …

Fix query builder multiselect type

---

.changeset/violet-shoes-rhyme.md
packages/picasso/src/test-utils/TestingPicasso.tsx
yarn.lock

[FX-4727]
This pull request removes `Picasso.injectFirst` directive as it is not relevant to testing environment and removes styles import to avoid errors like
```bash
// Staff Portal
ERROR in ../../../../node_modules/@toptal/picasso/test-utils/TestingPicasso.js 3:0-22
Module not found: Error: Can't resolve './styles.css' in '/Users/aleksandr/toptal/staff-portal/node_modules/@toptal/picasso/test-utils'
resolve './styles.css' in '/Users/aleksandr/toptal/staff-portal/node_modules/@toptal/picasso/test-utils'
using description file: /Users/aleksandr/toptal/staff-portal/node_modules/@toptal/picasso/package.json (relative path: ./test-utils)
Field 'browser' doesn't contain a valid alias configuration
using description file: /Users/aleksandr/toptal/staff-portal/node_modules/@toptal/picasso/packag …
```

[FX-4727] Remove injectFirst and styles import from TestingPicasso

---

.changeset/dry-insects-wink.md
package.json
packages/picasso-charts/package.json
packages/picasso-forms/package.json
packages/picasso/package.json
yarn.lock

[FX-4727]
This pull request reverts `debounce@2.0` update (https://github.com/toptal/picasso/pull/4079), as it causes Staff Portal Cypress tests to fail with the following error
```
@staff-portal/clients-profile-app:   2) Enable Embedded Contract Signing
@staff-portal/clients-profile-app:        when the mutation is not successful
@staff-portal/clients-profile-app:          does not enable embedded contract signing and displays a form error:
@staff-portal/clients-profile-app:      Error: The following error originated from your application code, not from Cypress.
@staff-portal/clients-profile-app:   > Debounced method called with different contexts.
@staff-portal/clients-profile-app: When Cypress detects uncaught errors originating from your application it will automatically fail the …
```

[FX-NULL] Revert debounce update

---

.changeset/friendly-avocados-unite.md
packages/picasso/src/SelectBase/hooks/use-select-props/use-item-on-click-handler/test.ts
packages/picasso/src/SelectBase/hooks/use-select-props/use-item-on-click-handler/use-item-on-click-handler.ts
packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/test.ts
packages/picasso/src/SelectBase/hooks/use-select-props/use-select-handler/use-select-handler.ts

[CPT-1480]
The select input gains focus after clicking on a menu item only when the select is not multiple. This prevents it from closing on multiple selections when the user clicks/focuses on the search input.
- [Temploy](https://picasso.toptal.net/CPT-1480-fe-keep-picasso-select-dropdown-open-when-a-selection-is-made-in-search-mode)
- Open the Picasso Select
- Go to Limit section.
- Click on the search input.
- Then click on any option.
- The search options should remain visible.
- Open the Picasso Select
- Go to Limit section.
- Enter anything or click on the search
- Click on any field.
- The search options should close.
- n/a Ensure the changed/created components have not caused …

[CPT-1480] Prevent multiple Select from closing when search was clicked

---

.storybook/components/PicassoBook/Page.js
cypress/component/BarChart.spec.tsx
packages/picasso-forms/src/Form/story/HighlightAutofill.example.tsx
packages/picasso-forms/src/Form/story/index.jsx

[FX-4802]
* Cypress Test `Highlight fields with default value` is flaky. We need to wait for appearance of `Button` element on the page before taking a screenshot
* Visual Test `renders custom chart with custom tooltip on hover` is flaky. Need to click on area before triggering `hover` event
- Run Happo Visual tests
- N/A Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- N/A Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- N/A Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been …

[FX-4802] Fix flaky happo visual test

---

.github/workflows/davinci-alpha-package.yml

[FX-4785](https://toptal-core.atlassian.net/browse/FX-4785)
After this is merged, there will be two options available:
`@toptal-bot run package:alpha-release` works as before
`@toptal-bot run package:alpha-release root` will publish packages from the root folder (".")
- [Temploy](https://picasso.toptal.net/fx-4785-alpha-with-custom-root)
- Can't test without merging
<details> …

Optionally run alpha from a different root

---

.changeset/good-crabs-obey.md
packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso-forms/src/Dropzone/Dropzone.tsx
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
packages/picasso-forms/src/Form/story/Horizontal.example.tsx
packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
packages/picasso/src/FormField/styles.ts
packages/picasso/src/FormLabel/FormLabel.tsx
packages/picasso/src/FormLabel/styles.ts

[CRT-6946]
[FX-4808]
This PR aims to adjust form labels alignement.
As of today I wasn't able to find any generic CSS solution to apply styles only for FormField and/or FormLabel. That is proposed solution is based on the knowledge that the specific form component has height above 48px, in that case we align label to the top.
1. Here is a PR in Client Portal with updated Picasso https://github.com/toptal/client-portal/pull/8013
- as you can see in [generated Happo screenshots in Client Portal](https://happo.io/a/431/p/1314/compare/75ec96db99c080bfbcf5b8d2288225b33bd85105/8fcd8ee9535e680b56c4993fdd71c99a889be6d6) there are no diffs, which is good, as we fixed alignment in this PR
3. review `Form*` Happo screenshots in Picasso
| Before.                                 | After. …

[CRT-6946][FX-4808] Adjust form labels alignement

---

.changeset/tender-crabs-accept.md
packages/picasso-tailwind/src/index.js

[FX-NNNN]
We don't have BASE spacing in the TailwindCSS config, this PR fixes it.
- [Temploy](https://picasso.toptal.net/fx-null-tailwind-spacing)
- Ensure the changed/created components have not caused …

Add BASE spacings to the theme config

---

.changeset/beige-clocks-float.md
packages/picasso/src/PasswordInput/PasswordInput.tsx
packages/picasso/src/PasswordInput/story/Sizes.example.tsx
packages/picasso/src/PasswordInput/story/index.jsx

[no-jira]
The `PasswordInput` component accepts the `size` prop, but it was not working properly. The component rendered in default size, regardless of the `size` value.
- [Temploy](https://picasso.toptal.net/taco-fix-passwordinput-size)
- Check the new **Sizes** example in `PasswordInput` storybook
| ![image](https://github.com/toptal/picasso/assets/597793/d0c67981-a164-4f13-98e9-bf236a6f090d) | ![image](https://github.com/toptal/picasso/assets/597793/314a1870-1060-44cb-be6a-45f23b0053e5) |
- [-] codemod is created and showcased in the changeset
- [-] test alpha package of Picasso in StaffPortal
> …

[TACO] Fix PasswordInput size prop

---

.changeset/tiny-games-remain.md
packages/picasso-forms/src/utils/scroll-to-error-decorator.ts

[FX-NNNN]
The errors from the onSubmit callback of the Form  component are swallowed. It’s pretty dangerous as it prevents our error monitoring tool from reporting such error and it’s challenging to debug it.
I tried to create a sandbox but I’m way over the limit of 10 drafts of the free tier. I was able to reproduce the problem on the picasso website though: https://picasso.toptal.net/?path=/story/picasso-forms-form--form
```jsx
import {
FormNonCompound as Form,
SubmitButton
} from '@toptal/picasso-forms'
const handleSubmit = () => {
throw new Error('Some error')
}
return (
<Form
autoComplete='off'
onSubmit={values => handleSubmit(values)}
>
<SubmitButton>Submit</SubmitButton>
</Form>
)
}
export default Example
```
Use this snippet and …

Prevent Form onSubmit rejections from being swallowed

---

.changeset/flat-rats-search.md
packages/picasso/src/TimePicker/styles.ts

[TOP-4258](https://toptal-core.atlassian.net/browse/TOP-4258)
Fix **TimePicker** component duplicate icons.
- [Temploy](https://picasso.toptal.net/fix-timepicker-duplicate-icons)
- Make sure we have one **TimePicker** icon and we can click on it to open the time selector (the time selector is not available on [Firefox and Safari](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/time)).
> To reproduce the bug, you should have the most recent versions of Chrome, as discussed [here](https://toptal-core.slack.com/archives/CERF5NHT3/p1709211732462009?thread_ts=1709210865.916469&cid=CERF5NHT3).
| …

Fix TimePicker duplicate clock icons

---

.changeset/small-trainers-hug.md
packages/base/Checkbox/src/Checkbox/Checkbox.tsx
packages/base/Form/src/FormLabel/FormLabel.tsx
packages/base/Form/src/FormLabel/__snapshots__/test.tsx.snap
packages/base/Form/src/FormLabel/test.tsx
packages/picasso-forms/src/Autocomplete/Autocomplete.tsx
packages/picasso-forms/src/AvatarUpload/AvatarUpload.tsx
packages/picasso-forms/src/Checkbox/Checkbox.tsx
packages/picasso-forms/src/CheckboxGroup/CheckboxGroup.tsx
packages/picasso-forms/src/DatePicker/DatePicker.tsx
packages/picasso-forms/src/Dropzone/Dropzone.tsx
packages/picasso-forms/src/FieldLabel/FieldLabel.tsx
packages/picasso-forms/src/FieldWrapper/FieldWrapper.tsx
packages/picasso-forms/src/FieldWrapper/story/index.jsx
packages/picasso-forms/src/FileInput/FileInput.tsx
packages/picasso-forms/src/Form/Form.tsx
packages/picasso-forms/src/Form/story/Horizontal.example.tsx
packages/picasso-forms/src/Input/Input.tsx
packages/picasso-forms/src/NumberInput/NumberInput.tsx
packages/picasso-forms/src/PasswordInput/PasswordInput.tsx
packages/picasso-forms/src/RadioGroup/RadioGroup.tsx
packages/picasso-forms/src/Rating/Rating.tsx
packages/picasso-forms/src/RichTextEditor/RichTextEditor.tsx
packages/picasso-forms/src/Select/Select.tsx
packages/picasso-forms/src/Switch/Switch.tsx
packages/picasso-forms/src/TagSelector/TagSelector.tsx
packages/picasso-forms/src/TimePicker/TimePicker.tsx

[CRT-7024]
As discussed in https://toptal-core.slack.com/archives/CERF5NHT3/p1709118058674239 and https://toptal-core.slack.com/archives/CCC3GP6CC/p1709110403440549 the `endAdornment` prop needs to be introduced in Picasso's Label component to be able to cover all cases needed in CP.
- review code and Happo screenshots
- n/a test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details> …

[CRT-7024] Introduce 'labelEndAdornment' prop for Label component

---

.github/workflows/release.yml

The release job is canceled by timeout. We need to increase the timeout.
- N/A Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- N/A Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)
- N/A Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- N/A Annotate all `props` in component with documentation
- N/A Create `examples` for component
- N/A Ensure that deployed demo has expected results and good examples
- N/A Ensure the …

Increase a timeout for release job

---

.changeset/polite-files-shake.md
packages/picasso/package.json

[FX-NNNN]
We already have TailwindCSS setup and we are ready to migrate first components. Before that, we need to release a semantic breaking change, so users are notified that we expect them to have Tailwind setup in their projects from now on.
- [Temploy](https://picasso.toptal.net/fx-null-tailwind-peer-dependency)
<details>
<summary>PR …

Add TailwindCSS as a peer dependency

---

.changeset/chilled-feet-buy.md
packages/base/Menu/src/Menu/hooks/use-drilldown-menu/use-drilldown-menu.ts

[TOP-4328]
Description
Submenu on drilldown menu does not hide if you move mouse to the siblings items
How to test
Add Menu component with 'variant' prop = drilldown and add two children as Menu.Items, one of which with 'menu' prop equal to the Menu Component. Try to hover to item with drilldown submenu, it opens, then try to navigate to other menu.item. you will see that previosly opened submenu still open
<details>
<summary>PR …

[TOP-4328] Hide submenu on other menu item focus

---

ci/jobs/picasso-kill-temploys/Jenkinsfile

It is not needed, Picasso is a public repo, and the old credentials are outdated
- Temploy
<details>
<br />
</details>
<details> …

Remove github authorization from picasso API calls

---

.changeset/twenty-islands-love.md
packages/shared/package.json

[FX-NNNN]
When using `shared` without the main Picasso package, the consumers are unable to build because `@types/color` is only present in `devDependencies`. Since we intend on all packages working separately, this should be fixed
- [Temploy](https://picasso.toptal.net/fx-xxx-move-color-types-to-deps)
- When installing `@toptal/picasso-shared` directly, `@types/color` should be installed
<details>
<br />
</details>
<details>
<br /> …

Move `color` types to regular dependencies

---

.changeset/brave-spies-visit.md
packages/base/Table/package.json
packages/base/Table/src/Table/story/Sortable.example.tsx
packages/base/Table/src/Table/story/index.jsx
packages/base/Table/src/TableCell/TableCell.tsx
packages/base/Table/src/TableSortableCell/TableSortableCell.tsx
packages/base/Table/src/TableSortableCell/__snapshots__/test.tsx.snap
packages/base/Table/src/TableSortableCell/index.ts
packages/base/Table/src/TableSortableCell/story/index.jsx
packages/base/Table/src/TableSortableCell/test.tsx
packages/base/Table/src/index.ts
packages/picasso/src/index.ts

[FX-4816](https://toptal-core.atlassian.net/browse/FX-4816)
Adds a required functionality to sort table items by exposing a custom table cell with a circular button containing an icon.
An example on how it can be used is also available in the Storybook now.
- [Temploy](https://picasso.toptal.net/fx-4816-add-table-sorting-to-the-header-in-table-component)
- Check out the code for the `TableSortableCell`
- See the new story for `Table` with a sortable example at the end
<details>
<br />
- `@toptal-anvil ping reviewers` - Ping FX team for …

[FX-4816] Add TableSortableCell

---

.changeset/loud-baboons-approve.md
.changeset/olive-llamas-retire.md
.changeset/quiet-cobras-exist.md
cypress/support/commands.jsx
packages/base/Carousel/src/CarouselNavigation/CarouselNavigation.tsx
packages/base/Carousel/src/CarouselNavigation/styles.ts
packages/base/Page/src/Page/Page.tsx
packages/base/Page/src/Page/__snapshots__/test.tsx.snap
packages/base/Page/src/Page/styles.ts
packages/base/Page/src/PageHamburger/PageHamburger.tsx
packages/base/Page/src/PageHamburger/styles.ts
packages/base/Page/src/PageSidebar/styles.ts
packages/base/Page/src/PageTopBar/__snapshots__/test.tsx.snap
packages/base/Page/src/PageTopBar/styles.ts
packages/base/Page/src/PageTopBarMenu/styles.ts
packages/base/Test-Utils/src/test-utils/TestingPicasso.tsx
yarn.lock

[FX-NNNN]
We need mui styles to be injected first in cypress to have the same setup as product. After we updated the style order in Cypress, some bugs appeared in PageSidebar and Carousel.
Also some screenshots were updated, but it looks like the old screenshots were wrong
- [Temploy](https://picasso.toptal.net/fx-null-happo-browser-update)
- Check Happo screenshots
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/con …

Update Cypress Tailwind setup

---

packages/base/Table/src/TableSortableCell/__snapshots__/test.tsx.snap
packages/base/Table/src/TableSortableCell/test.tsx

[FX-NNNN]
Removes the warning/error on DOM nesting from the `TableSortableCell` test file
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-sortable-test)
-Tests should pass
<details>
<br /> …

Fix TableSortableCell DOM nesting in test

---

.changeset/polite-boxes-burn.md
.changeset/unlucky-zebras-do.md
packages/base/Tooltip/src/Tooltip/Tooltip.tsx
packages/base/Tooltip/src/Tooltip/story/Offset.example.tsx
packages/base/Tooltip/src/Tooltip/story/index.jsx
packages/picasso-query-builder/src/FieldSelector/FieldSelector.tsx
packages/picasso-query-builder/src/FieldSelector/styles.ts
packages/picasso-query-builder/src/QueryBuilder/story/FieldDescription.example.tsx
packages/picasso-query-builder/src/QueryBuilder/story/index.jsx
packages/picasso-query-builder/src/Select/Select.tsx
packages/picasso-query-builder/src/utils/generate-select-options.ts

[CPT-2029]
- We want to improve the query builder so that its users can provide a tooltip to help their end-users understand what a field is for.
- To achieve this functionality, we added an optional property to override the styles of the tooltip popover
**Note:**
For the clause: **Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core**
The implementation was issued from a Toptal design; please reach out to me to receive the link if you want to.
- [Temploy](https://picasso.toptal.net/CPT-2029-fe-add-optional-tooltip-for-a-menu-item-in-the-picasso-select)
- Open the query builder storybook
- Scroll to field description
- Open the fields selector
- Move the mouse over the …

[CPT-2029] Add support to optional tooltip for query builder fields 

---

bin/refresh-tsconfig-references.mjs
cypress/component/DatePicker.spec.tsx
package.json
packages/base/Backdrop/tsconfig.json
packages/base/Fade/tsconfig.json
packages/base/Paper/tsconfig.json
packages/base/Table/tsconfig.json

Because tsconfig references can become outdated, I'm setting up running the refresh script on every `package.json` change for lint-staged
- [Temploy](https://picasso.toptal.net/feature/update-tsc-references-on-lint)
- Modifying a `package.json` should trigger tsconfig project references refresh for that project
- [NA] Create …

Add refresh tsconfig dependencies to lint-staged

---

packages/base/TreeView/src/StaticTreeView/story/index.jsx

[FX-NNNN]
The screenshot for StaticTreeView has been flaky for a long time, the function that we were currently using for waiting for images to load is not working. 
According to [the documentation](https://docs.happo.io/docs/storybook#waiting-for-a-condition-to-be-truthy) we can use `waitFor` function. The screenshot will be taken after the condition is true.
- [Temploy](https://picasso.toptal.net/fix-cypress-flaky-test)
- The CI should be green
- Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/doc …

Wait for image to be fully loaded

---

.changeset/green-keys-nail.md
packages/base/Accordion/src/AccordionCompound/index.ts
packages/base/Alert/src/AlertCompound/index.ts
packages/base/ApplicationUpdateNotification/src/ApplicationUpdateNotificationCompound/index.ts
packages/base/Avatar/src/AvatarCompound/index.ts
packages/base/Breadcrumbs/src/BreadcrumbsCompound/index.ts
packages/base/Button/src/ButtonCompound/index.ts
packages/base/Form/src/FormCompound/index.ts
packages/base/Grid/src/GridCompound/index.ts
packages/base/Helpbox/src/HelpboxCompound/index.ts
packages/base/Menu/src/MenuCompound/index.ts
packages/base/Modal/src/ModalCompound/index.ts
packages/base/Note/src/NoteCompound/index.ts
packages/base/Notification/src/NotificationCompound/index.ts
packages/base/OverviewBlock/src/OverviewBlockCompound/index.ts
packages/base/Page/src/PageCompound/index.ts
packages/base/Page/src/PageTopBarCompound/index.ts
packages/base/Radio/src/RadioCompound/index.ts
packages/base/Step/src/StepperCompound/index.ts
packages/base/Table/src/TableCompound/index.ts
packages/base/Tabs/src/TabsCompound/index.ts
packages/base/Tag/src/TagCompound/index.ts
packages/base/Tagselector/src/TagSelectorCompound/index.ts
packages/picasso-forms/src/FormCompound/index.ts

[FX-5115]
When we leave on Typescript to set types for compound components, it is resolving wrongly paths to other packages.
We can't have `packages/shared/dist-package/src` in generated files as they do not exist and it needs to be resolved to `@toptal/picasso-shared`. It seems like a bug in Typescript itself.
When we explicitly type the compound component, the types are generated correctly.
- [Temploy](https://picasso.toptal.net/fx-5115-types)
- check screenshot bellow, or
- you can check locally the branch and open story of Page and try to read types of `Page.Article`
- on current commit it should show proper types
- if you remove the types from the Page compound component, it will not work again
| …

[FX-5115] Update types of compound components

---

packages/base/Table/src/Table/__snapshots__/test.tsx.snap
packages/base/Table/src/TableBody/TableBody.tsx
packages/base/Table/src/TableBody/__snapshots__/test.tsx.snap
packages/base/Table/src/TableCell/__snapshots__/test.tsx.snap
packages/base/Table/src/TableRow/__snapshots__/test.tsx.snap
packages/base/Table/src/TableSectionHead/__snapshots__/test.tsx.snap

[FX-4622]
Migration to Tailwind.
- [Temploy](https://picasso.toptal.net/fx-4622-migrate-tablebody)
- Check the [production](https://picasso.toptal.net/?path=/story/components-table--table) and compare it with the temploy.
| ![Picasso - Table - Google Chrome 2024-04-12 at 11 56 58 AM](https://github.com/toptal/picasso/assets/100089376/b1c028c9-dd2f-4390-b3e9-d904b197ada3) | ![Picasso - Table - Google Chrome 2024-04-12 at 2 49 37 PM](https://github.com/toptal/picasso/assets/100089376/ae72c352-7836-4f64-8f63-b7c5852bb635)
|
- ~Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contrib …

[FX-4622] Migrate TableBody to TailwindCSS

---

.changeset/strong-houses-buy.md
packages/base/Tag/src/Indicator/Indicator.tsx
packages/base/Tag/src/Indicator/styles.ts
packages/base/Tag/src/TagRectangular/story/Indicators.example.tsx
packages/base/Tag/src/TagRectangular/story/Variants.example.tsx
packages/base/Tag/src/TagRectangular/styles.ts
packages/base/Tag/src/TagRectangular/types.ts
yarn.lock

[FX-5178]
Adds new values for the `Tag` component `variant` and `indicator` props.
- [Temploy](https://picasso.toptal.net/fx-5178-new-tag-colors)
| ![image](https://github.com/toptal/picasso/assets/134127624/20b464f6-e7d3-439b-8ab5-20d0a19b2875) | ![image](https://github.com/toptal/picasso/assets/134127624/615b058b-77b5-4933-83c6-6a9bc3860ab9) |
<details>
<br />
- …

[FX-5178] New `Tag` colors

---

README.md

This pull request adds guide on running visual tests locally (in fact moves it from https://toptal-core.slack.com/archives/GG3F4AS4T/p1712657917104799 to Picasso `README` file).
- Check out the https://github.com/toptal/picasso/tree/FX-NULL-update-readme-dsfdksf0?tab=readme-ov-file#running-visual-tests-locally
- [N/A] Ensure that deployed demo has …

[FX-NULL] Add guide on running visual tests locally

---

.changeset/clean-kiwis-try.md
packages/picasso-query-builder/src/QueryBuilder/QueryBuilder.tsx
packages/picasso-query-builder/src/QueryBuilder/story/CustomRunQueryButton.example.tsx
packages/picasso-query-builder/src/QueryBuilder/story/index.jsx
packages/picasso-query-builder/src/RunQueryButton/RunQueryButton.tsx
yarn.lock

[CPT-2187](https://toptal-core.atlassian.net/browse/CPT-2187)
In this PR we added new property in order to provide desired text/functionality to Run Query button. Considering that `totalCount` and `totalCountLoading` props are something custom that should not be defined on the level of library we removed these props from Query Builder.
Also we removed deprecation of `hideControls` property that was introduced before. There was a misalignment and at the moment we are not planning to move controls to consumers because Run Query and Clear Query it is something common. Instead not showing these controls it is an edge case which is handled by `hideControls`.
- [Temploy](https://picasso.toptal.net/CPT-2187-allow-qb-controls-customization-from-consumers)
- Check Custom Run Query Button story
| …

[CPT-2187] Allow qb controls customization from consumers

---

.changeset/brave-mirrors-obey.md
packages/base/Button/src/Button/Button.tsx

[FX-5195]
Drop `index` of `Button` styles, to force it to the end of `<head>` (higher precedence), button variants still need a even lower index, to have priority over base `Button`
- [Temploy](https://picasso.toptal.net/FX-5195-fix-button-css-precedence)
- [PR on SP](https://github.com/toptal/staff-portal/pull/12641) should have buttons as before (without [blue coloring](https://github.com/toptal/staff-portal/pull/12540#pullrequestreview-2032922124))
No screenshots
<details>
<br /> …

[FX-5195] Fix button css precedence

---

.changeset/brown-starfishes-sneeze.md
.changeset/odd-ads-give.md
.changeset/red-brooms-rush.md
.storybook/components/CodeExample/CodeExample.tsx
.storybook/stories/tutorials/merging-classes/story/index.jsx
Dockerfile
packages/picasso-tailwind-merge/package.json
packages/picasso-tailwind-merge/src/index.ts
packages/picasso-tailwind-merge/src/test.ts
packages/picasso-tailwind-merge/src/twMerge.ts
packages/picasso-tailwind-merge/tsconfig.json
packages/picasso-tailwind/src/index.d.ts
packages/picasso/README.md
tsconfig.pkgsrc.json

[FX-5306]
Add new package `picasso-tailwind-merge` that exports configured `twMerge` that works correctly with the Picasso TailwindCSS theme.
The basic configurations were done. In the future, we should extend the theme when we add new custom classes or discover that some classes are not merged correctly. 
1. Go to `packages/base/Typography/src/Typography/Typography.tsx`.
2. Import `twMerge` from `@toptal/picasso-tailwind-merge`.
3. On line 194 replace `cx` with `twMerge`.
4. Run Storybook.
5. Check if example normal text example has `font-inherit-size` class. If it is, then it works. 
check the [new documentation](https://picasso.toptal.net/fx-5306-configure-twmerge/?path=/story/tutorials-merging-classes--merging-classes)
> All **_development checks_** should be done …

[FX-5306] Configure twMerge

---

.changeset/thin-jeans-mix.md
packages/base/FileInput/src/FileList/__snapshots__/test.tsx.snap
packages/base/FileInput/src/FileListItem/FileListItem.tsx
packages/base/FileInput/src/FileListItem/__snapshots__/test.tsx.snap
packages/base/Form/src/FieldRequirements/FieldRequirementItem.tsx
packages/base/Form/src/FieldRequirements/FieldRequirements.tsx
packages/base/Section/src/Section/Section.tsx
packages/base/Section/src/Section/__snapshots__/test.tsx.snap
packages/base/Tabs/src/TabDescription/TabDescription.tsx
packages/base/Tag/src/Tag/__snapshots__/test.tsx.snap
packages/base/Tag/src/TagRectangular/__snapshots__/test.tsx.snap
packages/base/Timeline/src/Timeline/__snapshots__/test.tsx.snap
packages/base/Timeline/src/TimelineRow/TimelineRow.tsx
packages/base/Typography/package.json
packages/base/Typography/src/Typography/Typography.tsx
packages/base/Typography/tsconfig.json
packages/base/UserBadge/src/UserBadge/UserBadge.tsx

[FX-5185]
Replace `classnames` with `twMerge` in `Typography`.
- [Temploy](https://picasso.toptal.net/fx-5185-use-twmerge-in-typography)
<details>
<br />
</details>
<details>
<br /> …

[FX-5185] Use twMerge in Typography

---

.changeset/smooth-frogs-stare.md
packages/base/AccountSelect/src/AccountSelect/__snapshots__/test.tsx.snap
packages/base/Link/src/Link/Link.tsx
packages/base/Link/src/Link/__snapshots__/test.tsx.snap
packages/base/Page/src/PageTopBar/__snapshots__/test.tsx.snap

[FX-NNNN]
Fixes the line-height difference with MUI Link
- [Temploy](https://picasso.toptal.net/fx-xxx-fix-link-line-height)
- The screenshot tests should no longer differ from master on smaller screens
<details>
<br />
</details>
<details>
<br />
**You are not OK** …

Update link line-height

---

.changeset/tough-ties-hear.md
packages/base/TreeView/src/TreeView/TreeView.tsx
packages/base/TreeView/src/TreeView/variables.ts

[FX-4718](https://toptal-core.atlassian.net/browse/FX-4718)
Removes deprecated props from `TreeView`.
There are no usages of the prop across the entire org.
- [Temploy](https://picasso.toptal.net/fx-4718-remove-deprecated-treeview-props)
- CI should pass, no other changes
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd …

[FX-4718] Remove deprecated props

---

.changeset/healthy-buckets-accept.md
.changeset/orange-horses-end.md
packages/picasso-tailwind-merge/package.json
packages/picasso-tailwind-merge/src/test.ts
packages/picasso-tailwind-merge/src/twMerge.ts
packages/picasso-tailwind-merge/tsconfig.json
packages/picasso-tailwind/package.json
packages/picasso-tailwind/src/index.js

[FX-5554]
Because picasso-tailwind is a pure CJS module, it caused a few problems with the expected webpack setup, which would try to transpile it to an ESM module. Besides, this dependency brought the whole `tailwind` package to the runtime bundle, which is unnecessary for such a simple case.
I also added a unit test to guarantee that the 2 packages are in sync, while also adding a not to `picasso-tailwind` to remind developers that the two need to have the same value
- [Temploy](https://picasso.toptal.net/fix/picasso-tailwind-dep-on-merge)
| Insert screenshots or screen recordings | Insert …

[FX-5554] Remove picasso-tailwind dependency on picasso-tailwind-merge

---

.changeset/red-chairs-smoke.md
packages/base/Select/src/NativeSelect/NativeSelect.tsx
packages/base/Select/src/NonNativeSelect/NonNativeSelect.tsx
packages/base/Select/src/SelectCaret/index.tsx

[TOP-4660] 
- [Temploy](https://picasso.toptal.net/TOP-4660-export-select-caret)
- CI is green
<details>
<br />
</details>
<details>
<br /> …

[TOP-4660] Fix SelectCaret export

---

.changeset/angry-colts-scream.md
packages/base/Button/src/ButtonAction/ButtonAction.tsx
packages/base/Button/src/ButtonBase/ButtonBase.tsx
packages/base/Button/src/ButtonControlLabel/ButtonControlLabel.tsx

[FX-NNNN]
When we used 
```jsx
import { Button, Link, Tooltip } from '@toptal/picasso'
import { Player16 } from '@toptal/picasso-icons'
return (
<div>
<Tooltip content='Watch Pitch' compact>
<Button.Circular
as={Link}
size='small'
variant='flat'
disabled={false}
href={''}
target='_blank'
rel='noreferrer'
icon={<Player16 color='black' />}
/>
</Tooltip>
</div>
)
}
```
It threw error `Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.`
- [Temploy](https://picasso.toptal.net/fx-null-fix-button)
- Try ☝️ code snippet in the Picasso storybook, it should not throw an error
| Before. …

Fix button errors

---

.changeset/fast-ligers-exercise.md
packages/base/Drawer/src/Drawer/Drawer.tsx
packages/base/Drawer/src/Drawer/story/WithDisabledBackdrop.example.tsx
packages/base/Drawer/src/Drawer/story/index.jsx

[FX-5517](https://toptal-core.atlassian.net/browse/FX-5517)
Adds `disableBackdrop` prop to `Drawer`. This enables page interaction when Drawer is engaged.
- [Temploy](https://picasso.toptal.net/fx-5517-disable-backdrop-for-drawer)
- Check the `WithDisabledBackdrop` [story](https://picasso.toptal.net/fx-5517-disable-backdrop-for-drawer/?path=/story/components-drawer--drawer#with-disabled-backdrop) for Drawer at the very bottom
https://github.com/toptal/picasso/assets/18409292/9360f9ab-acbd-4119-98db-540360d8c718
<details>
<br />
- …

[FX-5517] Add `disableBackdrop` to Drawer

---

.changeset/olive-foxes-perform.md
packages/base/TypographyOverflow/src/TypographyOverflow/TypographyOverflow.tsx
packages/base/TypographyOverflow/src/TypographyOverflow/story/Placement.example.tsx
packages/base/TypographyOverflow/src/TypographyOverflow/story/index.jsx

[TI-2599]
Add placement prop to TypographyOverflow component 
- [Temploy](https://picasso.toptal.net/ti-2599)
- Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
</details>
<details>
<br />
1. Add `nit:` to your comment. (ex. `nit: I'd rename this variable from …

[TI-2599] Add placement prop to TypographyOverflow component

---

.github/workflows/ci.yaml
.github/workflows/release.yml

This pull request reverts the `toptal/davinci-github-actions/build-push-image` bump to solve the problem described [here](https://toptal-core.slack.com/archives/C03GLMT6L7N/p1719246572360519).
- [Temploy](https://picasso.toptal.net/FX-NULL-revert-github-actions-update)
- Run the command below locally (the image is built from this pull request), there should be no errors
```bash
docker run --rm -v /var/lib/jenkins/workspace/picasso-docs/deploy-docs:/app/deploy-docs -e DEPLOY_DOCS_PATH=/app/deploy-docs -e DEPLOY_DOCS_ARCHIVE=deploy-docs us-central1-docker.pkg.dev/toptal-hub/containers/picasso:dcdbe16f9fb143100c91493b1e1ac760c8585ee1 ./bin/release-docs
```
- [N/A] Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) …

Revert davinci-github-actions/build-push-image update

---

.github/workflows/ci.yaml
.github/workflows/release.yml
package.json

[FX-5568]
This pull request adds the `nx reset` command before building the Storybook to unblock the Picasso releases (right now package releases work, but https://picasso.toptal.net/ is not updated).
The reason is still unknown, the issue happens randomly based on https://jenkins-build.toptal.net/job/picasso-docs/ logs. It seems like https://github.com/toptal/davinci-github-actions/tree/master/build-push-image sometimes adds the `.nx/cache` folder to the image (created on some **runner A**) and then this image is used to run `"yarn build:storybook"` command on some **runner B**, so the `nx` throws error below as the cache was generated on **runner A**. 
```
17:02:31  The local cache artifact in "/app/.nx/cache/8544709143843587005" was not generated on this machine.
17:02:31  As a result, …
```

[FX-5568] Fix Picasso docs build

---

.changeset/tricky-tigers-swim.md
.changeset/warm-beds-admire.md
cypress/component/Button.spec.tsx
packages/base/Alert/src/Alert/__snapshots__/test.tsx.snap
packages/base/Button/src/Button/Button.tsx
packages/base/Button/src/Button/__snapshots__/test.tsx.snap
packages/base/Button/src/Button/styles.ts
packages/base/Button/src/ButtonBase/ButtonBase.tsx
packages/base/Button/src/ButtonCheckbox/__snapshots__/test.tsx.snap
packages/base/Button/src/ButtonControlLabel/ButtonControlLabel.tsx
packages/base/Button/src/ButtonGroup/__snapshots__/test.tsx.snap
packages/base/Button/src/ButtonRadio/__snapshots__/test.tsx.snap
packages/base/Button/src/ButtonSplit/__snapshots__/test.tsx.snap
packages/base/FileInput/src/FileInput/__snapshots__/test.tsx.snap
packages/base/Helpbox/src/Helpbox/__snapshots__/test.tsx.snap
packages/base/Modal/src/Modal/__snapshots__/test.tsx.snap
packages/base/Notification/src/use-notification/__snapshots__/test.tsx.snap
packages/base/Pagination/src/Pagination/__snapshots__/test.tsx.snap
packages/base/PromptModal/src/PromptModal/__snapshots__/test.tsx.snap
packages/base/Utils/src/utils/Modal/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap

[FX-5570]
When adopting the latest version in the Staff Portal, I found few visual issues with `<Button as={Link} />`
- [Temploy](https://picasso.toptal.net/fx-null-fix-button-2)
- Make sure that additions and changes on the design follow [Toptal's BASE …

[FX-5570] Fix visual problems when as Link

---

.changeset/calm-trainers-taste.md
packages/base/Drawer/package.json
packages/base/Drawer/src/Drawer/Drawer.tsx
packages/base/Drawer/tsconfig.json

[FX-5570]
- [Temploy](https://picasso.toptal.net/fx-null-use-our-backdrop)
<details>
<br />
</details> …

[FX-5570] Use our Backdrop

---

.changeset/modern-sheep-help.md
packages/base/Tag/src/Tag/Tag.tsx
packages/base/Tag/src/Tag/__snapshots__/test.tsx.snap

[FX-5607]
```jsx
<Tag icon={<Settings16 color='blue' />} variant='light-grey'>
Light grey
</Tag>
```
Previously, the icon always had the `text-graphite-700` color or `text-gray-500` when disabled. When user tries to customize, it is ignored. I checked the BASE design and there are cases where icon needs to be colored.
- [Temploy](https://picasso.toptal.net/fx-5607-tag-bug)
- Try to change color of Tag in the storybook ☝️ 
- Ensure the changed/created components have not caused accessibility issues. [How …

[FX-5607] Allow to customize the color of icon

---

.changeset/plenty-singers-design.md
packages/base/Calendar/src/Calendar/Calendar.tsx
packages/base/Calendar/src/Calendar/test.tsx

[FX-NNNN]
After the latest feature that we added, Cypress test in SP started failing. When user uses `maxDate`, all days past this date should be disabled, but they are not. 
I believe `toYear` was added to showcase only related years in the select box. I tested that it also works with only passing `maxDate` to the DayPicker
- [Temploy](https://picasso.toptal.net/fx-null-fix-day-picker)
- Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) …

Disable days past maxDate

---

.changeset/chilly-owls-appear.md
packages/base/Calendar/src/Calendar/Calendar.tsx
packages/base/Calendar/src/Calendar/test.tsx

[FX-5596]
when we pass `minDate` all days before that date have to be disabled.
- [Temploy](https://picasso.toptal.net/fx-null-fix-day-picker-2)
- …

[FX-5596] Disable days before minDate

---

.storybook/components/Markdown/Markdown.tsx
.storybook/components/Markdown/index.ts
.storybook/main.js
.storybook/stories/contribution/story/index.tsx
.storybook/stories/picasso/story/index.tsx
packages/picasso-charts/package.json
packages/picasso-charts/src/story/index.jsx
packages/picasso-forms/package.json
packages/picasso-forms/src/story/index.jsx
packages/picasso-pictograms/package.json
packages/picasso-pictograms/src/story/index.jsx
packages/picasso-query-builder/package.json
packages/picasso-query-builder/src/story/index.jsx
packages/picasso-rich-text-editor/package.json
packages/picasso/package.json
yarn.lock

[FX-5703](https://toptal-core.atlassian.net/browse/FX-5703)
Backports what `{ doc } from 'storybook-readme'` used to do to our internal `'react-markdown'` renderer.
Fixes https://github.com/toptal/picasso/security/dependabot/156
- [Temploy](https://picasso.toptal.net/fx-5703-picasso-html-minifier)
- Look at all the doc pages, they should be visually unchanged (with some exceptions)
- Some of the elements actually look nicer now as previously some styles were applied twice
| ![image](https://github.com/user-attachments/assets/10553435-e941-4853-b7c1-d6a2e4fe4ff7) | …

[FX-5703] Remove storybook-readme

---

package.json
yarn.lock

[FX-5698]
Fixes https://github.com/toptal/picasso/security/dependabot/151
Storybook uses versions 3 and 4, which we cannot update now. We need to use resolutions for it. I tested the storybook locally and everything works as before.
<details>
<br />
</details>
<details>
<br />
2. …

[FX-5698] Fix webpack-dev-middleware vulnerability

---

yarn.lock

[FX-5698]
Partially fixes 
- https://github.com/toptal/picasso/security/dependabot/158
- So far there is no proper fix for this issue. It is used only by `@storybook/core-server`
Fixes
- https://github.com/toptal/picasso/security/dependabot/148
<details>
<br />
</details>
<details>
<br /> …

[FX-5698] Fix ip vulnerability

---

.changeset/smart-ladybugs-play.md
cypress/component/Table.spec.tsx
packages/base/Collapse/src/Collapse/Collapse.tsx
packages/base/Collapse/src/Collapse/story/AppearOnRender.example.tsx
packages/base/Collapse/src/Collapse/story/index.jsx
packages/base/Collapse/src/Collapse/test.tsx
packages/base/Section/src/Section/__snapshots__/test.tsx.snap
packages/base/Table/src/Table/story/ExpandableRows.example.tsx
packages/shared/src/types.ts

[FX-5596]
After migrating from MUI@4, we encountered an issue with dynamic content inside the Collapse component. The primary problem was that the height property was not set to auto after the transition ended, which caused issues when the component was closing. Specifically, the browser was batching style changes and transitioning directly from auto to 0, skipping the intermediate height value (node.clientHeight). This behavior breaks the expected transition as the browser cannot animate from auto to a numeric value.
To resolve this, we introduced a mechanism to delay the update to the 0. This ensures that the transition updates the height from auto to the actual height (node.clientHeight), and then to 0, thereby making the transitions smooth.
- …

[FX-5596] Set height to auto after transition is finished

---

.changeset/pink-rings-suffer.md
packages/picasso-charts/src/BarChart/BarChart.tsx
packages/picasso-charts/src/BarChart/story/index.jsx
packages/picasso-charts/src/BarChart/utils/check-if-labels-exist-in-data.ts

[FX-5762](https://toptal-core.atlassian.net/browse/FX-5725)
- [Temploy](https://picasso.toptal.net/fx-5725-barchart-shows-extra-space-in-the-bottom/?path=/story/picasso-charts-barchart--barchart)
- Compare with https://picasso.toptal.net/?path=/story/picasso-charts-barchart--barchart
Comparison with `master`
https://github.com/user-attachments/assets/62a7211a-1768-4c5c-b154-21719287e9c4
- [N/A] Ensure the changed/created components have not caused …

[FX-5762] Completely hide axis when needed

---

.changeset/good-horses-brake.md
packages/base/Form/package.json
packages/base/Form/src/FormError/FormError.tsx
packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
packages/base/Form/src/FormError/styles.ts
packages/base/Form/src/FormHint/FormHint.tsx
packages/base/Form/src/FormHint/__snapshots__/test.tsx.snap
packages/base/Form/src/FormHint/styles.ts
packages/base/Form/tsconfig.json
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap

[FX-5533]
Refactor FormHint and FormError to TailwindCSS
- [Temploy](https://picasso.toptal.net/fx-5533-formhint)
- Check storybook and Happo screenshots
<details>
<br />
</details>
<details> …

[FX-5533] Refactor FormHint and FormError to TailwindCSS

---

.changeset/late-kids-unite.md
packages/base/Form/src/FormActionsContainer/FormActionsContainer.tsx
packages/base/Form/src/FormActionsContainer/styles.ts
packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
packages/base/Form/src/FormField/FormField.tsx
packages/base/Form/src/FormField/__snapshots__/test.tsx.snap
packages/base/Form/src/FormField/styles.ts
packages/base/Form/src/FormLabel/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Radio/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Rating/__snapshots__/test.tsx.snap

[FX-5534]
Migrate FormField and FormAction to TailwindCSS.
- [Temploy](https://picasso.toptal.net/fx-5534-formfield-and-formaction-to-tailwind)
- Check PR checks and storybook
- ~Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)~
- ~test alpha package of Picasso in StaffPortal~
> **GitHub Bot: …

[FX-5534] Migrate FormField and FormActionsContainer to TailwindCSS

---

.changeset/green-schools-sparkle.md
packages/base/Autocomplete/src/Autocomplete/__snapshots__/test.tsx.snap
packages/base/DatePicker/src/DatePicker/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/MonthSelect/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/YearSelect/__snapshots__/test.tsx.snap
packages/base/FileInput/src/FileInput/__snapshots__/test.tsx.snap
packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
packages/base/Input/src/Input/__snapshots__/test.tsx.snap
packages/base/NumberInput/src/NumberInput/__snapshots__/test.tsx.snap
packages/base/OutlinedInput/src/OutlinedInput/stylesRoot.ts
packages/base/Page/src/PageAutocomplete/__snapshots__/test.tsx.snap
packages/base/Select/src/NativeSelect/__snapshots__/test.tsx.snap
packages/base/Select/src/NonNativeSelect/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelector/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelectorInput/__snapshots__/test.tsx.snap
packages/base/Timepicker/src/TimePicker/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap

[FX-5771](https://toptal-core.atlassian.net/browse/FX-5771)
Previously the `:has` selector responsible for focus outlines was only triggered for `input` elements, however it should also work for `<select>` and `<textarea>`. 
This PR changes the selector to trigger for any `:focus` inside the element.
- [Temploy](https://picasso.toptal.net/fx-5771-focus-outline-does-not-appear-for-textarea-and-nativeselect)
- See the story for `Input` and `Select` => "Native"
- Compare with master - textearas and native selects should have the focus ring now
<details>
<br />
- …

[FX-5771] Fix `OutlinedInput` focus selector

---

.changeset/odd-monkeys-divide.md
packages/base/NumberInput/src/NumberInputEndAdornment/NumberInputEndAdornment.tsx

[FX-5795]
We should prevent the default action when click NumberInput's actions.
- [Temploy](https://picasso.toptal.net/fx-5795-fix-number-input)
- N/A Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- N/A Annotate all `props` in component with documentation
- N/A Create `examples` for component
- N/A Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
- `@toptal-bot run package:alpha-release` - Release alpha …

[FX-5795] Prevent the form from validation

---

.changeset/few-jeans-itch.md
packages/base/Input/src/Input/Input.tsx
packages/base/Input/src/Input/story/StatusHorizontal.example.tsx
packages/base/Input/src/Input/story/index.jsx

[FX-5766]
Fix multiline input adornment position for horizontal layout.
Go to http://localhost:9001/?path=/story/forms-input--input and check the `Status horizontal` story.
| ![image](https://github.com/user-attachments/assets/b10f4a4d-47e3-4fda-a0c9-80d620590430) | ![image](https://github.com/user-attachments/assets/2b47746e-06aa-425b-ab40-3bac336534dc) |
- ~Ensure that deployed demo has …

[FX-5766] Fix multiline input adornment position for horizontal layout

---

.changeset/twelve-steaks-melt.md
packages/base/Badge/src/Badge/Badge.tsx
packages/base/Badge/src/Badge/__snapshots__/test.tsx.snap
packages/base/Checkbox/src/Checkbox/Checkbox.tsx
packages/base/Checkbox/src/Checkbox/__snapshots__/test.tsx.snap
packages/base/Tabs/src/Tab/story/IconOrBadge.example.tsx
packages/base/Tabs/src/Tab/story/index.jsx
packages/base/Tabs/src/Tabs/story/index.jsx
packages/picasso-forms/src/Checkbox/__snapshots__/test.tsx.snap

[FX-5808]
This pull request
- removes `top-0 right-0` classes from Badge component.
[Original MUIv4 implementation](https://mui.com/base-ui/react-badge/components-api/) has these styles only for the badge (not root) itself in https://github.com/mui/material-ui/blob/v4.x/packages/material-ui/src/Badge/Badge.js#L78 (particularly `anchorOriginTopRightRectangular` as this is the only way Picasso used to use Badge).
- restores original font size for Checkbox root
- [Temploy](https://picasso.toptal.net/fx-5808-badges-are-misplaced)
- Check how tabs look in Staff Portal in https://t-staff-portal-pr-13553.toptal.net/clients/160751
- Check visual changes https://happo.io/a/675/p/1189/compare/b6f2db484bda3bfb5ffd325f92aeb174639783ab/187a936cb83477f540b33d1e2cd57cbb021a90f1?t=added
**Tabs**
Before …

[FX-5808] Fix badge placement in tabs and checkbox spacing

---

.github/workflows/ci.yaml
.github/workflows/security-secrets-scan.yaml
yarn.lock

[FX-NNNN]
Removing https://github.com/toptal/picasso/security/dependabot/165
- [Temploy](https://picasso.toptal.net/fx-null-fix-micromatch)
- CI is green …

Update micromatch to remove vulnerability

---

.changeset/quiet-cheetahs-collect.md
packages/base/Logo/package.json
packages/base/Logo/src/Logo/Logo.tsx
packages/base/Logo/src/Logo/styles.ts
packages/base/Logo/tsconfig.json
packages/base/Page/src/PageTopBar/__snapshots__/test.tsx.snap
packages/base/Page/src/SidebarLogo/__snapshots__/test.tsx.snap

[FX-5544]
This PR removes material-ui styles and replace them with Tailwind CSS classes.
- [Temploy](https://picasso.toptal.net/fx-5544-logo)
- Check the [production](https://picasso.toptal.net/?path=/story/components-logo--logo) and compare it with the temploy.
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~
- ~Ensure that deployed demo has expected results and good examples~
- ~Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in …

[FX-5544] Migrate Logo to TailwindCSS

---

.changeset/quiet-coins-switch.md
packages/base/List/src/ListItem/ListItem.tsx

[FX-4717]
This pull request deletes long deprecated icon property from `List.Item` component
- [Temploy](https://picasso.toptal.net/fx-4717-remove-custom-icons-on-list-item)
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
</details>
<details>
<br />
2. You have …

[FX-4717] Delete icon property

---

.github/workflows/notify-about-pending-release-pull-requests.yaml

This pull request adds ability to snooze notifications via `STALE_VERSION_PACKAGES_NOTIFICATION_SNOOZE_UNITL` environment variable.
<details>
<br />
</details>
<details>
<br /> …

[FX-NULL] Add ability to snooze notification

---

.changeset/short-hornets-punch.md
.changeset/short-hornets-ranch.md
packages/base/Autocomplete/src/Autocomplete/index.ts
packages/base/Checkbox/src/Checkbox/index.ts
packages/base/FileInput/src/FileInput/index.ts
packages/base/Form/src/Form/index.ts
packages/base/Input/src/Input/index.ts
packages/base/Radio/src/Radio/index.ts
packages/base/Radio/src/RadioGroup/index.ts
packages/base/Switch/src/Switch/index.ts
packages/base/Tagselector/src/TagSelector/TagSelector.tsx
packages/base/Tagselector/src/TagSelectorInput/TagSelectorInput.tsx
packages/base/Tooltip/src/Tooltip/index.ts

[FX-4714]
This pull request deletes previously deprecated exports of plain `Props`.
- [Temploy](https://picasso.toptal.net/fx-4714-remove-bare-props-inner-exports)
- [N/A] test alpha package of Picasso in StaffPortal
<details>
<br />
</details>
<details>
<br /> …

[FX-4714] Delete bare props exports

---

.changeset/three-coats-dress.md
.changeset/three-coats-press.md
cypress/component/TagSelector.spec.tsx
packages/base/Autocomplete/src/Autocomplete/Autocomplete.tsx
packages/base/Autocomplete/src/Autocomplete/OptionsMenu.tsx
packages/base/Autocomplete/src/Autocomplete/test.tsx
packages/base/Autocomplete/src/Autocomplete/types.ts
packages/base/Autocomplete/src/Autocomplete/use-autocomplete/use-autocomplete.ts
packages/base/Tagselector/src/TagSelector/TagSelector.tsx
packages/base/Tagselector/src/TagSelector/story/InitialSetValue.example.tsx
packages/base/Tagselector/src/TagSelector/story/OtherOptionSubmissionOnEnter.example.tsx
packages/base/Tagselector/src/TagSelector/story/index.jsx
packages/base/Tagselector/src/TagSelector/test.tsx

[FX-5837]
This pull request does two closely related things:
- fixes bug with thin popper container appearing when there are no options and no "empty options" text in `Autocomplete`. Use the code below to observe it in https://picasso.toptal.net/
<details>
<summary>Reproduction code</summary>
```
import React, { useState } from 'react'
import type { AutocompleteItem } from '@toptal/picasso'
import { Autocomplete, Form } from '@toptal/picasso'
import { isSubstring } from '@toptal/picasso-utils'
const [value, setValue] = useState('')
const [options, setOptions] = useState<AutocompleteItem[] | null>([])
return (
<div>
<Form autoComplete='off'>
<Autocomplete
placeholder='Start typing country...'
value={value}
options={[]}
noOptionsText={null}
onChange={newValue => { …
```

[FX-5837] Disable autocomplete in tag selector

---

.changeset/cuddly-trees-argue.md

[FX-5935]
I have accidentally committed to master https://github.com/toptal/picasso/commit/f8e5c8f82c54e011270a7bec58375d09153788ce. This is only changeset.
It's protection from wrong input, so nothing to test. Creating unit test would require big refactoring of component, which I decided to not do in this PR. Creating expensive test with rendering React I believe does not make sense.
<details>
<summary>PR …

[FX-5935] Handle unexpected input to the Link

---

.changeset/gentle-toes-deliver.md
.changeset/nasty-crews-own.md
.changeset/purple-worms-agree.md
.changeset/soft-insects-sparkle.md
packages/base/Dropzone/src/Dropzone/Dropzone.tsx
packages/base/Dropzone/src/Dropzone/__snapshots__/test.tsx.snap
packages/base/Form/src/FormHint/FormHint.tsx
packages/base/OutlinedInput/src/OutlinedInput/stylesRoot.ts
packages/picasso-rich-text-editor/src/RichTextEditor/styles.ts

[FX-5841]
Disabled state colors were not aligned with designs. This PR fixes this. 
- [Temploy](https://picasso.toptal.net/fx-5841-fix-disabled-state-color)
| ![image](https://github.com/user-attachments/assets/fecb0737-a165-4845-a9c8-2b57a734cfef) | ![image](https://github.com/user-attachments/assets/717976fb-7534-4ba2-a2e2-884a44047782) |
| ![image](https://github.com/user-attachments/assets/77eb01ce-8612-46a9-b66c-a19af5203241) | ![image](https://github.com/user-attachments/assets/a82addea-47ef-4405-a7d7-398924112e2b) |
| ![image](https://github.com/user-attachments/assets/4aae6df8-2186-453e-9671-28155bdd4231) | …

[FX-5841] Fix disabled state color 

---

.changeset/friendly-scissors-explain.md
packages/base/Autocomplete/src/Autocomplete/OptionsMenu.tsx
packages/base/Autocomplete/src/Autocomplete/test.tsx

This pull request returns the important condition omitted in https://github.com/toptal/picasso/pull/4534 during refactoring. 
Some consumers rely on dropdown not to be shown when `options` is set to `null` or `undefined` (for example, [here](https://github.com/toptal/staff-portal/blob/3c0c9ebfc1dd6bfe36bc50c0929bc6dcc3f5b99a/namespaces/gigs/libs/gigs/src/components/RequestSkills/components/SearchInput/SearchInput.tsx#L110)). Some Staff Portal Jest and Cypress tests started failing so the expected behavior is back.
Example of failing test that does not expect dropdown to be visible (the test fails to click covered `Save` button)
https://github.com/user-attachments/assets/9d4364bc-eabc-4198-85c5-df5ae323d969
- [Temploy](https://picasso.toptal.net/FX-NULL-fix-options-rendering)
- Staff …

[FX-NULL] Do not render dropdown when options are empty

---

.changeset/stupid-lions-deny.md
packages/base/Section/src/Section/Section.tsx

[FX-5151]
Override spacing of bordered collapsible `Section`s, to better follow BASE design
- [Temploy](https://picasso.toptal.net/fx-5151-change-section-component-padding-from-2rem-to-1-5rem)
- Check temploy and Happo screenshots
<details>
<br />
- `@toptal-anvil ping reviewers` - Ping …

[FX-5151] Fix padding for collapsible bordered Section

---

.changeset/red-wasps-taste.md
packages/base/AccountSelect/src/AccountSelect/__snapshots__/test.tsx.snap
packages/base/Link/src/Link/Link.tsx
packages/base/Link/src/Link/__snapshots__/test.tsx.snap
packages/base/Page/src/PageTopBar/__snapshots__/test.tsx.snap

[FX-5954]
Add `cursor: pointer` to Link when `onClick` is provided.
- [Temploy](https://picasso.toptal.net/fx-5954-link)
- Check Link story, remove `href`, add `onClick={() => {}}`
- Cursor pointer should be there
- Annotate all `props` in component …

[FX-5954] Add pointer cursor to Link when onClick is provided

---

.changeset/eighty-eagles-warn.md
packages/base/Tag/src/TagRectangular/TagRectangular.tsx
packages/base/Tag/src/TagRectangular/__snapshots__/test.tsx.snap

[FX-5973]
As we allow pass ReactNode to the `Tag.Rectangular`, users have errors when passing something else than span, because different tags cannot be rendered inside paragraph. `Tag` is also rendered as a span.
- [Temploy](https://picasso.toptal.net/fx-5973-tag) …

[FX-5973] Update tag to span

---

.changeset/curly-mails-admire.md
.changeset/four-drinks-wonder.md
packages/base/Dropdown/src/Dropdown/Dropdown.tsx
packages/base/Page/src/SidebarItem/SidebarItemCompact.tsx
packages/base/Page/src/SidebarItem/story/WithBadgeAndTag.example.tsx

[FX-5974]
Issue well described here https://toptal-core.slack.com/archives/CERF5NHT3/p1726711479310889
- [Temploy](https://picasso.toptal.net/fx-5974-sidebar-item)
- Make sure that additions …

[FX-5974] Fix disabled state when compact and collapsible

---

.changeset/wicked-yaks-cover.md
packages/base/Button/src/Button/styles.ts
packages/base/Pagination/src/Pagination/__snapshots__/test.tsx.snap

[FX-5956]
Users are using this use case
```
<ButtonGroup>
<Button variant='secondary' active>Foo</Button> 
<Button variant='secondary>Bar</Button>
</ButtonGroup
```
and when the button is active, there was not `z-index` set correctly
- [Temploy](https://picasso.toptal.net/fx-5956-button)
- Copy the use case ☝️ and try it in storybook
- Ensure the …

[FX-5956] Fix active state of buttons in button group

---

.changeset/lazy-boats-reflect.md
packages/base/Page/src/PageContent/PageContent.tsx
packages/base/Page/src/PageContent/styles.ts

[FX-5686]
- [Temploy](https://picasso.toptal.net/fx-5686-migrate-pagecontent)
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~
- ~Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).~
- ~Covered with tests ([visual …

[FX-5686] Migrate PageContent to TailwindCSS

---

.changeset/good-pans-smoke.md
packages/base/Autocomplete/src/Autocomplete/__snapshots__/test.tsx.snap
packages/base/DatePicker/src/DatePicker/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/MonthSelect/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/YearSelect/__snapshots__/test.tsx.snap
packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
packages/base/Input/src/Input/__snapshots__/test.tsx.snap
packages/base/NumberInput/src/NumberInput/__snapshots__/test.tsx.snap
packages/base/OutlinedInput/src/OutlinedInput/stylesRoot.ts
packages/base/Page/src/PageAutocomplete/__snapshots__/test.tsx.snap
packages/base/Select/src/NativeSelect/__snapshots__/test.tsx.snap
packages/base/Select/src/NonNativeSelect/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelector/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelectorInput/__snapshots__/test.tsx.snap
packages/base/Timepicker/src/TimePicker/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap

[FX-6033]
This pull request makes inputs not to break words via `text-nowrap`, as Firefox treats `/` as a whitespace.
Firefox breaks text on `/` (the adornment like `abcdefabcdefabcdefabcdef` does not break), so the `text-nowrap` was applied to the whole input ([similar problem](https://stackoverflow.com/a/56422035/1860213)).
https://github.com/user-attachments/assets/6646a4f7-c0fc-4027-bdd9-0c83f07b5ed7
⚠️ Alpha packages were applied in https://github.com/toptal/staff-portal/pull/13854, only Jest tests fail (due to snapshot problems).
- [Temploy](https://picasso.toptal.net/fx-6033-end-adornment-in-input-is-broken-in-firefox)
- Try the code below in Firefox
```jsx
import React, { useState } from 'react'
import { Input } from '@toptal/picasso'
const [value, …
```

[FX-6033] Add nowrap for input

---

.changeset/witty-seahorses-approve.md
packages/base/Page/src/Page/Page.tsx
packages/base/Page/src/Page/__snapshots__/test.tsx.snap
packages/base/Page/src/PageFooter/PageFooter.tsx
packages/base/Page/src/PageFooter/story/CopyrightContent.example.tsx
packages/base/Page/src/PageFooter/story/Default.example.tsx
packages/base/Page/src/PageFooter/story/RightContent.example.tsx
packages/base/Page/src/PageFooter/styles.ts

[FX-5687]
- [Temploy](https://picasso.toptal.net/fx-5687-migrate-pagefooter)
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API principles](https://github.com/toptal/picasso/blob/master/docs/contribution/component-api.md)~
- ~Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibility.md).~
- ~Covered with tests ([visual …

[FX-5687] Migrate PageFooter to TailwindCSS

---

.changeset/four-fishes-kneel.md
.changeset/strange-bulldogs-unite.md
cypress/component/PageTopBarMenu.spec.tsx
packages/base/Page/src/PageTopBarMenu/PageTopBarMenu.tsx
packages/base/UserBadge/src/UserBadge/UserBadge.tsx
packages/base/UserBadge/src/UserBadge/test.tsx

[FX-6047]
- [Temploy](https://picasso.toptal.net/fx-6047-fix-pagetopbar-menu-padding)
1. Go to `PageTopBar` stories page. 
2. Go to `Page.TopBar.Menu` stories.
3. Change screen size to `<1000px` and click on avatar in the right corner of `PageTopBar`. 
| ![image](https://github.com/user-attachments/assets/d65f67f2-2bd3-462d-b3f8-f3c949f0ccae) | ![image](https://github.com/user-attachments/assets/197e7c37-d4b1-4961-b26b-f38e60aa8ddc) |
- ~Read [CONTRIBUTING.md](https://github.com/toptal/picasso/blob/master/CONTRIBUTING.md) and [Component API …

[FX-6047] Fix UserBadge padding in PageTopBarMenu

---

.github/workflows/automerge-release.yaml

This pull request enables automatic merging of major release pull requests.
Similar pull requests
- https://github.com/toptal/topkit/pull/783 (works as seen in https://github.com/toptal/topkit/pull/784) ✅ 
- https://github.com/toptal/davinci/pull/2493 ⌛ 
- Will be tested after merge
- [N/A] …

[FX-NULL] Auto merge release pull requests

---

package.json
yarn.lock

[FX-6025]
I used `resolutions` because investigating `yarn.lock` I found out that it `@storybook/react@^6.5.15` in the end was the reason for having `micromatch` of version `3.1.10`. Installed version of `@storybook/react` was already the highest possible - `6.5.16`. The next highest is version 7, and we can't update to this version right now. Attempts to reinstall the chain of parents leading from `mistatch` to `@storybook/react` also did not work. 
But I cant be 100% sure that some other way can be used instead of resolution. 
- [Temploy](https://picasso.toptal.net/fx-6025-fix-micromatch-vulnerability)
- ~Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)~
- ~Double check if …

[FX-6025] Fix micromatch vulneralility

---

.github/workflows/ci.yaml
.github/workflows/davinci-alpha-package.yml
.github/workflows/release.yml

We are decomissioning `jenkins-build`
<details>
<br />
</details>
<details>
<br />
**You want your …

CI: Move jobs from build to main jenkins

---

.changeset/thick-peaches-build.md
.changeset/tiny-news-compete.md
.changeset/twelve-years-play.md
cypress/component/Slider.spec.tsx
jest.setup.js
packages/base/Carousel/src/Carousel/hooks/useAutoplay/use-autoplay.ts
packages/base/Slider/src/Slider/Slider.tsx
packages/base/Slider/src/Slider/__snapshots__/test.tsx.snap
packages/base/Slider/src/Slider/hooks/use-label-overlap.ts
packages/base/Slider/src/Slider/story/Default.example.tsx
packages/base/Slider/src/Slider/test.tsx
packages/base/Slider/src/SliderValueLabel/SliderValueLabel.tsx
packages/base/Utils/src/utils/useOnScreen/use-on-screen.ts
tailwind.config.js

[FX-5908]
Fix initial position of Slider when rendered directly on visible screen. `useOnScreen` is returning `false` by default, so before the `IntersectionObserver` actually starts observing, the tooltip blinks from the bottom to the top. I enhanced the hook to also return `isObserved`, so the component can check if the returned value is correct.
- [Temploy](https://picasso.toptal.net/fx-5908-slider)
- Go to the slider default story and add `tooltip='on'`
- there should not be any jumping of the tooltip
- Double check if …

[FX-5908] Fix initial position of Slider

---

.changeset/brave-games-explode.md
packages/base/NumberInput/src/NumberInput/NumberInput.tsx

[FX-6101]
This pull request disables the value change on wheel scroll in `NumberInput`. 
Tests will be added in https://toptal-core.atlassian.net/browse/FX-6102.
- [Temploy](https://picasso.toptal.net/fx-6101-unexpected-behavior-when-scrolling-through-numberinput-field-in-production-environment)
- Check how input behaves with and without `enableChangeOnMouseWheel` property
https://github.com/user-attachments/assets/e9a97a1b-cb76-42b1-abd3-14fda595365f
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
> All **_development checks_** should be done and set checked to pass …

[FX-6101] Disable value change on mouse wheel

---

.changeset/good-eagles-begin.md
packages/base/NumberInput/src/NumberInput/__snapshots__/test.tsx.snap
packages/base/NumberInput/src/NumberInputEndAdornment/NumberInputEndAdornment.tsx

[FX-6105]
This pull request fixes the border rendering in Safari.
The problem was found in https://github.com/toptal/client-portal/pull/9943.
- [Temploy](https://picasso.toptal.net/FX-6105-fix-input-border)
- Open `NumberInput` story in Chrome, Firefox, and Safari and make sure that it looks as expected
**Before**
**After**
https://github.com/user-attachments/assets/24770870-ca29-4241-8242-ea30e3f55d1f
- [N/A] Ensure …

[FX-6105] Fix number input controls border

---

.changeset/strong-needles-flow.md
packages/picasso-forms/src/NumberInput/NumberInput.tsx
packages/picasso-forms/src/NumberInput/test.tsx

[FX-6107]
This pull request makes `NumberInput` form control respect `min` and `max` parameters (there were not passed at all before).
- Check out branch locally
- Test the following code in any story
```jsx
import { FormActionsContainer } from '@toptal/picasso'
import { SPACING_4 } from '@toptal/picasso-utils'
import {
FormNonCompound as Form,
NumberInput,
SubmitButton,
} from '@toptal/picasso-forms'
const initialValues = {}
return (
<Form
onSubmit={values => window.alert(JSON.stringify(values, undefined, 2))}
>
<NumberInput
required
name='default-age'
label="What's your age?"
min='20'
placeholder='Minimum value - 20'
/>
<FormActionsContainer top={SPACING_4}>
<SubmitButton>Submit</SubmitButton>
</FormActionsContainer>
</Form>
)
}
export …
```

[FX-6107] Pass min and max to number input form field

---

packages/base/Link/src/Link/Link.tsx
packages/base/Link/src/Link/__snapshots__/test.tsx.snap
packages/base/Link/src/Link/test.tsx

[FX-NNNN]
This if a follow up of https://github.com/toptal/picasso/commit/f8e5c8f82c54e011270a7bec58375d09153788ce and #4547. Where I did not test code due to inability to add cheap test.
Extract all view logic into separate pure function. This allows adding many tests that run in few ms, raising confidence in our code without making tests suits running forever.
Locally `yarn test:unit:watch `
<details>
<br />
</details>
<details>
<br />
**You …

Refactor Link to add more cheap unit tests

---

.github/CODEOWNERS

Setting all fe engineers as owners of the repo.
<details>
<br />
</details>
<details>
<br />
1. There are leftovers like unnecessary logs, …

Set all FE engineers as owners of Picasso

---

.changeset/hip-pandas-bow.md
cypress/component/Input.spec.tsx
package.json
packages/base/Autocomplete/src/Autocomplete/__snapshots__/test.tsx.snap
packages/base/DatePicker/src/DatePicker/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/MonthSelect/__snapshots__/test.tsx.snap
packages/base/DateSelect/src/YearSelect/__snapshots__/test.tsx.snap
packages/base/Form/src/FormError/__snapshots__/test.tsx.snap
packages/base/Input/src/Input/__snapshots__/test.tsx.snap
packages/base/NumberInput/src/NumberInput/__snapshots__/test.tsx.snap
packages/base/OutlinedInput/src/OutlinedInput/OutlinedInput.tsx
packages/base/OutlinedInput/src/OutlinedInput/stylesRoot.ts
packages/base/Page/src/PageAutocomplete/__snapshots__/test.tsx.snap
packages/base/Select/src/NativeSelect/__snapshots__/test.tsx.snap
packages/base/Select/src/NonNativeSelect/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelector/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelectorInput/__snapshots__/test.tsx.snap
packages/base/Timepicker/src/TimePicker/__snapshots__/test.tsx.snap
packages/picasso-forms/src/Form/__snapshots__/test.tsx.snap

[BILL-5689]
User complained that the reset button was flickering. Please check `before` section in the screenshots
- [Temploy](https://picasso.toptal.net/BILL-5689-fix-reset-button-on-input)
- Go to `Input` story
- Pass `enableReset` to display the `X` reset button
- The button should always be displayed when hovering over the entire field (even over at the icon)
https://github.com/user-attachments/assets/d3e0cd67-c418-4e42-961f-962c56257f59
https://github.com/user-attachments/assets/c364f1cb-ce66-428e-8b26-992103a950d0
- [n/a] codemod is created and showcased in the changeset
- [n/a] test alpha package of Picasso in StaffPortal
> **GitHub Bot: TODOLess** …

[BILL-5689] Display reset button on root hover for Input component

---

.github/workflows/release.yml
ci/jobs/picasso-master-release/Jenkinsfile

[TAPS-436]
- n/a Add changeset according to [guidelines](https://github.com/toptal/picasso/blob/master/docs/contribution/changeset-guidelines.md) (if needed)
- n/a Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)
- n/a Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- n/a Ensure the changed/created components have not caused accessibility issues. [How to use accessibility plugin in storybook](https://github.com/toptal/picasso/blob/master/docs/contribution/accessibil …

[TAPS-436] Move notifications to new channel

---

.changeset/purple-beans-help.md
packages/base/Timepicker/src/TimePicker/TimePicker.tsx

[CPS-1474]
Fix `size` prop for TimePicker
- [Temploy](https://picasso.toptal.net/cps-1474-fix-timepicker-size)
- Go to this story: /?path=/story/forms-timepicker--timepicker
- Add `size='small'` and see that it works
| <img width="335" alt="image" src="https://github.com/user-attachments/assets/f24a7ec1-6741-4037-9f56-19bc3727cb6f" /> | <img width="372" alt="image" src="https://github.com/user-attachments/assets/45dd8ce5-6d48-4cb7-b03e-021fd149fbc1" /> |
Tested on Staff Portal storybook:
- N/A Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been …

[CPS-1474] Fix TimePicker size property

---

.changeset/perfect-dolls-march.md
packages/base/NumberInput/src/NumberInput/NumberInput.tsx
packages/base/NumberInput/src/NumberInput/story/WithEndAdornment.example.tsx
packages/base/NumberInput/src/NumberInput/story/index.jsx
packages/base/NumberInput/src/NumberInput/test.tsx

[MP-672]
`NumberInput` has the prop `endAdornment` but never uses it. This change aims to render `endAdornment` aside the controls, or isolated (when `hideControls` is `true`).
- [Temploy](https://picasso.toptal.net/MP-672-support-end-adornment-properly-in-number-input)
- Check NumberInput component on temploy
| Picasso | Example in Talent Portal with alpha |
| ---- | ---- |
| ![image](https://github.com/user-attachments/assets/efec3329-2cb4-4b7f-a12f-7dbe28ade805) | ![image](https://github.com/user-attachments/assets/e065bef8-79df-40a9-bc0d-d10332e3599c) |
- [n/a] Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)
- [n/a] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already …

[MP-672] Support `endAdornment` properly in NumberInput

---

.changeset/friendly-crabs-serve.md
.github/PULL_REQUEST_TEMPLATE.md
packages/base/Tabs/src/Tab/__snapshots__/test.tsx.snap
packages/base/Tabs/src/Tab/styles.ts
packages/base/Tabs/src/TabLabel/TabLabel.tsx
packages/base/Tabs/src/Tabs/__snapshots__/test.tsx.snap

[MP-598]
Aligns Tabs with [Base design](https://www.figma.com/design/5SCTOPrCDcHuk5We091GBn/Product-Library?node-id=246-11213&t=CFVgzhA9g0px4x9M-0).
- [Temploy](https://picasso.toptal.net/MP-598-tabs-height)
- Check visual changes
Base
Before changes
After changes
<details>
<br />
</details>
<details>
<br />
1. You have no …

[MP-598] Align tabs with base design

---

.changeset/nice-games-beg.md
packages/base/Button/src/Button/Button.tsx
packages/base/Button/src/Button/styles.ts
packages/base/Button/src/ButtonCircular/ButtonCircular.tsx
packages/base/Button/src/ButtonCircular/styles.ts

After discussion with Milos it appeared that the buttons in loading state, even if they are disabled should look like normal buttons, instead of becoming grey. So, here is the change.
Let's make them colorful!
- Open storybook and check Button with both `loading` and `disabled` at the same time.
- It should be disabled, but having color of the variant
| <img width="94" alt="Screenshot 2025-02-12 at 16 58 33" src="https://github.com/user-attachments/assets/98409dc9-e594-46f0-9a21-043b3151c02d" /> | <img width="95" alt="Screenshot 2025-02-12 at 16 58 39" src="https://github.com/user-attachments/assets/b153e100-c7ef-463f-88 …

Make loading disabled buttons colorful

---

.changeset/calm-insects-run.md
packages/base/Pagination/src/Pagination/Pagination.tsx
packages/base/Pagination/src/Pagination/__snapshots__/test.tsx.snap
packages/base/Pagination/src/Pagination/story/Disabled.example.tsx
packages/base/Pagination/src/Pagination/story/Variants.example.tsx
packages/base/Pagination/src/Pagination/test.tsx

[ER-45674]
Sometimes the backend doesn't have the total number results for a query (for example because getting the total count is expensive)
`<Pagination variant="compact">` UX works well for this use case, but the component expects `totalPages`. This removes the requirement.
When we don't have the `totalPages` we can't know in which page we are, so we can't know if we're in the last page to show the button disabled (we can know when we are on the first one though). To fix, this also adds a `nextDisabled` prop.
- [Temploy](https://picasso.toptal.net/er-45674-pagination-without-totals)
- See https://github.com/toptal/staff-portal/pull/14195
See storybook
> All **_development checks_** should be done and set …

[ER-45674] Allow not providing totalCount for compact Pagination

---

.changeset/tall-boxes-matter.md
packages/base/Section/src/Section/Section.tsx
packages/base/Section/src/Section/story/Controlled.example.tsx
packages/base/Section/src/Section/story/index.jsx
packages/base/Section/src/Section/test.tsx

[MP-945]
Make `Section` component controlled.
⚠️  There is height glitch, but it happens in `master` and will be addressed separately.
- [Temploy](https://picasso.toptal.net/MP-915-make-section-controlled)
- Check the `Controlled component` story
https://github.com/user-attachments/assets/6cecfc3c-a083-4eda-8818-9e7a5c841d6e
<details>
<br />
</details>
<details>
<br /> …

[MP-945] Add controlled Section behavior support

---

.changeset/lazy-radios-train.md
packages/base/Table/src/Table/__snapshots__/test.tsx.snap
packages/base/Table/src/TableBody/__snapshots__/test.tsx.snap
packages/base/Table/src/TableCell/TableCell.tsx
packages/base/Table/src/TableCell/__snapshots__/test.tsx.snap
packages/base/Table/src/TableFooter/__snapshots__/test.tsx.snap
packages/base/Table/src/TableHead/__snapshots__/test.tsx.snap
packages/base/Table/src/TableRow/__snapshots__/test.tsx.snap
packages/base/Table/src/TableSectionHead/__snapshots__/test.tsx.snap
packages/base/Table/src/TableSortableCell/__snapshots__/test.tsx.snap

By some reason now we have the last cell having custom extra padding. After discussion with Milos and checking Figma - https://www.figma.com/design/q2nvjiyO2CLqBv4DeJnU3i/Product-Library-Documentation?node-id=476-9897&t=ywR92i2wXfDtSkiq-4. We agreed that there should be no extra padding and the left padding for the first cell/column should be the same as the right padding for the last column.
Check padding for Table component in storybook.
<details>
<br />
</details>
<details>
<summary>PR …

Fix Table paddings for last column

---

.changeset/lovely-bikes-agree.md
packages/base/Tagselector/src/TagSelector/TagSelector.tsx
packages/base/Tagselector/src/TagSelector/__snapshots__/test.tsx.snap
packages/base/Tagselector/src/TagSelector/story/Sizes.example.tsx
packages/base/Tagselector/src/TagSelector/story/index.jsx
packages/base/Tagselector/src/TagSelectorInput/TagSelectorInput.tsx
packages/base/Tagselector/src/TagSelectorInput/__snapshots__/test.tsx.snap

[MP-996]
Make TagSelector support `large` size.
- [Temploy](https://picasso.toptal.net/MP-965-pass-props)
- Check [TagSelector stories](https://picasso.toptal.net/MP-965-pass-props/?path=/story/forms-tagselector--tagselector) and visual diffs
- [N/A] Covered with tests ([visual tests](https://github.com/toptal/picasso/blob/master/docs/contribution/visual-testing.md) included)
<details>
<br />
</details>
<details>
<br />
1. You …

[MP-996] Add size property to TagSelector

---

.changeset/honest-pumas-roll.md
packages/base/Autocomplete/src/Autocomplete/Autocomplete.tsx
packages/base/Autocomplete/src/Autocomplete/story/LargeSize.example.tsx
packages/base/Autocomplete/src/Autocomplete/story/index.jsx

[MP-917]
Picasso's Autocomplete passes its `...rest` props to the `Input` element, so technically it supports already passing `size='large'`, and it is working.
But `size` was not defined in the `Props` type, so we got a type error. This adds `size` to the `Props` type.
- Storybook: http://localhost:9001/?path=/story/forms-autocomplete--autocomplete#large-size
<details>
<br />
</details>
<details> …

[MP-917] Support size in Autocomplete props

---

.changeset/honest-toes-fail.md
packages/base/Page/src/PageTopBar/PageTopBar.tsx
packages/base/Page/src/PageTopBar/story/Variants.example.tsx
packages/base/Page/src/PageTopBar/styles.ts

[CPS-1596]
Add Picasso Black TopBar Variation
- Check the storybook
<details>
<br />
</details>
<details>
<br />
3. Code is …

[CPS-1596] Add Picasso Black PageTopBar Variant

---

.changeset/quick-cheetahs-compete.md
packages/base/Page/src/SidebarItem/types.ts
packages/base/Page/src/TopBarItem/TopBarItem.tsx

[BILL-5992]
Remove mui v4 import for MenuItem props, replacing them with the types defined in MenuItem component in the `@topta/picasso-menu` package.
Try alpha package in various portals.
No changes.
<details>
<br />
</details>
<details>
<br />
**You …

[BILL-5992] Remove mui v4 import for MenuItem props

---

.changeset/plenty-experts-compete.md
packages/base/Page/src/SidebarItem/SidebarItemAccordion.tsx
packages/base/Page/src/SidebarItem/SidebarItemCompact.tsx
packages/base/Page/src/SidebarItem/__snapshots__/test.tsx.snap
packages/base/Page/src/SidebarItem/styles.ts

[FF-12]
Migration of Sidebar item to tailwind
- All CI checks should pass
- Check `Sidebar.Item` on storybook
<details>
<br />
</details>
<details>
<br />
1. …

[BILL-💵, FF-12] Migrate sidebar item to tailwind

---

.changeset/khaki-bottles-nail.md
cypress/component/DatePicker.spec.tsx
packages/base/Calendar/src/Calendar/Calendar.tsx
packages/base/Calendar/src/Calendar/test.tsx
packages/base/DatePicker/src/DatePicker/DatePicker.tsx
packages/base/DatePicker/src/DatePicker/story/WithDisabledDays.example.tsx
packages/base/DatePicker/src/DatePicker/story/index.jsx

[BILL-💵]
It's not possible to disable specific days on the date picker, i.e. Monday, Tuesday etc... This PR allows this which is supported from our underlying component https://daypicker.dev/v8/advanced-guides/custom-modifiers#disabling-days
- Open storybook and `With Disabled Days` story
- The `disabledIntervals` prop should take precedence and work as before
<details>
<br />
</details>
<details>
<br />
1. You …

[BILL-💵] Allow specific days to be disabled on the date picker

---

.github/workflows/ci.yaml
.github/workflows/davinci-alpha-package.yml
.github/workflows/release.yml

GCR_ACCOUNT_KEY and JENKINS_SA_CREDENTIALS got [deprecated](https://toptal-core.slack.com/archives/C2W28V7L7/p1744790237117949) and it causes CI to [fail](https://github.com/toptal/picasso/actions/runs/14669358300/job/41172038918?pr=4738). Remove them from CI as they no longer seem necessary
- Green CI
<details>
<br />
</details>
<details>
<br /> …

Remove deprecated keys to unblock CI

---

.github/workflows/release.yml

Deprecating usage of `GCR_ACCOUNT_KEY` according to https://toptal-core.slack.com/archives/C2W28V7L7/p1744790237117949
Not testable
<details>
<br />
</details>
<details>
<br />
1. Something is broken after …

Fix release removing GCR_ACCOUNT_KEY secret

---

.changeset/real-eyes-kiss.md
packages/base/Modal/src/Modal/test.tsx
packages/base/Popper/src/Popper/Popper.tsx
packages/base/Utils/src/utils/__tests__/use-page-scroll-lock.test.tsx
packages/base/Utils/src/utils/use-page-scroll-lock.ts

When overlay elements that are based no Popper are shown, the body overflow is set to `hidden` to small - medium screens. This style breaks with any sticky element that may be visible – it immediately loses the "stickyness" while body overflow is hidden, causing an undesired visual behavior.
This PR changes that to overflow `clip` instead. Overflow `clip` behaves similar to `hidden`, but it doesn't a new scrolling area and sticky elements keep sticky. [See for context](https://toptal-core.slack.com/archives/CHK8E5JEN/p1745591412604209?thread_ts=1745431550.717609&cid=CHK8E5JEN)
https://github.com/user-attachments/assets/5593a5b2-bdee-4d93-80e5-84ba0d0158a4
- [Temploy](https://picasso.toptal.net/ff-x-replace-overflow-hidden-by-clip-popper)
- You can check it in action in this PR …

Replace overflow `hidden` by `clip` in Popper

---

.changeset/hungry-berries-march.md
packages/base/Section/src/Section/Section.tsx
packages/base/Section/src/Section/__snapshots__/test.tsx.snap

[MP-955]
The expand/collapse transitions for some of the `Section` variations were a bit "jumpy". This PR fixes them.
- Start storybook locally with `yarn start`
- Go to the Section component
- Expand and collapse all the different stories
https://github.com/user-attachments/assets/32012b9b-2a07-4ff9-b6ec-ded2abaa3369
https://github.com/user-attachments/assets/bcc7c7b7-9eee-4cda-9e82-e03f7678e7aa
- N/A codemod is created and showcased in the changeset
- N/A test alpha package of Picasso in StaffPortal
<details>
<br />
- `@toptal-anvil ping …

[MP-955] Fix abrupt animation on Section when expanded and collapsed

---

.changeset/friendly-papayas-clean.md
packages/base/PromptModal/src/PromptModal/PromptModal.tsx
packages/base/PromptModal/src/PromptModal/story/Variants.example.tsx

[HG-985]
- Go to [temploy](https://picasso.toptal.net/HG-985-prompt-modal-variant-primary/?path=/story/overlays-promptmodal--promptmodal#variants)
- Click "Open primary" button
- Modal that appears should have blue "Submit" button
| Insert screenshots or screen recordings | ![image](https://github.com/user-attachments/assets/ffdcf781-b282-440f-87df-b86f2013161f) |
- [n/a] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- [n/a] Annotate all …

[HG-985] Allow variant=primary for the PromptModal

---

.github/workflows/davinci-integration-tests.yml

`toptal/davinci-github-actions/integration-tests` does upload screenshots automatically. An attempt to upload them once again results in a failure https://github.com/toptal/picasso/actions/runs/15922756856/job/44913457950#step:10:32 
- [Temploy](https://picasso.toptal.net/fix-integration-tests)
- CI is green
- [n/a] Double check if `picasso-tailwind-merge` requires major update (check its `README.md`)
- [n/a] Make sure that additions and changes on the design follow [Toptal's BASE design](https://design.toptal.net/), and it's been already discussed with designers at #-base-core
- …

Remove cypress screenshots upload step from integration tests WF

---

.github/workflows/ci.yaml
.github/workflows/davinci-integration-tests.yml
.github/workflows/visual-testing.yml

[BILL-6530]
Move happo secrets to step level of the workflows
<details>
<br />
</details>
<details>
<br />
**You want your …

[BILL-6530] Move happo secrets to step level of the workflows

---

.github/workflows/release.yml

[BILL-6575]
Add incoming slack webhook type to the GHA
<details>
<br />
</details>
<details>
<br />
**You want your comments to …

[BILL-6575] Add incoming slack webhook type to the GHA

---

.changeset/public-places-dig.md
packages/base/Switch/src/Switch/Switch.tsx
packages/base/Switch/src/Switch/__snapshots__/test.tsx.snap

Fixes the Switch control width – it should not be triggered in the invisible area outside of actual component.
The problem
https://github.com/user-attachments/assets/b78483de-4f2f-4f9d-966f-cfcdaf273cb0
- [Temploy](https://picasso.toptal.net/NEWOFF-NULL-fix-switch-width)
- Compare with https://picasso.toptal.net/
- Check out visual changes
Before
https://github.com/user-attachments/assets/ff2fb485-95c2-4ca4-b9e3-0e02777f953b
After
https://github.com/user-attachments/assets/17986f1c-ee95-4906-ae02-6bef179bb0a2
- [N/A] Ensure the changed/created components have not caused accessibility issues. [How …

[NEWOFF-NULL] Fix Switch control width
